### ISSUE TITLE
[Q] Question regarding new cmd-line parameters

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#10]
#### Added --amd-only option. Only use amd cl-devices

If I add this parameter, does this mean, that the device count for --cl-devices is counting over the AMD devices, only?

#### (-E) To feed the pool(s) what they need.

What does this mean, exactly? What are possible values for `-E` ?

**Comment by sp-hash** [comment]
--amd-only will filter out NVIDIA opencl devices.

--xintensity (E) Valid values are 1 and up to xxxxx.  (default is 32)

It controls the workload that is sent to the gpu. High values give good hashrate but can produce stale shares and rejects on the pool. Some pools pay the same for stale shares, some give a penalty.

**Comment by RainbowMiner** [comment]
> --amd-only will filter out NVIDIA opencl devices.

Yes, that's clear, but does it change the GPU index for --cl-devices?

e.g.
OpenCL - Config:
0: INTEL1
1: AMD1
2: AMD2
3: AMD 3

To select all AMD I have currently used: `--cl-devices [1,2,3]`
If I use the --amd-only parameter, does this change to `--amd-only --cl-devices [0,1,2]` now?

Or do I get it completely wrong? How is that --cl-devices addressing handled exactly?

**Comment by sp-hash** [comment]
first question: --cl-devices [3,4]
second question: --cl-devices [3,4]
