### ISSUE TITLE
Error: Your system does not support CUDA 11.4 API

### ISSUE THREAD

**Issue by rgoyankaitrs** [sp-hash/TeamBlackMiner#102]
Error working with nvidia card. Getting error with latest version. Error: Your system does not support CUDA 11.4 API. 

Please help
![Capture](https://user-images.githubusercontent.com/27739649/139553929-dca3b5b4-6c30-40a4-817f-dc29dd48afef.PNG)

**Comment by sp-hash** [comment]
You need to install the latest driver.

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/issues/78
