### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm

### ISSUE THREAD

**Issue by gorgarp** [sp-hash/TeamBlackMiner#103]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin but we need more AMD supported options.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. Your project looks extremely promising and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by sp-hash** [comment]
Probobly not

**Comment by gorgarp** [comment]
Has any reconsideration been given to this? ETH merge is approaching and Flux is a very likely target for a good amount of that hash.

**Comment by sp-hash** [comment]
Yes, the ETH moving to POS changes things. 

The Team will move to support the more secure blockchains like Flux.

**Comment by sp-hash** [comment]
Check out the new LHR unlocking tool

https://github.com/sp-hash/TheBlackPill

Should give a boost on all FLUX mining software out there..

**Comment by gorgarp** [comment]
Hello, any news? I have a discord with 18,000 members who would love a software contender for the hash.

**Comment by gorgarp** [comment]
Hello. I just wanted to check in and see how this was coming along?
