### ISSUE TITLE
Request: Addition of simpleminer.app pool

### ISSUE THREAD

**Issue by Sirk6** [sp-hash/TeamBlackMiner#104]
Please add support for the etherum pool 

simpleminer.app

is not ssl and to connect is us1.simpleminer.app:25565

**Comment by binaryf** [comment]
Hi.

Is it a username login or is it anonymous mining ?

**Comment by Sirk6** [comment]
> Hi.
> 
> Is it a username login or is it anonymous mining ?

to mining in the pool use the cellphone number instead etherum wallet

**Comment by binaryf** [comment]
Ok. We will add you, but we can not register.
Do you know if you are using "ethereum stratum 1.0" (nicehash) or "ethproxy" protocol ?

**Comment by Sirk6** [comment]
> Ok. We will add you, but we can not register. Do you know if you are using "ethereum stratum 1.0" (nicehash) or "ethproxy" protocol ?

thanks a lot, this is the bat configuration: stratum+tcp://us1.simpleminer.app:25565 you need other information?

**Comment by Sirk6** [comment]
Protocol:  Stratum1

**Comment by binaryf** [comment]
Added in V1.23.
