### ISSUE TITLE
[TeamBlackMiner] No GPU devices available on platform 1

### ISSUE THREAD

**Issue by Youssef-Mekkaoui** [sp-hash/TeamBlackMiner#105]
Hello guys,

i got this error when i try to use Team BlackMiner on HiveOS :
No GPU devices available on platform 1 (Advanced Micro Devices, Inc.)

But with T-REX Miner it works well, can you guys help me please ?

I finally did --cl-all-devices in the settings to get it work but it's so slow ...

**And How to get my GPUs on CUDA please they are on OPEN CL and they are so slow ...**

![image](https://user-images.githubusercontent.com/16267835/140289649-41b96397-0808-4bea-add8-66a3f3581f12.png)

Cordially.

**Comment by Youssef-Mekkaoui** [comment]
I also have this when i do -G

![image](https://user-images.githubusercontent.com/16267835/140290076-2b098961-5021-4262-9199-b4f9fddb42c0.png)

But i'm running the latest drivers

**Comment by binaryf** [comment]
Which version number are you using ?

**Comment by Youssef-Mekkaoui** [comment]
I'm good, just needed to update my drivers .. thanks guys !
