### ISSUE TITLE
An error has occurred. Cannot receive data from pool

### ISSUE THREAD

**Issue by Sirk6** [sp-hash/TeamBlackMiner#109]
hi you add in the new version support for simpleminer.app when i run always send this message in red 
An error has occurred. Cannot receive data from pool

**Comment by binaryf** [comment]
Can you copy/paste all console information or make a screenshot ?

**Comment by Sirk6** [comment]
> Can you copy/paste all console information or make a screenshot ?

![2021-11-08](https://user-images.githubusercontent.com/89314606/140773131-9529d31d-988f-4430-b244-2240ca941520.png)

**Comment by binaryf** [comment]
Could be the protocol. Will try to change it.

**Comment by OctavioMaia** [comment]
Same happens on flexpool only on nvidia cards. On AMD cards for some reason it works perfectly.

I've tried 1.23, 1.22 and 1.21 and none work

**Comment by sp-hash** [comment]
If you mine with too high intensity / stale shares, some pools will cut the connection. Flexpool pay nothing for stales, so works best with a low --xintensity setting.

**Comment by OctavioMaia** [comment]
> If you mine with too high intensity / stale shares, some pools will cut the connection. Flexpool pay nothing for stales, so works best with a low --xintensity setting.

I know, I've read the docs, but specifiying somelink like `--xintensity 8 ` on 3060tis (non lhr), it connects but leads to 90% rejects.
When using the recommended 192 for the 3060tis it also does not connect.
`--xintensity 24` (default for AMD) gives me 100% accepted on my 5700/6800s.

Do you have any recommendation for 5700s and 3060Tis for intensity?

**Comment by binaryf** [comment]
> hi you add in the new version support for simpleminer.app when i run always send this message in red An error has occurred. Cannot receive data from pool

Since we can not register on the pool (We do not have an american phone number) we will just try to set another protocol.
Hope it works in next release.

**Comment by strannik357753** [comment]
> > hi you add in the new version support for simpleminer.app when i run always send this message in red An error has occurred. Cannot receive data from pool
> 
> Since we can not register on the pool (We do not have an american phone number) we will just try to set another protocol. Hope it works in next release.
F2pool same error on startup
![6575](https://user-images.githubusercontent.com/60912947/141266090-212d85cd-f424-4e77-b2d8-24df65bdd87f.png)

**Comment by strannik357753** [comment]
![124](https://user-images.githubusercontent.com/60912947/141348218-0fcde8b4-4529-4f21-95db-afe972fa4c4b.png)
1.24 also has this bug

**Comment by binaryf** [comment]
Strange. It works at second try. Will take a look. This is an annoying error.

**Comment by binaryf** [comment]
Fixed.

Thank you for reporting.
