### ISSUE TITLE
[Request] miner flags request

### ISSUE THREAD

**Issue by DatN132** [sp-hash/TeamBlackMiner#11]
Since there is an —amd-only option, there should also be an —nvidia-only option.
Also, there should be a —gpu option to select GPUs

Is there a flag that I’m missing where you can set the miner to not use the iGPU? This is relevant on APU systems

**Comment by sp-hash** [comment]
-Y --cl-devices [,]
-U --cuda-devices [,]
-z --cl-all-devices
-Z --cuda-all-devices
-b --amd-only

example:
-Y [1,2,3,4,5]
