### ISSUE TITLE
Help not working

### ISSUE THREAD

**Issue by matheusqro** [sp-hash/TeamBlackMiner#111]
The miner closes and does not start.

**Comment by sp-hash** [comment]
Run the ansicolor.reg script in the 7zip archive to activate colors in Windows program console.

This miner only works on windows 10 and linux

**Comment by matheusqro** [comment]
> Run the ansicolor.reg script in the 7zip archive to activate colors in Windows program console.
> 
> This miner only works on windows 10 and linux Can you post a picture when it exits?

![114733](https://user-images.githubusercontent.com/39939428/140763054-35c3eafd-e160-466a-a9e3-123b54b6725d.png)

**Comment by sp-hash** [comment]
it's because it's trying to mine on your internal graphics card. Use --nvidia-only

**Comment by matheusqro** [comment]
> --nvidia-only

Tranks bro :)

**Comment by matheusqro** [comment]
> it's because it's trying to mine on your internal AMD graphics card. Use --nvidia-only

Thanks bro :)
