### ISSUE TITLE
TeamBlackminer 1.23 doesn't see any CUDA devices in RaveOS,   1.22 works fine

### ISSUE THREAD

**Issue by ikorzha** [sp-hash/TeamBlackMiner#113]
Version 1.22:

Available Cuda devices
-----------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 1
    Memory: 24GB
    Memory clock rate (KHz): 9751000
    Memory bus width (bits): 384
    Peak memory bandwidth (GB/s): 936.096000

Device Number: 1
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 7
    Memory: 24GB
    Memory clock rate (KHz): 9751000
    Memory bus width (bits): 384
    Peak memory bandwidth (GB/s): 936.096000

Device Number: 2
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 11
    Memory: 24GB
    Memory clock rate (KHz): 9751000
    Memory bus width (bits): 384
    Peak memory bandwidth (GB/s): 936.096000

Available OpenCL devices
-------------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

Device Number: 1
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

Device Number: 2
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

root@RIG7:/app-data/miners/teamblackminer-1.22# 

Version 1.23:

root@RIG7:/app-data/miners/teamblackminer-1.23# ./TBMiner -D
./TBMiner: /usr/lib64/libcurl.so.4: no version information available (required by ./TBMiner)

Available Cuda devices
-----------------------

Available OpenCL devices
-------------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

Device Number: 1
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

Device Number: 2
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 0
    Memory: 24GB

root@RIG7:/app-data/miners/teamblackminer-1.23#

**Comment by sp-hash** [comment]
We added the cuda 11.5 build so you have to upgrade to the latest driver.

Cuda runtime API version: 11.5
