### ISSUE TITLE
Low hashrate Vega 56

### ISSUE THREAD

**Issue by SophosLab** [sp-hash/TeamBlackMiner#114]
Why is such low hashrate with VEGA56 GPU's? Only 30mh/s.
With same oc settings TRM returns 50mh/s.

**Comment by MrNuTruT** [comment]
Same with radeon VII only 50/60 MH/s WITH memtweak but 100mh/s on team red miner

**Comment by binaryf** [comment]
We actually don't know.
We are actually trying to beat Team Red Miner but this one we did not win.
