### ISSUE TITLE
1.23 Mixed Rig

### ISSUE THREAD

**Issue by GreyMamoN** [sp-hash/TeamBlackMiner#115]
Mixed Rig

2 x RX580
1 X GTX1070

1.22 Works great

1.23 does not see GTX 1070

Sorry for bad English...

____________________________________________________________________________________________________________________________

TeamBlackMiner 1.22

00:00:00 [2021-11-09 11:59:57.950]
00:00:00 [2021-11-09 11:59:58.003] OpenCL driver version: 470.63
00:00:00 [2021-11-09 11:59:58.006] Cuda driver version: 11.4
00:00:00 [2021-11-09 11:59:58.006] Cuda runtime API version: 11.4
00:00:00 [2021-11-09 11:59:58.006]
00:00:00 [2021-11-09 11:59:58.006]                                 
00:00:00 [2021-11-09 11:59:58.006]
00:00:00 [2021-11-09 11:59:58.006] Welcome to Team Black Miner 1.22
00:00:00 [2021-11-09 11:59:58.006]                                 
00:00:00 [2021-11-09 11:59:58.006]
00:00:00 [2021-11-09 11:59:58.006] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2021-11-09 11:59:58.006] GPU1 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2021-11-09 11:59:58.067] GPU2 NVIDIA GeForce GTX 1070 8GB added to miner as Cuda device
00:00:05 [2021-11-09 12:05:03.073]                                                                                 
00:00:05 [2021-11-09 12:05:03.073]------------------------------------------------------------------------------------------
00:00:05 [2021-11-09 12:05:03.073] ID     BOARD   TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:05 [2021-11-09 12:05:03.073] GPU0  Ellesme OpenCL  0       0       0/0     0       0       0       0
00:00:05 [2021-11-09 12:05:03.073] GPU1  Ellesme OpenCL  0       0       0/0     0       0       0       0
00:00:05 [2021-11-09 12:05:03.073] GPU2  1070    Cuda    1       224     55/0    79      2062    4050    133
00:00:05 [2021-11-09 12:05:03.073]                                                                     133
00:00:05 [2021-11-09 12:05:03.073] 
00:00:05 [2021-11-09 12:05:03.073] ID     BOARD   HASHRATE/W      HASHRATE        AVERAGE         SHARES
00:00:05 [2021-11-09 12:05:03.073] GPU0  Ellesme 0.00 H/W        31.97 MH/s      31.93 MH/s      3/0/0 (100.00%)
00:00:05 [2021-11-09 12:05:03.073] GPU1  Ellesme 0.00 H/W        32.75 MH/s      31.61 MH/s      0/0/0 (100.00%)
00:00:05 [2021-11-09 12:05:03.073] GPU2  1070    210.53 kH/W     28.00 MH/s      28.08 MH/s      1/0/0 (100.00%)
00:00:05 [2021-11-09 12:05:03.073]             210.53 kH/W     92.72 MH/s      91.61 MH/s      4/0/0 (100.00%)
00:00:05 [2021-11-09 12:05:03.073]------------------------------------------------------------------------------------------

____________________________________________________________________________________________________________________________

TeamBlackMiner 1.23

00:00:00 [2021-11-09 12:06:27.846]
00:00:00 [2021-11-09 12:06:27.890] OpenCL driver version: 470.63
00:00:00 [2021-11-09 12:06:27.892] Cuda driver version: 11.4
00:00:00 [2021-11-09 12:06:27.892] Cuda runtime API version: 11.5
00:00:00 [2021-11-09 12:06:27.892]
00:00:00 [2021-11-09 12:06:27.892]                                 
00:00:00 [2021-11-09 12:06:27.892]
00:00:00 [2021-11-09 12:06:27.892] Welcome to Team Black Miner 1.23
00:00:00 [2021-11-09 12:06:27.892]                                 
00:00:00 [2021-11-09 12:06:27.892]
00:00:00 [2021-11-09 12:06:27.892] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2021-11-09 12:06:27.892] GPU1 Ellesmere 8GB added to miner as OpenCL device
00:00:02 [2021-11-09 12:08:27.061]                                                                                 
00:00:02 [2021-11-09 12:08:27.061]------------------------------------------------------------------------------------------
00:00:02 [2021-11-09 12:08:27.061] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:00:02 [2021-11-09 12:08:27.061] GPU0    Ellesme  OpenCL  0       0       0/0     0       0       0       0      
00:00:02 [2021-11-09 12:08:27.061] GPU1    Ellesme  OpenCL  0       0       0/0     0       0       0       0      
00:00:02 [2021-11-09 12:08:27.061]                                                                          0      
00:00:02 [2021-11-09 12:08:27.061] 
00:00:02 [2021-11-09 12:08:27.061] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:00:02 [2021-11-09 12:08:27.061] GPU0    Ellesme  0.00 H/W      31.19 MH/s    42.06 MH/s    1/0/0        100.00% 
00:00:02 [2021-11-09 12:08:27.061] GPU1    Ellesme  0.00 H/W      30.86 MH/s    30.68 MH/s    1/0/0        100.00% 
00:00:02 [2021-11-09 12:08:27.061]                  0.00 H/W      62.05 MH/s    72.74 MH/s    2/0/0        100.00% 
00:00:02 [2021-11-09 12:08:27.061]------------------------------------------------------------------------------------------

**Comment by sp-hash** [comment]
You need to upgrade the nvidia graphic to the latest version since you are running the cuda 11.5 build.

Cuda runtime API version: 11.5
