### ISSUE TITLE
Console output is not full for 6900XT

### ISSUE THREAD

**Issue by rostyslavfilipchuk** [sp-hash/TeamBlackMiner#116]
miner version Version TeamBlackMiner_1_23_cuda_11_5
video drivers version 21.10.2 10/5/2021

launcher file
Set ETH_WALLET=0x89e60354d356c08fcadaf520fa9f0ffabc4a29c1

:loop
	TBMiner --algo ethash --hostname eu1.ethermine.org --port 4444 --wallet %ETH_WALLET% --worker-name 6900xt
	timeout 10
goto :loop

results
![image](https://user-images.githubusercontent.com/65414735/140960489-5e203274-e27a-4110-9c75-2f8117168398.png)

P.S nice hashrate 👍

**Comment by MrNuTruT** [comment]
same with the last version on hiveos with 6700XT and 5700XT 

![image](https://user-images.githubusercontent.com/11719145/140965324-3d92daeb-5528-4ba1-a266-502deaee35b6.png)

**Comment by binaryf** [comment]
We know about this issue and want to replace Amd ADL lib for reading GPU information as soon as possible.
