### ISSUE TITLE
Device duplicate

### ISSUE THREAD

**Issue by rcerebro** [sp-hash/TeamBlackMiner#117]
I have 2x 3070 (one LHR and one NLHR) plus 1x RX 590, see that device 0 repeats for GPU 0 (RTX 3070 NLHR) and GPU 0 (RX 590), going to GPU 1 (RTX 3070 LHR) , not adding it as GPU 2

**Comment by sp-hash** [comment]
cl devices and cuda devices have different numbering. use tbminer --list-devices to find the right id number

--cl-devices x --cuda-devices 0

**Comment by rcerebro** [comment]
Available Cuda devices
-----------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3070
    PCIe bus id: 11
    Memory: 8GB
    Memory clock rate (KHz): 7001000
    Memory bus width (bits): 256
    Peak memory bandwidth (GB/s): 448.064000

Device Number: 1
    Device name: NVIDIA GeForce RTX 3070
    PCIe bus id: 15
    Memory: 8GB
    Memory clock rate (KHz): 7001000
    Memory bus width (bits): 256
    Peak memory bandwidth (GB/s): 448.064000


Available OpenCL devices
-------------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3070
    PCIe bus id: 0
    Memory: 8GB

Device Number: 1
    Device name: NVIDIA GeForce RTX 3070
    PCIe bus id: 0
    Memory: 8GB

Device Number: 2
    Device name: Ellesmere
    PCIe bus id: 13
    Memory: 8GB

teamblackminer exited (exitcode=0), waiting to cooldown a bit

[ Hiveos_Casa ][                                                                                                                    [ teamblackminer ]                                                                                                                     ][ Exit: Ctrl+a d  Switch: Ctrl+a+a ][ 09/11 22:30 ]


How do I configure for hiveos to use GPU 0 and 1 (3070 and 590) for only teamblackminer and I will only use gminer for 3070 LHR for device 2?

**Comment by rcerebro** [comment]
I achieved. I will be testing your miner over the next few days. Thank you for your attention.

Information: Forecast for LHR?

**Comment by sp-hash** [comment]
--cl-devices [2] --cuda-devices [0]
