### ISSUE TITLE
Sorry the provided pool is not supported

### ISSUE THREAD

**Issue by luanwulin** [sp-hash/TeamBlackMiner#119]
version 1.2.3

if i use teamredminer, there is no problem. but if i switch to teamblackminer, i will get this warning.

i'm mining by ip address, please check this out. thks

47.108.249.141:443

**Comment by sp-hash** [comment]
we don't support private pools since we need to configure them. Why don't you use the full name of the pool.

**Comment by luanwulin** [comment]
> we don't support private pools since we need to configure them. Why don't you use the full name of the pool.

sorry this is not a private pool. this is a private ip of antpool，by mining through this ip,there is less latency.

if i use the domain of antpool like stratum+tcp://stratum-eth.antpool.com:443  trm has no problem,so is there any other things with my configuration?
