### ISSUE TITLE
[REQ] - Additional features for your consideration

### ISSUE THREAD

**Issue by tummyeto** [sp-hash/TeamBlackMiner#12]
- Separate Temperature reading for GPU Memory - especially useful for anyone on RTX 3000 series 
- Lock GPU core clock flag "--lock-cclock" or similar

**Comment by sp-hash** [comment]
- Lock GPU core clock flag "--lock-cclock" or similar

This can be done in the nvidiaprofile inspector. (disable force P2 State)

**Comment by sp-hash** [comment]
Temperature reading for GPU Memory  added in v1.02
