### ISSUE TITLE
low hashrate on  rx570 8gb and 1070ti

### ISSUE THREAD

**Issue by leewachu** [sp-hash/TeamBlackMiner#120]
Hi, i have problem with TBM on hiveos. Rx570 8gb with tweak but just have 28 mh/s and 1070ti just have 28 mh/s . How can I improve them? Thanks

**Comment by sp-hash** [comment]
570 works good with --xintensity 64 . you njeed to overclock memory and core to get 32-33 mhash on the 1070ti
