### ISSUE TITLE
How to use overclocking parameters? 

### ISSUE THREAD

**Issue by luoso** [sp-hash/TeamBlackMiner#121]
How to use overclocking parameters?  When I use the gminer kernel --lock_cclock 1100 --mclock 1200 these two parameters can keep 3070 at 61.56M.  However, using the two parameters of TBminer --lock-cclock [[,],[,]] --lock-mclock [[,],[,]] I tried many times and failed to overclock. How do I fill it in?

**Comment by sp-hash** [comment]
Only the corelock clock is working. the memory lock is only working for low memory clocks.

one card:

-lock_cclock [1200,1200]

6 cards:

-lock_cclock [[1200,1200], [1200,1200], [1200,1200], [1200,1200], [1200,1200],[1200,1200]]
