### ISSUE TITLE
Cpu verification failed. Share not sent to the pool

### ISSUE THREAD

**Issue by Olegik-ah** [sp-hash/TeamBlackMiner#122]
Hello!
TBM 1.21 works perfect, but if i update to 1.22 or 1.23 i have got continuous errors "Cpu verification failed. Share not sent to the pool" after switching back from ZIL to Ethash. Only miner restart helps...
It seems broken DAG file. Maybe the reason is incorrect overclock settings... But i cant understand witch gpu is the reason - afrer switching back from ZIL to Ethash ALL gpus give me incorrect shares.
I'am using hiveos (latest release, 5.4.0-hiveos #140 kernel) and nicehash pool. Algo Ethash.
Log in attachment
[teamblackminer.1.log.gz](https://github.com/sp-hash/TeamBlackMiner/files/7511522/teamblackminer.1.log.gz)

**Comment by Olegik-ah** [comment]
it seems that the bug with switching is present in version 1.21 too.
Here is the screen from another rig 8x1660S TBM 1.21:
![2021-11-10_13-12-17](https://user-images.githubusercontent.com/31293967/141094275-b7aa36d5-2e3c-4190-a694-cfdf999672dd.png)

**Comment by sp-hash** [comment]
Can you show us your launch config?

**Comment by sp-hash** [comment]
The 1660S only has 6gb of memory and TBM is storing both dag buffers in gpu memory. I think the increased epoc is causing this. But We will check if there is something we can do to fix it. Buffers shouldn't be cashed if not enough memory

**Comment by Olegik-ah** [comment]
Thanks for your reply!

This is hiveos. All default parameters
![2021-11-10_14-37-37](https://user-images.githubusercontent.com/31293967/141106505-8ad6d968-1860-4db1-83fd-ca62a2df1c78.png)

First log (Cpu verification failed) from one rig (7x1660s) TBM 1.23. Errors when switching from ZIL to ETH. Always reproduced on my rig (every switch) on 1.22/1.23. There is no error if running 1.21 on this rig.

Second log (out of memory) from another rig (8x1660s) TBM 1.21. Errors when switching from ETH to ZIL. Not always reproduced. Approximately once every 3-5 hours.

Perhaps these errors are related, perhaps not. Previously, rigs worked on Gminer/PhoenixMiner many days (10+) without errors.

**Comment by sp-hash** [comment]
Found a problem in the code that fetch the dag buffer after zil. fixed in v1.24

**Comment by Olegik-ah** [comment]
Thanks!
And when the release is planned?

**Comment by sp-hash** [comment]
v1.24 has been released now
