### ISSUE TITLE
TBM HiveOS 5700xt generates ZIL dag on ethash

### ISSUE THREAD

**Issue by RecountDust1** [sp-hash/TeamBlackMiner#123]
I am trying to setup TBM to mine ETH on a 5700xt + 3080 system. When generating the DAG files, the 5700xt (GPU0) tries to generate a ZIL dag and therefore never finds any shares. 

![image](https://user-images.githubusercontent.com/94061971/141134920-ad35857f-c05a-4c25-955d-0bf85e45cbd1.png)

I am not running any custom commands for DAG generation, xintensity or kernel selection. In Hiveos I have selected the ethash algorithm though adding `-a ethash` had no effect.

**Comment by sp-hash** [comment]
should be fixed in v1.25 please retest.
