### ISSUE TITLE
cuda 11.2

### ISSUE THREAD

**Issue by gustavofiod** [sp-hash/TeamBlackMiner#125]
![image](https://user-images.githubusercontent.com/45174143/141173410-51de9ac2-b618-417c-96da-c663bb730d50.png)
TMB needs CUDA 11.4. How do I configure 11.2 on HiveOS?

**Comment by sp-hash** [comment]
Cuda 11.2 is not supported on linux. you need to install the latest nvidia driver which support cuda 11.5.
