### ISSUE TITLE
Solo Mining ETH is interrupted /  

### ISSUE THREAD

**Issue by 0Gizmo0** [sp-hash/TeamBlackMiner#126]
Hello TB Team! I hope all is well.

I have never submitted anything on here before so if I am missing information please let me know and I will provide it :) 

Issue:

I am not sure if this is the miner or my setup but this only happens in TB miner, I start Solo Mining ETH and everything is fine and working great once it gets to 150+ shares or so, it Stops mining ETH and starts building a ZIL DAG out of no where and I have left a screenshot for you guys so you don't think I am crazy.

Once this happens shortly right after I start receiving " CPU verification failed" errors and I am not sure if they are related but it doesn't happen until the miner start building a ZIL DAG for some reason, I have left 2 screenshots any help from anyone!! would be awesome I love this miner

![TB2](https://user-images.githubusercontent.com/94086902/141213111-5273749b-5a21-4503-b18a-43910cfefc38.PNG)

![tb](https://user-images.githubusercontent.com/94086902/141212817-4ee35d55-e737-4bb9-a5ec-742611460c08.PNG)

**Comment by 0Gizmo0** [comment]
I forgot to mention that this only happens when I am using TB I have 6 hour logs on Trex to show you its working fine on other ones.

**Comment by sp-hash** [comment]
this has been fixed in v1.24

**Comment by 0Gizmo0** [comment]
Awesome I know 1.23 was just released can you tell me when 1.24 is coming
out ?

**Comment by sp-hash** [comment]
v1.24 has been released now

**Comment by 0Gizmo0** [comment]
Late response!!

Thank you so much and I must say we'll done on 1.27 :)

It's working the best it ever has for me personally on HiveOS.

Take care!!

Al
