### ISSUE TITLE
the hashrate in the pool does not match (lower than the miner shows)

### ISSUE THREAD

**Issue by strannik357753** [sp-hash/TeamBlackMiner#127]
![45654654](https://user-images.githubusercontent.com/60912947/141263134-04a8c20b-d72f-464c-b994-71b69c20dfb7.png)
![567587](https://user-images.githubusercontent.com/60912947/141263227-8dd1cfbf-ce36-41ab-8119-d5ebff25d09c.png)
![777](https://user-images.githubusercontent.com/60912947/141263634-fa48b8f0-dc77-49c9-b865-632cdc49e413.png)

perhaps the miner does not work well if it is greatly lowered PL
local hashrate 1186 mh
f2pool hashrate 1105 mh

trex miner
local hashrate 1165 mh
f2pool hashrate 1145 mh

**Comment by strannik357753** [comment]
the load on the processor also periodically rises sharpl
![7686](https://user-images.githubusercontent.com/60912947/141265008-c13aada1-426c-46b2-8bec-3b61644ac464.png)

**Comment by sp-hash** [comment]
Check the logfile for error messages. Lower the --xintensity for lower power

**Comment by sp-hash** [comment]
I tested the pool for 3 hours and all is looking good.

For nvidia add --xintensity 4096 in the launch config

![f2pool_v124](https://user-images.githubusercontent.com/9572668/141345575-9a742a28-a809-4d59-8cb8-9c717cafc6b1.png)

**Comment by strannik357753** [comment]
> I tested the pool for 3 hours and all is looking good.
> 
> client speed: 32.6 MHASH pool speed: 36 MHASH
> 
> For nvidia add --xintensity 4096 in the launch config
> 
> For amd add --xintensity 1024 in the launch config
> 
> ![f2pool_v124](https://user-images.githubusercontent.com/9572668/141345575-9a742a28-a809-4d59-8cb8-9c717cafc6b1.png)

tried 4096 and 3108 and 20 .., the hashrate graph is very ragged
![567786](https://user-images.githubusercontent.com/60912947/141645269-8e4fc10e-cde5-4a23-bb39-8b86e1561032.png)

**Comment by strannik357753** [comment]
![Снимок экрана 2021-11-13 161111](https://user-images.githubusercontent.com/60912947/141645279-c1836521-80d1-43ed-9b38-41333abdbdf3.png)

**Comment by strannik357753** [comment]
there are also spikes in CPU utilization, possibly at the time of finding solutions

**Comment by sp-hash** [comment]
There should be very little cpu usage. What cpu do you have in the rig? From the graph it looks like the miner is disconnecting to the pool. Did you find anything in the logs?

**Comment by strannik357753** [comment]
> There should be very little cpu usage. What cpu do you have in the rig? From the graph it looks like the miner is disconnecting to the pool. Did you find anything in the logs?
[teamblackminer.log](https://github.com/sp-hash/TeamBlackMiner/files/7532385/teamblackminer.log) 30x cards



attached a log, everything seems to be clean.
[teamblackminer.log](https://github.com/sp-hash/TeamBlackMiner/files/7532389/teamblackminer.log) 10x cards



[teamblackminer.log](https://github.com/sp-hash/TeamBlackMiner/files/7532393/teamblackminer.log) 10x cards
