### ISSUE TITLE
miner may freeze on restart and requires manual restart

### ISSUE THREAD

**Issue by strannik357753** [sp-hash/TeamBlackMiner#128]
![456456](https://user-images.githubusercontent.com/60912947/141347142-be11252a-3499-43b7-8948-33651a148759.png)
miner may freeze on restart and requires manual restart

**Comment by sp-hash** [comment]
what's in the miner.conf?

**Comment by strannik357753** [comment]
> что в miner.conf?

-W inno98714               -H eth-eu.f2pool.com               -p 6688               -a ethash               -w Giga                                             -N
-Z
-E 4096


this is a settings file, generated automatically hiveos

**Comment by sp-hash** [comment]
Perhaps (E) --xintensity 4096 is using too much power for your rig. Can you try to show the miner output?

**Comment by binaryf** [comment]
Is this related to connect to pool ?
Can you copy/paste in the console output.

**Comment by strannik357753** [comment]
> Is this related to connect to pool ? Can you copy/paste in the console output.

when to repeat, I will copy. most likely due to the miner not releasing the api port

**Comment by strannik357753** [comment]
> Perhaps (E) --xintensity 4096 is using too much power for your rig. Can you try to show the miner output? What cards do you have? try to reduce to 2048

ok
1070-1070ti-1080ti-2070-3060ti-3070

**Comment by binaryf** [comment]
Yep now i see.
Will add close socket on any exit.
