### ISSUE TITLE
Have a rig on ETH running all same 5700 samsumg cards only two GPU are  hashing @ 50.00 Mh but other 4 gpu are at 2444 khs. 

### ISSUE THREAD

**Issue by Whatname21** [sp-hash/TeamBlackMiner#129]

**Comment by binaryf** [comment]
Is this Windows 10 Cuda 11.5 build ?

**Comment by sp-hash** [comment]
The clocks are probobly too high. Try to reduce the clocks

**Comment by Whatname21** [comment]
The problem is the amd drivers hiveos needs 2040(5.11.0701) to run the miner. Have 2030 amd drivers on this rig all others running great on 2040 with same clocks. Nice hash increase on all amd cards on teamblackminer no need to bios mod.ty will lower clocks

**Comment by Whatname21** [comment]
Flux on nivia lhr could be a nice addition to the miner.
