### ISSUE TITLE
What is the best pools for this miner ? 

### ISSUE THREAD

**Issue by Youssef-Mekkaoui** [sp-hash/TeamBlackMiner#130]
Hello

What about ethermine ?

you don't say anything in FAQ.

**Comment by sp-hash** [comment]
Depends on the cards you have

Ethermine is good with --xintensity 24 on rx6700xt

**Comment by Youssef-Mekkaoui** [comment]
Full RIG : 6 x RTX  3090

One rig : 2 x RTX 3070 NON LHR +
               2 x RTX 3060 TI Non LHR

Whaty would you recommend

**Comment by sp-hash** [comment]
Switch to a pool that pay for stale shares.

**Comment by sp-hash** [comment]
On ethermine you can try --xintensity 64 or --xintensity 128 and use --kernel 8
