### ISSUE TITLE
Polaris GPU's not showing in Hive

### ISSUE THREAD

**Issue by JonC69** [sp-hash/TeamBlackMiner#131]
![TBM error](https://user-images.githubusercontent.com/94190539/141506252-3caef5f6-6228-488c-8e02-d7bc9b8aa709.JPG)
Any assistance with Polaris RX 580 cards not showing up when using TBM?
are they unsupported at present?

**Comment by sp-hash** [comment]
Upgrade to the the latest hiveos image.

**Comment by sp-hash** [comment]
this issue has been fixed in v1.51
