### ISSUE TITLE
Некрасивое отображение майнера))

### ISSUE THREAD

**Issue by Kolhoz33** [sp-hash/TeamBlackMiner#132]
Собственно ваш скрин в релизах совершенно не похож на то, что отображается в майнере...

как поправить?

https://i.imgsrc.com/cfm5n.png - ваш скрин
https://i.imgsrc.com/cfCo6.png - скрин с майнера

версия последняя, под виндой

это может быть связано с ???
`Could not open file: C:\Users\╨Ъ╨╛╨╗╤Е╨╛╨╖╨╜╨╕╨║\AppData\Local\Temp\dep-a45fc8.d`

**Comment by binaryf** [comment]
These codes are ANSI codes for displayin colors in the terminal.
Run the ansicolor.reg script in the 7zip archive to activate.

**Comment by sp-hash** [comment]
Запустите сценарий ansicolor.reg из архива 7zip, чтобы активировать цвета в программной консоли Windows.
