### ISSUE TITLE
Team Black Miner v1.24 with rejected shares

### ISSUE THREAD

**Issue by TunayCVS** [sp-hash/TeamBlackMiner#133]
When I mining with Team Black Miner on the my rig with amd 6600 xt and 6700 xt cards, I get at least 6-7 rejected shares in 1 hour and the efficiency drops under 97-98% on Hiveon Pool.

![Screenshot_20211113-234339_Hive OS](https://user-images.githubusercontent.com/45500622/141658602-5174d0ed-4ac9-442e-afd3-16324aae52d5.jpg)

**Comment by sp-hash** [comment]
try to add --xintensity 24

**Comment by sp-hash** [comment]
This bug was finally Fixed in v1.60
