### ISSUE TITLE
On a system with russian unicode (Cyrillic), the console looks strange.

### ISSUE THREAD

**Issue by code-audits** [sp-hash/TeamBlackMiner#134]
Hello,

I downloaded the miner and set it up according to the instructions: https://bytwork.com/en/soft/teamblackminer

On a system with russian Unicode (Cyrillic), the console looks strange.

![img-2021-11-14-14-01-44](https://user-images.githubusercontent.com/94292315/141678280-44213972-824a-45a5-8a6e-a9f103da1de9.png)

There are obviously extra characters in the console. How to remove them?

**Comment by sp-hash** [comment]
These codes are ANSI codes for displaying colors in the terminal.
Run the ansicolor.reg script in the 7zip archive to activate.

or you can run with --no-ansi

**Comment by code-audits** [comment]
> These codes are ANSI codes for displaying colors in the terminal. Run the ansicolor.reg script in the 7zip archive to activate.
> 
> or you can run with --no-ansi

Thanks. It works (`--no-ansi`). It might make sense to do this automatically, so that these characters are not by default.

**Comment by sp-hash** [comment]
but why don't you want colors?

Doubleclick on ansicolors.reg to enable colors in the windows terminal

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"VirtualTerminalLevel"=dword:00000001
