### ISSUE TITLE
Mix Polaris&RDNA GPU's not showing in HiveOS

### ISSUE THREAD

**Issue by Trololoooolololololo** [sp-hash/TeamBlackMiner#135]
TeamBlackMiner v.1.25. Hiveos-0.6-211-stable@211104 - latest, OpenCL 20.40-5.11.1001 - latest
![Screenshot_1](https://user-images.githubusercontent.com/94353393/141748586-c9161c12-c561-4206-9aee-81e77dfb878f.png)

RX580 not showing 
the commands didn't help: --auto-detect, --cl-all-devices, --amd-only, -xintensity [-1], --dagintensity [1].
Can you suggest more options?

**Comment by sp-hash** [comment]
can you ssh into the rig and run
$ tbminer --list-devices
 
?

**Comment by sp-hash** [comment]
we have tested TBM v1.25 in hiveos-0.6-211-stable@211104 with a gtx 1070 and a rx 580 card in the rig and it works fine.

**Comment by Trololoooolololololo** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/94353393/141777623-4197103b-322f-4a1e-8377-344871b2dc05.png)

What am I doing wrong?

**Comment by Trololoooolololololo** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/94353393/141778018-4d1b6add-4717-4b51-b7a4-b5178e366a56.png)

**Comment by Trololoooolololololo** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/94353393/141779300-7fe91a6c-2cba-4ccb-89a0-9fe853b25031.png)

**Comment by binaryf** [comment]
The cards are not showing up i see.

**Comment by sp-hash** [comment]
https://hiveos.farm/guides-amd_dr/ ?

**Comment by Trololoooolololololo** [comment]
> https://hiveos.farm/guides-amd_dr/ ?

I did this procedure before this topic, I chose version number 24, 
 "Do you want have RX4xx/RX5xx?(y/n)" - yes.
![Screenshot_4](https://user-images.githubusercontent.com/94353393/141786243-85dd4c7c-4308-44f1-9de8-2f30adbf4730.png)

**Comment by JonC69** [comment]
I have the same issue, rx 580 cards not showing up in a rig mixed with 6700xt's

**Comment by HedgeComp** [comment]
I also can confirm the same issue with an RX580. it is not detected at all. 
I did notice that when using the -D or --list-devices It shows that the BUS id has the same Card in the same bus which is not correct!
![BusId](https://user-images.githubusercontent.com/94635857/142490478-051e8643-253c-4f51-b611-2320caa6f865.jpg)

When I look at HiveOS this is the correct order of the Cards.
![HiveCardorder](https://user-images.githubusercontent.com/94635857/142490692-41075b54-4887-4497-a593-792929db3a33.jpg)

So it appears bus id 0 and 2 are detected in TBM as both being 3070

**Comment by HedgeComp** [comment]
update. did some more testing and re-arranged the PCI bus ports to test and the same issue occurs. What ever bus the RX580 is in , the 3070 is also appearing as listed by TBM as being in the same bus.

**Comment by HedgeComp** [comment]
Here is a shot from the console of hive OS confirming the GPU order:

![image](https://user-images.githubusercontent.com/94635857/142492480-1201047e-518e-4c69-8395-09be503c4629.png)

**Comment by sp-hash** [comment]
I still think this is a driver problem. Did you upgrade to the latest image? You need the latest drivers.
When installing AMD drivers in hiveos you are asked id you have 480/580 cards in the rig. And you have to select yes.

**Comment by HedgeComp** [comment]
I have already done that procedure and I was already running the latest AMD drivers. But I just reran  the script and selected yes to the RX580 prompt again. It made no difference.

I have been using Team Red Miner without any issue for months , so not sure this was an AMD driver issue if I can view it in other miners!??
