### ISSUE TITLE
Does this miner work with new Nvidia drivers beyond 472.12?

### ISSUE THREAD

**Issue by Globespy** [sp-hash/TeamBlackMiner#140]
Seems every other miner is having big issues with all Nvidia drivers beyond 472.12 and wondering if anyone has tested with newer drivers?
Thank you.

**Comment by sp-hash** [comment]
no issues with newer drivers

**Comment by Globespy** [comment]
> No issues with newer drivers. You should always use the latest driver on the Team Black Miner.

Thank you for the reply!
Wonder what magic you cooked into this miner to avoid the problems currently faced by GMiner, NBMiner and T-Rex?
What Nvidia driver are you using currently?
I'll test it out.

**Comment by sp-hash** [comment]
On windows you can use 496.76

**Comment by Globespy** [comment]
Nice! Will test.
