### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by GAV1974** [sp-hash/TeamBlackMiner#141]
![Снимок экрана (16)](https://user-images.githubusercontent.com/38362545/142632510-7d00e264-f47a-41a1-a599-135a95fa0210.png)

**Comment by sp-hash** [comment]
This is not the latest version. v1.26 has just been released. What is you launch config?

**Comment by binaryf** [comment]
Will investigate, but this looks like just what the error message says: No data from pool.

**Comment by GAV1974** [comment]
On version 1.26, the same error. I do not use the config, via the bat file.

**Comment by binaryf** [comment]
I think we solved this issue today. It is solved in next version.
Thank you for reporting.
