### ISSUE TITLE
Error(22): Duplicate share

### ISSUE THREAD

**Issue by gochisar** [sp-hash/TeamBlackMiner#143]
00:00:02 [2021-11-20 01:03:14.209] Job adc8eeddc3aa7715
00:00:02 [2021-11-20 01:03:14.651] Job 52678520e0eca787
00:00:02 [2021-11-20 01:03:14.761] Job 8860657a567350ff
00:00:02 [2021-11-20 01:03:15.751] GPU0 Solution found in 1.09s (Submit every 65.84 seconds)
00:00:02 [2021-11-20 01:03:15.841] GPU:0 Rejected (1/2) Reply: 89ms
00:00:02 [2021-11-20 01:03:15.841] mining.submit: Pool reponded with error
00:00:02 [2021-11-20 01:03:15.841] Error(22): Duplicate share
00:00:02 [2021-11-20 01:03:16.195] Job eaab86ee3bde6f06
00:00:02 [2021-11-20 01:03:16.305] Job 62f917465a6f37b5
00:00:02 [2021-11-20 01:03:18.175] Job 2c0f28f89e84631b
00:00:02 [2021-11-20 01:03:18.285] Job b90bd7c0541cca67
00:00:02 [2021-11-20 01:03:18.617] GPU0 Solution found in 0.34s (Submit every 44.96 seconds)
00:00:02 [2021-11-20 01:03:18.709] Accepted (2/3/0) Reply: 90ms
00:00:02 [2021-11-20 01:03:21.033] GPU0 Solution found in 2.75s (Submit every 35.01 seconds)
00:00:02 [2021-11-20 01:03:21.194] GPU:0 Rejected (2/4) Reply: 160ms
00:00:02 [2021-11-20 01:03:21.194] mining.submit: Pool reponded with error
00:00:02 [2021-11-20 01:03:21.194] Error(22): Duplicate share
00:00:02 [2021-11-20 01:03:21.257] GPU0 Solution found in 2.98s (Submit every 28.65 seconds)
00:00:02 [2021-11-20 01:03:21.352] GPU:0 Rejected (2/5) Reply: 94ms
00:00:02 [2021-11-20 01:03:21.352] mining.submit: Pool reponded with error
00:00:02 [2021-11-20 01:03:21.352] Error(22): Duplicate share
00:00:02 [2021-11-20 01:03:21.370] Job c0ee167a701e8a83
00:00:02 [2021-11-20 01:03:21.591] Job 84c81b2124f927f9
00:00:02 [2021-11-20 01:03:21.812] Job 26a3bceb73d1eb28
00:00:02 [2021-11-20 01:03:22.252] Job b414f3765b16939d
00:00:02 [2021-11-20 01:03:22.364] Job 4a9ae214fdbe3910
00:00:02 [2021-11-20 01:03:23.405] GPU1 Solution found in 1.12s (Submit every 24.42 seconds)
00:00:02 [2021-11-20 01:03:23.514] Accepted (3/6/0) Reply: 108ms
00:00:02 [2021-11-20 01:03:24.778] Job d8e0c26b1bedb655
00:00:02 [2021-11-20 01:03:24.889] Job ab57975ee29cba80

tb miner 1.26 cuda 11.5

2 GPU,   3080 and 3080 LHR
hiveon pool
program sends solutions twice

**Comment by sp-hash** [comment]
The hiveon pool will report duplicate share for every rejected share. Are you using LHR mode on the 3080LHR? default intensity?

**Comment by dsimka** [comment]
rx6600xt + hiveos 
Duplicate shares , when using TBM on hiveon pool.
Increased stales ot both pools hiveon and ethermine. I never had rejected with gminer or nbminer, with keeping low % stales like under 1.4%
Insane high reported hashrate compared to other miners???

00:01:45 [2021-11-19 22:40:32.100] eu-eth.hiveon.net (ethash)    PING: 100ms    DIFFICULTY: 268.43 M    EPOCH: 454
00:01:45 [2021-11-19 22:40:32.100]                                                                                 
00:01:45 [2021-11-19 22:40:32.100] 
00:01:45 [2021-11-19 22:40:32.100] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:45 [2021-11-19 22:40:32.100] GPU0    gfx1032  OpenCL  0       0       0/0     0       0       0       0      
00:01:45 [2021-11-19 22:40:32.100] GPU1    gfx1032  OpenCL  0       0       57/0    73      1100    1124    55     
00:01:45 [2021-11-19 22:40:32.100] GPU2    gfx1032  OpenCL  0       0       58/0    81      1100    1124    54     
00:01:45 [2021-11-19 22:40:32.100] GPU3    gfx1032  OpenCL  0       0       59/0    73      1100    1124    55     
00:01:45 [2021-11-19 22:40:32.100] GPU4    gfx1032  OpenCL  0       0       0/0     0       0       0       0      
00:01:45 [2021-11-19 22:40:32.100] GPU5    gfx1032  OpenCL  0       0       0/0     0       0       0       0      
00:01:45 [2021-11-19 22:40:32.100] GPU6    gfx1032  OpenCL  0       0       48/0    73      1100    1124    55     
00:01:45 [2021-11-19 22:40:32.100] GPU7    gfx1032  OpenCL  0       0       56/0    81      1100    1124    51     
00:01:45 [2021-11-19 22:40:32.100]                                                                          270    
00:01:45 [2021-11-19 22:40:32.100] 
00:01:45 [2021-11-19 22:40:32.100] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:45 [2021-11-19 22:40:32.100] GPU0    gfx1032  0.00 H/W      33.63 MH/s    33.62 MH/s    50/0/9       100.00% 
00:01:45 [2021-11-19 22:40:32.100] GPU1    gfx1032  615.26 kH/W   33.84 MH/s    33.77 MH/s    52/1/10      98.11%  
00:01:45 [2021-11-19 22:40:32.100] GPU2    gfx1032  624.58 kH/W   33.73 MH/s    33.44 MH/s    46/2/7       95.83%  
00:01:45 [2021-11-19 22:40:32.100] GPU3    gfx1032  604.43 kH/W   33.85 MH/s    33.41 MH/s    42/0/8       100.00% 
00:01:45 [2021-11-19 22:40:32.100] GPU4    gfx1032  0.00 H/W      34.41 MH/s    33.25 MH/s    56/1/9       98.25%  
00:01:45 [2021-11-19 22:40:32.100] GPU5    gfx1032  0.00 H/W      33.45 MH/s    33.56 MH/s    68/0/15      100.00% 
00:01:45 [2021-11-19 22:40:32.100] GPU6    gfx1032  616.09 kH/W   33.89 MH/s    33.75 MH/s    43/1/9       97.73%  
00:01:45 [2021-11-19 22:40:32.100] GPU7    gfx1032  664.30 kH/W   33.88 MH/s    33.31 MH/s    44/0/5       100.00% 
00:01:45 [2021-11-19 22:40:32.100]                  3124.66 kH/W  270.67 MH/s   268.12 MH/s   401/5/72     98.77%  
00:01:45 [2021-11-19 22:40:32.100]                                                                                 
00:01:45 [2021-11-19 22:40:32.100] SHARES PER MINUTE: 3.97                              POOL HASHRATE: 284.21 MH/s

ethermine
00:01:21 [2021-11-19 22:47:13.010] eu1.ethermine.org (ethash)    PING: 57ms    DIFFICULTY: 1.00     EPOCH: 454
00:01:21 [2021-11-19 22:47:13.010]                                                                                 
00:01:21 [2021-11-19 22:47:13.010] 
00:01:21 [2021-11-19 22:47:13.010] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:21 [2021-11-19 22:47:13.010] GPU0    gfx1032  OpenCL  0       24      0/0     0       0       0       0      
00:01:21 [2021-11-19 22:47:13.010] GPU1    gfx1032  OpenCL  0       24      46/0    73      1100    1124    53     
00:01:21 [2021-11-19 22:47:13.010] GPU2    gfx1032  OpenCL  0       24      48/0    73      1100    1124    54     
00:01:21 [2021-11-19 22:47:13.010] GPU3    gfx1032  OpenCL  0       24      49/0    73      1100    1124    51     
00:01:21 [2021-11-19 22:47:13.010] GPU4    gfx1032  OpenCL  0       24      0/0     0       0       0       0      
00:01:21 [2021-11-19 22:47:13.010] GPU5    gfx1032  OpenCL  0       24      0/0     0       0       0       0      
00:01:21 [2021-11-19 22:47:13.010] GPU6    gfx1032  OpenCL  0       24      49/0    73      1100    1109    53     
00:01:21 [2021-11-19 22:47:13.010] GPU7    gfx1032  OpenCL  0       24      54/0    73      1100    1150    49     
00:01:21 [2021-11-19 22:47:13.010]                                                                          260    
00:01:21 [2021-11-19 22:47:13.010] 
00:01:21 [2021-11-19 22:47:13.010] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:21 [2021-11-19 22:47:13.010] GPU0    gfx1032  0.00 H/W      32.87 MH/s    32.89 MH/s    24/0/0       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU1    gfx1032  623.98 kH/W   33.70 MH/s    33.71 MH/s    34/1/0       97.14%  
00:01:21 [2021-11-19 22:47:13.010] GPU2    gfx1032  613.13 kH/W   33.72 MH/s    33.75 MH/s    28/0/0       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU3    gfx1032  648.32 kH/W   33.71 MH/s    33.71 MH/s    28/0/0       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU4    gfx1032  0.00 H/W      34.46 MH/s    34.47 MH/s    26/0/1       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU5    gfx1032  0.00 H/W      34.47 MH/s    34.49 MH/s    46/0/1       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU6    gfx1032  628.35 kH/W   33.30 MH/s    33.32 MH/s    30/0/0       100.00% 
00:01:21 [2021-11-19 22:47:13.010] GPU7    gfx1032  672.69 kH/W   34.31 MH/s    34.34 MH/s    36/0/0       100.00% 
00:01:21 [2021-11-19 22:47:13.010]                  3186.48 kH/W  270.55 MH/s   270.68 MH/s   252/1/2      99.60%  
00:01:21 [2021-11-19 22:47:13.010]                                                                                 
00:01:21 [2021-11-19 22:47:13.010] SHARES PER MINUTE: 3.15                              POOL HASHRATE: 225.49 MH/s
Ethermine rejected 1

**Comment by gochisar** [comment]
i am try different scenarios.
Only 3080
Only 3080 LHR
3080 card with tb miner, 3080LHR with nbminer
3080 and 3080 LHR tb miner
if i use LHR card in any scenario, system LHR lock is affect other cards, drop down hashrates. 

tb miner 1.27 cuda 11.5 not work, exit with error.

if i start msi afterburner OC scanner, LHR cards gets more stable shares.
programmer must be think memory control subroutine interruption for LHR unblock

**Comment by sp-hash** [comment]
This is not version 1.27.  Try the latest version for duplicate shares fix.

**Comment by sp-hash** [comment]
This miner works best on pools that pay for stale shares.

On 2miners.com you can use --xintensity 1042 then you get improved poolside hashrate.

https://github.com/sp-hash/TeamBlackMiner/blob/main/FAQ.md

**Comment by sp-hash** [comment]
Whats the error? can you show a screenshot?

**Comment by sp-hash** [comment]
The cuda11_5 build was broken, so we have uploaded another one

**Comment by sp-hash** [comment]
Should be fixed in v1.28
