### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#144]
Hi, thank you for this awesome miner! It works great on my HiveOS system.

However, when I tried to run it on my CentOS 7 system, it gave a segmentation fault error immediately, even when I am just doing ./TBMiner --help. I also tried to run it in a Ubuntu 18.04 container and it still gave seg fault... I am using NVidia Driver Version: 470.57.02 CUDA Version: 11.4

Miners like GMiner have binaries that can work across many distros including CentOS 7. Is it possible you can provide binaries that can work on CentOS 7? I know it is an old OS, but I doubt there will be any performance hit for ETH compared to Ubuntu 18.

Thanks in advance!

**Comment by binaryf** [comment]
Yes. Noted. We want the linux build to work on as many Linux OSes as possible.

**Comment by hintro32** [comment]
> Yes. Noted. We want the linux build to work on as many Linux OSes as possible.

Thanks! Do you think you will be able to release a compatible build soon?
