### ISSUE TITLE
p104-100 

### ISSUE THREAD

**Issue by joginvik1** [sp-hash/TeamBlackMiner#147]
I have a rig with 6 1070 and 1 p104-100

cuda 0 to 6

cuda 0 (p 104-100) does not work, all 6 1070 work fine

TeamBlackMiner_1_27_cuda_11_4 

:loop
	TBMiner --algo ethash --hostname eu1.ethermine.org --port 4444 --wallet %ETH_WALLET% --worker-name %computername% -L --cuda-devices [1,2,3,4,5,6]
	timeout 10
goto :loop

**Comment by sp-hash** [comment]
Does it work with --kernel 0 or 1?

**Comment by joginvik1** [comment]
Its strange, but some 1070 work on kernel 0, other on kernel 1

**Comment by sp-hash** [comment]
If you don't specify --kernel parameter, the program will time all of the kernels and fins the fastest one. Gtx 1070 kernel 0 and 1 is usually the best one. In v1.28 we will do a change in the --dagintensity 1 option to try to avoid the crash on P104-100

**Comment by binaryf** [comment]
I think this one is not going into TBMiner Stable 1.0.
This is sp-hash's table, and even he could not do it :)
