### ISSUE TITLE
pool is not supported issue

### ISSUE THREAD

**Issue by DeanJing** [sp-hash/TeamBlackMiner#148]
00:00:00 [2021-11-22 15:47:04.857]                                                                                 
00:00:00 [2021-11-22 15:47:04.857] Sorry the provided pool is not supported
00:00:00 [2021-11-22 15:47:04.857] If you think this pool should be, then ask us to configure it
00:00:00 [2021-11-22 15:47:04.857] Shutting down threads
00:00:00 [2021-11-22 15:47:08.857] Exiting

Hi Boss,

It is not encouraged in China, so we would like to use a VPS to forward connections to pool, currently raw ip is not allow?

So, could you support this suitation?

**Comment by sp-hash** [comment]
We will add support for ip connection to all the pools we support in the next release.

**Comment by maktan38** [comment]
how do i set it up for miningrigrentals?

**Comment by sp-hash** [comment]
We currently have a bug in miningrentals when calculating the target.

**Comment by sp-hash** [comment]
raw ip of the pools we support is implemented in v1.28
