### ISSUE TITLE
ETC Pool Request

### ISSUE THREAD

**Issue by djkj84** [sp-hash/TeamBlackMiner#149]
Hi, would it possible to add support for "ETCMining.Club" please. 

stratum+tcp://etcmining.club:8008

Thanks

**Comment by sp-hash** [comment]
This pool doesn't have any payouts yet. Perhaps we can add it later when it grows.

**Comment by djkj84** [comment]
Payouts are happening now, we've finished the project and its now completely active.

**Comment by binaryf** [comment]
Will be added in next release.
