### ISSUE TITLE
Miner is not sharing data with pool

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#15]
The miner is connected to the pool, it is hashing but not sending solutions to the pool.

Script:
TBMiner --algo ethash -H us-eth.2miners.com -s -n -x 12020 --wallet %ETH_WALLET% --worker_name BlackTest --xintensity -1

Log output:
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m407←[0m←[1m]←[0m ←[7mOpenCL driver version: 471.96←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m407←[0m←[1m]←[0m ←[7mCuda driver version: 11.4←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m407←[0m←[1m]←[0m ←[7mCuda runtime API version: 11.4←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m407←[0m←[1m]←[0m ←[0m←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m407←[0m←[1m]←[0m ←[4m                                ←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m408←[0m←[1m]←[0m ←[0m←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m408←[0m←[1m]←[0m ←[1mWelcome to Team Black Miner 1.03←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m408←[0m←[1m]←[0m ←[4m                                ←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m408←[0m←[1m]←[0m ←[0m←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m559←[0m←[1m]←[0m ←[32mGPU0 NVIDIA GeForce RTX 3090 25GB (compute 8.6) added to miner as Cuda device←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m743←[0m←[1m]←[0m ←[32mGPU0 Started Cuda work thread←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m784←[0m←[1m]←[0m ←[1;36mTrying https://us-eth.2miners.com:12020 (ethash)←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m820←[0m←[1m]←[0m ←[36mExtranonce is set to 9387190473300377600←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m820←[0m←[1m]←[0m ←[32mPool responded successfully to subscribe←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m864←[0m←[1m]←[0m ←[32mPool responded successfully to extranonce subscribe←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m879←[0m←[1m]←[0m ←[36mExtranonce is set to 9387190473300377600←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m895←[0m←[1m]←[0m ←[36mExtranonce is set to 9387471948277088256←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m895←[0m←[1m]←[0m ←[32mPool responded successfully to authorize←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:07.←[0m←[0m910←[0m←[1m]←[0m ←[36mdifficulty is set to 2.031715←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:12.←[0m←[0m108←[0m←[1m]←[0m ←[36mGPU0 Starting generating ethash dag (Epoch: 440)←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:12.←[0m←[0m238←[0m←[1m]←[0m ←[36mGPU0 DAG generated in 4.30 seconds (4653054kb)←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:12.←[0m←[0m238←[0m←[1m]←[0m ←[36mGPU0 XIntensity set to Dynamic←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:12.←[0m←[0m238←[0m←[1m]←[0m ←[35mJob 3477a←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:19.←[0m←[0m202←[0m←[1m]←[0m ←[35mJob 3477c←[0m
←[1;36m     0m←[0m ←[1m[2021-09-13 10:00:20.←[0m←[0m959←[0m←[1m]←[0m ←[36mGPU0 Dag buffer verified ok!←[0m
	 
	 1m [2021-09-13 10:01:08.126] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     1m [2021-09-13 10:01:08.126] GPU0  3090    48/0    92      1669    10893   344     0.34    inf
     1m [2021-09-13 10:01:08.126]                                               344     0.34    inf
     1m [2021-09-13 10:01:08.126]
     1m [2021-09-13 10:01:08.126] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     1m [2021-09-13 10:01:08.126] GPU0  3090    Cuda    378.13 kH/W     130.08 MH/s     0.00 H/s        0/0/0 (100.00)
     1m [2021-09-13 10:01:08.126]                       378.13 kH/s     130.08 MH/s     0.00 H/s        0/0/0 (100.00)
     1m [2021-09-13 10:01:08.126]
     1m [2021-09-13 10:01:08.126]
     1m [2021-09-13 10:01:09.869] GPU0 Solution found in 3.71s (Submit every 62.53 seconds)
     1m [2021-09-13 10:01:14.665] GPU0 Solution found in 3.19s (Submit every 33.66 seconds)
     1m [2021-09-13 10:02:00.376] GPU0 Solution found in 4.48s (Submit every 37.67 seconds)

     2m [2021-09-13 10:02:09.140]
     2m [2021-09-13 10:02:09.140]
     2m [2021-09-13 10:02:09.140] https://us-eth.2miners.com:12020 (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     2m [2021-09-13 10:02:09.140]
     2m [2021-09-13 10:02:09.140]
     2m [2021-09-13 10:02:09.140] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     2m [2021-09-13 10:02:09.140] GPU0  3090    51/0    92      1662    10893   343     0.34    inf
     2m [2021-09-13 10:02:09.140]                                               343     0.34    inf
     2m [2021-09-13 10:02:09.140]
     2m [2021-09-13 10:02:09.140] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     2m [2021-09-13 10:02:09.140] GPU0  3090    Cuda    379.33 kH/W     130.11 MH/s     124.45 MH/s     0/0/0 (100.00)
     2m [2021-09-13 10:02:09.140]                       379.33 kH/s     130.11 MH/s     124.45 MH/s     0/0/0 (100.00)
     2m [2021-09-13 10:02:09.140]

	 2m [2021-09-13 10:02:09.140]

     2m [2021-09-13 10:03:06.559] GPU0 Solution found in 6.62s (Submit every 43.10 seconds)

     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164] https://us-eth.2miners.com:12020 (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     3m [2021-09-13 10:03:10.164] GPU0  3090    49/0    92      1669    10893   343     0.34    inf
     3m [2021-09-13 10:03:10.164]                                               343     0.34    inf
     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     3m [2021-09-13 10:03:10.164] GPU0  3090    Cuda    379.02 kH/W     130.00 MH/s     128.78 MH/s     0/0/0 (100.00)
     3m [2021-09-13 10:03:10.164]                       379.02 kH/s     130.00 MH/s     128.78 MH/s     0/0/0 (100.00)
     3m [2021-09-13 10:03:10.164]
     3m [2021-09-13 10:03:10.164]

     3m [2021-09-13 10:03:16.962] GPU0 Solution found in 2.38s (Submit every 37.91 seconds)

     4m [2021-09-13 10:04:11.156]
     4m [2021-09-13 10:04:11.156]
     4m [2021-09-13 10:04:11.156] https://us-eth.2miners.com:12020 (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     4m [2021-09-13 10:04:11.156]
     4m [2021-09-13 10:04:11.156]
     4m [2021-09-13 10:04:11.156] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     4m [2021-09-13 10:04:11.156] GPU0  3090    52/0    92      1660    10893   343     0.34    inf
     4m [2021-09-13 10:04:11.156]                                               343     0.34    inf
     4m [2021-09-13 10:04:11.156]
     4m [2021-09-13 10:04:11.156] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     4m [2021-09-13 10:04:11.156] GPU0  3090    Cuda    378.66 kH/W     129.88 MH/s     123.27 MH/s     0/0/0 (100.00)
     4m [2021-09-13 10:04:11.156]                       378.66 kH/s     129.88 MH/s     123.27 MH/s     0/0/0 (100.00)

     5m [2021-09-13 10:05:18.736] https://us-eth.2miners.com:12020 (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     5m [2021-09-13 10:05:18.736] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     5m [2021-09-13 10:05:18.736] GPU0  3090    43/0    92      173     454     60      0.06    inf
     5m [2021-09-13 10:05:18.736]                                               60      0.06    inf
     5m [2021-09-13 10:05:18.736]
     5m [2021-09-13 10:05:18.736] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     5m [2021-09-13 10:05:18.736] GPU0  3090    Cuda    2161.25 kH/W    129.67 MH/s     125.55 MH/s     0/0/0 (100.00)
     5m [2021-09-13 10:05:18.736]                       2161.25 kH/s    129.67 MH/s     125.55 MH/s     0/0/0 (100.00)
     5m [2021-09-13 10:05:41.413] GPU0 Solution found in 5.46s (Submit every 55.67 seconds)
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:19.145] https://us-eth.2miners.com:12020 (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:19.145] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     6m [2021-09-13 10:06:19.145] GPU0  3090    51/0    92      1663    10893   343     0.34    inf
     6m [2021-09-13 10:06:19.145]                                               343     0.34    inf
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:19.145] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     6m [2021-09-13 10:06:19.145] GPU0  3090    Cuda    374.51 kH/W     128.46 MH/s     114.20 MH/s     0/0/0 (100.00)
     6m [2021-09-13 10:06:19.145]                       374.51 kH/s     128.46 MH/s     114.20 MH/s     0/0/0 (100.00)
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:19.145]
     6m [2021-09-13 10:06:21.829] Shutting down threads
     6m [2021-09-13 10:06:21.833] Control thread exited
     6m [2021-09-13 10:06:21.833] Stratum thread exited
     6m [2021-09-13 10:06:21.851] GPU0 thread exited
     6m [2021-09-13 10:06:25.832] Exiting

**Comment by KillrBee** [comment]
I was able to get shares pushed to the pool when I simultaneously opened a t-Rex instance.

**Comment by sp-hash** [comment]
The bug has been fixed. Will release a patch later today

**Comment by KillrBee** [comment]
Shares are accepted with --no-cpu flag is active, but only before 'ansi' logging starts:

TBMiner --algo ethash -H us-eth.2miners.com -s -n -x 12020 --wallet %ETH_WALLET% --worker_name BlackTest --xintensity -1 -L --no-cpu

0m [2021-09-13 10:57:24.985] OpenCL driver version: 471.96
     0m [2021-09-13 10:57:24.985] Cuda driver version: 11.4
     0m [2021-09-13 10:57:24.985] Cuda runtime API version: 11.4
     0m [2021-09-13 10:57:24.985] 
     0m [2021-09-13 10:57:24.985]                                 
     0m [2021-09-13 10:57:24.985] 
     0m [2021-09-13 10:57:24.985] Welcome to Team Black Miner 1.03
     0m [2021-09-13 10:57:24.985]                                 
     0m [2021-09-13 10:57:24.985] 
     0m [2021-09-13 10:57:25.136] GPU0 NVIDIA GeForce RTX 3090 25GB (compute 8.6) added to miner as Cuda device
     0m [2021-09-13 10:57:25.316] Trying https://us-eth.2miners.com:12020 (ethash)
     0m [2021-09-13 10:57:25.340] GPU0 Started Cuda work thread
     0m [2021-09-13 10:57:25.358] Extranonce is set to 9291488981218754560
     0m [2021-09-13 10:57:25.358] Pool responded successfully to subscribe
     0m [2021-09-13 10:57:25.406] Pool responded successfully to extranonce subscribe
     0m [2021-09-13 10:57:25.422] Extranonce is set to 9291488981218754560
     0m [2021-09-13 10:57:25.422] Extranonce is set to 9291770456195465216
     0m [2021-09-13 10:57:25.437] Pool responded successfully to authorize
     0m [2021-09-13 10:57:25.455] difficulty is set to 2.031715
     0m [2021-09-13 10:57:29.687] GPU0 Starting generating ethash dag (Epoch: 440)
     0m [2021-09-13 10:57:29.812] GPU0 DAG generated in 4.33 seconds (4653054kb)
     0m [2021-09-13 10:57:29.812] GPU0 XIntensity set to Dynamic
     0m [2021-09-13 10:57:29.812] Job 6cc2c
     0m [2021-09-13 10:57:37.154] Job 6cc2f
     0m [2021-09-13 10:57:38.797] GPU0 Dag buffer verified ok!
     0m [2021-09-13 10:57:44.446] Job 6cc30
     0m [2021-09-13 10:57:45.773] GPU0 Solution found in 1.66s (Submit every 20.88 seconds)
*****  ^  This was sent to Pool   ^  *******
     0m [2021-09-13 10:57:45.820] Accepted (1/1/0) Reply: 47ms
     0m [2021-09-13 10:57:51.524] Job 6cc31
     0m [2021-09-13 10:57:57.190] Job 6cc33
     0m [2021-09-13 10:58:04.251] Job 6cc34
     0m [2021-09-13 10:58:09.181] Job 6cc35
     0m [2021-09-13 10:58:12.708] GPU0 Solution found in 4.13s (Submit every 23.91 seconds)
*****  ^  This was sent to Pool   ^  *******
     0m [2021-09-13 10:58:12.744] Accepted (2/2/0) Reply: 35ms
     0m [2021-09-13 10:58:16.230] Job 6cc36
     0m [2021-09-13 10:58:23.636] Job 6cc37
     1m [2021-09-13 10:58:26.163] 
     1m [2021-09-13 10:58:26.163] 
     1m [2021-09-13 10:58:26.163] https://us-eth.2miners.com:12020 (ethash)    PING: 41ms    DIFFICULTY: 2.03     EPOCH: 440
     1m [2021-09-13 10:58:26.163]                                                                                           
     1m [2021-09-13 10:58:26.163] 
     1m [2021-09-13 10:58:26.163] ID	BOARD	TEMP	FAN	CORE	MEM	WATT	kW/h	COST/h
     1m [2021-09-13 10:58:26.163] GPU0	3090	50/0	92	1640	10893	343	0.34	inf
     1m [2021-09-13 10:58:26.163] 						343	0.34	inf
     1m [2021-09-13 10:58:26.163] 
     1m [2021-09-13 10:58:26.163] ID	BOARD	TYPE	HASHRATE/W	HASHRATE	AVERAGE		SHARES
     1m [2021-09-13 10:58:26.163] GPU0	3090	Cuda	382.79 kH/W	131.30 MH/s	0.00 H/s	2/0/0 (100.00)
     1m [2021-09-13 10:58:26.163] 			382.79 kH/s	131.30 MH/s	0.00 H/s	2/0/0 (100.00)

...
     3m [2021-09-13 11:00:44.928] GPU0 Solution found in 6.31s (Submit every 39.99 seconds)
***** (X) ^  This was NOT sent to Pool   ^ (X)  *******
     3m [2021-09-13 11:00:50.795] GPU0 Solution found in 5.40s (Submit every 34.30 seconds)
***** (X) ^  This was NOT sent to Pool   ^ (X)  *******
     3m [2021-09-13 11:01:16.495] GPU0 Solution found in 3.02s (Submit every 33.07 seconds)
***** (X) ^  This was NOT sent to Pool   ^ (X)  *******
     4m [2021-09-13 11:01:29.133] 
     4m [2021-09-13 11:01:29.133] https://us-eth.2miners.com:12020 (ethash)    PING: 41ms    DIFFICULTY: 2.03     EPOCH: 440
     4m [2021-09-13 11:01:29.133]                                                                                           
     4m [2021-09-13 11:01:29.133] 
     4m [2021-09-13 11:01:29.133] ID	BOARD	TEMP	FAN	CORE	MEM	WATT	kW/h	COST/h
     4m [2021-09-13 11:01:29.133] GPU0	3090	52/0	92	1657	10893	343	0.34	inf
     4m [2021-09-13 11:01:29.133] 						343	0.34	inf
     4m [2021-09-13 11:01:29.133] 
     4m [2021-09-13 11:01:29.133] ID	BOARD	TYPE	HASHRATE/W	HASHRATE	AVERAGE		SHARES
     4m [2021-09-13 11:01:29.133] GPU0	3090	Cuda	377.43 kH/W	129.46 MH/s	129.67 MH/s	2/0/0 (100.00)
     4m [2021-09-13 11:01:29.133] 			377.43 kH/s	129.46 MH/s	129.67 MH/s	2/0/0 (100.00)
     4m [2021-09-13 11:01:29.133]

**Comment by KillrBee** [comment]
Okay great!

Thanks

**Comment by sp-hash** [comment]
fixed in v1.04
