### ISSUE TITLE
Feature request - Payout to 2 wallets with percentage weight

### ISSUE THREAD

**Issue by slypire** [sp-hash/TeamBlackMiner#150]
Hello, you should add option for "maintenence fee" where we would be able to add custom wallet with a custom fee percentage to our workers.
It would help a lot for people that maintain a lot of rigs for different people.

**Comment by Olegik-ah** [comment]
I think so too:))
Great idea!

**Comment by smosguru** [comment]
Yes I need the same functionality, please make it up :)

**Comment by sp-hash** [comment]
We will add this in v1.28

**Comment by slypire** [comment]
awesome, if possible it would be good to create that each rig mines for about 140 seconds daily to secondary wallet, that would amount around 10%(if I did math correctly) and also make it possible to change it!

thank you

**Comment by smosguru** [comment]
Sounds good, idea @slypire is not bad. Do you have some date v1.28?

**Comment by sp-hash** [comment]
We will do it this way. On startup we create a random number from 0 to 99 and if the number is let's say under 10 we use the 2nd wallet. the parameter 10 can be be adjusted to what you want. The program will mine on this address until it stops, but you can add the --miningtime parameter to let it restart after xxx minutes.
