### ISSUE TITLE
How to disable CPU verification of shares

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#151]
I want to disable CPU verification since I know my rigs produce negligible amount of invalid shares. Does the -N option disable it or does it do something else? If -N doesn't disable it, is there a way to disable it?

**Comment by sp-hash** [comment]
Why do you want to disable it? Sending invalid shares to the pool can block your ip adress.

**Comment by hintro32** [comment]
> Why do you want to disable it? Sending invalid shares to the pool can block your ip adress. Mine on a pool with a high difficulty, then the cpu doesn't need to verify the shares so often.

It should lower share latency slightly, and not to mention cpu verification can wrongly reject shares, especially if the cpu is overclocked and mining, which I have observed with other miners.

**Comment by sp-hash** [comment]
ok. We might include this as it's not very hard to implement.
