### ISSUE TITLE
Only getting 27~29 for Polaris cards while all other miners give 31~32MH

### ISSUE THREAD

**Issue by skygunner** [sp-hash/TeamBlackMiner#153]
On a 12 cards rig.

**Comment by sp-hash** [comment]
you can try to add a few more watts of power, and use the latest drivers.

 ID     BOARD   HASHRATE/W      HASHRATE        AVERAGE         SHARES
 GPU0  Ellesme 0.00 H/W        33.59 MH/s      33.25 MH/s      1/0/0 (100.00%)
 GPU1  Ellesme 0.00 H/W        33.73 MH/s      32.73 MH/s      2/0/0 (100.00%)
 GPU2  Ellesme 0.00 H/W        30.22 MH/s      29.90 MH/s      2/0/0 (100.00%)
