### ISSUE TITLE
ok so i cant get teamblackminer to run on hive os,

### ISSUE THREAD

**Issue by ditime** [sp-hash/TeamBlackMiner#155]
it constantly just gives me this message over and over

Skipping miner log rotation due to execution time < 30sec

00:00:00 [2021-10-30 19:25:55.496]
00:00:00 [2021-10-30 19:25:55.496] Sorry. SSL is not fully implemented yet
00:00:00 [2021-10-30 19:25:55.496] Shutting down threads
00:00:00 [2021-10-30 19:25:59.496] Exiting

teamblackminer exited (exitcode=0), waiting to cooldown a bit

**Comment by sp-hash** [comment]
ssl mining is not working use the normal ports

https://github.com/sp-hash/TeamBlackMiner/issues/16
