### ISSUE TITLE
logs of Aggregated HASHRATE/W is incorrect 

### ISSUE THREAD

**Issue by purija** [sp-hash/TeamBlackMiner#156]
The Hashrate/W log statement value is incorrect. The Hashrate/W values are currently added up only. 
The correct aggretion would be an addition of the Hashrate/W values and division of entry amounts to keep the correct relationship of Hashrate per watt. 
<img width="1325" alt="Screen Shot 2021-11-25 at 14 15 03" src="https://user-images.githubusercontent.com/4713054/143450231-9740f9fa-29c1-4ee0-b234-ecccb5d57e86.png">

**Comment by sp-hash** [comment]
fixed in v1.28
