### ISSUE TITLE
TeamBlackMiner Discord?

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#158]
Will you be open to creating a TeamBlackMiner Discord server? I think that way questions and issues can be addressed much faster and help the community grow.

**Comment by sp-hash** [comment]
We don't have a discord, but you can reach us at bitcointalk

https://bitcointalk.org/index.php?topic=5358334.0

**Comment by sp-hash** [comment]
replies: 1362
views: 15837
