### ISSUE TITLE
maintenance

### ISSUE THREAD

**Issue by smosguru** [sp-hash/TeamBlackMiner#159]
Hello, 

i have question, is my setup correct? 

--algo ethash --hostname eth-eu1.nanopool.org --port 9999 --wallet XYZ.$rigName/email@example.com -d --maintainance-wallet adress XYZ.$rigName/email@example.com--maintainance-percent 5

really **--maintainance-wallet adress** not _--maintenance-wallet address_

Best regards

**Comment by sp-hash** [comment]
spelling errors in v1.29 we will rename to

--maintenance-wallet
--maintenance-percent

put the workername in the --workername

--wallet wallet --workername $rigName/email@example.com

**Comment by smosguru** [comment]
And my setup is ok? But on maintenance wallet I don't see worker. And I see full hashrate on primary.

**Comment by sp-hash** [comment]
If you set 5%. The maintainance wallet will run in average 5 out of 100 times. 

We check for random(100) < 5 at startup, and if its true we mine 100% of the shares to the maintainance wallet.
you can combine with --miningtime  360 (6 hours) to restart the miner every 6 hours.

**Comment by smosguru** [comment]
ok, thanks now working? How i can verify that this setup working correctly? In miner i dont see any changes. THX

**Comment by sp-hash** [comment]
if the wallet is mining to the maintainance wallet it will give the message to the console/log:

The Wallet changed to the maintenance Wallet.

**Comment by smosguru** [comment]
Really sorry, but i think that no working correct for me. I absolutelly dont see any changes on maintenance wallet. If i set 99% for maintenance I don't see any changes with balance. I don't see rig on rig list.

_--algo ethash --hostname eth-eu1.nanopool.org --port 9999 --wallet CUSTOMERWALLET --worker-name $rigName/email@example.com -d --maintainance-wallet adress OURWALLET --maintainance-percent 99 --worker-name $rigName/email@example.com_

Is setup ok? If i setting 99% for maintainance wallet, on customer wallet really hashrate and shares go down, but on our wallet i dont see change.

Best regards, really thank you for your help.

**Comment by smosguru** [comment]
Hello, can you check my setup if is all ok?

_--algo ethash --hostname eth-eu1.nanopool.org --port 9999 --wallet CUSTOMERWALLET --worker-name $rigName/email@example.com -d --maintainance-wallet OURWALLET --maintainance-percent 10 --worker-name $rigName/email@example.com_

If i understand right, this is 10% maintenance fee to our wallet for all time mining? Because I dont see this rigs on OURWALLET on nanopool. Thank you for your reply.

**Comment by smosguru** [comment]
Do I understand that function correctly? If I set 10%, will the miner select 1-10 or 10-90 each time he starts and then mine for a randomly selected wallet (client, our company) until the next restart?
