### ISSUE TITLE
SSL mining doesn't work

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#16]
6 minutes of mining,  135 MH/s, 0 shares submitted to the pool -- slow share discovery rate - should be every 30 seconds or less.
     
5m [2021-09-13 17:05:55.199] GPU0 Solution found in 1.95s (Submit every 85.41 seconds)
     5m [2021-09-13 17:05:57.377] Job 70008
     5m [2021-09-13 17:05:58.402] Job 7000a
     5m [2021-09-13 17:05:59.426] Job 7000c
     5m [2021-09-13 17:06:06.594] Job 7000d
     5m [2021-09-13 17:06:08.652] Job 7000e
     5m [2021-09-13 17:06:09.687] Job 70010
     5m [2021-09-13 17:06:12.655] GPU0 Solution found in 3.60s (Submit every 71.81 seconds)
     5m [2021-09-13 17:06:16.879] Job 70011
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120] 2miners.com (ethash)    PING: 0ms    DIFFICULTY: 2.03     EPOCH: 440
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
     6m [2021-09-13 17:06:19.120] GPU0  3090    54/0    95      1697    11288   362     0.36    inf
     6m [2021-09-13 17:06:19.120]                                               362     0.36    inf
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
     6m [2021-09-13 17:06:19.120] GPU0  3090    Cuda    372.90 kH/W     134.99 MH/s     133.98 MH/s     0/0/0 (100.00)
     6m [2021-09-13 17:06:19.120]                       372.90 kH/s     134.99 MH/s     133.98 MH/s     0/0/0 (100.00)
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:19.120]
     6m [2021-09-13 17:06:22.023] Job 70013
     6m [2021-09-13 17:06:29.375] Job 70015
     6m [2021-09-13 17:06:30.228] Shutting down threads
     6m [2021-09-13 17:06:30.230] Control thread exited
     6m [2021-09-13 17:06:30.234] Stratum thread exited
     6m [2021-09-13 17:06:30.336] GPU0 thread exited
     6m [2021-09-13 17:06:34.244] Exiting

**Comment by sp-hash** [comment]
looks like the miner is finding shares, but you miss the accepted messages from the pool,

5m [2021-09-13 17:06:12.655] GPU0 Solution found in 3.60s (Submit every 71.81 seconds)

**Comment by sp-hash** [comment]
I can verify that ssl connection is broken. We are unable to get response from the pool. So the miner will shut down after a while. Put in the todo list.

**Comment by markuznw** [comment]
Same here, ssl connection seems broken (flexpool) using amd 5700xt. All ok with normal port

**Comment by luanwulin** [comment]
> In v1.21 ssl has been diabled because of the issues. We are working on a fix.

when will this feature release? really need this , many thks for your hard work

**Comment by binaryf** [comment]
Ok. The issue has been moved to the top of the list.

**Comment by luanwulin** [comment]
> Ok. The issue has been moved to the top of the list.

so, can we support ssl asap? for some reasons, i can not mining. i'm mining through ssl to hide my connect, if tbm cannot support ssl, i have to consider other miner. please work on this. tks a lot

**Comment by binaryf** [comment]
Will be fixed in v1.29.
Sorry about the delay.

**Comment by luanwulin** [comment]
> Will be fixed in v1.29.
> 
> Sorry about the delay.

can we use ssl on v 1.30😆

**Comment by binaryf** [comment]
I was unable to fix the different issues with SSL with the codebase as it is.
So I think the networking code has to be rewritten with a library more suitable.
This is still important, but we will not be able to complete this before the next release.

**Comment by luanwulin** [comment]
> I was unable to fix the different issues with SSL with the codebase as it is. So I think the networking code has to be rewritten with a library more suitable. This is still important, but we will not be able to complete this before the next release.

trm and lolminer has released a new feature to handle dns problem, but tbm still can not use ssl. you really missed opportunity to attract users ._.`

**Comment by binaryf** [comment]
I hope it is never too late. I will find the time to do it.

**Comment by sp-hash** [comment]
We support mining to ipadresses. So you can setup a ssh tunnel from china.

See ip example script:
 TBMinerLinux/tbminer_flexpool_hke.sh

**Comment by luanwulin** [comment]
> TBMinerLinux/tbminer_flexpool_hke.sh

sorry,where can i find TBMinerLinux/tbminer_flexpool_hke.sh

**Comment by binaryf** [comment]
We can not probably not include SSL support in Version 1.0 Stable.
And maybe we will drop AMD support.
