### ISSUE TITLE
[Hive Os] v 1.28 Cannot create gpuinfo: Read-only system

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#160]
Hello i have a problem with my 2 rigs on hiveos

![image](https://user-images.githubusercontent.com/11719145/143774288-429bb2c1-d028-4da1-8058-6f536d733660.png)

thanks

**Comment by sp-hash** [comment]
We need to write files to the folder in order to show stats. but you can try with --no-stats

**Comment by MrNuTruT** [comment]
I would like to have the stats how to do?

**Comment by sp-hash** [comment]
You need to ssh into the rig and give write permission to the folder the file is located.

**Comment by sp-hash** [comment]
https://forum.hiveos.farm/t/would-love-some-help-filesystem-is-read-only-rebooting-problem-happened-out-of-nowhere/19333/5

**Comment by MrNuTruT** [comment]
Ok thanks but where is the file path ?
