### ISSUE TITLE
HiveOS RX 6600 XT GPU thread exited

### ISSUE THREAD

**Issue by dsimka** [sp-hash/TeamBlackMiner#161]
00:00:00 [2021-11-28 18:10:39.992] OpenCL driver version: 350.623
00:00:00 [2021-11-28 18:10:40.016] Cuda driver version: 11.4
00:00:00 [2021-11-28 18:10:40.016] Cuda runtime API version: 11.4
00:00:00 [2021-11-28 18:10:40.016] 
00:00:00 [2021-11-28 18:10:40.016]                                 
00:00:00 [2021-11-28 18:10:40.016] 
00:00:00 [2021-11-28 18:10:40.016] Welcome to Team Black Miner 1.28
00:00:00 [2021-11-28 18:10:40.016]                                 
00:00:00 [2021-11-28 18:10:40.016] 
00:00:00 [2021-11-28 18:10:40.016] GPU0 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU1 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU2 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU3 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU4 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU5 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU6 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.016] GPU7 gfx1032 8GB added to miner as OpenCL device
00:00:00 [2021-11-28 18:10:40.017] Trying eu-eth.hiveon.net:4444 (ethash)
00:00:00 [2021-11-28 18:10:40.019] GPU0 Started CL work thread
00:00:00 [2021-11-28 18:10:40.020] GPU1 Started CL work thread
00:00:00 [2021-11-28 18:10:40.021] Shutting down threads
00:00:00 [2021-11-28 18:10:40.021] GPU1 thread exited
00:00:00 [2021-11-28 18:10:40.021] GPU0 thread exited
00:00:00 [2021-11-28 18:10:40.021] GPU2 Started CL work thread
00:00:00 [2021-11-28 18:10:40.022] Shutting down threads
00:00:00 [2021-11-28 18:10:40.022] GPU2 thread exited
00:00:00 [2021-11-28 18:10:40.022] GPU3 Started CL work thread
00:00:00 [2021-11-28 18:10:40.022] GPU3 thread exited
00:00:00 [2021-11-28 18:10:40.023] GPU4 Started CL work thread
00:00:00 [2021-11-28 18:10:40.024] GPU5 Started CL work thread
00:00:00 [2021-11-28 18:10:40.025] GPU6 Started CL work thread
00:00:00 [2021-11-28 18:10:40.026] GPU7 Started CL work thread
00:00:00 [2021-11-28 18:10:40.034] Api thread exited
00:00:00 [2021-11-28 18:10:44.021] Exiting

**Comment by sp-hash** [comment]
What's your launch configuration? try to launch with --xintensity 24

**Comment by dsimka** [comment]
--xintensity 24  , --xintensity 78 , the same

**Comment by sp-hash** [comment]
Did you try other pools? Is one device working? try -Y [0]

**Comment by Michiru007** [comment]
i have the same problem, i change dag intensity, its same, i change miner, its work

**Comment by sp-hash** [comment]
can you try v1.27 ?

**Comment by Michiru007** [comment]
i try to downgrade 1.28-cuda 115, 1.28, 1.27 1,26= the same problem

**Comment by esille** [comment]
Same here, on version 1.28 Dag verification always fails on 6800 XT GPU. Tried with --dagintesity default,1,2,5. Had to revert back to 1.27 which works fine...except memory leak still present.

**Comment by sp-hash** [comment]
This will be fixed in v1.29. Will release soon.

**Comment by sp-hash** [comment]
v1.29 has been released. Can you try please?

**Comment by esille** [comment]
> v1.29 has been released. Can you try please?

Works for me.
