### ISSUE TITLE
NO GPU available

### ISSUE THREAD

**Issue by smosguru** [sp-hash/TeamBlackMiner#162]
![image](https://user-images.githubusercontent.com/93115701/143779967-7d5485b7-0279-48dd-8ec4-91d5db0ebe9f.png)

Hello, if try change miner on our 3090 rigs, this issue. If i change back previous miner, working correct.

**Comment by sp-hash** [comment]
you need to upgrade to a nvidia driver that can run cuda 11.4 code. Latest driver
