### ISSUE TITLE
Latest version Binance Pool

### ISSUE THREAD

**Issue by malisdanny** [sp-hash/TeamBlackMiner#163]
1.28 dont work with binance pool in hiveos, 1.27 working fine...

**Comment by sp-hash** [comment]
works in windows. What's the error message?

**Comment by malisdanny** [comment]
![2021-11-29 (2)](https://user-images.githubusercontent.com/81848622/143808914-0d4b849d-e5df-44bd-825e-6fd8df3d8c59.png)
Now its a DUG error

**Comment by Michiru007** [comment]
downgrade at 1.27 for the moment .

**Comment by sp-hash** [comment]
This will be fixed in v1.29. Will release soon.

**Comment by sp-hash** [comment]
v1.29 has been released. Can you try please

**Comment by malisdanny** [comment]
Thank you !!! 1.29 is working, a bit lower hashrate than 1.27 :)
