### ISSUE TITLE
Compatible Linux builds

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#164]
Hi, sorry to ask about this again, but will you be able to release Linux builds that are compatible with more Linux versions (e.g. CentOS 7) soon?

**Comment by binaryf** [comment]
What happends on CentOS 7 when you run tbminer ?

**Comment by hintro32** [comment]
> What happens on CentOS 7 when you run tbminer ?
With gcc 11.2 and relatively new libcurl and glibc installed
./TBMiner: /lib64/libcurl.so.4: no version information available (required by ./TBMiner)
./TBMiner: relocation error: ./TBMiner: symbol __shm_directory, version GLIBC_PRIVATE not defined in file libpthread.so.0 with link time reference

I managed to make it find of run in a ubuntu 18 container, but I had this error:
source/sp_workers/cl_gpu.cpp:cl_get_driver_version():210: A OpenCL runtime error occured: m

I don't have AMD GPU or driver installed.

**Comment by hintro32** [comment]
When using --list-devices, Available Cuda devices shows the devices correctly, but then

Available OpenCL devices
-------------------------
18962:07 [2021-12-01 02:00:31.402] source/sp_workers/cl_gpu.cpp:cl_setup_devices():385: A OpenCL runtime error occured: 
18962:07 [2021-12-01 02:00:31.402] Shutting down threads
18962:07 [2021-12-01 02:00:35.402] Exiting

I tried the -G option too and still doesn't work... IMHO the -G option should prevent this behavior even in the absence of OpenCL libraries.

**Comment by binaryf** [comment]
I think you are right. The -G option should prevent the use of OpenCL.
I will fix this thing now.

**Comment by hintro32** [comment]
By the way, the hashrate ans shares rate on 1.29 is lower than 1.28 for my rtx 2080 gpus. Will that be fixed?

**Comment by hintro32** [comment]
@binaryf 
Is there any progress on making compatible Linux builds?
Currently it is really a pain to maintain running on CentOS 7 through a ubuntu container... Your Linux builds also appear to be quite unstable/sensitive, resulting in segmentation fault at launch in many environments. I couldn't get it to run in my CentOS 7 desktop environment (only works in headless environment), so I tried to use Valgrind to check what's going on. Turns out the miner can't pass Valgrind on any of my systems, indicating bad memory access caused by the miner. The command used is "valgrind ./TBMiner --version", and TBMiner 1.31 is used except on Hive OS.

Hive OS 0.6-212@211205:
![image](https://user-images.githubusercontent.com/81028826/145124974-08f5f2d5-b160-4742-b7b4-1b379b25a6f0.png)

Ubuntu 18.04 container on CentOS 7:
```
valgrind ./TBMiner --version
==5432== Memcheck, a memory error detector
==5432== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5432== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==5432== Command: ./TBMiner --version
==5432== 
==5432== Invalid read of size 4
==5432==    at 0x85EFF73: dl_main (rtld.c:1203)
==5432==    by 0x8607DCF: _dl_sysdep_start (dl-sysdep.c:253)
==5432==    by 0x85EF127: _dl_start_final (rtld.c:414)
==5432==    by 0x85EF127: _dl_start (rtld.c:521)
==5432==    by 0x85EE097: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==5432==    by 0x1: ???
==5432==    by 0x1FFF000CEA: ???
==5432==    by 0x1FFF000CF4: ???
==5432==  Address 0x208040 is not stack'd, malloc'd or (recently) free'd
==5432== 
==5432== 
==5432== Process terminating with default action of signal 11 (SIGSEGV)
==5432==  Access not within mapped region at address 0x208040
==5432==    at 0x85EFF73: dl_main (rtld.c:1203)
==5432==    by 0x8607DCF: _dl_sysdep_start (dl-sysdep.c:253)
==5432==    by 0x85EF127: _dl_start_final (rtld.c:414)
==5432==    by 0x85EF127: _dl_start (rtld.c:521)
==5432==    by 0x85EE097: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==5432==    by 0x1: ???
==5432==    by 0x1FFF000CEA: ???
==5432==    by 0x1FFF000CF4: ???
==5432==  If you believe this happened as a result of a stack
==5432==  overflow in your program's main thread (unlikely but
==5432==  possible), you can try to increase the size of the
==5432==  main thread stack using the --main-stacksize= flag.
==5432==  The main thread stack size used in this run was 8388608.
==5432== 
==5432== HEAP SUMMARY:
==5432==     in use at exit: 0 bytes in 0 blocks
==5432==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==5432== 
==5432== All heap blocks were freed -- no leaks are possible
==5432== 
==5432== For lists of detected and suppressed errors, rerun with: -s
==5432== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault
```

Ubuntu 20.04:
![tb on ub20](https://user-images.githubusercontent.com/81028826/145123732-aa723383-d585-4ba3-b9f4-5b4e6f5448c6.png)

Here is Gminer by comparison, no issue with Valgrind at all:
![image](https://user-images.githubusercontent.com/81028826/145124143-58b6b735-fa24-4a80-96ee-5405dd1e7390.png)

**Comment by sp-hash** [comment]
Thanks for testing.
I see that we use more stack than the recommended settings. This is something we can solve in 1.32

**Comment by hintro32** [comment]
> Thanks for testing. I see that we use more stack than the recommended settings. This is something we can solve in 1.32

That's great, thanks. Do you have an ETA for 1.32?

**Comment by binaryf** [comment]
--version and --list-devices had some resources that was not freed on exit.
Fixed.
