### ISSUE TITLE
Teamblackminer cannot display GPU in hiveos

### ISSUE THREAD

**Issue by tzl19930701** [sp-hash/TeamBlackMiner#165]
Teamblackminer does not run

**Comment by sp-hash** [comment]
NVIDIA or AMD?`You need to install the latest drivers

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/issues/78

**Comment by tzl19930701** [comment]
AMD rx6600              Is the latest driver

**Comment by tzl19930701** [comment]
AMD rx6600 Is the latest driver


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sp-hash/TeamBlackMiner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sp-hash/TeamBlackMiner] Teamblackminer cannot display GPU in hiveos (Issue #165)





 
Closed #165.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
