### ISSUE TITLE
TeamBlackMiner works standalone on 2Miners but not with AwesomeMiner

### ISSUE THREAD

**Issue by smyers63** [sp-hash/TeamBlackMiner#166]
I really like the fact that TeamBlackMiner gives me better hashrate.  I'd like to use it entirely but it's not working on 2MIners with Awesome Miner.  It works in Awesome Miner with the other pools I use, it works on 2Miners as a standalone, and other miners work in Awesome Miner on 2Miners.  I want to be able to have TeamBlackMiner set as my ETH miner in a profit-switching setup on Awesome Miner along with the other miners that are already working without special config on my Nvidia 3080/3090 rig (PhoenixMiner, T-Rex, Nanominer, lolminer).  Right now, I either have to avoid 2Miners or I have to avoid TeamBlackMiner to use profit-switching in Awesome Miner.

**Comment by sp-hash** [comment]
2miners.com is working fine but the ssl port is not. See example in

tbminer_2miners_eth

**Comment by smyers63** [comment]
The issue I described has nothing to do with SSL - I was not using the SSL port.  I was using TBM with Awesome Miner to manage profit-switching with other miners like Phoenix Miner, T-Rex and others on several pools including 2Miners.  TBMiner works in that situation with other pools but does not on 2Miners.  I don't use SSL on any pools.  The other miners work on 2Miners with the same configuration that TBM does not work with.  TBM works as a standalone program but when used with Awesome Miner, it will not connect to 2Miners.  It appears that maybe the wallet address isn't being passed from Awesome Miner to TBM.  Again, using TBM by itself as a standalone program works but I need it to work with Awesome Miner for the profit-switching that Awesome Miner provides.  I can send you more data concerning the issue and if you're not familiar with Awesome Miner, I can give you the data to configure it.

[tbminer-awesomeminer-diag.txt](https://github.com/sp-hash/TeamBlackMiner/files/7629980/tbminer-awesomeminer-diag.txt)
.

**Comment by sp-hash** [comment]
`C:\Users\Scott-miner\AppData\Local\AwesomeMiner\teamblackminer_1_27_cuda_11_4_2\TeamBlackMiner_1_27_cuda_11_4\TBMiner.exe  -a ethash -H us-eth.2miners.com -p 2020 -P x -W smyers63 --api --api-port 4029
`
2miners require the wallet as workername not the username smyers63

**Comment by sp-hash** [comment]
https://www.awesomeminer.com/pools/2miners
