### ISSUE TITLE
teamblackminer在hiveos中没法正常工作。

### ISSUE THREAD

**Issue by tzl19930701** [sp-hash/TeamBlackMiner#167]
矿池被屏蔽了，用的vps转接的矿池，teamblackminer提示无法连接地址

**Comment by tzl19930701** [comment]
直接连接flex矿池也不行
![ca29502efbe8ddf88012238bc67fa15](https://user-images.githubusercontent.com/95277712/144168103-de547143-01de-44c7-9767-03ec2ebb9ae1.png)

**Comment by tzl19930701** [comment]
help me

**Comment by binaryf** [comment]
No problem. We will add your forwarding service.

**Comment by tzl19930701** [comment]
Can you tell me after adding

**Comment by binaryf** [comment]
It will be in the next version. v1.30.
