### ISSUE TITLE
Missing stats on RX5700 XT Aorus/Gigabyte GPUs

### ISSUE THREAD

**Issue by esille** [sp-hash/TeamBlackMiner#168]
Two of GPUs doesn't show any stats however mining works fine. 
![CleanShot 2021-12-01 at 15 16 27](https://user-images.githubusercontent.com/59832428/144251417-f4f3e7d0-6763-4c2a-a84a-3cfd8f434f89.png)

Two cards with missing stats are Aorus RX5700 XT. 

![CleanShot 2021-12-01 at 15 28 32](https://user-images.githubusercontent.com/59832428/144252506-4516b827-84b5-44e5-b5e3-77f76a8c1ee0.png)

**Comment by sp-hash** [comment]
Can you run tbminer --list-devices please ?

**Comment by esille** [comment]
`root@Garage:/hive/miners/teamblackminer/1.29# ./TBMiner -D

Available Cuda devices
-----------------------


Available OpenCL devices
-------------------------

Device Number: 0
    Device name: gfx1030
    PCIe bus id: 22
    Memory: 16GB

Device Number: 1
    Device name: gfx1010
    PCIe bus id: 19
    Memory: 8GB

Device Number: 2
    Device name: gfx1010
    PCIe bus id: 16
    Memory: 6GB

Device Number: 3
    Device name: gfx1010
    PCIe bus id: 13
    Memory: 8GB

Device Number: 4
    Device name: gfx1010
    PCIe bus id: 10
    Memory: 8GB

Device Number: 5
    Device name: gfx1010
    PCIe bus id: 7
    Memory: 8GB

Device Number: 6
    Device name: gfx1010
    PCIe bus id: 3
    Memory: 6GB
`

**Comment by binaryf** [comment]
Sorry to say we do not know how to handle this.
We see to much of these kind of error reports, and we now think this is a hardware/os issue.
