### ISSUE TITLE
Lower hashrate on 1,29

### ISSUE THREAD

**Issue by KaranisPL** [sp-hash/TeamBlackMiner#169]
Hi. after installing version 1.29 going from 1.27 I noticed a decrease in hashrate. It's normal? The number of shared errors has significantly decreased, however, they still occur and the hashrate is lower than 1.27. how to fix it? I used flexpool

**Comment by sp-hash** [comment]
You can use --xintensity 284  to get back the speed. Note that flexpool doesn't pay for stale shares so the higher hashrate might be removed by the pool. (stale)

on 2miners.com and miningpoolhub you get best speed with --xintensity 4096

https://github.com/sp-hash/TeamBlackMiner/blob/main/FAQ.md
