### ISSUE TITLE
windows start fail =cannot received data from pool

### ISSUE THREAD

**Issue by Eltonton** [sp-hash/TeamBlackMiner#171]
hello i trying on windows 10 cuda 11.5 lastest driver nvidia .
Can you help me ?
this is the message 
<img width="546" alt="Capture" src="https://user-images.githubusercontent.com/68582398/144639692-32aa7d7d-3d3e-42a6-9365-73283fbddcb3.PNG">

**Comment by sp-hash** [comment]
what's your launch config?

**Comment by Eltonton** [comment]
Set ETH_WALLET=**

:loop
	TBMiner --algo ethash --hostname eth.2miners.com --port 2020 --wallet %ETH_WALLET% --worker-name %computername%
	timeout 5
goto :loop

i trying to launching another .bat without change something. same fail

**Comment by sp-hash** [comment]
Are you using a wifi connection? Your ip has probobly been blocked, or you are mining through a proxy,

**Comment by Eltonton** [comment]
no wifi.
 Lan connection .
same conf for all miner of all my rig.
No proxy
I try to launch on another rig hiveos .
Start ok but Nothing Mhs for all Gpu

**Comment by Eltonton** [comment]
stratum conf?

**Comment by sp-hash** [comment]
Perhaps you can try to increase the -t --timeout  ? Is your connection slow?

**Comment by Eltonton** [comment]
I trying this.
My connection is vdsl2+ 110mb/sec ping 25ms

**Comment by binaryf** [comment]
You really should try a discussion group or try to find support elsewhere.
