### ISSUE TITLE
[BUG] Teamblack v1.30 very high CPU load

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#172]
Hi,

I just tried the new release on a Windows 10, 6 x GTX1070 test rig. The rig has a Pentium CPU with 2 cores/4 threads - Teamblack uses always more than 50% CPU. For now, I'll stay with Teamblack 1.29.

**Comment by sp-hash** [comment]
yes, we fixed it. please refresh the release tab.

**Comment by sp-hash** [comment]
linux soon

**Comment by sp-hash** [comment]
TeamBlackMiner_1_30_cuda_11_5_cpufix.7z

**Comment by sp-hash** [comment]
linux added as well
