### ISSUE TITLE
[Q] Index for parameter --lhr-unlock

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#173]
Hi,

does --lhr-unlock need to be setup for all Nvidia GPUs in a rig, even if --cuda-devices select only some of the GPUs?

e.g. 
we have 4 GPUs: 1x GTX1070, 1x RTX3060, 2x RTX3070 and we run one TBminer instance for every model. Which parameters are correct, if we want to enable LHR unlock for all RTX30xx GPUs?
- GTX1070: `TBminer --cuda-devices [0]`
- RTX3060: `TBminer --cuda-devices [1] --lhr-unlock [0,1,0,0]` or `TBminer --cuda-devices [1] --lhr-unlock [1]`
- RTX3070: `TBminer --cuda-devices [2,3] --lhr-unlock [0,0,1,1]` or `TBminer --cuda-devices [2,3] --lhr-unlock [1,1]`

I have currently implemented the second option in the RainbowMiner. So is this ok?

**Comment by sp-hash** [comment]
For one device use one argument:

GTX1070: TBminer --cuda-devices [0]
RTX3060: TBminer --cuda-devices [1] --lhr-unlock [1]
RTX3070: TBminer --cuda-devices [2,3] --lhr-unlock [1,1] 

But why do dont you mine all gpus in the same instance?

 TBminer  --lhr-unlock [0,1,1,1]
 
You might need to adjust the unlock if it doesn't work/or slow. add a number to thevalue
 
 TBminer  --lhr-unlock [0,5,5,5]
