### ISSUE TITLE
Weird kernel and Xintensity behavior and cuda error

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#174]
I found that sometimes kernel and Xintensity are displayed as 0. Is this normal?

With options -G -U [1,2,3,4,5,6,7,8,9] -E 2048:
![image](https://user-images.githubusercontent.com/81028826/144769307-ab1d87e5-640c-4cea-88db-3eb84c7fee0a.png)

Also I found that the miner throws cuda runtime error with Tesla V100 cards, so I'll have to keep them on Gminer for now :(
![image](https://user-images.githubusercontent.com/81028826/144768661-3b3502ef-018f-4cf2-be72-4cf8915c2e2f.png)

**Comment by sp-hash** [comment]
>-G -U [1,2,3,4,5,6,7,8,9] -E 2048:

So you don't wantto mine with gpu0? - 2048 should set the correct intensity on all the devices, if you get 0 it will revert to the default intensity. We will check if it is a bug in the code.

**Comment by hintro32** [comment]
> > -G -U [1,2,3,4,5,6,7,8,9] -E 2048:
> 
> So you don't wantto mine with gpu0? - 2048 should set the correct intensity on all the devices, if you get 0 it will revert to the default intensity. We will check if it is a bug in the code.

It displays correctly when I use all GPUs. 
![image](https://user-images.githubusercontent.com/81028826/144823152-ed2b69bf-fdaa-40ed-90dc-04accef9fc3f.png)
I guess this is some sort of display bug but shouldn't affect mining.

Also, would you be able to make the miner work with V100 GPUs? Thanks

**Comment by sp-hash** [comment]
yes. Error in the display. We have fixed it in v1.32

Also added support for cuda 6.0, 7.0, 8.0 so the V100 should be working
