### ISSUE TITLE
Not displayed on OS

### ISSUE THREAD

**Issue by tzl19930701** [sp-hash/TeamBlackMiner#175]
Not displayed on OS only
![image](https://user-images.githubusercontent.com/95277712/144773896-d40d2810-4519-44fb-8219-9ea4af4f47a0.png)

**Comment by tzl19930701** [comment]
help me

**Comment by sp-hash** [comment]
Sorry I don't understand the question?

**Comment by tzl19930701** [comment]
用teamblackminer时hiveos显示gpu不运行，但是矿机显示屏上显示内核正常运行

**Comment by sp-hash** [comment]
Hiveos get the rig information from our API. Perhaps you can ask in the hiveos forum? Not sure why it doesn't work for you,

**Comment by tzl19930701** [comment]
好的  谢谢你
