### ISSUE TITLE
HiveOS Pool-name required

### ISSUE THREAD

**Issue by XING-IF** [sp-hash/TeamBlackMiner#176]
I have a problem with TBM on HiveOs. I can't use an IP adress, I have to use the flight sheet selection and check the host name. If not, I get a message "pool not supported". Due to DNS issues in some countries, this can be a probllem for some users.

**Comment by tzl19930701** [comment]
直接让他加上代理服务器功能就可以了

**Comment by binaryf** [comment]
Due to our implementation we add hostnames and ip when we configure an check a new pool.
If you are using a forwarding IP or have a pool ip we have not added, please give us the IP address.

**Comment by tzl19930701** [comment]
ip地址被限制了，只能用转发才能连上

**Comment by binaryf** [comment]
Will you be able to connect to the forwarding ip directly or is it a http or https proxy server ?

**Comment by tzl19930701** [comment]
能直接链接到代理服务器
不能直接链接到矿池

**Comment by binaryf** [comment]
Ok, I understand.
Our proxy code have yet not been tested.
If you can provide a proxy service I can test and make the necessary changes.

Another thing is SSL. We need to rewrite the networking code and this will take some time.

**Comment by XING-IF** [comment]
The proxy is hke.fpmirror.com and is the hke flexpool server which cannot be connected through the proxy address, neither the IP. The ports are 13271 and SSL 5555

**Comment by tzl19930701** [comment]
@XING-IF 提供一个代理服务器的ip给他，你有吗，比如那个ip转发的哪个矿池，让他试一下能不能通

**Comment by tzl19930701** [comment]
？

**Comment by tzl19930701** [comment]
@binaryf 用的这个服务器ip165.154.71.243:2001转发的这个矿池地址eth-hke.flexpool.io:22271

**Comment by binaryf** [comment]
Ok, thanks.
Since the networking code will be rewritten this will take some time.

**Comment by tzl19930701** [comment]
可以用代理服务器的时候告诉我们一声可以吗？

**Comment by binaryf** [comment]
Hard to say. But I will work on it this week.

**Comment by tzl19930701** [comment]
1.31版本中，代理服务器功能可以用了吗？

**Comment by binaryf** [comment]
Hello, hke.fpmirror.com is now working and we will soon release a new version.

**Comment by y525455383** [comment]
> 1.31版本中，代理服务器功能可以用了吗？

好像还是不能用

**Comment by binaryf** [comment]
Yes.
Todays release.
