### ISSUE TITLE
Problems with ETC+ZIL on rustpool

### ISSUE THREAD

**Issue by sp-hash** [sp-hash/TeamBlackMiner#179]
@bitcointalk

[quote author=sxemini link=topic=5358334.msg58635833#msg58635833 date=1638788165]
I get 34,4 mh on my 6600xt. After 24h no reject share on rustpool and ethermine.
But ETC+Zil will not work for me. Cannot subscribe to the pool.
[/quote]

**Comment by binaryf** [comment]
This we will probably look at.
