### ISSUE TITLE
No stats for AMD

### ISSUE THREAD

**Issue by markuznw** [sp-hash/TeamBlackMiner#18]
Hello, using 5700xt here and I get empty stats. Using 21.7.2 drivers.

No issues with teamredminer and phoenixminer. Thank you

![AnyDesk_MfcQAcNl1U](https://user-images.githubusercontent.com/779743/133280589-1071f287-aa19-4c98-a471-b164f301f984.png)

**Comment by sp-hash** [comment]
We are working on it.

**Comment by sp-hash** [comment]
v1.05 has stats and temp control for amd.

**Comment by markuznw** [comment]
Not working here, the only added info is 5700XT on BOARD, there is still no temp/fan/core/mem (besides watt which I've read you're still working on).
It also prints an error each time it does stats
"Cannot open nvidia-smi for gpu utilization information"
