### ISSUE TITLE
Missing stat on 6600xt msi

### ISSUE THREAD

**Issue by bonbonmark** [sp-hash/TeamBlackMiner#180]
No stat on 6600xt msi, verion 1.30
![Image 1](https://user-images.githubusercontent.com/12341661/144839718-300e03b0-5c1b-4e34-97bf-150b7619a65d.png)

![list-device](https://user-images.githubusercontent.com/12341661/144839847-ee58325d-f7ec-4143-af61-c6ace828f9e1.png)

**Comment by hintro32** [comment]
RTX A6000 is also missing stats
![image](https://user-images.githubusercontent.com/81028826/144823152-ed2b69bf-fdaa-40ed-90dc-04accef9fc3f.png)

**Comment by sp-hash** [comment]
yes. on windows we haven't found a new enough framework yet to do stats on the latest AMD cards. this is on the todo list.

For the rtxA600 make sure the program has access to nvidia-smi. Download the 800mb full driver from NVIDIA and it should be included.

**Comment by hintro32** [comment]
> yes. on windows we haven't found a new enough framework yet to do stats on the latest AMD cards. this is on the todo list.
> 
> For the rtxA600 make sure the program has access to nvidia-smi. Download the 800mb full driver from NVIDIA and it should be included.

I have nvidia-smi:
![image](https://user-images.githubusercontent.com/81028826/144922097-502a9c29-b2c4-44ca-abaf-117306513309.png)

**Comment by sp-hash** [comment]
I see that you are on a old driver. Upgrading the driver might help

**Comment by helman** [comment]
seeing the same issue on version 1.31 on HiveOS
AMD RX 6600 XT some has the stats and some don't

![Screen Shot 2021-12-09 at 11 36 43 am](https://user-images.githubusercontent.com/1606411/145313522-fdf6519a-8c81-437a-af2d-f27252358cae.png)

**Comment by Dojo76** [comment]
![TBM](https://user-images.githubusercontent.com/96024607/145729106-f46b36a7-1131-4d11-9951-2e43f87c472e.jpg)

Same here in 1.32 and older

**Comment by binaryf** [comment]
We are getting tired of all this issues with different hardware and setups.
This thread is closed.

**Comment by helman** [comment]
Love how the dev team reacting with the issue, great support! I think we will need to pay them more to look at this issue so they won't be tired for the service they charge

**Comment by sp-hash** [comment]
Did you try 1.35? shluld be fixed

**Comment by helman** [comment]
Hi @sp-hash thanks for the clarification, i haven't tried that yet, will try it soon, and thank you for fixing it 😉
but the previous comments gave me a negative impression.
