### ISSUE TITLE
Strange hashrate behavior since version 1.29

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#181]
On version 1.29, 1.30, 1.31, the hashrate would start out high and then suddenly drops. This seems to happen faster with higher than default Xintensity, with default the miner would go a few minutes before showing the drop in hashrate, but with higher values the drop typically happens around the first minute, resulting in something that looks like this:
![image](https://user-images.githubusercontent.com/81028826/144926948-59e2bbee-ea82-4d80-9d28-31808df388f7.png)
And sometimes the miner would show ridiculously high hashrate for the first minute before dropping:
![image](https://user-images.githubusercontent.com/81028826/144927435-7da2285c-b47c-4fc6-a4b2-02095e0512cf.png)
![image](https://user-images.githubusercontent.com/81028826/144927588-c33cd589-9a5f-4a98-a16d-8064a84ce1d0.png)

This happens to all my Turing and Ampere cards, on both Hive OS and CentOS 7. Note that my cards are not throttling, and this hashrate drop didn't happen with versions 1.28 and earlier.

**Comment by sp-hash** [comment]
In the first minutes the miner is verifying the dag buffer, it is also trying different kernels since you have autotune on. 

You should experiment with the --kernel and the tweak parameters. Perhaps a combo will give a faster hashrate. I would expect that with --xintensity 4046
something like

--kernel 8 --tweak 7

will be the fastest.

**Comment by hintro32** [comment]
> In the first minutes the miner is verifying the dag buffer, it is also trying different kernels since you have autotune on.
> 
> You should experiment with the --kernel and the tweak parameters. Perhaps a combo will give a faster hashrate. I would expect that with --xintensity 4046 something like
> 
> --kernel 8 --tweak 7
> 
> Will be the fastest. A different kernel kan give as much as +10% boost on some systems. Tweak is adding more parallell work, so good for cards with many shaders and on high intensity

Version 1.29 and later end up with lower hashrate with same kernel and same Xintensity, isn't that a concern?

**Comment by sp-hash** [comment]
No tweak can be used for normal cards as well but it has another purpose.Iin 1.29 we have added more samples to the average hashrate in order to stabilize the fluctating hashrate of the LHR cards. Lower speed on --xintensity 4096?

**Comment by hintro32** [comment]
Yes, lower speed even with -E 4096.

**Comment by sp-hash** [comment]
Strange. Are you running the cuda 11.5 build?

**Comment by hintro32** [comment]
> Strange. Are you running the cuda 11.5 build? The 11.2 build is slower on rtx cards

I will try the 11.5 builds when I get a chance. Hive OS only has cuda 11.5 build up to version 1.28, and it doesn't seem to make a difference there.

**Comment by sp-hash** [comment]
Found a couple of issues and fixed them in 1.32. some of the LHR code was run for non LHR devices. The average function had a index bug.

**Comment by hintro32** [comment]
> Found a couple of issues and fixed them in 1.32. some of the LHR code was run for non LHR devices. The average function had a index bug. Ethproxy pools somethimes got cpu validation errors and skipping submitting solutions. Cuda 11.4 is also slower than 11.5. We have built linux versions with the latest driver on the latest 11.5 builds, perhaps thats why hiveos and smos didn't use the 11.5 builds for 1.29-1.31?

Hi, thanks for the new release, it fixed a lot of bugs. However, the hashrate still seems lower than version 1.28. Is that normal?
