### ISSUE TITLE
Cannot find TeamBlackMiner on hive OS

### ISSUE THREAD

**Issue by GuardianLiarus** [sp-hash/TeamBlackMiner#182]
Hello, i can't seem to be able to find you guy's miner when i use ETC or Vertcoin in HiveOS even though i see the updates being applied to Hive

**Comment by sp-hash** [comment]
In the app?

**Comment by GuardianLiarus** [comment]
> In the app?

Indeed, just checked on PC and it does appear, so it's a hive app issue.

Though while i'm at it, i just tried to mine vertcoin with the miner under Hive, console says to use a valid protocol

![Screenshot_20211207-000258_VNC_Viewer](https://user-images.githubusercontent.com/45693898/144936755-f0bf7703-ef4d-4cc0-86bb-62561c68e820.png)

**Comment by sp-hash** [comment]
to mine vertcoin you need to download spminer. They havent added it to hiveos yet but uoubcan install as a custom miner

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/blob/main/VERTCOIN.md
