### ISSUE TITLE
Invalid Share not reported in Hiveos

### ISSUE THREAD

**Issue by Ricco59163** [sp-hash/TeamBlackMiner#184]
I have a GTX2060 , all invalid share are not reported in red section in hiveos 

Witch parameter Can resolve my problem

thx for your job

**Comment by sp-hash** [comment]
We report the rejected share count in our api

https://github.com/sp-hash/TeamBlackMiner/blob/main/API.md

The api should be enabled at default in hivos. But if not you can ask the hiveos devs.
