### ISSUE TITLE
Support Mining Rig Rentals

### ISSUE THREAD

**Issue by cncr04s** [sp-hash/TeamBlackMiner#185]
You can email us support at miningrigrentals.com

We're requesting you add support for our rig/pool services.
*.miningrigrentals.com and *.miningrigrentals.io on port 3344 for both eth and etc we use esm1 or esm2 (ethereum proxy). Your miner appears to use esm3/nicehash/ethereumstratum1.0, which we don't support.
We'd hope that our clients could use your miner with our service instead of other miners...

**Comment by binaryf** [comment]
We have implemented ethereum proxy protocol and it is now working.
I will also add miningrigrentals.io hostname and ips and test ETC.
