### ISSUE TITLE
Need to support server IP 

### ISSUE THREAD

**Issue by y525455383** [sp-hash/TeamBlackMiner#186]
Hello, I am a miner from mainland China. Your miner is very good, I appreciate it very much. 
Because of some government policy reasons, I need to connect to the mining pool through server transfer. However, when I enter my server Ip and corresponding port in miner, miner displays "This mining pool is not supported". 
I sincerely hope that you can solve this problem in the next version, thank you.

**Comment by sp-hash** [comment]
You can connect to a supported pool using the ipadress instead.

f.ex>
eth-hk.flexpool.io

has the ip

16.163.8.49

**Comment by y525455383** [comment]
![Uploading 1111.jpg…]()

the red word

**Comment by y525455383** [comment]
![image](https://user-images.githubusercontent.com/95900668/145537979-8bf6e2cb-4b03-4636-a9c8-d643ab81e56a.png)

**Comment by y525455383** [comment]
sorry the provided is not supported....

**Comment by binaryf** [comment]
The IP address have been updated. It is now working.
New release will be soon.
