### ISSUE TITLE
compatibility issues on linux distributions

### ISSUE THREAD

**Issue by oiG8Uchi** [sp-hash/TeamBlackMiner#187]
pc a : epyc 7551p + supermicro - h11ssl-i + 4 navi 22 + 2 navi 21, kernel version : 5.11.22 ( tooked a few commits from the 5.12 kernel to use /sys/class/drm/card*/device/pp_od_clk_voltage interface, because other kernel versions cannot make navi22 and navi21 run normally at the same time. )
pc b : celeron g1840 + asrock - z87 extreme6 + 3 navi 23, kernel version : 5.10.84 ( uses the dkms source code and firmware provided by amd drivers 21.40.1. )
both pcs are running gentoo linux

works well under glibc-2.33
error under glibc-2.34 :
`tbminer_1_31: /lib64/libpthread.so.0: version 'GLIBC_PRIVATE' not found ( required by tbminer_1_31 )`

both appear :
`tbminer_1_3x: /usr/lib64/libcurl.so.4: no version information available ( required by tbminer_1_3x )`

both pcs crash when "tbminer_1_32 -D", dmesg log:
`tbminer_1_32[26936]: segfault at 30 ip 00007f37a2bce3e8 sp 00007ffc3e1b1810 error 4 in libapr-1.so.0.7.0[7f37a2bba000+22000]`
`Code: 1f 00 4c 89 ef e8 48 c3 fe ff e9 66 ff ff ff e8 4e c3 fe ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 41 54 55 48 8d 6f 08 53 <48> 83 7f 30 00 74 41 48 89 fb 48 89 ef e8 e6 d4 fe ff 85 c0 75 25`

nvidia-drivers-460.39 is not supported. this is the highest version of the driver known to allow 3060 lhr v1 to run at 50mh/s 

ssl protocol mining pool address not supported, socks5 proxy not supported ( including mining dev. fee through the socks5 proxy, which is very important for users in mainland china. )

in pc a, rocm-smi and sensors display info. normally, but the TEMP/FAN/CORE/MEM/WATT in the tbm are all displayed as 0. 
in pc b, the info. displayed is all fine.

**Comment by binaryf** [comment]
It is on the list.
TLS, some proxy support, better Linux support and fixing the stats displayed as 0.

**Comment by binaryf** [comment]
It is on the list.
TLS, some proxy support, better Linux support and fixing the stats displayed as 0.

**Comment by hintro32** [comment]
About the driver requirement, according to https://docs.nvidia.com/deploy/cuda-compatibility/index.html, "applications compiled with a CUDA Toolkit release from within a CUDA major release family can run, with limited feature-set, on systems having at least the minimum required driver version as indicated". It sounds like CUDA 11.x builds can theoretically run as long as the driver version >=450.80.02.

**Comment by sp-hash** [comment]
We are using new features in the cuda toolkit, so our miner need cuda 11.2 or newer. Running it on 11.0 or 11.1 will give error messages. We are still building 11.2 versions for windows in order to support the 3060LHR1 fulll unlock.

**Comment by oiG8Uchi** [comment]
@sp-hash 
![image](https://user-images.githubusercontent.com/95996550/145710481-a746cca3-5876-4077-b8e2-de38cf3e62c7.png)
the built-in CUDA version of the 460.39 driver is 11.2. perhaps other reasons have caused tbm to fail to detect the 3060 lhr v1

**Comment by hintro32** [comment]
![image](https://user-images.githubusercontent.com/81028826/145711131-205c823c-e383-4b1e-9b52-87b37d87d249.png)
These forward compatibility packages offered by Nvidia supposedly allow you to mix-match driver and CUDA version. Not sure how well these packages work in general, but currently the miner does not work with them.

**Comment by sp-hash** [comment]
A cuda11.2 linux build is what you need. We might do that later.

**Comment by oiG8Uchi** [comment]
> Please provide the following information when you report a crash:

=================================================================

pool_ip: 
pool_hostname: asia-eth.2miners.com
pool_port: 2020
pool_ssl_port: 0
pool_http_path: 
keep_alive: 0
wallet: *****
worker_name: *****
verbose: 1
algo: ethash
log: 0
logfile: 
ssl: 0
ssl_verify: 0
ssl_cert: 
no_redirect: 0
retries: 4
retry_pause: 17
timeout: 185
cl_device 0: 0
cl_device 1: 1
cl_device 2: 2
x_intensity 0: -1
x_intensity 1: -1
x_intensity 2: -1
x_intensity 3: -1
x_intensity 4: -1
x_intensity 5: -1
x_intensity 6: -1
x_intensity 7: -1
x_intensity 8: -1
x_intensity 9: -1
x_intensity 10: -1
x_intensity 11: -1
x_intensity 12: -1
x_intensity 13: -1
x_intensity 14: -1
x_intensity 15: -1
x_intensity 16: -1
x_intensity 17: -1
x_intensity 18: -1
x_intensity 19: -1
x_intensity 20: -1
x_intensity 21: -1
x_intensity 22: -1
x_intensity 23: -1
x_intensity 24: -1
x_intensity 25: -1
x_intensity 26: -1
x_intensity 27: -1
x_intensity 28: -1
x_intensity 29: -1
x_intensity 30: -1
x_intensity 31: -1
x_intensity 32: -1
x_intensity 33: -1
x_intensity 34: -1
x_intensity 35: -1
x_intensity 36: -1
x_intensity 37: -1
x_intensity 38: -1
x_intensity 39: -1
x_intensity 40: -1
x_intensity 41: -1
x_intensity 42: -1
x_intensity 43: -1
x_intensity 44: -1
x_intensity 45: -1
x_intensity 46: -1
x_intensity 47: -1
x_intensity 48: -1
x_intensity 49: -1
x_intensity 50: -1
x_intensity 51: -1
x_intensity 52: -1
x_intensity 53: -1
x_intensity 54: -1
x_intensity 55: -1
x_intensity 56: -1
x_intensity 57: -1
x_intensity 58: -1
x_intensity 59: -1
x_intensity 60: -1
x_intensity 61: -1
x_intensity 62: -1
x_intensity 63: -1
dag_intensity 0: 0
dag_intensity 1: 0
dag_intensity 2: 0
dag_intensity 3: 0
dag_intensity 4: 0
dag_intensity 5: 0
dag_intensity 6: 0
dag_intensity 7: 0
dag_intensity 8: 0
dag_intensity 9: 0
dag_intensity 10: 0
dag_intensity 11: 0
dag_intensity 12: 0
dag_intensity 13: 0
dag_intensity 14: 0
dag_intensity 15: 0
dag_intensity 16: 0
dag_intensity 17: 0
dag_intensity 18: 0
dag_intensity 19: 0
dag_intensity 20: 0
dag_intensity 21: 0
dag_intensity 22: 0
dag_intensity 23: 0
dag_intensity 24: 0
dag_intensity 25: 0
dag_intensity 26: 0
dag_intensity 27: 0
dag_intensity 28: 0
dag_intensity 29: 0
dag_intensity 30: 0
dag_intensity 31: 0
dag_intensity 32: 0
dag_intensity 33: 0
dag_intensity 34: 0
dag_intensity 35: 0
dag_intensity 36: 0
dag_intensity 37: 0
dag_intensity 38: 0
dag_intensity 39: 0
dag_intensity 40: 0
dag_intensity 41: 0
dag_intensity 42: 0
dag_intensity 43: 0
dag_intensity 44: 0
dag_intensity 45: 0
dag_intensity 46: 0
dag_intensity 47: 0
dag_intensity 48: 0
dag_intensity 49: 0
dag_intensity 50: 0
dag_intensity 51: 0
dag_intensity 52: 0
dag_intensity 53: 0
dag_intensity 54: 0
dag_intensity 55: 0
dag_intensity 56: 0
dag_intensity 57: 0
dag_intensity 58: 0
dag_intensity 59: 0
dag_intensity 60: 0
dag_intensity 61: 0
dag_intensity 62: 0
dag_intensity 63: 0
templimit 0: 95
templimit 1: 95
templimit 2: 95
templimit 3: 95
templimit 4: 95
templimit 5: 95
templimit 6: 95
templimit 7: 95
templimit 8: 95
templimit 9: 95
templimit 10: 95
templimit 11: 95
templimit 12: 95
templimit 13: 95
templimit 14: 95
templimit 15: 95
fan_speed_limit: 0
cuda_all: 0
amd_only: 0
nvidia_only: 0
cl_all: 0
auto_detect: 0
gpu_sleep: 30
electricity_cost: 0.000000
electricity_currency: 
enable_ansi: 1
enable_stats: 1
no_cpu: 1
api: 0
api_ip: 
api_port: 0
miner run time: 471
pool reply time: 131ms
miner_device_number: 0
board_name: gfx1032
memory: 8 GB
pcie_id: 3
cl_device_index: 0
cl_platform_id: 0
cl_platform_type: 2
cl_platform_version: OpenCL 2.0 AMD-APP (3305.0)
cl_platform_version_major: 2
cl_platform_version_minor: 0
cl_device_version: OpenCL 2.0 
cl_device_version_major: 2
cl_device_version_minor: 0
cl_nv_compute: 
cl_nv_compute_major: 0
cl_nv_compute_minor: 0
cl_sm_count: 14
miner_device_number: 1
board_name: gfx1032
memory: 8 GB
pcie_id: 6
cl_device_index: 1
cl_platform_id: 0
cl_platform_type: 2
cl_platform_version: OpenCL 2.0 AMD-APP (3305.0)
cl_platform_version_major: 2
cl_platform_version_minor: 0
cl_device_version: OpenCL 2.0 
cl_device_version_major: 2
cl_device_version_minor: 0
cl_nv_compute: 
cl_nv_compute_major: 0
cl_nv_compute_minor: 0
cl_sm_count: 14
miner_device_number: 2
board_name: gfx1032
memory: 8 GB
pcie_id: 9
cl_device_index: 2
cl_platform_id: 0
cl_platform_type: 2
cl_platform_version: OpenCL 2.0 AMD-APP (3305.0)
cl_platform_version_major: 2
cl_platform_version_minor: 0
cl_device_version: OpenCL 2.0 
cl_device_version_major: 2
cl_device_version_minor: 0
cl_nv_compute: 
cl_nv_compute_major: 0
cl_nv_compute_minor: 0
cl_sm_count: 16
board: gfx1032
temp: 35
fan: 244
core: 895
mem: 950
power: 51
hashrate: 30.10 MH/s
hashrate (avg): 30.35 MH/s
accepted: 94
rejected: 0
board: gfx1032
temp: 34
fan: 244
core: 895
mem: 950
power: 52
hashrate: 30.37 MH/s
hashrate (avg): 30.35 MH/s
accepted: 99
rejected: 0
board: gfx1032
temp: 36
fan: 244
core: 945
mem: 1150
power: 63
hashrate: 34.09 MH/s
hashrate (avg): 34.24 MH/s
accepted: 102
rejected: 1
job: 35f34
bondary: 000000007e00001ef75b06324f6a8168014d8054c386f8c928e8981e0d036f18
header: 17fb7a9ced1ca371dd217912386fe2bc83f884a7b910a167effacbf011a63954
seed: 1bccaca36bfde6e5a161cf470cbf74830d92e1013ee417c3e7c757acd34d8e08
epoch: 461
block: -1
start_nonce: 13615789048424562688
extranonce_len: 4
difficulty: 2.031715
send buffer: ''
send buffer length: 0
recv buffer: '{"id":null,"method":"mining.notify","params":["35f34","1bccaca36bfde6e5a161cf470cbf74830d92e1013ee417c3e7c757acd34d8e08","17fb7a9ced1ca371dd217912386fe2bc83f884a7b910a167effacbf011a63954",false],"height":13849793}
'
recv buffer length: 214
recv buffer more data flag: 372020088

=================================================================
Please provide the above information when you report a crash.

**Comment by sp-hash** [comment]
1.32 and 1.33 had bugs. please upgrade to 1.35

**Comment by oiG8Uchi** [comment]
this is just one of the problems encountered. all versions from 1.32 to 1.35 will cause segfault due to problems with apr and glibc. there are also several other problems. I think it would be more appropriate to reopen this issue.

**Comment by oiG8Uchi** [comment]
I downgraded the version of apr to 1.6.3 to solve the segfault caused by this library, but other segfaults appeared:
`[286228.765981] tbminer_1_35[16988]: segfault at 18 ip 00007f9ede3e5eb0 sp 00007ffc0b48da48 error 4 in libpthread-2.33.so[7f9ede3e2000+f000]`
`[286228.766011] Code: 00 87 55 00 83 fa 01 0f 8e 30 ff ff ff 45 31 d2 ba 01 00 00 00 be 01 00 00 00 48 89 ef b8 ca 00 00 00 0f 05 e9 14 ff ff ff 90 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 7c 00 00 00 53 48`

**Comment by hintro32** [comment]
I would suggest making the Linux builds more static, limiting dependency to perhaps just glibc like many other closed-source miners do.

**Comment by oiG8Uchi** [comment]
I used debootstrap today to build a chroot environment of the ubuntu bionic version, rocm-smi, clinfo has been able to display info. normally, but I still get the segmentation fault prompt when I run the latest version:
```
[952196.479359] TBMiner[26074]: segfault at 18 ip 00007f16f09edfd0 sp 00007ffde96e4b18 error 4 in libpthread-2.27.so[7f16f09e4000+1a000]
[952196.479374] Code: 01 41 83 f9 01 0f 87 4f fb ff ff 48 8d 0d 28 a9 00 00 48 8d 35 b6 a7 00 00 48 8d 3d ea a7 00 00 ba ae 01 00 00 e8 70 b8 ff ff <8b> 47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 0f 85 ab 00 00 00 48
```
It seems that I have no way to run the latest version on my pc.

**Comment by sp-hash** [comment]
did you try the 11.4 build? I just uploaded a new one

**Comment by oiG8Uchi** [comment]
I just ran TBMiner in TeamBlackMiner_1_35_Ubuntu_18_04_Cuda_11_4.tar.gz and got the same error

**Comment by oiG8Uchi** [comment]
my mistake. if don’t run -D to get the gpu list and only mining, it seems to work. but
![image](https://user-images.githubusercontent.com/95996550/147276193-23c69b48-3577-44ab-b7a9-09f8d09e2211.png)
![image](https://user-images.githubusercontent.com/95996550/147276391-002798b6-8ee6-4f7f-bb2c-9ea199778b24.png)

**Comment by binaryf** [comment]
I have decided we will not support any more Linux distributions.
It is too much work, and we do not see that as important.
