### ISSUE TITLE
Issue with busy GPUs and hashrate

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#189]
The miner doesn't skip busy GPUs when the -U option is used. Also the hashrate starts out good but still ends up lower than 1.28, even with the CUDA 11.5 build on Hive OS.

**Comment by sp-hash** [comment]
Found a bug in the -U, program hang when selecting non existing device. Fixed in v1.32

**Comment by hintro32** [comment]
Thanks for the update. 1.33 does seem to have helped with the hashrate problem, but for my 2080 and A6000 cards it still seems around 2% lower than 1.28. Is it because of changes made for LHR cards?

**Comment by sp-hash** [comment]
The 2080 and A6000 are rare cards. Optimizing for the 3xxxx series normally decline the performance of the older models.

**Comment by hintro32** [comment]
Can you show some sustained hashrate data on 1.28 vs 1.33 on Linux? I have yet to see a non lhr card that increased in hashrate from 1.28 to 1.33, and another person also noticed the drop in hashrate in 1.29 https://github.com/sp-hash/TeamBlackMiner/issues/169#issue-1069217735. 
A6000 is very similar to high end 30 series cards, shouldn't it benefit from those optimizations?

**Comment by hintro32** [comment]
On another note, I noticed some GPU timeout errors:
![image](https://user-images.githubusercontent.com/81028826/146633663-819ade85-c2bf-4e46-ab96-34df47122dbc.png)
![image](https://user-images.githubusercontent.com/81028826/146633671-c2c8db6e-7f50-4785-a51c-d5acff5dcc92.png)
This is strange considering these GPUs are at stock (can't be overclocked) and are at good temperatures. Any idea what might have caused the errors?

**Comment by sp-hash** [comment]
Can you run the following please?


nvidia-smi --query-gpu=gpu_bus_id,temperature.gpu,power.draw,fan.speed,clocks.sm,clocks.mem,temperature.memory -i 0000:01:00.0 --format=csv,noheader,nounits

**Comment by sp-hash** [comment]
f

**Comment by hintro32** [comment]
```
nvidia-smi --query-gpu=gpu_bus_id,temperature.gpu,power.draw,fan.speed,clocks.sm,clocks.mem,temperature.memory -i 00000000:3B:00.0 --format=csv,noheader,nounits
00000000:3B:00.0, 63, 197.96, [N/A], 1380, 877, 77
```

**Comment by sp-hash** [comment]
Strange that the stats doesn't work. Can you try tbminer --list-devices please. What is the output

**Comment by hintro32** [comment]
While mining:
```
./TBMiner -G -D

Available Cuda devices
-----------------------

Segmentation fault
```
I’ll try again later when it’s not mining

**Comment by sp-hash** [comment]
Fixed the GPU timeout errors. This is a pretty serious bug that can give -5% poolside. I think we will release 1.34 tomorrow.
