### ISSUE TITLE
It stops working immediately after the start

### ISSUE THREAD

**Issue by Zaqsnaider** [sp-hash/TeamBlackMiner#19]
Hello. Right after the start, this is the picture. Help please.
Driver Version: 461.92
Windows 10
swap file 50gb
TBMiner.exe --algo ethash --hostname eu1.ethermine.org --port 4444 --wallet xxxxx--worker_name Xxxxxx --server_passwd x --cuda-devices [0,1,2,3,4] --no-ansi --no-cpu --templimit 68 --xintensity -1
![1111](https://user-images.githubusercontent.com/42960166/133384093-1ed7f1d7-a5a3-48b9-b1c9-5b1bfce442d8.jpg)

**Comment by sp-hash** [comment]
Windows 7 or 8 ?  you need windows 10

**Comment by Zaqsnaider** [comment]
I indicated that I use Windows 10. Take a closer look.

**Comment by binaryf** [comment]
I browsed the sourcode to see if program could exit silently without an error message.
There should be a message before exit is called.
Is this the behaviour every time you start the program or do you also have some different output ?

**Comment by sp-hash** [comment]
Do you have internal graphics or amd cards enabled in the rig?

**Comment by Zaqsnaider** [comment]
Yes, there is an active internal graphics.

**Comment by Zaqsnaider** [comment]
log-file
     0m [2021-09-15 19:58:53.776] OpenCL driver version: 461.92
     0m [2021-09-15 19:58:53.776] Cuda driver version: 11.2
     0m [2021-09-15 19:58:53.776] Cuda runtime API version: 11.2
     0m [2021-09-15 19:58:53.776] 
     0m [2021-09-15 19:58:53.776]                                 
     0m [2021-09-15 19:58:53.776] 
     0m [2021-09-15 19:58:53.776] Welcome to Team Black Miner 1.04
     0m [2021-09-15 19:58:53.776]                                 
     0m [2021-09-15 19:58:53.776] 
     0m [2021-09-15 19:58:53.924] GPU0 P106-100 6GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 19:58:54.068] GPU1 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 19:58:54.209] GPU2 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 19:58:54.355] GPU3 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 19:58:54.487] GPU4 GeForce GTX 1060 6GB 6GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 19:58:54.551] Trying eu1.ethermine.org:4444 (ethash)
     0m [2021-09-15 19:58:54.576] Extranonce is set to 6437051242395992064
     0m [2021-09-15 19:58:54.576] Pool responded successfully to subscribe
     0m [2021-09-15 19:58:54.577] Difficulty is set to 1.000000
     0m [2021-09-15 19:58:54.603] Pool responded successfully to extranonce subscribe
     0m [2021-09-15 19:58:54.609] Pool responded successfully to authorize
     0m [2021-09-15 19:58:54.674] GPU0 Started Cuda work thread
     0m [2021-09-15 19:58:54.859] GPU1 Started Cuda work thread
     0m [2021-09-15 19:58:55.048] GPU2 Started Cuda work thread
     0m [2021-09-15 19:58:55.245] GPU3 Started Cuda work thread
     0m [2021-09-15 19:58:55.417] GPU4 Started Cuda work thread
     0m [2021-09-15 19:58:59.687] GPU0 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 19:58:59.687] GPU0 DAG generated in 5.01 seconds (4661244kb)
     0m [2021-09-15 19:58:59.687] GPU0 XIntensity set to Dynamic
     0m [2021-09-15 19:58:59.687] Job 22ecec
     0m [2021-09-15 19:58:59.689] Shutting down threads
     0m [2021-09-15 19:58:59.691] Stratum thread exited
     0m [2021-09-15 19:58:59.692] Control thread exited
     0m [2021-09-15 19:58:59.894] GPU4 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 19:58:59.915] GPU4 DAG generated in 4.50 seconds (4661244kb)
     0m [2021-09-15 19:58:59.915] GPU1 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 19:58:59.915] GPU2 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 19:58:59.915] GPU4 XIntensity set to Dynamic
     0m [2021-09-15 19:58:59.915] GPU3 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 19:58:59.927] GPU4 thread exited
     0m [2021-09-15 19:58:59.932] GPU1 DAG generated in 4.67 seconds (4661244kb)
     0m [2021-09-15 19:58:59.933] GPU1 XIntensity set to Dynamic
     0m [2021-09-15 19:58:59.945] GPU3 DAG generated in 4.68 seconds (4661244kb)
     0m [2021-09-15 19:58:59.945] GPU3 XIntensity set to Dynamic
     0m [2021-09-15 19:58:59.946] GPU1 thread exited
     0m [2021-09-15 19:58:59.958] GPU2 DAG generated in 4.69 seconds (4661244kb)
     0m [2021-09-15 19:58:59.958] GPU2 XIntensity set to Dynamic
     0m [2021-09-15 19:58:59.960] GPU3 thread exited
     0m [2021-09-15 19:58:59.969] GPU2 thread exited
     0m [2021-09-15 19:59:03.696] Exiting
     0m [2021-09-15 20:05:09.127] You have to specify a valid protocol
     0m [2021-09-15 20:05:09.128] Valid protocols are zil, ethash and etchash
     0m [2021-09-15 20:05:09.128] Shutting down threads
     0m [2021-09-15 20:05:13.135] Exiting
     0m [2021-09-15 20:05:15.249] You have to specify a valid protocol
     0m [2021-09-15 20:05:15.249] Valid protocols are zil, ethash and etchash
     0m [2021-09-15 20:05:15.249] Shutting down threads
     0m [2021-09-15 20:05:19.250] Exiting
     0m [2021-09-15 20:05:47.944] OpenCL driver version: 461.92
     0m [2021-09-15 20:05:47.944] Cuda driver version: 11.2
     0m [2021-09-15 20:05:47.944] Cuda runtime API version: 11.2
     0m [2021-09-15 20:05:47.944] 
     0m [2021-09-15 20:05:47.944]                                 
     0m [2021-09-15 20:05:47.944] 
     0m [2021-09-15 20:05:47.944] Welcome to Team Black Miner 1.04
     0m [2021-09-15 20:05:47.944]                                 
     0m [2021-09-15 20:05:47.944] 
     0m [2021-09-15 20:05:48.118] GPU0 P106-100 6GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 20:05:48.292] GPU1 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 20:05:48.467] GPU2 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 20:05:48.648] GPU3 GeForce GTX 1070 8GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 20:05:48.809] GPU4 GeForce GTX 1060 6GB 6GB (compute 6.1) added to miner as Cuda device
     0m [2021-09-15 20:05:48.859] Trying eu1.ethermine.org:4444 (ethash)
     0m [2021-09-15 20:05:48.891] Extranonce is set to 15015001157653233664
     0m [2021-09-15 20:05:48.891] Pool responded successfully to subscribe
     0m [2021-09-15 20:05:48.925] Difficulty is set to 1.000000
     0m [2021-09-15 20:05:48.925] Pool responded successfully to extranonce subscribe
     0m [2021-09-15 20:05:48.931] Pool responded successfully to authorize
     0m [2021-09-15 20:05:49.019] GPU0 Started Cuda work thread
     0m [2021-09-15 20:05:49.212] GPU1 Started Cuda work thread
     0m [2021-09-15 20:05:49.406] GPU2 Started Cuda work thread
     0m [2021-09-15 20:05:49.597] GPU3 Started Cuda work thread
     0m [2021-09-15 20:05:49.850] GPU4 Started Cuda work thread
     0m [2021-09-15 20:05:54.095] GPU0 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 20:05:54.096] GPU0 DAG generated in 5.08 seconds (4661244kb)
     0m [2021-09-15 20:05:54.096] GPU0 XIntensity set to Dynamic
     0m [2021-09-15 20:05:54.096] Job e5c768
     0m [2021-09-15 20:05:54.098] Shutting down threads
     0m [2021-09-15 20:05:54.105] Control thread exited
     0m [2021-09-15 20:05:54.105] Stratum thread exited
     0m [2021-09-15 20:05:54.229] GPU1 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 20:05:54.336] GPU1 DAG generated in 4.80 seconds (4661244kb)
     0m [2021-09-15 20:05:54.337] GPU2 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 20:05:54.337] GPU4 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 20:05:54.337] GPU1 XIntensity set to Dynamic
     0m [2021-09-15 20:05:54.337] GPU3 Starting generating ethash dag (Epoch: 441)
     0m [2021-09-15 20:05:54.352] GPU1 thread exited
     0m [2021-09-15 20:05:54.357] GPU4 DAG generated in 3.85 seconds (4661244kb)
     0m [2021-09-15 20:05:54.357] GPU4 XIntensity set to Dynamic
     0m [2021-09-15 20:05:54.372] GPU3 DAG generated in 4.77 seconds (4661244kb)
     0m [2021-09-15 20:05:54.372] GPU3 XIntensity set to Dynamic
     0m [2021-09-15 20:05:54.373] GPU4 thread exited
     0m [2021-09-15 20:05:54.387] GPU2 DAG generated in 4.85 seconds (4661244kb)
     0m [2021-09-15 20:05:54.387] GPU2 XIntensity set to Dynamic
     0m [2021-09-15 20:05:54.387] GPU3 thread exited
     0m [2021-09-15 20:05:54.396] GPU2 thread exited
     0m [2021-09-15 20:05:58.102] Exiting

**Comment by sp-hash** [comment]
Your gpu order is different than normal. can you run nvidia-smi --listdevices ?

**Comment by Zaqsnaider** [comment]
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi --list-gpus
GPU 0: P106-100 (UUID: GPU-10b9f650-0734-6a3e-f7fe-6c3788369e18)
GPU 1: GeForce GTX 1070 (UUID: GPU-b30ae7e1-cca3-8486-0aab-eef70f0c3956)
GPU 2: GeForce GTX 1070 (UUID: GPU-a06e9d53-6719-c892-6f1f-94d708213cef)
GPU 3: GeForce GTX 1060 6GB (UUID: GPU-d172d8fb-b6e5-f11a-54a5-4d49e5c83bdd)
GPU 4: GeForce GTX 1070 (UUID: GPU-40ee4f91-3a50-bb97-3246-49ae7b63a452)

C:\Program Files\NVIDIA Corporation\NVSMI>

**Comment by sp-hash** [comment]
Reproduced and fixed. v1.05
There was an index problem in the code if the internal graphics was on and amd
