### ISSUE TITLE
Problem with temps/ stats in the miner on hiveos

### ISSUE THREAD

**Issue by sp-hash** [sp-hash/TeamBlackMiner#192]
@hiveforum

![tbm](https://user-images.githubusercontent.com/9572668/146099585-fa27a7ef-0891-4fc6-a041-7812ce3d3306.png)
![tbm_flight](https://user-images.githubusercontent.com/9572668/146099589-7b3e7ff1-99ce-408c-b8b1-9a5bb040132d.png)

Hi guys, I’ve been facing an issue with one of my 6600xts; while in TBM Temps, power and fan parameters shown on worker dashboard, but there is no data on miner screen.

Issue started after adding my 3rd GPU, but 3rd GPU is ok,

Interestingly 1st GPU parameters are missing in miner screen.

Switched to TRM to check if parameteres still missing, but everything was OK there. Switched back to TBM and again missing parameters.

Another thing is 1st GPU fan speed is noticably higher from others, started again with addition of 3rd GPU, tried and checked both TBM and TRM, same results, and again insterestingly this GPU is located on top left, not facing any other gpus backplate, so it uses fresh air directly, no reason to go high temps. (AutoFan enabled with GPU:47, Mem:57)

Any ideas and/or suggestions?
Thanks in advance.

**Comment by binaryf** [comment]
Again, I have looked at the source-code and can not find any mistakes.
