### ISSUE TITLE
beginner issues. can't start. worker name error. 

### ISSUE THREAD

**Issue by dimitriovic** [sp-hash/TeamBlackMiner#193]
Hi, I try to mine on windows but it gives me a "worker name error"
I have a 6800xt and 6 nvidia. for now I'm trying to mine on 6800xt only.
here is my config:

Set ETH_WALLET= my wallet
:loop
	TBMiner --algo ethash --hostname eu1.ethermine.org --port 5555 --wallet %ETH_WALLET% --worker_name TEST1amd --xintensity -1 --templimit 66 -b -d
	timeout 10
goto :loop

**Comment by binaryf** [comment]
Try --worker-name

**Comment by dimitriovic** [comment]
ok the problem was underscore, it should be --worker-name TEST1amd and not --worker_name TEST1amd
for newbies like me -b is for amd gpu only and -d is allowing api.
Seems the 6800xt is doing really fine: 66.7mh/s ... ^^ wait a little bit and will uplaod a screenshot

**Comment by dimitriovic** [comment]
on my other computer I went to http://127.0.0.1:4068 but it did not work. am I missing something ?
should I add this:
-F 127.0.0.1 -R 4068

**Comment by binaryf** [comment]
Good it worked out. :) 
You should enable ansi colors. Do you have the *.reg script in your program folder ?
