### ISSUE TITLE
Memory Junction Temperature is 0

### ISSUE THREAD

**Issue by jandrop** [sp-hash/TeamBlackMiner#195]
![image](https://user-images.githubusercontent.com/8020875/146641299-2b226982-b3b3-4417-9af8-0b73fd4e862e.png)

I realize that in the temp section there's a 0 that should be the Memory temp, right? I think this is a bug.

**Comment by hintro32** [comment]
What does ```nvidia-smi --query-gpu=gpu_bus_id,temperature.gpu,power.draw,fan.speed,clocks.sm,clocks.mem,temperature.memory --format=csv,noheader,nounits``` show?
For some of my GPUs the last value (mem temp) shows N/A, in which case it is not the miner's fault but the driver's.

Also for a long time I couldn't get it to display any GPU stats, but it is working now after I updated my environment to ubuntu 20.04 and updated the miner's dependencies: libapr1 libssl-dev curl zlib1g libidn2-0 libpsl-dev

I also noticed this happening when I ran multiple instances of the miner on the same machine for testing out 1.28 vs 1.33:
![image](https://user-images.githubusercontent.com/81028826/146663925-071f4334-e0d2-4af0-a24d-774744e392f8.png)
It seems that with the same settings (Xintensity, clocks, etc.), 1.28 has higher hashrate but also more stales.

**Comment by sp-hash** [comment]
If you run the second instance of the miner in a seperate folder, you don't get the nvidia-smi error messages.

**Comment by jandrop** [comment]
> 
![image](https://user-images.githubusercontent.com/8020875/146677022-f4df0cbb-6300-4027-99b5-345d59d0f4a8.png)

**Comment by sp-hash** [comment]
So this is not supported yet for your card. Little we can do about it.
