### ISSUE TITLE
Why is ZIL dag generated? Command line does not contain any ZIL settings

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#196]
00:04:04 [2021-12-19 13:53:03.091] Pool responded successfully to subscribe
00:04:04 [2021-12-19 13:53:03.145] Pool responded successfully to authorize
00:04:04 [2021-12-19 13:53:03.160] Pool responded successfully to extranonce subscribe
00:04:04 [2021-12-19 13:53:03.175] Difficulty is set to 0.248137
00:04:04 [2021-12-19 13:53:03.217] Job 0000000062d1d6b9
**00:04:04 [2021-12-19 13:53:03.959] GPU0 Starting generating zil dag (Epoch: 0)**
00:04:04 [2021-12-19 13:53:03.959] GPU0 DAG generated in 0.63 seconds (1048574kb)
00:04:04 [2021-12-19 13:53:03.959] GPU0 kernel 6 selected
00:04:04 [2021-12-19 13:53:03.959] Job 0000000062d1d6b9
00:04:04 [2021-12-19 13:53:07.270] Job 0000000062d1d6ba
00:04:04 [2021-12-19 13:53:09.627] Job 0000000062d1d6bb
00:04:04 [2021-12-19 13:53:12.215] Job 0000000062d1d6bc

My command line does not contain any ZIL settings:

`TBMiner.exe --algo ethash --hostname daggerhashimoto.eu-west.nicehash.com --port 3353 --wallet ###########################.########--worker-name ########## --server-passwd x --tweak 2 --api --api-port 4001 --cuda-devices [0]`

**Comment by sp-hash** [comment]
The daggerhashimoto soloport on nicehash can be any coin.
