### ISSUE TITLE
malloc invalid size error

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#197]
![image](https://user-images.githubusercontent.com/81028826/146721802-4061df2a-c1a7-4e1b-8f83-e22ddf9dbc27.png)
Version 1.33 on Linux

**Comment by hintro32** [comment]
Log file seems to only go up to 20:08
![image](https://user-images.githubusercontent.com/81028826/146724670-e70250f7-0d4d-41b2-985c-e971be4d3fa1.png)

**Comment by sp-hash** [comment]
fixed in 1.34
