### ISSUE TITLE
1.35 issues

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#199]
The 1.35 cuda 11.5 build for Linux is giving me a lot of issues on crazypool:
![image](https://user-images.githubusercontent.com/81028826/147011927-1c39cbfa-3db3-471a-bac2-73ac769387fc.png)
![image](https://user-images.githubusercontent.com/81028826/147010342-f2130752-ec99-464f-88d9-548586998f6f.png)
Perhaps the 20 second timeout is too short.
For now I'll use a different pool or use an older version.

I also noticed this popping up in recent versions (including 1.35):
```sh: 1: cannot create gpuinfo: File exists```
![image](https://user-images.githubusercontent.com/81028826/147010854-8dcdb271-99d5-4a17-9bf7-948bb08f89a4.png)
Is this file why we should run different instances of the miner in different directories?

**Comment by hintro32** [comment]
I know you are focusing more on LHR cards atm, but can we pay a bit more attention to the performance regression on non LHR cards? Here's another person who said their RTX 3080 saw about 2% decrease in hashrate: https://bitcointalk.org/index.php?topic=5358334.msg58622456#msg58622456

I hope questions about non LHR hashrate decrease can be properly addressed soon. No, I don't think this is caused by driver/cuda version, cards being too "rare/old", or miner settings. This is either caused by different calculation of hashrate or some change in the code that adversely affected non LHR cards.

**Comment by hintro32** [comment]
Another minor bug, when two shares are found at almost the same time, the displayed pool reply time is incorrect:
![image](https://user-images.githubusercontent.com/81028826/147045467-8da6e489-c51d-482a-b0d5-34662c225a46.png

**Comment by sp-hash** [comment]
If you use low --dagintensity, the performace might go down abit. In v1.35 you can try with different dag intensies
to see if it helps

**Comment by hintro32** [comment]
I have been using -K 8. However, even with -E 4096 -K 8, I can't make the hashrate as high as -default in 1.28. I am guessing some sort of LHR unlock wrongly kicks in, because 1.35 is able to briefly have the same hashrate as 1.28. Interestingly, the hashrate drop happens faster with higher -E values.

BTW I added -t 80 when using 1.35 and it works fine with crazypool now.

**Comment by sp-hash** [comment]
Use -K 9 it is the maximum on NVIDIA

**Comment by hintro32** [comment]
I tried that, it actually makes the hashrate lower.

**Comment by binaryf** [comment]
Thank you for the feedback.
We may have written this miner to complex.
