### ISSUE TITLE
sorry the provided pool is not supported

### ISSUE THREAD

**Issue by y525455383** [sp-hash/TeamBlackMiner#201]
<img width="646" alt="tbm1" src="https://user-images.githubusercontent.com/95900668/147382335-1557f5ae-8e74-4e13-9ed6-d8d457f192fc.png">

**Comment by sp-hash** [comment]
which pool?

**Comment by y525455383** [comment]
2miner，But I use the ip address forwarded by my own server.

**Comment by sp-hash** [comment]
Use the ipadress of the pool directly.

**Comment by y525455383** [comment]
I'm in mainland China and can't use the ipadress of the pool directly.

**Comment by sp-hash** [comment]
ip adresses should work if you set up a ssh tunnel.

**Comment by y525455383** [comment]
how to set up a ssh tunnel

**Comment by y525455383** [comment]
我认为你们数据库中只提供了各个矿池的官方ip地址，而不允许我们使用中转的ip地址链接？

**Comment by sp-hash** [comment]
yes, but we support different ports so you can use ssh tunnel. Google it

**Comment by y525455383** [comment]
你们不准备支持 矿工自己服务器的端口，right？

**Comment by DeanJing** [comment]
> 你们不准备支持 矿工自己服务器的端口，right？
他们不做大陆生意，问了也白问。我也提过，但他们根本不当回事，拉倒吧，表显都是假的，用回TRM。
