### ISSUE TITLE
Any plans to integrate VertHash into TBMiner?

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#203]
If not I recommend you update the documentation:

https://github.com/sp-hash/TeamBlackMiner#supported-algorithms-and-developer-commission

**Comment by sp-hash** [comment]
Vertcoin is supported, but you need to copy spminer into the folder.

https://github.com/sp-hash/TeamBlackMiner/blob/main/VERTCOIN.md
