### ISSUE TITLE
p104-100 issue

### ISSUE THREAD

**Issue by alexstab** [sp-hash/TeamBlackMiner#209]
mine p104-100 dont accept other than --dagintensity 1. others cards in my rig are ok with --dagintensity 9 (2x1060,3060ti and quadro 4000)
so mine p104 works at -30% of their hashrate...about 24/26mhs vs 32/34mhs.
alex

**Comment by sp-hash** [comment]
I think we've had problems with the p104-100 in the past releases as well. Wich driver and cuda version are you running? Linux or windows?

**Comment by alexstab** [comment]
i use win 10 nvidia driver 471.11 cuda 11.4. i think the problem appeared after 1.32...in 1.32 mine p104 were all in 32/34 range.

**Comment by sp-hash** [comment]
Ok. Checked in a possible fix in v1.37
