### ISSUE TITLE
Hard time generating DAG

### ISSUE THREAD

**Issue by Kroissan** [sp-hash/TeamBlackMiner#21]
First, i need to say that your work looks rlly promising, i did break the 200Mhs with 6x6600xt. I had to reduce my memory clock compared to Teamredminer but i'm still getting better performance.

However, dag generation is a bit erratic. I had to put a -100mhz offset on memory over what i used whith team red miner to generate DAGs. When the dag are generated i can go +50Mhz easily.
The dag generation seems too stressfull for memory and idk if you could make it go slower but less intensive so i can keep my memory configuration when starting the miner. 

Also stats totally dont work, 0 everywhere. Using windows 10 21H1, Adrenalin 21.8.2. I can do some more testing if u want me too. (teamblackminer v1.04)

**Comment by sp-hash** [comment]
I can reduce it abit in v1.05

**Comment by Kroissan** [comment]
Dag generation is better in 1.06 thanks
