### ISSUE TITLE
1.36 and Ubuntu 18 and CUDA 11.4

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [sp-hash/TeamBlackMiner#210]
Will you compile 1.36 binary also for Ub18 with cuda 11.4 compatible?

**Comment by sp-hash** [comment]
Perhaps. later.

**Comment by hintro32** [comment]
> Will you compile 1.36 binary also for Ub18 with cuda 11.4 compatible?

The 20.04 build works for me on 18.04 too

**Comment by sp-hash** [comment]
Can you try the 1.38 binary please?

**Comment by tymoteuszrogalewski** [comment]
your version for Ub20 is not working under Ub18 (SimpleMining). Ub 20 requires newer version of GLIBC than present in Ub18.

root@simplemining:/home/miner/TeamBlackMiner_1_38_Ubuntu_20_04_Cuda_11_5# ./TBMiner --help
./TBMiner: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./TBMiner)

And most important for now is that our (SimpleMining) clients most use images with only CUDA 11.4 support. CUDA 11.5 support will be in SimpleMining added in future, but actually it isnt.

**Comment by hintro32** [comment]
> your version for Ub20 is not working under Ub18 (SimpleMining). Ub 20 requires newer version of GLIBC than present in Ub18.
> 
> root@simplemining:/home/miner/TeamBlackMiner_1_38_Ubuntu_20_04_Cuda_11_5# ./TBMiner --help ./TBMiner: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./TBMiner)
> 
> And most important for now is that our (SimpleMining) clients most use images with only CUDA 11.4 support. CUDA 11.5 support will be in SimpleMining added in future, but actually it isnt.

GLIBCXX is not GLIBC, you just need to install a recent GCC and libstdc++6, by doing something like ```apt install gcc-9 libstdc++6```

I do agree CUDA 11.4 support should be added.

**Comment by tymoteuszrogalewski** [comment]
We don't want do such "mass updates" on working clients rigs - too much risk of failure.
In future our system will be based on Ub20, but not in near future. Actual official SimpleMining images are based on Ub18 with CUDA 11.4 support and this is requirements for miners to work.
Thank you.
