### ISSUE TITLE
DAG generation behavior

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#211]
It seems that the miner doesn't start generating DAG for GPUs other than GPU0 until 20 seconds later. The time taken to generate DAG for those GPUs also don't make sense (0.05 seconds). Is this normal behavior?
![image](https://user-images.githubusercontent.com/81028826/148619872-d815ce45-0f85-4c0b-a549-fe6dbffa6b57.png)

**Comment by hintro32** [comment]
Also it seems like the displayed shares per minute is wrong after 16 minutes:
At 15 min:
![image](https://user-images.githubusercontent.com/81028826/148621066-2df60915-4412-499e-bdc7-27091936f937.png)
16 min:
![image](https://user-images.githubusercontent.com/81028826/148621141-15155ed5-e562-484c-b68d-49a74c9fabe9.png)

Or is shares per minute tracked in a 15-minute window? That seems too short to be accurate.

**Comment by sp-hash** [comment]
Dag buffers should be created in parallell. I think that the console output is delayed. 20 seconds for dag generation and validation seems abit high, but perhaps you are running slow cards?

--dagintensity 9 is the fastest on nvidia.

**Comment by sp-hash** [comment]
Seems to be a small bug in the shares per minute calculation. will check it

**Comment by hintro32** [comment]
> Dag buffers should be created in parallell. I think that the console output is delayed. 20 seconds for dag generation and validation seems abit high, but perhaps you are running slow cards?
> 
> --dagintensity 9 is the fastest on nvidia.

They are all the same cards, and when using only one card dag gen and verification finishes in less than 10 seconds
![image](https://user-images.githubusercontent.com/81028826/148641504-54f9fe52-87a5-4c10-9ddd-fd76246fcd41.png)

**Comment by sp-hash** [comment]
Submitted a possible fix in 1.37

**Comment by sp-hash** [comment]
can you try 1.37 please

https://github.com/sp-hash/TeamBlackMiner/releases/tag/v1.37

perhaps --daginsity 8 is working now on the p104?

**Comment by hintro32** [comment]
> can you try 1.37 please
> 
> https://github.com/sp-hash/TeamBlackMiner/releases/tag/v1.37
> 
> perhaps --daginsity 8 is working now on the p104?

Things do look better now, but seems like other cards still lag GPU0:

![image](https://user-images.githubusercontent.com/81028826/148660076-50a88f2e-e4e5-430c-b831-2c5c60dd69de.png)
and the lag is larger with lower DAG intensities:
![image](https://user-images.githubusercontent.com/81028826/148660170-2a38f20d-04be-4d05-897b-ac6b5d904ee6.png)
![image](https://user-images.githubusercontent.com/81028826/148660204-983f2ea0-bd35-45ac-87bc-dd5efa8905d5.png)

**Comment by hintro32** [comment]
Somehow version 1.32 seems to do better:
![image](https://user-images.githubusercontent.com/81028826/148663747-ab4150fa-cddb-4cc3-9dda-f62223d1c17f.png)

**Comment by sp-hash** [comment]
try to run without dagintensity

**Comment by hintro32** [comment]
> try to run without dagintensity

![image](https://user-images.githubusercontent.com/81028826/148660204-983f2ea0-bd35-45ac-87bc-dd5efa8905d5.png)
