### ISSUE TITLE
1.38 problem hiveos

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#214]
Hello i have problem with the new versions.

Rig with only AMD

![image](https://user-images.githubusercontent.com/11719145/148967190-5aa3a89a-4edf-4b56-b232-bb877e9c60af.png)

**Comment by eosphor** [comment]
Same problem

**Comment by esille** [comment]
Same here

**Comment by mevlutfazergt69** [comment]
Same problem with Nvidia

**Comment by sp-hash** [comment]
hiveos just released a new version with 1.38. Cuda 11.5 only. cuda 11.4 build today or tomorrow

**Comment by sp-hash** [comment]
from @bitcointalk:

run

sudo apt-get install --only-upgrade libstdc++6

**Comment by sp-hash** [comment]
ubuntu 18.04 11.4 build released
