### ISSUE TITLE
1.38 timeout error

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#216]
I launched the miner with -t 30, and the miner reconnected at one point due to the 30 second limit, but soon after the miner went on with nothing but "cannot open nvidia-smi" errors for minutes before it finally exited.
![image](https://user-images.githubusercontent.com/81028826/149065025-802fddea-3b94-497b-aaff-ee12da8ae518.png)
![image](https://user-images.githubusercontent.com/81028826/149065119-623b8d73-b4a7-458c-a203-99305565bd36.png)
![image](https://user-images.githubusercontent.com/81028826/149065166-e930c761-50ac-484b-8324-f1dc72363645.png)
![image](https://user-images.githubusercontent.com/81028826/149065228-a2c58bd7-2715-4490-8d0b-1a7af096e1b0.png)

Also what is this gpuinfo file? This might not be relevant, but I put my miner files on a network drive to easily sync across devices

**Comment by hintro32** [comment]
On another occasion:
![image](https://user-images.githubusercontent.com/81028826/149073165-1d898182-7cf2-4962-9ab9-c2169c8e53c9.png)
![image](https://user-images.githubusercontent.com/81028826/149073198-334f50a5-3f1c-4398-b1da-6a2506d4dfdd.png)

**Comment by sp-hash** [comment]
The fix is not to use -t 30 on crazypool, but I will try to reproduce.

**Comment by sp-hash** [comment]
fixed in v1.41
