### ISSUE TITLE
1.39  (Windows 11): Odd launch behavior / error on GTX 1660

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#217]
Command line used:
TBMiner.exe --algo etchash --hostname europe.etchash-hub.miningpoolhub.com --port 20615 --wallet ############.####### --worker-name ######## --server-passwd x --tweak 2 --api --api-port 4005 --cuda-devices [0]

Binary used:
TeamBlackMiner_1_39_cuda_11_6.7z

When launched in a normal CMD window the miner starts just fine:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/30080938/149558830-7711d32e-ca4c-47a0-8c86-f0999124717c.png">
(Note the CUDA version 11.**5**)

However when stated with (same parameters used):
`[Kernel32]::CreateProcess($BinaryPath, "$BinaryPath $ArgumentList", [ref]$SecAttr, [ref]$SecAttr, $false, $CreationFlags, [IntPtr]::Zero, $WorkingDirectory, [ref]$StartupInfo, [ref]$ProcessInfo)`

<img width="406" alt="image" src="https://user-images.githubusercontent.com/30080938/149559187-83396236-cc3e-44ec-8b3c-eb9134a8c533.png">
(Note the CUDA version 11.**6**)

Older versions were working fine.

Edit:
TeamBlackMiner_1_39_cuda_11_5.7z works in both cases.

**Comment by UselessGuru** [comment]
My bad. False alarm
>> When launched in a normal CMD window the miner starts just fine:
this was pointing to another directory.

**Comment by sp-hash** [comment]
yes. I uploaded 11_5. For the cuda 11.6 build you need to install the latest driver. the toolkit was released yesterday, so I haven't had time to test it yet.
