### ISSUE TITLE
Suggestion: add an option to disable NVML GPU stats

### ISSUE THREAD

**Issue by hintro32** [sp-hash/TeamBlackMiner#218]
Many other miners offer this option, which is useful for reducing program output and avoiding situations like this:
![image](https://user-images.githubusercontent.com/81028826/149579487-cc72d059-dd41-4b33-9b69-631cc180b558.png)
![image](https://user-images.githubusercontent.com/81028826/149579559-df77872f-dfc0-4e58-8df7-d5c8b76b2ec2.png)

**Comment by sp-hash** [comment]
-B --no-stats Disable statistics. A flag to disable statistics.

**Comment by hintro32** [comment]
But that disables all the stats, I still want hashrate and shares stats.
