### ISSUE TITLE
Add a Ton mining algorithm 

### ISSUE THREAD

**Issue by filzek** [sp-hash/TeamBlackMiner#219]
Hi,

We tested some good things to bring a new light to cryptoscene.

We have been able to commute from eth to ton mining and make the two profitable, so, why not add this to Teamblackminer so we can mining Eth+ton and let us choose how many delivery shares from each Eth to jump to Ton and how many shares to jump back to Eth.

It is the way we do right now using a firewall code to block pool communications to literally pause the miner until the log from the secondary coin has meet the shares delivered and so we block other pool firewall. Also when activated the firewall for one pool we change the OverClock for the coin.

**Comment by pdieppa** [comment]
No many crypto miner programs will support TON since you will not be able to mine it in about 3 months.

**Comment by sp-hash** [comment]
fpga algo
