### ISSUE TITLE
[BUG] gpu informations display shift 

### ISSUE THREAD

**Issue by boucz** [sp-hash/TeamBlackMiner#22]
Hello,
On this rig I have 4 GPU (1080ti, 1080ti, 3080, rx480 8GB)
The array of informations does have a row shift (TEMP for GPU0 is displayed in GPU1, TEMP for GPU1 is displayed in GPU2...)

![image](https://user-images.githubusercontent.com/12842861/133618725-c7695237-df1f-4cf2-99de-d7ea2435e8c6.png)

i'm using TeamBlackMiner_1_04_Ubuntu_18_04_Cuda_11_4 in hiveOS.
Thanks for you're work !

**Comment by sp-hash** [comment]
yes, this has been fixed in v1.05. Going to be released soon

**Comment by boucz** [comment]
Ok, thanks !
