### ISSUE TITLE
1.24 только запускается на винде.остальные все не пашут((

### ISSUE THREAD

**Issue by slavan005** [sp-hash/TeamBlackMiner#222]

**Comment by sp-hash** [comment]
скриншот

**Comment by slavan005** [comment]
[![FastPic.Ru](https://i116.fastpic.org/thumb/2022/0115/a8/e0cc44391c2ff34c1d70c316aa2325a8.jpeg)](https://fastpic.org/view/116/2022/0115/e0cc44391c2ff34c1d70c316aa2325a8.jpg.html)

**Comment by sp-hash** [comment]
try to run with --no-ansi and --dagintensity 1

**Comment by slavan005** [comment]
в новой версии все работает
