### ISSUE TITLE
Hi admin

### ISSUE THREAD

**Issue by ykutlu** [sp-hash/TeamBlackMiner#223]
2miners pool work eth mining. alternate paying system (ETH-NANO and ETH-BTC)

when i insert real eth adres, program working,
when i insert nano address or BTC address program exit.

waiting repair... Thansk...
(PS: interesting version 1.23 working)

Set ETH_WALLET=nano_1p4pa5rho9oh1ojuxmu5eojn3976umme37ui8sik7fb4xnq65epxtjem43rg
:loop
	TBMiner --algo ethash --hostname eth.2miners.com --port 2020 --wallet %ETH_WALLET% --worker-name %computername%
	timeout 10
goto :loop

or

Set ETH_WALLET=1GAeCrkBSachVg7bVVVzPtnH5yWAs3PWgG
:loop
	TBMiner --algo ethash --hostname eth.2miners.com --port 2020 --wallet %ETH_WALLET% --worker-name VegaRig2 -b 
	timeout 10
goto :loop

**Comment by sp-hash** [comment]
We will fix it in the next release

**Comment by sp-hash** [comment]
fixed in v1.41
