### ISSUE TITLE
[HiveOs] 1.39 terminate called after throwing an instance of 'cl::BuildError'

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#224]
Hello i have problem with the new version of TBM

![image](https://user-images.githubusercontent.com/11719145/149633149-7efa9aa0-9d34-41bc-80be-1e1cd6418b36.png)

**Comment by MrNuTruT** [comment]
Rig only AMD card

**Comment by sp-hash** [comment]
fixed in 1.40

**Comment by unknown2this** [comment]
Can you create a release for Cuda 11.4?

**Comment by sp-hash** [comment]
cuda 11.4 added
