### ISSUE TITLE
[AMD] Missing/Inaccurate Resource Metrics

### ISSUE THREAD

**Issue by chrishilbert** [sp-hash/TeamBlackMiner#226]
My AMD card watt usages are way off compared to all other miners.  Some are missing.  GPU0 should be ~110 to 120w (RX 6800), GPU1/2 are missing (RX 6700, RX6600), GPU3 should be ~40w and identical to GPU2, and GPU4 (RX 6600 XT) should be ~50w.

00:00:09 [2022-01-17 08:09:06.506] nanopool.org (ethash)    PING: 138ms    VARDIFF: 2.33     EPOCH: 467
00:00:09 [2022-01-17 08:09:06.506]                                                                                 
00:00:09 [2022-01-17 08:09:06.506] 
00:00:09 [2022-01-17 08:09:06.506] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:00:09 [2022-01-17 08:09:06.506] GPU0    gfx1032  OpenCL  0       71      41/0    153     935     1079    50     
00:00:09 [2022-01-17 08:09:06.506] GPU1    gfx1032  OpenCL  0       71      0/0     0       0       0       0      
00:00:09 [2022-01-17 08:09:06.506] GPU2    gfx1032  OpenCL  0       71      0/0     0       0       0       0      
00:00:09 [2022-01-17 08:09:06.506] GPU3    gfx1031  OpenCL  0       71      46/0    153     1200    1074    88     
00:00:09 [2022-01-17 08:09:06.506] GPU4    gfx1030  OpenCL  0       71      47/0    153     1275    1059    82

**Comment by chrishilbert** [comment]
Also note the fan speeds are all 60, but showing incorrectly.

**Comment by chrishilbert** [comment]
Last observation.  It looks like the GPUs are ordered inversely.  GPU0 = GPU4 and so on.  That would explain the higher watts maybe.  Therefore the 2 GPUs with 0 data are both XFX RX 6600s.

**Comment by sp-hash** [comment]
Yes we use a different order than hiveos. Run tbminer --list-devices to see the order.

**Comment by chrishilbert** [comment]
Can you add an option to make the order match HiveOS?  I'm running this on HiveOS.  All the other miners I've tried (a lot of em) use the same order as HiveOS.

I only get the wrong output from TBM.  Gminer, TRM, etc all display proper metrics/values.  Where's the miner window on HiveOS?  I'm looking at it in SSH and in the HiveOS dashboard.

**Comment by sp-hash** [comment]
We have flipped the order in v1.41

**Comment by chrishilbert** [comment]
Did you get the 6600s to display data?

**Comment by sp-hash** [comment]
We have flipped the order of AMD cards to be equal to hiveos.
