### ISSUE TITLE
nanopool connection disconnect/timeout

### ISSUE THREAD

**Issue by chrishilbert** [sp-hash/TeamBlackMiner#227]
Getting a lot of disconnects/timeouts to nano pool.  Might need to be tweaked to a higher timeout?

00:01:27 [2022-01-17 09:27:53.787] Job 591ae
00:01:27 [2022-01-17 09:27:54.365] Job 591af
00:01:27 [2022-01-17 09:27:56.677] Job 591b0
00:01:27 [2022-01-17 09:27:58.002] Have not received response from pool, 20 seconds
00:01:27 [2022-01-17 09:27:58.002] Stratum thread exited
00:01:27 [2022-01-17 09:27:58.044] Pool connection disconnected or timed out
00:01:27 [2022-01-17 09:27:58.044] Starting new stratum thread
00:01:27 [2022-01-17 09:27:58.045] Trying eth-us-east1.nanopool.org:9999 (ethash)
00:01:27 [2022-01-17 09:27:58.285] Pool responded successfully to subscribe
00:01:27 [2022-01-17 09:27:58.400] Pool responded successfully to extranonce subscribe
00:01:27 [2022-01-17 09:27:58.400] Extranonce is set to 4318389092694884352
00:01:27 [2022-01-17 09:27:58.423] Pool responded successfully to authorize
00:01:27 [2022-01-17 09:27:58.423] Difficulty is set to 2.328200
00:01:27 [2022-01-17 09:27:58.701] Job 29a016
00:01:28 [2022-01-17 09:27:59.568] Job 29a017
00:01:28 [2022-01-17 09:28:02.458] Job 29a018

**Comment by sp-hash** [comment]
Was this in v1.40?

Are you on a slow connection? You can try to set the timout to 80 seconds with -t 80

**Comment by chrishilbert** [comment]
This is v1.40.  It's on a bidirectional gigabit connection hardwired.

**Comment by chrishilbert** [comment]
-t 80 added in HiveOS didn't get rid of the error :/

**Comment by chrishilbert** [comment]
00:00:07 [2022-01-17 12:28:52.241] Job 299bd7
00:00:07 [2022-01-17 12:28:53.002] Have not received response from pool, 20 seconds
00:00:07 [2022-01-17 12:28:53.002] Stratum thread exited
00:00:07 [2022-01-17 12:28:53.080] Pool connection disconnected or timed out
00:00:07 [2022-01-17 12:28:53.080] Starting new stratum thread
00:00:07 [2022-01-17 12:28:53.081] Trying eth-us-east1.nanopool.org:9999 (ethash)
00:00:07 [2022-01-17 12:28:53.351] Pool responded successfully to subscribe
00:00:07 [2022-01-17 12:28:53.484] Pool responded successfully to extranonce subscribe
00:00:07 [2022-01-17 12:28:53.484] Extranonce is set to 15897425209641140224
00:00:07 [2022-01-17 12:28:53.508] Pool responded successfully to authorize
00:00:07 [2022-01-17 12:28:53.508] Difficulty is set to 2.328200
00:00:07 [2022-01-17 12:28:53.654] Job 29b1d8
00:00:07 [2022-01-17 12:28:55.631] Job 29b1d9
00:00:07 [2022-01-17 12:28:57.325] Job 29b1da
00:00:07 [2022-01-17 12:28:57.426] GPU1 Solution found in 2.08s (Submit every 44.61 seconds)
00:00:07 [2022-01-17 12:28:57.570] Accepted (10/10/0) Reply: 144ms
00:00:07 [2022-01-17 12:28:57.607] Job 29b1d

**Comment by sp-hash** [comment]
fixed in v1.41
