### ISSUE TITLE
V1.40 RX 6700XT Lower Hashrate

### ISSUE THREAD

**Issue by Dysgenesis** [sp-hash/TeamBlackMiner#228]
Hey there,

I've used v1.27 until today's hiveos update which no longer supports that version so I switched to the latest 1.40. The issue is I was getting around 49-50 Mhs with v1.27 on a single RX 6700XT, not it has dropped to around 48's. I've also tried some different oc's yet the result is same. A tiny fix for that would be awesome.

Thanks!

**Comment by sp-hash** [comment]
Increase the --xintensity  to 128 . On the 2miners pool you can use --xintensity 1024

**Comment by Dysgenesis** [comment]
Thanks! Seems better than before. It's been like 1 and half an hour and hashrates hit 49~. I was getting 495 in total but now it's 493. I'll update the post tomorrow after checking it again. Attaching some SS below.
![Screenshot_20220117-212247_Hive OS](https://user-images.githubusercontent.com/97901622/149822019-82cf72ba-b541-434c-bb83-ddb80bd13c0a.jpg)
![Screenshot_20220113-162226_Hive OS](https://user-images.githubusercontent.com/97901622/149822092-5f298bfa-7d7c-47fa-a240-d8ea20ac4b27.jpg)
