### ISSUE TITLE
[BUG] share submit information compute error

### ISSUE THREAD

**Issue by boucz** [sp-hash/TeamBlackMiner#23]
Hi

I'm using TeamBlackMiner_1_04_Ubuntu_18_04_Cuda_11_4 in hiveOS.

![image](https://user-images.githubusercontent.com/12842861/133619819-80966915-0758-4d29-9d3a-892bd479ebc0.png)

The "submit every xxxx seconds" is false.

Thanks for you're work !

**Comment by sp-hash** [comment]
fixed in v1.05
