### ISSUE TITLE
Missing h-manifest

### ISSUE THREAD

**Issue by Dysgenesis** [sp-hash/TeamBlackMiner#230]
Hey again.
I've tried v1.40 for all night long yet it has never hit the expected hashrate so I wanted to rollback to v1.27 which was the best working option for me (RX 6700XT rig). I get this error when I try to custom install v 1.27:
TeamBlackMiner_1_27_Ubuntu_18_04_Cuda_11_5
https://github.com/sp-hash/TeamBlackMiner/releases/download/v1.27/TeamBlackMiner_1_27_Ubuntu_18_04_Cuda_11_5.tar.gz
Already installed
No TeamBlackMiner_1_27_Ubuntu_18_04_Cuda_11_5/h-manifest.conf
Any help would be great!

**Comment by Dysgenesis** [comment]
V1.27 is no longer supported by HiveOs that's why I have to sideload it by custom miner tab. Attaching a SS. Thanks!

![Untitled](https://user-images.githubusercontent.com/97901622/149914437-5812184f-ad00-4ada-97d7-71e369a7c997.png)

**Comment by sp-hash** [comment]
Perhaps 1024 is too high. try --xintensity 595. I will upload 1.42 beta soon with a possible fix for gpu timeout on high intensity

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/releases/download/v1.42/TeamBlackMiner_1_42_Ubuntu_18_04_Cuda_11_5.tar.xz

**Comment by Dysgenesis** [comment]
Hey thanks! Seems like hiveos doesn't support tar.xz , guess it should be tar.gz otherwise I can not sideload that.

**Comment by sp-hash** [comment]
I renamed the file. perhaps it will work

**Comment by hintro32** [comment]
> Hey thanks! Seems like hiveos doesn't support tar.xz , guess it should be tar.gz otherwise I can not sideload that.

No, hiveos definitey supports tar.xz, you can decompress it by using ```tar xf "the file"``` .
