### ISSUE TITLE
All AMD GPU Rig not showing Polaris cards

### ISSUE THREAD

**Issue by JonC69** [sp-hash/TeamBlackMiner#231]
I've attempted to use TBM in Hive OS since version 1.17 all the way through to current version on my mixed AMD card rig.

The newer 5500xt's , 6700xt's all start mining and have hash rate, the 580 RX cards do not.
its like the miner ignores them completely.

Teamredminer is in use fine with same clocks and settings currently, and TBM works on all my Nvidia rigs.

any assistance or am I correct and the issue is TBM not liking the Polaris cards

**Comment by sp-hash** [comment]
This is usually a driver problem. When you upgrade the driver you are asked if you want polaris support or not.

Did you try

TBMiner --list-devices

is the card visible?

**Comment by sp-hash** [comment]
This issue has been fixed in v1.51
