### ISSUE TITLE
[Hiveos] No GPU devices available on platform 1 (Advanced Micro Devices, Inc.)

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#233]
![image](https://user-images.githubusercontent.com/11719145/150653074-efedddd9-b1a7-4ea2-bf14-c80c83f2347a.png)

Why do I have this message?

**Comment by hintro32** [comment]
It tries to detect AMD cards by default but you don't have one. You can put -G in Extra config arguments to avoid seeing this.

**Comment by sp-hash** [comment]
1.43 has been released in hiveos

**Comment by MrNuTruT** [comment]
same on 1.43

**Comment by sp-hash** [comment]
should be fixed.. tnx

**Comment by binaryf** [comment]
Ofcourse he means THX! :) Sorry rune was overworked.

**Comment by sp-hash** [comment]
fixed in 1.47
