### ISSUE TITLE
[Hiveos] Dag verification failed 

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#234]
Hello 

I created a new rig with 4 3060 ti that I already had and that worked great with team black miner but since I changed I always have "Dag verifcation failed" It work well on T-REX.

I lowered the OC of the card but nothing.

any solution for this?

![image](https://user-images.githubusercontent.com/11719145/150692528-2a745c59-33fd-4ed3-8199-d52d99285e22.png)

![image](https://user-images.githubusercontent.com/11719145/150692600-83f55bd6-779d-47a2-85cd-d1ae59fed366.png)

**Comment by sp-hash** [comment]
try v1.44. You might also need to lower the xintensity
