### ISSUE TITLE
API....port in use during miner reload

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [sp-hash/TeamBlackMiner#237]
As I wrote today...there is a some issue with free port 4068 for API after miner stop.

I did some debug and during start new miner process (after prev stopping) I see that in tru port 4068 is not used...(no listening process at all on this port after miner stop), but until there is a some TIME_WAIT processes (by API client?) related to this port - the new running miner proces TBMiner can use this port as server.

After about 10-20 second the last TIME_WAIT process is disapearing and just 1 second after that new API server is established and errors in console stops writing about busy port)

```
miner@simplemining:~$ netstat -tanp | grep 4068
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:4068          127.0.0.1:49208         TIME_WAIT   -
```
...this is blocking reusing port 4068 by the miner and when it disapears, then....
...its start working ok as below:

```
miner@simplemining:~$ netstat -tanp | grep 4068
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:4068          0.0.0.0:*               LISTEN      18295/TBMiner

```
With other miners we dont have such issues during miner reload/change miner versions.

Best regards.

**Comment by sp-hash** [comment]
I think this was a problem in the bugged  v1.44. 1.45 should be fine

**Comment by tymoteuszrogalewski** [comment]
1.45 still problem exists.

`00:00:00 [2022-01-26 10:13:26.195] Cannot initialize API server. Port in use. Retrying in 6 secs
`...until the last TIME_WAIT connection disapear from system.

```
root@simplemining:/home/miner# netstat -tanp | grep 4068
tcp        0      0 127.0.0.1:4068          127.0.0.1:47082         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47118         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47070         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47058         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47042         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47086         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47114         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47038         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47090         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47062         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47054         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47094         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47046         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47050         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47122         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47034         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47106         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47074         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47102         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47110         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47078         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47066         TIME_WAIT   -
tcp        0      0 127.0.0.1:4068          127.0.0.1:47098         TIME_WAIT   -
```

I do API request like this:
curl -s http://127.0.0.1:4068/summary
...maybe connection are not finished properly by API server? or method with checking if port is available for bind?

I just checked other miners like bminer, gminer and there is no such problem. API also uses similat "curl" connection. And during miner reload their API is binded just after miner start to API port even if there was old TIME_WAIT old api clients entries.

**Comment by sp-hash** [comment]
Found the problem. We use 17 seconds to exit the miner on linux, and 4 seconds on windows. Changed it back to 4, in 1.46
