### ISSUE TITLE
no stats for amd rx 6600 on windows 

### ISSUE THREAD

**Issue by drewsolace** [sp-hash/TeamBlackMiner#238]
![sphash](https://user-images.githubusercontent.com/98333751/150809475-d48169ce-96fd-4f38-80cc-155006a72bfc.png)

Just switched over to TBM on my work station to test for my other rigs. Not showing any stats for my GPU. Thanks

**Comment by sp-hash** [comment]
Stats on windows are only working for older cards at the moment.

**Comment by drewsolace** [comment]
I was unaware, sorry to bother. Thanks!

**Comment by binaryf** [comment]
Yep.

**Comment by sp-hash** [comment]
fixed in v1.52
