### ISSUE TITLE
RTX 3090 Memory Temp Reading 0

### ISSUE THREAD

**Issue by dustinkasel** [sp-hash/TeamBlackMiner#239]
While the core temp is reading correctly, memory temp comes back as 0. It is read properly in other tools (t-rex miner, gpuz, etc)

**Comment by sp-hash** [comment]
Waiting for Nvidia to add it into the nvidia-smi

https://forums.developer.nvidia.com/t/request-gpu-memory-junction-temperature-via-nvidia-smi-or-nvml-api/168346/287?page=3
