### ISSUE TITLE
Miner fails at 32-34 minutes mining Ether @ 2miners.com

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#24]
Miner seems to continually crash at around the 32-34 minute mark on Eth.2Miners.com with error (note spelling error on received):

 Have not recieved data from pool for 3 min
 Pool connection disconnected or timed out

Intensity @ 128 = 32 mins
Intensity @ 256 = 34 mins
Intensity @ 512 = 33 mins (see output below)

    32m [2021-09-16 11:35:15.504] Job 43b69
    32m [2021-09-16 11:35:22.346] Job 43b6a
    32m [2021-09-16 11:35:25.082] Job 43b6c
    32m [2021-09-16 11:35:26.451] Job 43b6d
    32m [2021-09-16 11:35:34.660] Job 43b6e
    32m [2021-09-16 11:35:40.133] Job 43b70
    32m [2021-09-16 11:35:41.502] Job 43b72
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184] eth.2miners.com (ethash)    PING: 119ms    DIFFICULTY: 2.03     EPOCH: 441
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    33m [2021-09-16 11:35:43.184] GPU0  3090    49/0    95      1524    11160   335     0.34    inf
    33m [2021-09-16 11:35:43.184]                                               335     0.34    inf
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    33m [2021-09-16 11:35:43.184] GPU0  3090    Cuda    398.62 kH/W     133.54 MH/s     133.52 MH/s     36/0/3 (100.00)
    33m [2021-09-16 11:35:43.184]                       398.62 kH/s     133.54 MH/s     133.52 MH/s     36/0/3 (100.00)
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:43.184]
    33m [2021-09-16 11:35:45.610] Job 43b73
    33m [2021-09-16 11:35:46.978] Job 43b74
    33m [2021-09-16 11:35:52.450] Job 43b75
    33m [2021-09-16 11:35:59.296] GPU0 Solution found in 7.22s (Submit every 54.83 seconds)
    33m [2021-09-16 11:35:59.296] Job 43b76
    33m [2021-09-16 11:35:59.421] Accepted (37/37/4) Reply: 125ms
    33m [2021-09-16 11:36:06.138] Job 43b77
    33m [2021-09-16 11:36:07.507] Job 43b79

*******
    33m [2021-09-16 11:36:12.007] Have not recieved data from pool for 3 min
    33m [2021-09-16 11:36:12.022] Pool connection disconnected or timed out
*******    

    33m [2021-09-16 11:36:12.022] Starting new stratum thread
    33m [2021-09-16 11:36:12.379] Extranonce is set to 14921832940362006528
    33m [2021-09-16 11:36:14.351] Job 43b7a
    33m [2021-09-16 11:36:21.190] Job 43b7c
    33m [2021-09-16 11:36:28.030] Job 43b7d
    33m [2021-09-16 11:36:34.872] Job 43b7f
    33m [2021-09-16 11:36:41.713] Job 43b80
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141] eth.2miners.com (ethash)    PING: 119ms    DIFFICULTY: 2.03     EPOCH: 441
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    34m [2021-09-16 11:36:44.141] GPU0  3090    49/0    95      1520    11160   335     0.34    inf
    34m [2021-09-16 11:36:44.141]                                               335     0.34    inf
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    34m [2021-09-16 11:36:44.141] GPU0  3090    Cuda    398.60 kH/W     133.53 MH/s     133.52 MH/s     37/0/4 (100.00)
    34m [2021-09-16 11:36:44.141]                       398.60 kH/s     133.53 MH/s     133.52 MH/s     37/0/4 (100.00)
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:44.141]
    34m [2021-09-16 11:36:49.923] Job 43b81
    34m [2021-09-16 11:36:51.292] Job 43b83
    34m [2021-09-16 11:36:55.396] Job 43b85
    34m [2021-09-16 11:36:59.500] Job 43b86

**Comment by sp-hash** [comment]
2miners will trow you out of the pool if you have more than 5% stale shares. Change pool, or reduce the xintensity.

**Comment by sp-hash** [comment]
release v1.05 beta has been released. you can try with --xintensity -1
