### ISSUE TITLE
RX 6600 incorrect wattage

### ISSUE THREAD

**Issue by chrishilbert** [sp-hash/TeamBlackMiner#241]
I have 1 card showing ~39 watts on HiveOS and I know it is within 1 or 2 watts of that, but TBM is showing 1/2 that wattage.  GPU0 below.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/2332975/151677831-3e5e9c2f-3db6-43fc-bc1e-1ea012cea5a1.png">

**Comment by sp-hash** [comment]
Let it run for a longer period. Still low wattage?

**Comment by chrishilbert** [comment]
Yes.  It was incorrect for the entire run overnight.  I got a some rejected shares on TBM - none ever on any other miner.  So I switched off it this morning again. I bounce around between miners.

**Comment by sp-hash** [comment]
There is a known issue with rejects on the hiveon pool. Try to change the pool. see the faq for recomended pols

**Comment by chrishilbert** [comment]
I have 0 mining rejections on Gminer, TeamRedMiner, etc going to HiveOn.  I would like to continue to use it.

**Comment by sp-hash** [comment]
There is a bug in the ethproxy implementation. We have tried to fix it many times, but it keeps comming back. Its on the todo list

**Comment by chrishilbert** [comment]
Cool. That should be priority over this stupid metrics/reporting bug!  TBM has some social media posts out there about the rejected shares being an issue.

**Comment by chrishilbert** [comment]
Got it running again.  Still off on watts:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/2332975/151721008-2f874b46-abd4-4675-9709-31bd359338e2.png">

**Comment by binaryf** [comment]
Sorry a was late on this tread. I Have only seen 0 rejects and 100 % confirmed hashes.

**Comment by sp-hash** [comment]
Rejected share bug fixed in 1.49

**Comment by chrishilbert** [comment]
Now I wait for HiveOS to over the update.

**Comment by sp-hash** [comment]
incorrect watt fixed in v1.52

**Comment by chrishilbert** [comment]
Still having it on 1.52

**Comment by chrishilbert** [comment]
Also showing 0 temps I assume for memory junction.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/2332975/152683682-145f7e54-c527-4bc2-b314-81047a841c58.png">
