### ISSUE TITLE
3070 loses power and fan speed

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#243]
I have mixed rig and have some 3070s and some mix of others, 2 of my 3070s, after max of 30 mins work, lose their power and fan speed and they just show the hashrate, I'm not near my rig and can't know are they turned off really or not.
I'm on hiveos and doesn't have this issue with other miners, 
Also it has many rejected shares on hiveon pool (duplicate share)

**Comment by sp-hash** [comment]
rejected share and timeout bug fixed in 1.49

**Comment by sepehrland** [comment]
I'm not talking about timeout, 2 of my cards in hiveos lose the power and fan speed, cards are ok with other miners

**Comment by sp-hash** [comment]
Do you see power and speed in the console of the miner?

**Comment by sp-hash** [comment]
3070 LHR card? The card might have crashed. The solutuion is to reduce the memclock slightly. You need to check in the mining window/logs of the miner.
