### ISSUE TITLE
Dear Developers, I need you to support this ETH pool!

### ISSUE THREAD

**Issue by Heiligergeorg** [sp-hash/TeamBlackMiner#244]
[
<img width="1070" alt="1643806707(1)" src="https://user-images.githubusercontent.com/98889644/152158435-d4d913fc-b709-4580-8e88-1787263a3577.png">
](url)

https://c3pool.com/
info about ETH is in the lab area
it's a great pool, me and my friends really like it. I need your helps!

**Comment by Heiligergeorg** [comment]
Skipping miner log rotation due to execution time < 30sec
                                                                                                                                                                                                                     
00:00:00 [2022-02-02 15:01:40.226]                                                                                 
00:00:00 [2022-02-02 15:01:40.226] Sorry the provided pool is not supported
00:00:00 [2022-02-02 15:01:40.226] If you think this pool should be, then ask us to configure it
00:00:00 [2022-02-02 15:01:40.226] Shutting down threads
00:00:00 [2022-02-02 15:01:44.226] Exiting
                                                                                                                                                                                                                     
teamblackminer exited (exitcode=0), waiting to cooldown a bit

**Comment by Heiligergeorg** [comment]
@sp-hash @binaryf

**Comment by Heiligergeorg** [comment]
@sp-hash @binaryf please!

**Comment by sp-hash** [comment]
It will be added in the next release

**Comment by sp-hash** [comment]
added in v1.50
