### ISSUE TITLE
gigabyte 3060ti v2 not detected.

### ISSUE THREAD

**Issue by samwandosamtin** [sp-hash/TeamBlackMiner#246]
well, i can mine using different miner with that gpu. 
![image](https://user-images.githubusercontent.com/62579452/152233394-d09409c1-c9e2-4c57-bed3-b508b4af41ab.png)

![image](https://user-images.githubusercontent.com/62579452/152233447-bcbba6c1-bbcb-4adc-adc3-79704bb02840.png)

**Comment by sp-hash** [comment]
you need to install the latest driver

**Comment by samwandosamtin** [comment]
> I think you need to install the latest driver

Using 472.12 tho. not that old. Gonna try
![image](https://user-images.githubusercontent.com/62579452/152234180-6fe6ceff-0629-45be-99bf-9c7cb37482e9.png)

**Comment by samwandosamtin** [comment]
> --cuda-devices [1]

didn't work

**Comment by sp-hash** [comment]
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

you need driver  472.50 or newer. cuda 11.4.3
