### ISSUE TITLE
Dag verification failed

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#247]
I'm on hiveos and hive pool and 1.49 cuda 115
After a while(1 hour approximately), all of my cards(3070 and 3060ti(not lock)) just show the mh in dashboard, zero fan and in the console I have this error: dag verification failed 
and no hashrate in the pool and because of the hashrates show in the dashboard the watch dog option in hiveos not work and not reboot the miner
Same overclock works without any issues on trex but lower hashrate

**Comment by sp-hash** [comment]
You need to lower the memclock on one of the gpus in the rig. If the dag verification fails, 1.49 will copy a working dag from one of the other gpus.
