### ISSUE TITLE
CPU9 gets only rejected shares on 1.49

### ISSUE THREAD

**Issue by konwin** [sp-hash/TeamBlackMiner#248]
I have a 10x 3060Ti nLHR rig running ubuntu 21.04 with cuda 11.5 and nvidia drivers 495.46.
With TBM 1.47 it runs flawlessly on ethermine. With 1.49 GPU9 gets only rejected shares!
Also the API shows still "1.48" for "version" when running 1.49!

**Comment by sp-hash** [comment]
The version number was not increased in the linux version, but the code changes should be in place. Try to reduce the clocks on the last gpu. 1.47 has a gpu timeout bug for gpu's that fail, that can cause lower hashrates.

**Comment by konwin** [comment]
But the GPU9 is running since nearly one year without a problem with these clocks. And with 1.49 100% rejects! I switched back to 1.47 and everything is fine again!

**Comment by sp-hash** [comment]
But does it work if you reduce the mem clock on gpu9, or is this another error?

**Comment by sp-hash** [comment]
Found a possible fix. v1.50

**Comment by konwin** [comment]
Issue is still active. I tested with GPU9 running stock frequencies and 1.50.
API:
`{
  "name": "TBMiner",
  "version": "1.50",
  "api_version": "1.3",
  "num_gpu_threads": 10,
  "total_hashrate": 596898150,
  "total_accepted": 32,
  "total_rejected": 3,
  "total_stale": 0,
  "uptime_minutes": 5
}{
  "url": "eu1.ethermine.org",
  "port": 4444,
  "worker": "tbm",
  "algo": "ethash",
  "job": "xxxxxx",
  "epoch": 471,
  "block": 0,
  "diff": 1,
  "ping": 18.685714285714287
}{
  "0": {
    "gpu": 0,
    "pcie_id": 1,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 62,
    "mem_temp": 0,
    "fan": 64,
    "core_clock": 855,
    "mem_clock": 7875,
    "watt": 130,
    "hashrate": 59807324,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "1": {
    "gpu": 1,
    "pcie_id": 5,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 53,
    "mem_temp": 0,
    "fan": 39,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 113,
    "hashrate": 60385868,
    "dag": true,
    "accepted": 1,
    "rejected": 0,
    "stale": 0
  },
  "2": {
    "gpu": 2,
    "pcie_id": 6,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 52,
    "mem_temp": 0,
    "fan": 36,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 110,
    "hashrate": 60393772,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "3": {
    "gpu": 3,
    "pcie_id": 7,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 50,
    "mem_temp": 0,
    "fan": 30,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 116,
    "hashrate": 60436648,
    "dag": true,
    "accepted": 0,
    "rejected": 0,
    "stale": 0
  },
  "4": {
    "gpu": 4,
    "pcie_id": 8,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 48,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 124,
    "hashrate": 60850597,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "5": {
    "gpu": 5,
    "pcie_id": 9,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 55,
    "mem_temp": 0,
    "fan": 45,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 121,
    "hashrate": 60786294,
    "dag": true,
    "accepted": 4,
    "rejected": 0,
    "stale": 0
  },
  "6": {
    "gpu": 6,
    "pcie_id": 12,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 7850,
    "watt": 122,
    "hashrate": 59986191,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "7": {
    "gpu": 7,
    "pcie_id": 13,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 55,
    "mem_temp": 0,
    "fan": 42,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 115,
    "hashrate": 60382348,
    "dag": true,
    "accepted": 2,
    "rejected": 0,
    "stale": 0
  },
  "8": {
    "gpu": 8,
    "pcie_id": 14,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 54,
    "mem_temp": 0,
    "fan": 42,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 115,
    "hashrate": 60321792,
    "dag": true,
    "accepted": 4,
    "rejected": 0,
    "stale": 0
  },
  "9": {
    "gpu": 9,
    "pcie_id": 15,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 70,
    "mem_temp": 0,
    "fan": 56,
    "core_clock": 1965,
    "mem_clock": 6800,
    "watt": 186,
    "hashrate": 53466161,
    "dag": true,
    "accepted": 0,
    "rejected": 3,
    "stale": 0
  }
}`
LOG:
`00:00:05 [2022-02-03 23:27:01.764] GPU9 Solution found in 1.37s (Submit every 11.72 seconds)
00:00:05 [2022-02-03 23:27:01.782] Rejected (28/31) Reply: 18ms
00:00:05 [2022-02-03 23:27:01.782] mining.submit: Pool reponded with error`

**Comment by sp-hash** [comment]
Do you have the same problem at another pool? F.ex on hiveon.com?

**Comment by sp-hash** [comment]
I did a small change in 1_50 fixed that might help. cuda 11_4 build. Can you test please?

https://github.com/sp-hash/TeamBlackMiner/releases/download/v1.50/TeamBlackMiner_1_50_Ubuntu_18_04_Cuda_11_4_fixed.tar.xz

**Comment by konwin** [comment]
Looks like an ethermine problem.
With GPU9 running stock frequencies on miningpoolhub:
`
{
  "name": "TBMiner",
  "version": "1.51",
  "api_version": "1.3",
  "num_gpu_threads": 10,
  "total_hashrate": 596202200,
  "total_accepted": 73,
  "total_rejected": 0,
  "total_stale": 0,
  "uptime_minutes": 32
}{
  "url": "europe.ethash-hub.miningpoolhub.com",
  "port": 20535,
  "worker": "tbm",
  "algo": "ethash",
  "job": "8128",
  "epoch": 471,
  "block": 0,
  "diff": 3.0000000027939677,
  "ping": 23.684931506849313
}{
  "0": {
    "gpu": 0,
    "pcie_id": 1,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 67,
    "mem_temp": 0,
    "fan": 74,
    "core_clock": 855,
    "mem_clock": 7875,
    "watt": 131,
    "hashrate": 59762149,
    "dag": true,
    "accepted": 13,
    "rejected": 0,
    "stale": 0
  },
  "1": {
    "gpu": 1,
    "pcie_id": 5,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 48,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 111,
    "hashrate": 60157946,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "2": {
    "gpu": 2,
    "pcie_id": 6,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 55,
    "mem_temp": 0,
    "fan": 45,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 108,
    "hashrate": 60322511,
    "dag": true,
    "accepted": 8,
    "rejected": 0,
    "stale": 0
  },
  "3": {
    "gpu": 3,
    "pcie_id": 7,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 53,
    "mem_temp": 0,
    "fan": 39,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 114,
    "hashrate": 60262886,
    "dag": true,
    "accepted": 9,
    "rejected": 0,
    "stale": 0
  },
  "4": {
    "gpu": 4,
    "pcie_id": 8,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 58,
    "mem_temp": 0,
    "fan": 54,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 124,
    "hashrate": 60710759,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "5": {
    "gpu": 5,
    "pcie_id": 9,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 121,
    "hashrate": 60672586,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "6": {
    "gpu": 6,
    "pcie_id": 12,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 7850,
    "watt": 122,
    "hashrate": 59980118,
    "dag": true,
    "accepted": 9,
    "rejected": 0,
    "stale": 0
  },
  "7": {
    "gpu": 7,
    "pcie_id": 13,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 57,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 113,
    "hashrate": 60297873,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "8": {
    "gpu": 8,
    "pcie_id": 14,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 57,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 115,
    "hashrate": 60365353,
    "dag": true,
    "accepted": 7,
    "rejected": 0,
    "stale": 0
  },
  "9": {
    "gpu": 9,
    "pcie_id": 15,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 73,
    "mem_temp": 0,
    "fan": 64,
    "core_clock": 1950,
    "mem_clock": 6800,
    "watt": 192,
    "hashrate": 56284129,
    "dag": true,
    "accepted": 4,
    "rejected": 0,
    "stale": 0
  }
}`
on ethermine:
`
{
  "name": "TBMiner",
  "version": "1.51",
  "api_version": "1.3",
  "num_gpu_threads": 10,
  "total_hashrate": 597020318,
  "total_accepted": 106,
  "total_rejected": 13,
  "total_stale": 0,
  "uptime_minutes": 14
}{
  "url": "eu1.ethermine.org",
  "port": 4444,
  "worker": "tbm",
  "algo": "ethash",
  "job": "357e95",
  "epoch": 471,
  "block": 0,
  "diff": 1,
  "ping": 58.588235294117645
}{
  "0": {
    "gpu": 0,
    "pcie_id": 1,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 66,
    "mem_temp": 0,
    "fan": 74,
    "core_clock": 855,
    "mem_clock": 7875,
    "watt": 131,
    "hashrate": 60435919,
    "dag": true,
    "accepted": 10,
    "rejected": 0,
    "stale": 0
  },
  "1": {
    "gpu": 1,
    "pcie_id": 5,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 55,
    "mem_temp": 0,
    "fan": 45,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 111,
    "hashrate": 60229915,
    "dag": true,
    "accepted": 18,
    "rejected": 0,
    "stale": 0
  },
  "2": {
    "gpu": 2,
    "pcie_id": 6,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 55,
    "mem_temp": 0,
    "fan": 45,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 109,
    "hashrate": 60292938,
    "dag": true,
    "accepted": 10,
    "rejected": 0,
    "stale": 0
  },
  "3": {
    "gpu": 3,
    "pcie_id": 7,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 53,
    "mem_temp": 0,
    "fan": 39,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 114,
    "hashrate": 60373900,
    "dag": true,
    "accepted": 15,
    "rejected": 0,
    "stale": 0
  },
  "4": {
    "gpu": 4,
    "pcie_id": 8,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 58,
    "mem_temp": 0,
    "fan": 54,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 124,
    "hashrate": 60838631,
    "dag": true,
    "accepted": 15,
    "rejected": 0,
    "stale": 0
  },
  "5": {
    "gpu": 5,
    "pcie_id": 9,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 57,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 121,
    "hashrate": 60851529,
    "dag": true,
    "accepted": 14,
    "rejected": 0,
    "stale": 0
  },
  "6": {
    "gpu": 6,
    "pcie_id": 12,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 60,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 7850,
    "watt": 123,
    "hashrate": 59898124,
    "dag": true,
    "accepted": 10,
    "rejected": 0,
    "stale": 0
  },
  "7": {
    "gpu": 7,
    "pcie_id": 13,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 57,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 115,
    "hashrate": 60357891,
    "dag": true,
    "accepted": 8,
    "rejected": 0,
    "stale": 0
  },
  "8": {
    "gpu": 8,
    "pcie_id": 14,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 57,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 115,
    "hashrate": 60318186,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "9": {
    "gpu": 9,
    "pcie_id": 15,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 73,
    "mem_temp": 0,
    "fan": 66,
    "core_clock": 1950,
    "mem_clock": 6800,
    "watt": 192,
    "hashrate": 53442955,
    "dag": true,
    "accepted": 0,
    "rejected": 13,
    "stale": 0
  }
}`

**Comment by sp-hash** [comment]
Did you try the latest 1.50 11.4 build?

**Comment by konwin** [comment]
Yes. See json `"version": "1.51"`

**Comment by sp-hash** [comment]
Did a small change. perhaps it will work. in 1.51 final. Linux only build

**Comment by konwin** [comment]
Bug still present with GPU9 and latest TeamBlackMiner_1_51_Ubuntu_18_04_Cuda_11_5.tar.xz on ethermine:
`
{
  "name": "TBMiner",
  "version": "1.51",
  "api_version": "1.3",
  "num_gpu_threads": 10,
  "total_hashrate": 603405970,
  "total_accepted": 201,
  "total_rejected": 22,
  "total_stale": 0,
  "uptime_minutes": 27
}{
  "url": "eu1.ethermine.org",
  "port": 4444,
  "worker": "tbm",
  "algo": "ethash",
  "job": "5ad880",
  "epoch": 471,
  "block": 0,
  "diff": 1,
  "ping": 30.672645739910315
}{
  "0": {
    "gpu": 0,
    "pcie_id": 1,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 68,
    "mem_temp": 0,
    "fan": 78,
    "core_clock": 855,
    "mem_clock": 7875,
    "watt": 131,
    "hashrate": 60020292,
    "dag": true,
    "accepted": 28,
    "rejected": 0,
    "stale": 0
  },
  "1": {
    "gpu": 1,
    "pcie_id": 5,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 110,
    "hashrate": 60367399,
    "dag": true,
    "accepted": 22,
    "rejected": 0,
    "stale": 0
  },
  "2": {
    "gpu": 2,
    "pcie_id": 6,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 48,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 109,
    "hashrate": 60393396,
    "dag": true,
    "accepted": 22,
    "rejected": 0,
    "stale": 0
  },
  "3": {
    "gpu": 3,
    "pcie_id": 7,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 53,
    "mem_temp": 0,
    "fan": 39,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 113,
    "hashrate": 60345808,
    "dag": true,
    "accepted": 28,
    "rejected": 0,
    "stale": 0
  },
  "4": {
    "gpu": 4,
    "pcie_id": 8,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 57,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 124,
    "hashrate": 60752870,
    "dag": true,
    "accepted": 17,
    "rejected": 0,
    "stale": 0
  },
  "5": {
    "gpu": 5,
    "pcie_id": 9,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 60,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 122,
    "hashrate": 60767803,
    "dag": true,
    "accepted": 15,
    "rejected": 0,
    "stale": 0
  },
  "6": {
    "gpu": 6,
    "pcie_id": 12,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 61,
    "mem_temp": 0,
    "fan": 62,
    "core_clock": 855,
    "mem_clock": 7850,
    "watt": 123,
    "hashrate": 60006105,
    "dag": true,
    "accepted": 23,
    "rejected": 0,
    "stale": 0
  },
  "7": {
    "gpu": 7,
    "pcie_id": 13,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 57,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 115,
    "hashrate": 60358735,
    "dag": true,
    "accepted": 17,
    "rejected": 0,
    "stale": 0
  },
  "8": {
    "gpu": 8,
    "pcie_id": 14,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 59,
    "mem_temp": 0,
    "fan": 57,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 115,
    "hashrate": 60363991,
    "dag": true,
    "accepted": 29,
    "rejected": 0,
    "stale": 0
  },
  "9": {
    "gpu": 9,
    "pcie_id": 15,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 62,
    "mem_temp": 0,
    "fan": 64,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 110,
    "hashrate": 60451363,
    "dag": true,
    "accepted": 0,
    "rejected": 22,
    "stale": 0
  }
}
`
miningpoolhub is running fine!
`
{
  "name": "TBMiner",
  "version": "1.51",
  "api_version": "1.3",
  "num_gpu_threads": 10,
  "total_hashrate": 603446582,
  "total_accepted": 65,
  "total_rejected": 0,
  "total_stale": 0,
  "uptime_minutes": 18
}{
  "url": "europe.ethash-hub.miningpoolhub.com",
  "port": 20535,
  "worker": "tbm",
  "algo": "ethash",
  "job": "5dc1",
  "epoch": 471,
  "block": 0,
  "diff": 3.0000000027939677,
  "ping": 32.261538461538464
}{
  "0": {
    "gpu": 0,
    "pcie_id": 1,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 68,
    "mem_temp": 0,
    "fan": 76,
    "core_clock": 855,
    "mem_clock": 7875,
    "watt": 132,
    "hashrate": 59809465,
    "dag": true,
    "accepted": 7,
    "rejected": 0,
    "stale": 0
  },
  "1": {
    "gpu": 1,
    "pcie_id": 5,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 48,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 111,
    "hashrate": 60274120,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "2": {
    "gpu": 2,
    "pcie_id": 6,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 56,
    "mem_temp": 0,
    "fan": 48,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 109,
    "hashrate": 60236924,
    "dag": true,
    "accepted": 9,
    "rejected": 0,
    "stale": 0
  },
  "3": {
    "gpu": 3,
    "pcie_id": 7,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 53,
    "mem_temp": 0,
    "fan": 42,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 114,
    "hashrate": 60312311,
    "dag": true,
    "accepted": 11,
    "rejected": 0,
    "stale": 0
  },
  "4": {
    "gpu": 4,
    "pcie_id": 8,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 58,
    "mem_temp": 0,
    "fan": 54,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 123,
    "hashrate": 60844896,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "5": {
    "gpu": 5,
    "pcie_id": 9,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 60,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 121,
    "hashrate": 60851456,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "6": {
    "gpu": 6,
    "pcie_id": 12,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 60,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 7850,
    "watt": 122,
    "hashrate": 60007927,
    "dag": true,
    "accepted": 7,
    "rejected": 0,
    "stale": 0
  },
  "7": {
    "gpu": 7,
    "pcie_id": 13,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 57,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 114,
    "hashrate": 60415942,
    "dag": true,
    "accepted": 5,
    "rejected": 0,
    "stale": 0
  },
  "8": {
    "gpu": 8,
    "pcie_id": 14,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 58,
    "mem_temp": 0,
    "fan": 51,
    "core_clock": 855,
    "mem_clock": 7976,
    "watt": 116,
    "hashrate": 60285558,
    "dag": true,
    "accepted": 6,
    "rejected": 0,
    "stale": 0
  },
  "9": {
    "gpu": 9,
    "pcie_id": 15,
    "board_name": "NVIDIA GeForce RTX 3060 Ti",
    "type": "Cuda",
    "xintensity": 284,
    "gpu_temp": 60,
    "mem_temp": 0,
    "fan": 60,
    "core_clock": 855,
    "mem_clock": 8000,
    "watt": 111,
    "hashrate": 60393273,
    "dag": true,
    "accepted": 4,
    "rejected": 0,
    "stale": 0
  }
}`

**Comment by sp-hash** [comment]
fixed in v1.52

**Comment by konwin** [comment]
Fix confirmed!
