### ISSUE TITLE
Invalid/Rejected Shares

### ISSUE THREAD

**Issue by chrishilbert** [sp-hash/TeamBlackMiner#249]
Still getting some invalid/rejected shares across all my GPUs on 1.49.  Figured I'd open an issue to track it.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/2332975/152403499-db7e1bca-f1cf-4846-8934-a0056167f5fa.png">

**Comment by chrishilbert** [comment]
Caught one:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/2332975/152415368-38d9d5ae-d673-4b27-91c8-7d6629a6cc0d.png">

**Comment by sp-hash** [comment]
tnx. The opencl ethproxy loop has been changed abit in v1.50. Hopefully it will work.

**Comment by sp-hash** [comment]
v1.50 will be released today
