### ISSUE TITLE
TeamBlackMiner v1.49 Update - AMD 6700XT rejected shares

### ISSUE THREAD

**Issue by geoffwade** [sp-hash/TeamBlackMiner#251]
Have had excellent results with the recent TeamBlackMiner updates on latest HIVEOS.   The recent v1.49 update experienced a very strange event.   On mining rig1, all AMD 6700XT no issues.  On mining rig2, all AMD 6700XT I had one GPU that started experiencing 100% rejection rate on ethermine.   I rolled back to last TeamBlackMiner version and the symptom followed.  I switched over to Gminer and other misc miners and the suspect GPU has zero issues.  Any ideas would be greatly appreciated!   TeamBlackMiner for life!

**Comment by sp-hash** [comment]
try the new v1.50

**Comment by geoffwade** [comment]
Will do.  I always wait for Hive to include the miner updates, so will hold tight for now.  I'm only seeing 1.49-cuda115 right now as the latest.

**Comment by geoffwade** [comment]
Hive just pushed the update. :-). TeamBlackMiner v1.50 (fixed rejected shares on the 9th device CUDA bug; fixed ethproxy on OpenCL; added support for more pools).  Updated and all looks great on the suspect GPU.
