### ISSUE TITLE
AMD OpenCL devices

### ISSUE THREAD

**Issue by angelobpool** [sp-hash/TeamBlackMiner#253]
Hi, to explain the issue I'll describe my setting and my tests trying to understand what is happening:
Mixed RIG 13 GPU:
1 Nvidia 2080ti
8 AMD 5700/5700xt
4 AMD Rx580

HiveOS
AMD driver 20.40 (5.11.1001)
Nvidia driver 495.44 (tried with 470.86 cuda 11.4 but the issue remains the same)

The issue is that I'am not able to get all AMD working together, the nvidia one always woks fine.
With the last release, at this time 1.50, it only works with Ellsmere/Polaris:
![tbm150](https://user-images.githubusercontent.com/43997819/152508264-4a1f9cb2-08af-4438-9cd7-16ae82af194f.jpg)

If I ask to list devices:
![tbm150-list](https://user-images.githubusercontent.com/43997819/152508547-761ed1e1-b39a-495d-b85f-385711ff4b0f.jpg)

If I try an older version of Team Black Miner like the 1.40 it only works with the Navi cards and not the rx580:
![tbm140](https://user-images.githubusercontent.com/43997819/152508626-ea842fc9-9fc5-4fcd-a854-4c019f3a08be.jpg)

List result:
![tbm140-list](https://user-images.githubusercontent.com/43997819/152508777-c6935c0f-8a40-4efc-a95a-f95ab23a3ef7.jpg)

I also noticed but I do not know if it is related or not, that in mixed Nvidia/AMD rigs the miner says the Nvidia driver as OpenCL driver version, like in the previous screen "OpenCL driver version: 495.44"

In AMD only rigs it says:
![image](https://user-images.githubusercontent.com/43997819/152508988-21d83c55-c293-4393-811d-63ff9cc18802.png)

Thanks in advance, if you need any information I'll try to provide

**Comment by sp-hash** [comment]
As a workaround you can run v1.40 with the --amd-only flag, and the v1.50 with the rest. 2 instances of the miner software.

In the latest version we have flipped the gpu order in order to match the order in hiveos and other miners. We also scan the opencl gpu platforms in reverse order. I will have another look at the code. Perhaps we missed something here.

**Comment by angelobpool** [comment]
Hi, thanks for the fast feedback, I thought about doing that as a workaround, but I was hoping to use one of the latest releases with the Navi cards as they have a huge improvement. I'll think around about what I can do to optimize thing, maybe I'll move the old Polaris card elsewhare in another rig.
Thanks again

**Comment by sp-hash** [comment]
I have a fix ready in v1.51. Moved a ellesmere card onto a 7 card rig to test.
