### ISSUE TITLE
Duplicate Shares

### ISSUE THREAD

**Issue by chrishilbert** [sp-hash/TeamBlackMiner#254]
Much improved with the ethproxy fixes, but still getting a bit of duplicates on 1.50

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2332975/152605015-5a24b450-4997-442d-bd43-0f202040d282.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2332975/152604940-9303c82a-f549-4231-9e06-3d031d14607d.png">

**Comment by binaryf** [comment]
Very good.
I am actually very proud right now.

**Comment by sp-hash** [comment]
Reproduced and fixed with only 1 card in the rig.

v1.52
