### ISSUE TITLE
[HiveOs] 1.52

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#256]
Hi,

I have test the v1.52 and 1 of my 6 card AMD is not running.

And the -Y is revert to the old version

**Comment by sp-hash** [comment]
Same difference in 1.51?

**Comment by MrNuTruT** [comment]
In 1.51 all card work but the -Y is the same of 1.52

**Comment by sp-hash** [comment]
I will include  all-platform switch in the next release. So revert to 1.51 settings as default, and let the users who have problems use the new switch.

**Comment by sp-hash** [comment]
added in v1.55
