### ISSUE TITLE
alternative pool hostname for backup

### ISSUE THREAD

**Issue by konwin** [sp-hash/TeamBlackMiner#257]
I'm mining on miningpoolhub.com and europe.ethash-hub.miningpoolhub.com suddenly disappeared today in the morning. Different DNS checking pages show there is no A record for europe.ethash-hub.miningpoolhub.com any more available.
Could you implement to add a second hostname as "backup-server" in the config file? Like this my rig just stopped mining till I switched to us-east.ethash-hub.miningpoolhub.com manually but I would like to add us-east as an alternative pool hostname if the main pool hostname fails!

**Comment by sp-hash** [comment]
as a workaround you can add elements to the startup bat files;

:loop
	TBMiner --algo ethash --hostname eth.2miners.com --port 2020 --wallet %ETH_WALLET% --worker-name %computername%
	timeout 10
	TBMiner --algo ethash --hostname eth-eu1.nanopool.org --port 9999 --wallet %ETH_WALLET% --worker-name %computername%
	timeout 10
goto :loop

**Comment by Niteblade** [comment]
I'm using TBM in HiveOS, and would like to see the option to configure a roll-over pool when my primary pool goes down for whatever reason.

**Comment by sp-hash** [comment]
A rollover pool option has not yet been implemented.

**Comment by sp-hash** [comment]
A failover pool option has now been implemented

https://github.com/sp-hash/TeamBlackMiner/blob/main/FAILOVER.md
