### ISSUE TITLE
Gpu #. Cpu verification failed

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#259]
After working good for hours, I found that the miner resets and my nvidia 3070s NLHR show this error: gpu #. Cpu verification failed, Share not sent to the pool
I'm on hiveos and version 1.54 cuda 115

**Comment by sp-hash** [comment]
I am working on a fix to reset the clocks when dag is regenerated. in 1.55. Until then  you might need to reduce the clocks abit

**Comment by sp-hash** [comment]
--dagintensity 1 can help. Also if one of your cards in the rig is clocked lower than the others, the working dag will be copied over to the devices that fail
