### ISSUE TITLE
Ezil SSL Port

### ISSUE THREAD

**Issue by Vetrov77** [sp-hash/TeamBlackMiner#260]
Good day! How do I write the port ssl://eu.ezil.me:25443 to bat file? Old entry TBMiner --algo ethash --hostname eu.ezil.me --port 5555.
I tried but TBMiner doesn't work.

Thanks!

**Comment by sp-hash** [comment]
SSL mining had issues and has been disabled.

**Comment by sp-hash** [comment]
--hostname eu.ezil.me --port 5555

**Comment by Vetrov77** [comment]
Thank you for your reply!

Good luck and progress!

**Comment by sp-hash** [comment]
Mining over ssl implemented in v1.63.
