### ISSUE TITLE
Not stable hashrate in amd

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#261]
I have 2 amd asus 5600xt cards, the hashrate of them are not stable and goes up and down sometimes for about 0.5 mh and very rarely times goes down about 5~10 mh for some seconds in one of this cards. I don't have this issue with other miners, look at the dots on the hashrate line.

![20220209_205124](https://user-images.githubusercontent.com/52125793/153255106-19fb44d2-40f3-4dee-9469-e10da6f2f9a9.jpg)
![20220209_205035](https://user-images.githubusercontent.com/52125793/153255263-9390d4dc-fe15-4585-9b44-da50813d66c9.jpg)

**Comment by sp-hash** [comment]
You need to check the logfiles in the miner window. Perhaps you have alot of rejected  shares. The pool hashrate is too low, so something is wrong with your setup. Which version of TBM are you running?

**Comment by sepehrland** [comment]
As you can see I have 2 reject shares and both of them are for one of my amd 5600xt cards, and my version is 1.54 cuda 115
The pool hashrate is not always under 400, it is between 350 to 500

**Comment by sp-hash** [comment]
Are they running on the default intensity? Try to reduce the memclock a little bit perhaps the memory temp is too high and the card trottle.  You can also try --xintensity -1 , which will try to find the optimal intensity for you cards. Works good on Amd cards.

**Comment by sepehrland** [comment]
> 

Yes they are running default intensity and my temps are about 68
Let me check the -1 intensity, I will update the changes here

**Comment by sepehrland** [comment]
> Are they running on the default intensity? Try to reduce the memclock a little bit perhaps the memory temp is too high and the card trottle. You can also try --xintensity -1 , which will try to find the optimal intensity for you cards. Works good on Amd cards.On high intensities TBM might need a few watt each per card, so make sure your PSU can handle the extra power.

the default xintensity  for AMDs is not -1?

**Comment by sp-hash** [comment]
It used to be in the older versions, but not in v1.54. dynamic intensity will give variation in the hashrate because the workload to the gpu is going up and down based on the hashrate.
