### ISSUE TITLE
--lock_mclock not working at all in Windows!

### ISSUE THREAD

**Issue by Andrix82** [sp-hash/TeamBlackMiner#262]
this has simply NO effect at all on different systems.
Smaller/Higher absolute values, offset values dont change anything, also started with admin rights. Core clock setting is woring!
Both with older versions with the min max and the new single value in 1.55
Need to change with MSI afterburner but thats the known problem with DAG creation

**Comment by sp-hash** [comment]
It's working but only on the nvidia-smi limits.

**Comment by sp-hash** [comment]
TBM can copy a working dag from another gpu, so a fix on the dag verifixation would be toadd an older card in the rig, and let this card create the dag buffer. Then the 3070/3060ti's can be clocked even higher than before.

**Comment by sp-hash** [comment]
![3080ti-3070](https://user-images.githubusercontent.com/9572668/153862709-13e36dca-87a0-4f3a-8ad8-935fba6b2fa6.png)
