### ISSUE TITLE
WHY the hell are the clocks changed BEFORE the DAG Generation/Verification and not afterwards ?

### ISSUE THREAD

**Issue by Andrix82** [sp-hash/TeamBlackMiner#263]
Thats the normal and logical order in all other miners and IF the lock_mclock would work solve all the issues with DAG Generation....

**Comment by sp-hash** [comment]
lock_mclock cannot currently set the hight clocks required by miningsoftare. This is a limitation in the nvidia-smi tool that we use.

**Comment by sp-hash** [comment]
![3080ti-3070](https://user-images.githubusercontent.com/9572668/153862575-7d88b8e3-495c-4294-b393-5d434a1b42b6.png)
