### ISSUE TITLE
teamblackminer什么时候添加服务器转发功能

### ISSUE THREAD

**Issue by tzl19930701** [sp-hash/TeamBlackMiner#264]
teamblackminer 有没有计划将服务器转发功能加入

**Comment by tzl19930701** [comment]
不懂我说的什么意思吗？

**Comment by sp-hash** [comment]
Yes. We plan to fix the SSL connection first.

**Comment by tzl19930701** [comment]
大概什么时候能用服务器转发功能

**Comment by tzl19930701** [comment]
？

**Comment by oiG8Uchi** [comment]
I think the required parameters should be like:
--pool_mode 2miners -H 10.0.0.1 -P 2020

**Comment by sp-hash** [comment]
Mining over ssl implemented in v1.63.
