### ISSUE TITLE
exit if dag verification fails

### ISSUE THREAD

**Issue by konwin** [sp-hash/TeamBlackMiner#265]
could you add an option to exit when dag verification fails x-times?

**Comment by sp-hash** [comment]
v1.58 will exit the program if a gpu return too many rejected shares.

**Comment by konwin** [comment]
Yes, but it still doesnt exit when dag verification fails :(
Ran over 4 hours without mining ...
![anydesk_20220309-194815-545](https://user-images.githubusercontent.com/44242369/157545313-ac3acb4a-5847-430e-b137-91899738d50a.png)

**Comment by sp-hash** [comment]
fixed in v1.59
