### ISSUE TITLE
AMD 6800/XT and 6900XT Cards stop mining but continue hashing

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#266]
Cards will stop accepting jobs but continue to provide a Hashrate figure for random amounts of time before beginning to accept jobs again or crashing.

> 00:01:02 [2022-02-18 08:21:19.051] GPU0 Solution found in 7.97s (Submit every 129.83 seconds)
00:01:02 [2022-02-18 08:21:19.051] Job 6d321
00:01:02 [2022-02-18 08:21:19.098] Accepted (29/29/0) Reply: 47ms
00:01:02 [2022-02-18 08:21:21.723] Job 6d322
00:01:02 [2022-02-18 08:21:29.739] Job 6d323
00:01:02 [2022-02-18 08:21:32.411] Job 6d325
00:01:03 [2022-02-18 08:21:34.009] 
00:01:03 [2022-02-18 08:21:34.009] 
00:01:03 [2022-02-18 08:21:34.009] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:03 [2022-02-18 08:21:34.009]                                                                                 
00:01:03 [2022-02-18 08:21:34.009] 
00:01:03 [2022-02-18 08:21:34.009] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:03 [2022-02-18 08:21:34.009] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:03 [2022-02-18 08:21:34.009]                                                                          0      
00:01:03 [2022-02-18 08:21:34.009] 
00:01:03 [2022-02-18 08:21:34.009] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:03 [2022-02-18 08:21:34.009] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:03 [2022-02-18 08:21:34.009]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:03 [2022-02-18 08:21:34.009]                                                                                 
00:01:03 [2022-02-18 08:21:34.009] SHARES PER MINUTE: 0.46				POOL HASHRATE: 66.95 MH/s
00:01:03 [2022-02-18 08:21:34.009] 
00:01:03 [2022-02-18 08:21:37.756] Job 6d327
00:01:03 [2022-02-18 08:21:45.772] Job 6d32a
00:01:03 [2022-02-18 08:21:53.788] Job 6d32b
00:01:03 [2022-02-18 08:21:59.131] Job 6d32c
00:01:03 [2022-02-18 08:22:00.467] Job 6d32f
00:01:03 [2022-02-18 08:22:07.149] Job 6d330
00:01:03 [2022-02-18 08:22:08.485] Job 6d331
00:01:03 [2022-02-18 08:22:15.164] Job 6d333
00:01:03 [2022-02-18 08:22:17.837] Job 6d336
00:01:03 [2022-02-18 08:22:19.173] Job 6d337
00:01:03 [2022-02-18 08:22:25.852] Job 6d338
00:01:03 [2022-02-18 08:22:29.859] Job 6d33a
00:01:04 [2022-02-18 08:22:34.011] 
00:01:04 [2022-02-18 08:22:34.011] 
00:01:04 [2022-02-18 08:22:34.011] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:04 [2022-02-18 08:22:34.011]                                                                                 
00:01:04 [2022-02-18 08:22:34.011] 
00:01:04 [2022-02-18 08:22:34.011] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:04 [2022-02-18 08:22:34.011] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:04 [2022-02-18 08:22:34.011]                                                                          0      
00:01:04 [2022-02-18 08:22:34.011] 
00:01:04 [2022-02-18 08:22:34.011] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:04 [2022-02-18 08:22:34.011] GPU0    6900XT   0.00 H/W      66.72 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:04 [2022-02-18 08:22:34.011]                  0.00 H/W      66.72 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:04 [2022-02-18 08:22:34.011]                                                                                 
00:01:04 [2022-02-18 08:22:34.011] SHARES PER MINUTE: 0.45				POOL HASHRATE: 65.90 MH/s
00:01:04 [2022-02-18 08:22:34.011] 
00:01:04 [2022-02-18 08:22:36.538] Job 6d33b
00:01:04 [2022-02-18 08:22:44.554] Job 6d33c
00:01:04 [2022-02-18 08:22:45.890] Job 6d33e
00:01:04 [2022-02-18 08:22:47.226] Job 6d33f
00:01:04 [2022-02-18 08:22:49.898] Job 6d341
00:01:04 [2022-02-18 08:22:56.579] Job 6d342
00:01:04 [2022-02-18 08:23:03.260] Job 6d343
00:01:04 [2022-02-18 08:23:04.595] Job 6d345
00:01:04 [2022-02-18 08:23:11.276] Job 6d346
00:01:05 [2022-02-18 08:23:34.037] 
00:01:05 [2022-02-18 08:23:34.037] 
00:01:05 [2022-02-18 08:23:34.037] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:05 [2022-02-18 08:23:34.037]                                                                                 
00:01:05 [2022-02-18 08:23:34.037] 
00:01:05 [2022-02-18 08:23:34.037] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:05 [2022-02-18 08:23:34.037] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:05 [2022-02-18 08:23:34.037]                                                                          0      
00:01:05 [2022-02-18 08:23:34.037] 
00:01:05 [2022-02-18 08:23:34.037] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:05 [2022-02-18 08:23:34.037] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:05 [2022-02-18 08:23:34.037]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:05 [2022-02-18 08:23:34.037]                                                                                 
00:01:05 [2022-02-18 08:23:34.037] SHARES PER MINUTE: 0.45				POOL HASHRATE: 64.89 MH/s
00:01:05 [2022-02-18 08:23:34.037] 
00:01:06 [2022-02-18 08:24:34.028] 
00:01:06 [2022-02-18 08:24:34.028] 
00:01:06 [2022-02-18 08:24:34.028] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:06 [2022-02-18 08:24:34.028]                                                                                 
00:01:06 [2022-02-18 08:24:34.028] 
00:01:06 [2022-02-18 08:24:34.028] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:06 [2022-02-18 08:24:34.029] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:06 [2022-02-18 08:24:34.029]                                                                          0      
00:01:06 [2022-02-18 08:24:34.029] 
00:01:06 [2022-02-18 08:24:34.029] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:06 [2022-02-18 08:24:34.029] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:06 [2022-02-18 08:24:34.029]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:06 [2022-02-18 08:24:34.029]                                                                                 
00:01:06 [2022-02-18 08:24:34.029] SHARES PER MINUTE: 0.44				POOL HASHRATE: 63.90 MH/s
00:01:06 [2022-02-18 08:24:34.029] 
00:01:07 [2022-02-18 08:25:34.011] 
00:01:07 [2022-02-18 08:25:34.011] 
00:01:07 [2022-02-18 08:25:34.011] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:07 [2022-02-18 08:25:34.011]                                                                                 
00:01:07 [2022-02-18 08:25:34.011] 
00:01:07 [2022-02-18 08:25:34.011] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:07 [2022-02-18 08:25:34.011] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:07 [2022-02-18 08:25:34.011]                                                                          0      
00:01:07 [2022-02-18 08:25:34.011] 
00:01:07 [2022-02-18 08:25:34.011] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:07 [2022-02-18 08:25:34.011] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:07 [2022-02-18 08:25:34.011]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:07 [2022-02-18 08:25:34.011]                                                                                 
00:01:07 [2022-02-18 08:25:34.011] SHARES PER MINUTE: 0.43				POOL HASHRATE: 62.95 MH/s
00:01:07 [2022-02-18 08:25:34.011] 
00:01:08 [2022-02-18 08:26:34.019] 
**00:01:08 [2022-02-18 08:26:34.019]** 

...

>00:01:23 [2022-02-18 08:41:34.010] SHARES PER MINUTE: 0.35				POOL HASHRATE: 50.81 MH/s
00:01:23 [2022-02-18 08:41:34.010] 
00:01:24 [2022-02-18 08:42:34.006] 
00:01:24 [2022-02-18 08:42:34.006] 
00:01:24 [2022-02-18 08:42:34.006] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:24 [2022-02-18 08:42:34.006]                                                                                 
00:01:24 [2022-02-18 08:42:34.006] 
00:01:24 [2022-02-18 08:42:34.006] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:24 [2022-02-18 08:42:34.006] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:24 [2022-02-18 08:42:34.006]                                                                          0      
00:01:24 [2022-02-18 08:42:34.006] 
00:01:24 [2022-02-18 08:42:34.006] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:24 [2022-02-18 08:42:34.006] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:24 [2022-02-18 08:42:34.006]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:24 [2022-02-18 08:42:34.006]                                                                                 
00:01:24 [2022-02-18 08:42:34.006] SHARES PER MINUTE: 0.35				POOL HASHRATE: 50.21 MH/s
00:01:24 [2022-02-18 08:42:34.006] 
00:01:25 [2022-02-18 08:43:34.016] 
00:01:25 [2022-02-18 08:43:34.016]
00:01:25 [2022-02-18 08:43:34.016] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:25 [2022-02-18 08:43:34.016]                                                                                 
00:01:25 [2022-02-18 08:43:34.016] 
00:01:25 [2022-02-18 08:43:34.016] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:25 [2022-02-18 08:43:34.016] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:25 [2022-02-18 08:43:34.016]                                                                          0      
00:01:25 [2022-02-18 08:43:34.016] 
00:01:25 [2022-02-18 08:43:34.016] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:25 [2022-02-18 08:43:34.016] GPU0    6900XT   0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:25 [2022-02-18 08:43:34.016]                  0.00 H/W      66.71 MH/s    66.71 MH/s    29/0/0       100.00% 
00:01:25 [2022-02-18 08:43:34.016]                                                                                 
00:01:25 [2022-02-18 08:43:34.016] SHARES PER MINUTE: 0.34				POOL HASHRATE: 49.62 MH/s
00:01:25 [2022-02-18 08:43:34.016] 
**00:01:25 [2022-02-18 08:44:02.436] Job 6d4a1**
00:01:25 [2022-02-18 08:44:10.473] Job 6d4a2
00:01:25 [2022-02-18 08:44:17.148] Job 6d4a3
00:01:25 [2022-02-18 08:44:23.823] Job 6d4a4
00:01:25 [2022-02-18 08:44:31.834] Job 6d4a5
00:01:25 [2022-02-18 08:44:33.170] Job 6d4a6
00:01:26 [2022-02-18 08:44:34.007] 
00:01:26 [2022-02-18 08:44:34.007] 
00:01:26 [2022-02-18 08:44:34.007] us-eth.2miners.com (ethash)    PING: 43ms    VARDIFF: 2.03     EPOCH: 474
00:01:26 [2022-02-18 08:44:34.007]                                                                                 
00:01:26 [2022-02-18 08:44:34.007] 
00:01:26 [2022-02-18 08:44:34.007] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:01:26 [2022-02-18 08:44:34.007] GPU0    6900XT   OpenCL  0       256     0/0     0       0       0       0      
00:01:26 [2022-02-18 08:44:34.007]                                                                          0      
00:01:26 [2022-02-18 08:44:34.007] 
00:01:26 [2022-02-18 08:44:34.007] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:01:26 [2022-02-18 08:44:34.007] GPU0    6900XT   0.00 H/W      1121.81 kH/s  66.41 MH/s    29/0/0       100.00% 
00:01:26 [2022-02-18 08:44:34.007]                  0.00 H/W      1121.81 kH/s  66.41 MH/s    29/0/0       100.00% 
00:01:26 [2022-02-18 08:44:34.007]                                                                                 
00:01:26 [2022-02-18 08:44:34.007] SHARES PER MINUTE: 0.34				POOL HASHRATE: 49.04 MH/s
00:01:26 [2022-02-18 08:44:34.007] 
00:01:26 [2022-02-18 08:44:38.512] Job 6d4a7

This circumvents the watchdog I have in Windows, because I have no access to the power information from the client window due to some OpenCL issue, I can only go by the current HashRate which remains constant.  On my HiveOS machines I am able to monitor the actual number of shares submitted over a timeframe and recycle the miner if it doesn't provide any valid shares for 2 minutes, but this only helps when all the cards are inactive, so I also have to monitor by power usage which is not an ideal solution, but is better than having my AMD test rig not provide shares for different periods of time over night.

**Comment by sp-hash** [comment]
A fix is ready in 1.56

**Comment by sp-hash** [comment]
fixed in 1.56
