### ISSUE TITLE
3060ti LHR v3

### ISSUE THREAD

**Issue by alexstab** [sp-hash/TeamBlackMiner#268]
Hi!
i have several problems with my gigabyte 2060ti LHR v3 running tbm..
i can barely get to 37 mhs at --lhr-unlock -95!

win10 tbm v1.56 cuda 11.4 nvidia driver 472.12..

**Comment by sp-hash** [comment]
The lhr unlock is made for cuda 11.5 and the latest drivers.

try to add tweak


--lhr-unlock 1 --tweak -1
--lhr-unlock 1 --tweak -2
--lhr-unlock 1 --tweak -3

**Comment by alexstab** [comment]
I have tried everything but I can only stabilize my 3060ti LHR v3 on 36 / 37mhs..

**Comment by sp-hash** [comment]
What's your memclock? I get best rates with 8100(windows) / (2025 linux) on the 3070. 43MHASH. Dag validation will fail, so you need an older card in the rig to be able to pass the validation stage.

**Comment by alexstab** [comment]
core clock 1250 mem 8000.. dag is ok. at unlock -80 reset every 14sec..

**Comment by sp-hash** [comment]
Did you set the TDP to 55%

**Comment by alexstab** [comment]
With afterburner at very low voltage (mv 743) its okay at -85 with 37 mhs without any reset.. but as soon as it starts to rise it resets again
