### ISSUE TITLE
First invalid share starts other cards invalid shares 

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#269]
Finally, I found that why suddenly the rig starts to have many invalid shares, the first invalid share happen in a card, make other cards to start invalid shares.

**Comment by sp-hash** [comment]
was the dag buffer copied from one of the gpus on to the others? Do you have any logs? Please run with --log

**Comment by sepehrland** [comment]
> was the dag buffer copied from one of the gpus on to the others? Do you have any logs? Please run with --log

I'm on hiveos, let me enable the log and send the log file when it happened again.

**Comment by sepehrland** [comment]
now let me explain the log:

**It's my normal log before the rejected shares start:**


eth.2miners.com (ethash)    PING: 31ms    VARDIFF: 2.03     EPOCH: 476
                                                                                

_ID_________BOARD____TYPE____KERN____XINT____TEMP____FAN_____CORE____MEM_____WATT___
_GPU0____gfx1010__OpenCL__0_______-1______42/0____80______1350____900_____67_____
_GPU1____gfx1010__OpenCL__0_______-1______55/0____80______1350____900_____72_____
_GPU2____3070_____CUDA____13______3100____57/0____64______1095____7900____124____
_GPU3____3070_____CUDA____13______3100____58/0____60______1095____7900____118____
_GPU4____3070_____CUDA____13______3100____59/0____57______1095____7900____110____
_GPU5____3060Ti___CUDA____13______3100____57/0____50______1500____8250____125____
_GPU6____3070_____CUDA____2_______3100____58/0____62______1095____7900____115____
_GPU7____3070_____CUDA____13______3100____59/0____49______1095____7900____124____


_ID______BOARD____HASHRATE/W____HASHRATE______AVERAGE_______SHARES_______RATE____
_GPU0____gfx1010__627.06_kH/W___43.89_MH/s____44.07_MH/s____266/0/0______100.00%_
_GPU1____gfx1010__605.29_kH/W___44.19_MH/s____44.19_MH/s____256/0/0______100.00%_
_GPU2____3070_____502.50_kH/W___62.31_MH/s____62.18_MH/s____409/0/0______100.00%_
_GPU3____3070_____528.20_kH/W___62.33_MH/s____62.20_MH/s____405/0/0______100.00%_
_GPU4____3070_____561.64_kH/W___62.34_MH/s____62.34_MH/s____407/0/0______100.00%_
_GPU5____3060Ti___519.25_kH/W___64.91_MH/s____64.74_MH/s____411/0/0______100.00%_
_GPU6____3070_____542.07_kH/W___62.34_MH/s____62.34_MH/s____413/0/0______100.00%_
_GPU7____3070_____498.71_kH/W___62.34_MH/s____62.34_MH/s____357/0/0______100.00%_
__________________548.09_kH/W___464.64_MH/s___464.39_MH/s___2924/0/0_____100.00%_
______________________________________________________________________________
_SHARES_PER_MINUTE:_3.04				POOL_HASHRATE:_442.51_MH



**and it is what happened in one of my cards suddenly:**

[2022-02-28 09:45:50.551] GPU3    3070     **1640.32** kH/W  62.33 MH/s    62.20 MH/s    407/0/0      100.00% 

KH/W increases significantly and fan goes to 0 and temp dropped and after 5 mins KH/W and all others is 0

then I have this : 

GPU3: GPU thread crashed exiting program.
00:16:19 [2022-02-28 10:01:51.827] Shutting down threads
00:16:19 [2022-02-28 10:01:51.827] Stratum thread exited

and miner resets automatically

after reset I have this : 

00:00:00 [2022-02-28 10:02:18.425] GPU3 Dag verification failed, retrying while waiting for other gpus..
00:00:00 [2022-02-28 10:02:18.451] GPU3 Fetching ethash dag (Epoch: 476)
00:00:00 [2022-02-28 10:02:18.451] GPU3 XIntensity set to 3100
00:00:00 [2022-02-28 10:02:18.458] GPU2 Dag verification failed, retrying while waiting for other gpus..
00:00:00 [2022-02-28 10:02:18.487] GPU2 Fetching ethash dag (Epoch: 476)
00:00:00 [2022-02-28 10:02:18.488] GPU2 XIntensity set to 3100
00:00:00 [2022-02-28 10:02:18.784] GPU5 Dag verification failed, retrying while waiting for other gpus..
00:00:00 [2022-02-28 10:02:18.809] GPU5 Fetching ethash dag (Epoch: 476)
00:00:00 [2022-02-28 10:02:18.809] GPU5 XIntensity set to 3100
00:00:00 [2022-02-28 10:02:20.271] GPU6 Dag verification failed, retrying while waiting for other gpus..
00:00:00 [2022-02-28 10:02:20.274] GPU7 Dag verification failed, retrying while waiting for other gpus..
00:00:00 [2022-02-28 10:02:20.275] GPU4 Dag verification failed, retrying while waiting for other gpus..



I don't have this issue with other miners .

**Comment by sp-hash** [comment]
You need to reduce the clocks on one of the gpu's so that the dag will go through,

**Comment by sepehrland** [comment]
how much should I reduce ? 
I change the core from 1100 to 1060 and MEM from 1800 to 1700
is it enough ?

**Comment by sepehrland** [comment]
as I found these days, it's not just about one of my cards:

**Normal hashrates:**
GPU0    gfx1010  626.86 kH/W   43.88 MH/s    43.87 MH/s    304/0/0 
GPU1    gfx1010  601.84 kH/W   43.93 MH/s    43.93 MH/s    333/0/0
GPU2    3070     506.59 kH/W   62.31 MH/s    62.31 MH/s    460/0/0
GPU3    3070     528.29 kH/W   62.34 MH/s    62.34 MH/s    457/0/0
GPU4    3070     566.66 kH/W   62.33 MH/s    62.34 MH/s    436/0/0
GPU5    3060Ti   515.09 kH/W   64.90 MH/s    64.90 MH/s    457/0/0
GPU6    3070     542.11 kH/W   62.34 MH/s    62.34 MH/s    399/0/0
GPU7    3070     502.68 kH/W   62.33 MH/s    62.34 MH/s    417/0/0

**Then:**
GPU0    gfx1010  1900.51 kH/W  43.71 MH/s    43.87 MH/s    304/0/0
GPU1    gfx1010  825.30 kH/W   43.74 MH/s    43.92 MH/s    333/0/0
GPU2    3070     1449.08 kH/W  62.31 MH/s    62.31 MH/s    460/0/0
GPU3    3070     1684.88 kH/W  62.34 MH/s    62.34 MH/s    457/0/0
GPU4    3070     1889.01 kH/W  62.34 MH/s    62.34 MH/s    436/0/0
GPU5    3060Ti   1622.62 kH/W  64.90 MH/s    64.90 MH/s    457/0/0
GPU6    3070     542.10 kH/W   62.34 MH/s    62.34 MH/s    399/0/0
GPU7    3070     1416.79 kH/W  62.34 MH/s    62.34 MH/s    417/0/0

hashrate/w goes up and then :
GPU0: has timed out, trying to restart..
GPU3: has timed out, trying to restart..
GPU4: has timed out, trying to restart..
GPU5: has timed out, trying to restart..
GPU7: has timed out, trying to restart..

it happened at least once a day

**Comment by sp-hash** [comment]
timeouts fixed in 1.58
