### ISSUE TITLE
No reported Hashrate on ethermine graph

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#27]
Hello,

I have try one night Team Black Miner,

My 3080 gaming X trio has passed 98 to 102 mh/s this is great.

But on ethermine graph i have no reported Hash Rate but i can see valid shares.

It's normal on ethermine we don't see reported hash rate ?

thank you so much

**Comment by sp-hash** [comment]
What is your launch config?

use v1.5 some bugs where fixed in the previous versions

**Comment by MrNuTruT** [comment]
I use the last version the 1.5
I use the ethermine file which already exists.

this is my file : 

Set ETH_WALLET=XXXXXXX

:loop
	TBMiner --algo ethash --hostname eu1.ethermine.org --port 4444 --wallet %ETH_WALLET% --xintensity 1 --worker_name PcKingKong
	timeout 10
goto :loop

**Comment by sp-hash** [comment]
you bat looks correct. You need to mine for 15 minutes in order for the stats to show.
https://ethermine.org/miners/walletadress/dashboard

**Comment by MrNuTruT** [comment]
I have mine 5 hours two time and and i have never seen the reported hashrate

https://ethermine.org/miners/8231aa188b0d54e8991776e939e790b3ec62d537/dashboard

look

**Comment by sp-hash** [comment]
The reported hashrate is the green line in the graph. The orange line is the average rate (poolside) 

poolside average in the 5 hours is 288.3MHASH, reported in the mining window is 283.9

![hashrate](https://user-images.githubusercontent.com/9572668/133939893-de92c70f-f1e8-4845-a17f-6d73739a5515.png)

**Comment by MrNuTruT** [comment]
![image](https://user-images.githubusercontent.com/11719145/133940169-022a8cbb-4ba5-43ed-9607-cb35473d7038.png)

**Comment by sp-hash** [comment]
Ok. reproduced and fixed in v1.07.
