### ISSUE TITLE
error

### ISSUE THREAD

**Issue by githubqy** [sp-hash/TeamBlackMiner#273]
The error appears in the window after the script is executed：
C:\gc\tbminer\source\sp_stratum\eth_stratum_pool. CPP :sp_pool_tcp_connect():64:  A curl runtime error occured: Timeout was reached

**Comment by sp-hash** [comment]
What does the script look like?

**Comment by sp-hash** [comment]
Anonymous encrypted mining support ssl added in the latest release v1.63
