### ISSUE TITLE
AMD 6800-series cards drop power but don't register as failed

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#274]
Cards will continue to register as hashing in the miner console, but power drops to idle without any timeout or failure messages in the log file.  Cards aren't heavily overclocked / under-volted and often this behaviour shows up shortly after miner startup.

See GPU1 in images below:

<img width="832" alt="Screen Shot 2022-03-09 at 10 11 39 AM" src="https://user-images.githubusercontent.com/90629276/157470978-b36cf22e-d95e-4caf-892a-91bf279baae3.png">
 
<img width="1211" alt="Screen Shot 2022-03-09 at 10 11 19 AM" src="https://user-images.githubusercontent.com/90629276/157471021-3d5b91b9-bf5f-49bc-ad1a-0794adbfcd95.png">

**Comment by sp-hash** [comment]
Can you check if the dag verification has passed in the logfile?

**Comment by KillrBee** [comment]
> Can you check if the dag verification has passed in the logfile?

It did pass verification, but I see that it started to hash but failed very soon into to the run (as you can see by the initial temperature increase and subsequent decrease to ambient in the included image):

<img width="646" alt="Screen Shot 2022-03-09 at 10 58 34 AM" src="https://user-images.githubusercontent.com/90629276/157479882-cfbcedc8-dc27-4f3e-93d4-e943aa7c4ba7.png">

**Comment by sp-hash** [comment]
I have added some more fixes and debug output in 1.59
