### ISSUE TITLE
source/sp_cuda/cudaminer.cpp:cuda_search():958: A cuda runtime error occured: an illegal memory access was encountered

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#276]
I'm using 1.61, Nvidia Driver 495.46 (CUDA 11.5), Hive OS
I forced this issue after upgrade to 1.61 and after some accepted shares:
source/sp_cuda/cudaminer.cpp:cuda_search():958: A cuda runtime error occured: an illegal memory access was encountered
Shutting down threads
Stratum thread exited

and miner reset.

**Comment by sp-hash** [comment]
Make sure that you have enough virtual memory/swap. 4gb per card should be enougj.

**Comment by sepehrland** [comment]
How can I check or change that on linux(HiveOS)?

**Comment by sp-hash** [comment]
https://minerstat.com/help/how-to-increase-virtual-memory-on-linux

**Comment by sepehrland** [comment]
> https://minerstat.com/help/how-to-increase-virtual-memory-on-linux

It's for msOS not hiveOS

**Comment by sp-hash** [comment]
hiveos is based on ubuntu 18.04:

https://www.codegrepper.com/search.php?answer_removed=1&q=increase%20swap%20space%20ubuntu%2018.04

**Comment by sepehrland** [comment]
> hiveos is based on ubuntu 18.04:
> 
> https://www.codegrepper.com/search.php?answer_removed=1&q=increase%20swap%20space%20ubuntu%2018.04

I did it and it now it's stable for a day, I think it's better to notice it somewhere to the others, because in hiveOS, there isn't any swap by default.

**Comment by sepehrland** [comment]
it did not work at it happened again

**Comment by sepehrland** [comment]
your solution not works and the issue occurs again

**Comment by sepehrland** [comment]
> your solution not works and the issue occurs again, I have 8Gb ram installed which always has about 5.4Gb free, also, as you said, create 32Gb swap for 8 cards, but, this error happened again.

I have updated my nvidia driver to cuda 11.6 (510.60.02) and it seems the problem solved now!
