### ISSUE TITLE
many invalid shares after miner resets

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#277]
with any reason if miner resets, it starts many invalid shares until I reboot the rig.

**Comment by sepehrland** [comment]
Error:An error has occurred. Cannot receive data from pool
I'm on 2miners and 1.61

**Comment by sp-hash** [comment]
Problems with the internet connection? Why don't you show me more of the logfile

**Comment by sepehrland** [comment]
> Problems with the internet connection? Why don't you show me more of the logfile

00:22:03 [2022-03-30 22:27:33.922] eth.2miners.com (ethash)    PING: 29ms    DIFFICULTY: 2.03     EPOCH: 482
00:22:03 [2022-03-30 22:27:33.922]                                                                                 
00:22:03 [2022-03-30 22:27:33.922] 
00:22:03 [2022-03-30 22:27:33.922] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:22:03 [2022-03-30 22:27:33.922] GPU0    gfx1010  OpenCL  0       71      41/0    80      1100    890     60     
00:22:03 [2022-03-30 22:27:33.922] GPU1    gfx1010  OpenCL  0       71      58/0    80      1100    890     65     
00:22:03 [2022-03-30 22:27:33.922] GPU2    3070     CUDA    13      284     61/0    61      1095    7950    111    
00:22:03 [2022-03-30 22:27:33.922] GPU3    3070     CUDA    13      284     62/0    54      1095    7950    119    
00:22:03 [2022-03-30 22:27:33.922] GPU4    3070     CUDA    13      284     63/0    62      1095    7950    125    
00:22:03 [2022-03-30 22:27:33.922] GPU5    3060Ti   CUDA    2       284     62/0    46      1500    8200    125    
00:22:03 [2022-03-30 22:27:33.922] GPU6    3070     CUDA    13      284     62/0    56      1095    7950    115    
00:22:03 [2022-03-30 22:27:33.922] GPU7    3070     CUDA    13      284     61/0    50      1095    7950    125    
00:22:03 [2022-03-30 22:27:33.922]                                                                          845    
00:22:03 [2022-03-30 22:27:33.922] 
00:22:03 [2022-03-30 22:27:33.922] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:22:03 [2022-03-30 22:27:33.922] GPU0    gfx1010  754.01 kH/W   42.22 MH/s    42.59 MH/s    382/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU1    gfx1010  647.68 kH/W   42.75 MH/s    42.73 MH/s    375/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU2    3070     561.85 kH/W   62.37 MH/s    62.36 MH/s    511/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU3    3070     524.10 kH/W   62.37 MH/s    62.40 MH/s    521/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU4    3070     495.59 kH/W   62.44 MH/s    62.44 MH/s    550/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU5    3060Ti   509.30 kH/W   64.17 MH/s    64.17 MH/s    595/0/0      100.00% 
00:22:03 [2022-03-30 22:27:33.922] GPU6    3070     538.25 kH/W   62.44 MH/s    62.43 MH/s    559/1/0      99.82%  
00:22:03 [2022-03-30 22:27:33.922] GPU7    3070     499.71 kH/W   62.46 MH/s    62.43 MH/s    520/2/0      99.62%  
00:22:03 [2022-03-30 22:27:33.922]                  566.31 kH/W   461.22 MH/s   461.55 MH/s   4013/3/0     99.93%  
00:22:03 [2022-03-30 22:27:33.922]                                                                                 
00:22:03 [2022-03-30 22:27:33.922] SHARES PER MINUTE: 3.03				POOL HASHRATE: 441.14 MH/s
00:22:03 [2022-03-30 22:27:33.922] 
00:22:03 [2022-03-30 22:27:36.239] Job f13ca
00:22:03 [2022-03-30 22:27:36.688] GPU5 Solution found in 0.46s (Submit every 22.64 seconds)
00:22:03 [2022-03-30 22:27:36.833] Accepted (4014/4017/0) Reply: 145ms
00:22:03 [2022-03-30 22:27:43.206] Job f13cb
00:22:03 [2022-03-30 22:27:47.210] GPU6 Solution found in 4.01s (Submit every 22.63 seconds)
00:22:03 [2022-03-30 22:27:47.391] Accepted (4015/4018/0) Reply: 180ms
00:22:03 [2022-03-30 22:27:50.445] Job f13cc
00:22:03 [2022-03-30 22:27:53.764] GPU2 Solution found in 3.32s (Submit every 22.61 seconds)
00:22:03 [2022-03-30 22:27:53.923] Accepted (4016/4019/0) Reply: 159ms
00:22:04 [2022-03-30 22:27:57.494] Job f13cd
00:22:04 [2022-03-30 22:28:05.711] Job f13ce
00:22:04 [2022-03-30 22:28:08.517] Job f13cf
00:22:04 [2022-03-30 22:28:08.671] Job f13d0
00:22:04 [2022-03-30 22:28:15.661] Job f13d1
00:22:04 [2022-03-30 22:28:22.668] Job f13d2
00:22:04 [2022-03-30 22:28:24.260] error: 0 recieve
00:22:04 [2022-03-30 22:28:24.260] An error has occurred. Cannot receive data from pool
00:22:04 [2022-03-30 22:28:24.260] Shutting down threads
00:22:04 [2022-03-30 22:28:24.260] Stratum thread exited
00:22:04 [2022-03-30 22:28:24.262] GPU4 thread exited
00:22:04 [2022-03-30 22:28:24.272] GPU2 thread exited
00:22:04 [2022-03-30 22:28:24.307] GPU0 thread exited
00:22:04 [2022-03-30 22:28:24.316] Control thread exited
00:22:04 [2022-03-30 22:28:24.320] GPU5 thread exited
00:22:04 [2022-03-30 22:28:24.342] GPU7 thread exited
00:22:04 [2022-03-30 22:28:24.360] GPU6 thread exited
00:22:04 [2022-03-30 22:28:24.369] GPU3 thread exited
00:22:04 [2022-03-30 22:28:24.493] GPU1 thread exited
00:22:04 [2022-03-30 22:28:28.260] Exiting

**Comment by sp-hash** [comment]
[quote]
00:22:04 [2022-03-30 22:28:24.260] error: 0 recieve
00:22:04 [2022-03-30 22:28:24.260] An error has occurred. Cannot receive data from pool
[/quote]

Here is the problem. We have disabled the watchdog, so instead to try to fix it we exit the miner. So you need to prevent the miner to exit and continue mining. Here is a problem with the pool connection, we could try to restart the stratum thread. might work...

**Comment by sp-hash** [comment]
v1.62 has been released with less crashes/restarts on linux.  Check it out
