### ISSUE TITLE
No Stats for amd 6600xt

### ISSUE THREAD

**Issue by Kroissan** [sp-hash/TeamBlackMiner#28]
Upgraded to v1.06 and it still don't show any stats. For only two of my GPUs, it detected that they are 6600xt. For stats(clk, tdp) their is still "0" everywhere.

**Comment by markuznw** [comment]
Same here on 5700xt, 1.06 didn't fix anything compared to 1.05 (besides the nvidia_smi error :D)

**Comment by sp-hash** [comment]
Fixed in 1.07
