### ISSUE TITLE
Large number of duplicate shares being produced

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#280]
[quote author=KillrBee link=topic=5358334.msg59812333#msg59812333 date=1649525817]
I don't know if it's the extra card or version 1.62 CUDA 11.5, but I'm getting a LOT of duplicate share rejects from 2miners now.
[/quote]

I've gone back to v1.61 to see if it's a v1.62 issue, or if it's a Nvidia issue - these duplicates are only happening with the Nvidia cards -- I've gone from 0 rejects for any reason during a month of mining to this:

root@red-ether:/var/log/miner/teamblackminer# cat teamblackminer.log |grep -i -A 3 'rejected'
00:00:00 [2022-04-09 23:25:15.941] Rejected (1/2) Reply: 32ms
00:00:00 [2022-04-09 23:25:15.941] mining.submit: Pool reponded with error
00:00:00 [2022-04-09 23:25:15.941] Error: Duplicate share
00:00:00 [2022-04-09 23:25:22.147] Job 237c5
--
00:00:06 [2022-04-09 23:31:35.940] Rejected (25/27) Reply: 58ms
00:00:06 [2022-04-09 23:31:35.940] mining.submit: Pool reponded with error
00:00:06 [2022-04-09 23:31:35.940] Error: Duplicate share
00:00:06 [2022-04-09 23:31:35.988] Job 23839
--
00:00:29 [2022-04-09 23:54:31.467] Rejected (121/124) Reply: 33ms
00:00:29 [2022-04-09 23:54:31.467] mining.submit: Pool reponded with error
00:00:29 [2022-04-09 23:54:31.467] Error: Duplicate share
00:00:29 [2022-04-09 23:54:31.902] Job 239f7
--
00:00:30 [2022-04-09 23:55:01.868] Rejected (125/129) Reply: 36ms
00:00:30 [2022-04-09 23:55:01.868] mining.submit: Pool reponded with error
00:00:30 [2022-04-09 23:55:01.868] Error: Duplicate share
00:00:30 [2022-04-09 23:55:02.089] Job 23a02
--
00:00:50 [2022-04-10 00:15:15.372] Rejected (205/210) Reply: 32ms
00:00:50 [2022-04-10 00:15:15.372] mining.submit: Pool reponded with error
00:00:50 [2022-04-10 00:15:15.372] Error: Duplicate share
00:00:50 [2022-04-10 00:15:21.649] Job 23b8f
--
00:01:14 [2022-04-10 00:38:41.341] Rejected (297/303) Reply: 37ms
00:01:14 [2022-04-10 00:38:41.341] mining.submit: Pool reponded with error
00:01:14 [2022-04-10 00:38:41.341] Error: Duplicate share
00:01:14 [2022-04-10 00:38:42.002] Job 23d4f
--
00:01:24 [2022-04-10 00:49:03.203] Rejected (342/349) Reply: 31ms
00:01:24 [2022-04-10 00:49:03.203] mining.submit: Pool reponded with error
00:01:24 [2022-04-10 00:49:03.203] Error: Duplicate share
00:01:24 [2022-04-10 00:49:10.090] 
--
00:01:28 [2022-04-10 00:53:16.519] Rejected (356/364) Reply: 55ms
00:01:28 [2022-04-10 00:53:16.519] mining.submit: Pool reponded with error
00:01:28 [2022-04-10 00:53:16.519] Error: Duplicate share
00:01:28 [2022-04-10 00:53:17.171] Job 23e6a
--
00:01:43 [2022-04-10 01:07:52.884] Rejected (404/413) Reply: 38ms
00:01:43 [2022-04-10 01:07:52.884] mining.submit: Pool reponded with error
00:01:43 [2022-04-10 01:07:52.884] Error: Duplicate share
00:01:43 [2022-04-10 01:07:58.636] Job 23f80
--
00:02:19 [2022-04-10 01:44:22.682] Rejected (549/559) Reply: 34ms
00:02:19 [2022-04-10 01:44:22.682] mining.submit: Pool reponded with error
00:02:19 [2022-04-10 01:44:22.682] Error: Duplicate share
00:02:19 [2022-04-10 01:44:28.558] Job 2425b
--
00:03:15 [2022-04-10 02:39:44.678] Rejected (769/780) Reply: 38ms
00:03:15 [2022-04-10 02:39:44.678] mining.submit: Pool reponded with error
00:03:15 [2022-04-10 02:39:44.678] Error: Duplicate share
00:03:15 [2022-04-10 02:39:51.101] Job 2468a
--
00:04:11 [2022-04-10 03:35:40.675] Rejected (990/1002) Reply: 39ms
00:04:11 [2022-04-10 03:35:40.675] mining.submit: Pool reponded with error
00:04:11 [2022-04-10 03:35:40.675] Error: Duplicate share
00:04:11 [2022-04-10 03:35:41.378] Job 24af3
--
00:04:16 [2022-04-10 03:41:18.807] Rejected (1013/1026) Reply: 31ms
00:04:16 [2022-04-10 03:41:18.807] mining.submit: Pool reponded with error
00:04:16 [2022-04-10 03:41:18.807] Error: Duplicate share
00:04:16 [2022-04-10 03:41:19.307] Job 24b6f
--
00:04:33 [2022-04-10 03:58:14.434] Rejected (1087/1101) Reply: 30ms
00:04:33 [2022-04-10 03:58:14.434] mining.submit: Pool reponded with error
00:04:33 [2022-04-10 03:58:14.434] Error: Duplicate share
00:04:33 [2022-04-10 03:58:14.835] Job 24ca2
--
00:05:18 [2022-04-10 04:43:26.956] Rejected (1243/1258) Reply: 34ms
00:05:18 [2022-04-10 04:43:26.956] mining.submit: Pool reponded with error
00:05:18 [2022-04-10 04:43:26.956] Error: Duplicate share
00:05:18 [2022-04-10 04:43:28.004] Job 25010
--
00:06:05 [2022-04-10 05:29:49.418] Rejected (1399/1415) Reply: 36ms
00:06:05 [2022-04-10 05:29:49.418] mining.submit: Pool reponded with error
00:06:05 [2022-04-10 05:29:49.418] Error: Duplicate share
00:06:05 [2022-04-10 05:29:51.066] Job 253b5
--
00:06:39 [2022-04-10 06:03:59.484] Rejected (1525/1542) Reply: 35ms
00:06:39 [2022-04-10 06:03:59.484] mining.submit: Pool reponded with error
00:06:39 [2022-04-10 06:03:59.484] Error: Duplicate share
00:06:39 [2022-04-10 06:04:00.159] Job 25658
--
00:07:08 [2022-04-10 06:33:08.192] Rejected (1632/1650) Reply: 34ms
00:07:08 [2022-04-10 06:33:08.192] mining.submit: Pool reponded with error
00:07:08 [2022-04-10 06:33:08.192] Error: Duplicate share
00:07:08 [2022-04-10 06:33:08.618] Job 2589c
--
00:07:56 [2022-04-10 07:21:16.451] Rejected (1792/1811) Reply: 71ms
00:07:56 [2022-04-10 07:21:16.451] mining.submit: Pool reponded with error
00:07:56 [2022-04-10 07:21:16.451] Error: Duplicate share
00:07:56 [2022-04-10 07:21:18.459] Job 25c3c
--
00:07:56 [2022-04-10 07:21:25.276] Rejected (1793/1813) Reply: 34ms
00:07:56 [2022-04-10 07:21:25.276] mining.submit: Pool reponded with error
00:07:56 [2022-04-10 07:21:25.276] Error: Duplicate share
00:07:56 [2022-04-10 07:21:25.765] Job 25c3e

I will monitor the results in v1.61 and provide an update when:
(a) I get more duplicates 
/or/
(b) I mine for a few hours with no duplicates

**Comment by KillrBee** [comment]
Update:  It's happening on v1.61 as well.

00:00:19 [2022-04-10 08:31:18.390] Rejected (68/69) Reply: 32ms
00:00:19 [2022-04-10 08:31:18.390] mining.submit: Pool reponded with error
00:00:19 [2022-04-10 08:31:18.390] Error: Duplicate share
00:00:19 [2022-04-10 08:31:25.329] Job 25b03

So this tells me that there's some interference happening between my new 3090Ti card and my 3090 + 2060S.

**Comment by KillrBee** [comment]
This seems to be a pattern found in the duplicates:   GPU 5 = 3090; GPU 6 = 2060S

00:00:29 [2022-04-09 23:54:29.309] Accepted (120/122/0) Reply: 32ms
00:00:29 [2022-04-09 23:54:30.019] GPU6 Solution found in 5.38s (Submit every 16.42 seconds)
00:00:29 [2022-04-09 23:54:30.051] Accepted (121/123/0) Reply: 31ms
00:00:29 [2022-04-09 23:54:31.434] GPU5 Solution found in 6.80s (Submit every 16.35 seconds)
00:00:29 [2022-04-09 23:54:31.467] Rejected (121/124) Reply: 33ms
00:00:29 [2022-04-09 23:54:31.467] mining.submit: Pool reponded with error
00:00:29 [2022-04-09 23:54:31.467] Error: Duplicate share
--
00:00:30 [2022-04-09 23:55:00.204] GPU6 Solution found in 5.42s (Submit every 16.15 seconds)
00:00:30 [2022-04-09 23:55:00.236] Accepted (125/128/0) Reply: 32ms
00:00:30 [2022-04-09 23:55:01.689] Job 23a01
00:00:30 [2022-04-09 23:55:01.831] GPU5 Solution found in 0.18s (Submit every 16.04 seconds)
00:00:30 [2022-04-09 23:55:01.868] Rejected (125/129) Reply: 36ms
00:00:30 [2022-04-09 23:55:01.868] mining.submit: Pool reponded with error
00:00:30 [2022-04-09 23:55:01.868] Error: Duplicate share
--
00:00:50 [2022-04-10 00:15:13.819] GPU6 Solution found in 6.26s (Submit every 16.52 seconds)
00:00:50 [2022-04-10 00:15:13.859] Accepted (205/209/0) Reply: 39ms
00:00:50 [2022-04-10 00:15:14.860] Job 23b8e
00:00:50 [2022-04-10 00:15:15.339] GPU5 Solution found in 0.78s (Submit every 16.45 seconds)
00:00:50 [2022-04-10 00:15:15.372] Rejected (205/210) Reply: 32ms
00:00:50 [2022-04-10 00:15:15.372] mining.submit: Pool reponded with error
00:00:50 [2022-04-10 00:15:15.372] Error: Duplicate share

**Comment by sp-hash** [comment]
Can you run 

tbminer --list-devices please.

I haven't seen this bug before on 2miners, but it could indicates that the cards are working on the same nonce range, and thus reducing the  performance. What's your exact launch config?

**Comment by KillrBee** [comment]
Here's the CUDA list:  

Available Cuda devices
-----------------------

Device Number: 0
    Device name: NVIDIA GeForce RTX 3090 Ti
    PCIe bus id: 45
    Memory: 24GB
    Memory clock rate (KHz): 10501000
    Memory bus width (bits): 384
    Peak memory bandwidth (GB/s): 1008.096000

Device Number: 1
    Device name: NVIDIA GeForce RTX 3090
    PCIe bus id: 55
    Memory: 24GB
    Memory clock rate (KHz): 9751000
    Memory bus width (bits): 384
    Peak memory bandwidth (GB/s): 936.096000

Device Number: 2
    Device name: NVIDIA GeForce RTX 2060 SUPER
    PCIe bus id: 61
    Memory: 24GB
    Memory clock rate (KHz): 7001000
    Memory bus width (bits): 256
    Peak memory bandwidth (GB/s): 448.064000

**Comment by KillrBee** [comment]
It seems to only be happening when I have both the AMD and Nvidia cards running together in the same instance of TBMiner.  So it could be either the combination of the AMD+NVidia devices, or maybe it could be that there are 7 cards (regardless of their type), running in a single instance of the miner?

**Comment by sp-hash** [comment]
Can you try v1.66 please? We have solved some reconnect bugs.
