### ISSUE TITLE
TBM not hashing

### ISSUE THREAD

**Issue by scorpio8783** [sp-hash/TeamBlackMiner#281]
Hello,

i am using minerstate os on my 2 3070's mining rig, when trying TBM on 2miners pool it is not hashing, although it is working well with gminer.
nvidia driver 460. 67
any help is highly appreciated
thanks

note:My rig doesn't have any screen attached, and i access it remotely

**Comment by sp-hash** [comment]
You need a newer driver to be able to run. The Cuda 11.4 build will work with 470.57.02 or later driver.

**Comment by scorpio8783** [comment]
> You need a newer driver to be able to run. The Cuda 11.4 build will work with 470.57.02 or later driver.



> You need a newer driver to be able to run. The Cuda 11.4 build will work with 470.57.02 or later driver.

updated my drivers to lates 510.60.02 and still not hashing 
![Screenshot_20220420-000727](https://user-images.githubusercontent.com/82088548/164102409-9183039c-c657-4bd6-b2e4-edcd28476593.png)

![Screenshot_20220420-001752](https://user-images.githubusercontent.com/82088548/164103504-e053697c-fe6d-485c-b01f-fabdcbc0d5a4.png)

anything else is needed to solve the problem

fyi: i removed all overclocking setups that i used with gminer and still no luck

**Comment by sp-hash** [comment]
The box.pool.ms has not yet been configured.

**Comment by scorpio8783** [comment]
> The box.pool.ms has not yet been configured. The second pic is from 2miners. Can you provide the complete launch config?
> 
> --worker-name

![Screenshot_20220420-153006](https://user-images.githubusercontent.com/82088548/164230873-c659a5fd-8fd8-4fb2-810c-02cac8c56e41.png)
![Screenshot_20220420-153015](https://user-images.githubusercontent.com/82088548/164231251-d213c7ac-58c4-4896-9ee5-4c2fa8af620b.png)

Try minerstat os ( msos ) with TBM to know what i am facing, i mean everything is set fine, why not mining!! even benchmarking is not working with TBM, every other miner that mines ethash does work except the best one.. yours
