### ISSUE TITLE
application crash in last hiveos update

### ISSUE THREAD

**Issue by sepehrland** [sp-hash/TeamBlackMiner#282]
I have updated my hiveos to 0.6-216 and after that I can't use teamblackminer, 
it says application crash, 
I attached the crash log file

also I've seen this error : 
source/sp_cuda/cudaminer.cpp:cuda_init_device():68: A cuda runtime error occured: driver shutting down

but other miners like t-rex and phoenix works.
[crash_report.txt](https://github.com/sp-hash/TeamBlackMiner/files/8520707/crash_report.txt)

**Comment by sp-hash** [comment]
I need the output to the console log in order to debug. Run with --log

**Comment by sepehrland** [comment]
> I need the output to the console log in order to debug. Run with --log

[tlog.log](https://github.com/sp-hash/TeamBlackMiner/files/8522113/tlog.log)

**Comment by sp-hash** [comment]
You need to add 4gb of swap per card. so 32GB swap on a 8 card rig (harddrive memory)

**Comment by sepehrland** [comment]
> You need to add 4gb of swap per card. so 32GB swap on a 8 card rig (harddrive memory)

I did it, but still has this problem
[tlog2.log](https://github.com/sp-hash/TeamBlackMiner/files/8523392/tlog2.log)
![20220420_205246](https://user-images.githubusercontent.com/52125793/164279098-da5f91ea-1f05-4781-8f2c-de0ec83c4948.jpg)

**Comment by sp-hash** [comment]
What do you get with:

tbminer --list-devices

Does it work with --cuda-all-devices?

what is  BITBY-RU-MODDED 6600xt?

**Comment by sepehrland** [comment]
> 

--list devices > just list my nvidia devices
Does it work with --cuda-all-devices? yes, it works without my 2 amds
what is BITBY-RU-MODDED 6600xt? it's a custom VBIOS which I use for more than 1 year, it makes the cards have more hashrate.

**Comment by sp-hash** [comment]
Try with --all-platforms

**Comment by sepehrland** [comment]
> Try with --all-platforms
> 
> does the AMD cards work with --amd-only ?

sorry, I did not notice the first lines of --list devices, it contains my amd cards : 
Device Number: 0                                                                                                                                                        
    Device name: gfx1010:xnack-                                                                                                                                         
    PCIe bus id: 17                                                                                                                                                     
    opencl platform id: 1                                                                                                                                               
    Memory: 6GB                                                                                                                                                         


Device Number: 1                                                                                                                                                        
    Device name: gfx1010:xnack-                                                                                                                                         
    PCIe bus id: 9                                                                                                                                                      
    opencl platform id: 1                                                                                                                                               
    Memory: 6GB

**Comment by sepehrland** [comment]
> Try with --all-platforms
> 
> does the AMD cards work with --amd-only ?

all platforms not works,
and AMD cards not work with amd only

**Comment by sepehrland** [comment]
I flash my amd cards with original VBIOS, but it does not help.

**Comment by sp-hash** [comment]
should be fixed in the new version v1.63
