### ISSUE TITLE
中国用户需要用ssh服务器转发才能连接大部分矿池，tmb什么时候能支持。

### ISSUE THREAD

**Issue by tzl19930701** [sp-hash/TeamBlackMiner#284]
中国用户需要用ssh服务器转发才能连接大部分矿池，tmb什么时候能支持。

**Comment by sp-hash** [comment]
soon. perhaps this week.

**Comment by sp-hash** [comment]
Anonymous mining support added in  the latest release v1.63

**Comment by tzl19930701** [comment]
需要通过服务器转发才能连接，不是简单的ssl匿名

**Comment by sp-hash** [comment]
You can setup a local host file which point to a proxy pool, it will work as long as the proxypool connects to etheremine. 

ip adress

xxx.xxx.xxx.xxx eu.ethermine.org

**Comment by tzl19930701** [comment]
只能代理ethermine池吗？我试了一下flexpool代理不成功啊。

**Comment by tzl19930701** [comment]
![image](https://user-images.githubusercontent.com/95277712/167787695-9da283dd-09db-4af4-8008-03a2450d5e89.png)
这样对吗

**Comment by tzl19930701** [comment]
麻烦帮忙解决一下

**Comment by sp-hash** [comment]
use port 5555

:loop
	TBMiner --algo ethash --hostname eth-sg.flexpool.io --ssl --ssl-port 5555 --wallet %ETH_WALLET% --worker-name %computername%
	timeout 10
goto :loop

ip:
18.139.179.92
13.214.83.223 
?

**Comment by sp-hash** [comment]
![flexpool_ssl](https://user-images.githubusercontent.com/9572668/168012130-94a2e395-47b3-473e-aff5-b640ac720c49.png)

**Comment by tzl19930701** [comment]
可能是我没有表达清楚，我需要通过中国以外的vps转发才能连接矿池。比如我的vps地址是17.102.13.45，预先设置通过vps连接到矿池 eth-sg.flexpool.io，我需要在tbminer里直接填写vps的ip地址17.102.13.45。

**Comment by tzl19930701** [comment]
帮帮我



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sp-hash/TeamBlackMiner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sp-hash/TeamBlackMiner] 中国用户需要用ssh服务器转发才能连接大部分矿池，tmb什么时候能支持。 (Issue #284)
