### ISSUE TITLE
did support cuda driver 11.2 ?

### ISSUE THREAD

**Issue by REXX-dev** [sp-hash/TeamBlackMiner#285]
00:00:00 [2022-05-03 15:10:57.638] OpenCL driver version: 460.32
00:00:00 [2022-05-03 15:10:57.644] Cuda driver version: 11.2
00:00:00 [2022-05-03 15:10:57.644] Cuda runtime API version: 11.4
00:00:00 [2022-05-03 15:10:57.644]
00:00:00 [2022-05-03 15:10:57.644]
00:00:00 [2022-05-03 15:10:57.644]
00:00:00 [2022-05-03 15:10:57.644] Welcome to Team Black Miner 1.62
00:00:00 [2022-05-03 15:10:57.644]
00:00:00 [2022-05-03 15:10:57.644]
00:00:00 [2022-05-03 15:10:57.644] No devices are set
00:00:00 [2022-05-03 15:10:57.644] Shutting down threads
00:00:00 [2022-05-03 15:11:01.644] Exiting

**Comment by sp-hash** [comment]
no. cuda 11.4 or newer.

1.55 has a 11.3 bouild if it helps.
https://github.com/sp-hash/TeamBlackMiner/releases/tag/v1.55

**Comment by sp-hash** [comment]
v1.63 has been released with a build for cuda 11.3. This version will hash at full speed on the RTX 3060 LHR v1 with 370 the developer driver
