### ISSUE TITLE
Miner disconnects after ~30 minutes 

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#29]
There are no stale shares reported, but the miner continues to disconnect and reduce overall reported hashrate at the pool.

    35m [2021-09-20 11:51:31.143] us.woolypooly.com (ethash)    PING: 61ms    DIFFICULTY: 250.00 M    EPOCH: 442
    35m [2021-09-20 11:51:31.143]
    35m [2021-09-20 11:51:31.143]
    35m [2021-09-20 11:51:31.143] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    35m [2021-09-20 11:51:31.143] GPU0  3090    51/0    91      1647    10991   347     0.35    0.03USD
    35m [2021-09-20 11:51:31.143]                                               347     0.35    0.03USD
    35m [2021-09-20 11:51:31.143]
    35m [2021-09-20 11:51:31.143] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    35m [2021-09-20 11:51:31.143] GPU0  3090    Cuda    375.92 kH/W     130.44 MH/s     130.47 MH/s     62/0/0 (100.00)
    35m [2021-09-20 11:51:31.143]                       375.92 kH/s     130.44 MH/s     130.47 MH/s     62/0/0 (100.00)
    35m [2021-09-20 11:51:31.143]
    35m [2021-09-20 11:51:31.143]35m [2021-09-20 11:51:36.346] Job 43440b0592bd27d6
    35m [2021-09-20 11:51:37.991] GPU0 Solution found in 1.79s (Submit every 34.00 seconds)
    35m [2021-09-20 11:51:38.042] Accepted (63/63/0) Reply: 50ms
    35m [2021-09-20 11:51:43.175] Job 6b8c9e368ee84ea1
    35m [2021-09-20 11:51:50.349] Job 84acd4e818de2113
    35m [2021-09-20 11:51:56.215] GPU0 Solution found in 6.00s (Submit every 33.75 seconds)
    35m [2021-09-20 11:51:56.254] Accepted (64/64/0) Reply: 38ms
    35m [2021-09-20 11:51:57.354] Job a32a124503cf641c
    35m [2021-09-20 11:52:00.679] Job 127b7f1f20111a84
    35m [2021-09-20 11:52:00.855] Job fd78b98897322e66
**********
    35m [2021-09-20 11:52:01.013] Have not received data from pool for 3 min
    35m [2021-09-20 11:52:01.028] Pool connection disconnected or timed out
    35m [2021-09-20 11:52:01.028] Starting new stratum thread
**********
    35m [2021-09-20 11:52:03.309] GPU0 Solution found in 2.62s (Submit every 33.34 seconds)
    35m [2021-09-20 11:52:03.446] Accepted (65/65/0) Reply: 137ms
    35m [2021-09-20 11:52:03.834] Job 333149b5ea4909de
    35m [2021-09-20 11:52:04.010] Job df5afcb74ca988bd
    35m [2021-09-20 11:52:04.185] Job 923a836b9dbfbd10
    35m [2021-09-20 11:52:04.385] GPU0 Solution found in 0.35s (Submit every 32.85 seconds)
    35m [2021-09-20 11:52:04.733] Accepted (66/66/0) Reply: 347ms
    35m [2021-09-20 11:52:05.764] Job 7663489d3e1bc421
    35m [2021-09-20 11:52:05.939] Job 01e2f449746fe25c
    35m [2021-09-20 11:52:09.088] Job 81662869c3b97b30
    35m [2021-09-20 11:52:09.264] Job a7bc7f9d14351734
    35m [2021-09-20 11:52:11.713] Job e5961ac386e0adc4
    35m [2021-09-20 11:52:11.888] Job c310b29ec47fd3fa
    35m [2021-09-20 11:52:18.886] Job 8603d5778dd033c8

**Comment by sp-hash** [comment]
Might be an issue with this pool. we need to investegate.

**Comment by sp-hash** [comment]
Reproduced and fixed in v1.07
