### ISSUE TITLE
Verthash hashrate on TBMiner 1.64 (Windows) low for some cards

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#291]
Command line used:

TBMiner.exe --algo verthash --hostname verthash.mine.zergpool.com --port 4534 --wallet **********************************0 --server-passwd ****************,c=BTC,pl=0 --api --api-port 4001

00:00:00 [2022-06-24 19:04:47.605]
00:00:00 [2022-06-24 19:04:47.697] OpenCL driver version: 516.40
00:00:00 [2022-06-24 19:04:47.720] Cuda driver version: 11.7
00:00:00 [2022-06-24 19:04:47.720] Cuda runtime API version: 11.5
00:00:00 [2022-06-24 19:04:47.720]
00:00:00 [2022-06-24 19:04:47.720]
00:00:00 [2022-06-24 19:04:47.720]
00:00:00 [2022-06-24 19:04:47.720] Welcome to Team Black Miner 1.64
00:00:00 [2022-06-24 19:04:47.720]
00:00:00 [2022-06-24 19:04:47.720]
00:00:00 [2022-06-24 19:04:47.720] GPU0 gfx1010:xnack- added to miner as OpenCL device
00:00:00 [2022-06-24 19:04:47.720] GPU1 Ellesmere added to miner as OpenCL device
00:00:00 [2022-06-24 19:04:47.818] GPU2 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2022-06-24 19:04:47.864] GPU3 NVIDIA GeForce GT 1030 2GB added to miner as Cuda device
00:00:00 [2022-06-24 19:04:47.910] GPU4 NVIDIA GeForce GTX 750 Ti 2GB added to miner as Cuda device
00:00:00 [2022-06-24 19:04:47.910] Trying to read verthash data file from disk
00:00:00 [2022-06-24 19:04:48.262] Verthash data file has been loaded succesfully
00:00:00 [2022-06-24 19:04:53.176] Verthash data file has been verified succesfully
00:00:00 [2022-06-24 19:04:53.176] Trying verthash.mine.zergpool.com:4534 (verthash)
00:00:00 [2022-06-24 19:04:53.206] GPU0 Intensity set to 96
00:00:00 [2022-06-24 19:04:53.222] GPU1 Intensity set to 96
00:00:00 [2022-06-24 19:04:53.238] GPU2 Intensity set to 4096
00:00:00 [2022-06-24 19:04:53.241] GPU2 Load verthash data size 1283457024
00:00:00 [2022-06-24 19:04:53.254] GPU3 Intensity set to 4096
00:00:00 [2022-06-24 19:04:53.254] GPU3 Load verthash data size 1283457024
00:00:00 [2022-06-24 19:04:53.276] GPU4 Intensity set to 4096
00:00:00 [2022-06-24 19:04:53.277] Api server started at 127.0.0.1:4001
00:00:00 [2022-06-24 19:04:53.278] GPU4 Load verthash data size 1283457024
00:00:00 [2022-06-24 19:04:53.429] Pool responded successfully to extranonce subscribe
00:00:00 [2022-06-24 19:04:53.429] Pool responded successfully to authorize
00:00:00 [2022-06-24 19:04:53.429] Difficulty is set to 2.000000
00:00:00 [2022-06-24 19:04:53.730] GPU0 Load verthash data size 1283457024
00:00:00 [2022-06-24 19:04:53.904] GPU1 Load verthash data size 1283457024
00:00:00 [2022-06-24 19:04:54.254] GPU4 Verthash data loaded to gpu
00:00:00 [2022-06-24 19:04:54.255] Job d61c
00:00:00 [2022-06-24 19:04:54.255] GPU4 next target: 0000007fff800000
00:00:00 [2022-06-24 19:04:54.639] GPU3 Verthash data loaded to gpu
00:00:00 [2022-06-24 19:04:54.652] Job d61c
00:00:00 [2022-06-24 19:04:54.652] GPU3 next target: 0000007fff800000
00:00:00 [2022-06-24 19:04:59.874] GPU2 Verthash data loaded to gpu
00:00:00 [2022-06-24 19:04:59.874] Job d61c
00:00:00 [2022-06-24 19:04:59.874] GPU2 next target: 0000007fff800000
00:00:00 [2022-06-24 19:05:00.971] GPU0 Verthash data loaded to gpu
00:00:00 [2022-06-24 19:05:00.987] Job d61c
00:00:00 [2022-06-24 19:05:00.987] GPU0 next target: 0000007fff800000
00:00:00 [2022-06-24 19:05:01.794] GPU1 Verthash data loaded to gpu
00:00:00 [2022-06-24 19:05:01.795] Job d61c
00:00:00 [2022-06-24 19:05:01.795] GPU1 next target: 0000007fff800000
00:00:00 [2022-06-24 19:05:13.705] GPU2 Solution found in 20.29s (Submit every 26.11 seconds)
00:00:00 [2022-06-24 19:05:13.858] Accepted (1/1/0) Reply: 144ms
00:00:00 [2022-06-24 19:05:18.572] Job d61d
00:00:00 [2022-06-24 19:05:18.573] Job d61d
00:00:00 [2022-06-24 19:05:18.573] Job d61d
00:00:00 [2022-06-24 19:05:18.601] Job d61d
00:00:00 [2022-06-24 19:05:18.613] Job d61d
00:00:01 [2022-06-24 19:05:54.066] Job d61e
00:00:01 [2022-06-24 19:05:54.066] Job d61e
00:00:01 [2022-06-24 19:05:54.068] Job d61e
00:00:01 [2022-06-24 19:05:54.070] Job d61e
00:00:01 [2022-06-24 19:05:54.213] Job d61e
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625] mine.zergpool.com (verthash)    PING: 144ms    DIFFICULTY: 2.00     EPOCH: 0
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2022-06-24 19:05:54.625] GPU0    5700XT   OpenCL  0       96      0/0     46      2040    1840    0
00:00:01 [2022-06-24 19:05:54.625] GPU1    580S     OpenCL  0       96      0/0     0       0       0       0
00:00:01 [2022-06-24 19:05:54.625] GPU2    1660S    CUDA    0       0       56/0    47      1915    7413    73
00:00:01 [2022-06-24 19:05:54.625] GPU3    1030     CUDA    0       0       61/0    50      1906    3453    0
00:00:01 [2022-06-24 19:05:54.625] GPU4    750Ti    CUDA    0       0       49/0    45      1241    3274    11
00:00:01 [2022-06-24 19:05:54.625]                                                                          84
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
**00:00:01 [2022-06-24 19:05:54.625] GPU0    5700XT   0.00 H/W      _33.69 H/s_     34.95 H/s     0/0/0        100.00%**
**00:00:01 [2022-06-24 19:05:54.625] GPU1    580S     0.00 H/W      _27.17 H/s_     27.42 H/s     0/0/0        100.00%**
00:00:01 [2022-06-24 19:05:54.625] GPU2    1660S    5447.00 H/W   441.25 kH/s   442.73 kH/s   1/0/0        100.00%
00:00:01 [2022-06-24 19:05:54.625] GPU3    1030     0.00 H/W      89.61 kH/s    89.49 kH/s    0/0/0        100.00%
00:00:01 [2022-06-24 19:05:54.625] GPU4    750Ti    2207.00 H/W   28.70 kH/s    28.71 kH/s    0/0/0        100.00%
00:00:01 [2022-06-24 19:05:54.625]                  1530.00 H/W   559.62 kH/s   561.00 kH/s   1/0/0        100.00%
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:54.625] SHARES PER MINUTE: 1.00                              POOL HASHRATE: 143.17 MH/s
00:00:01 [2022-06-24 19:05:54.625]
00:00:01 [2022-06-24 19:05:58.913] GPU3 Solution found in 4.86s (Submit every 35.66 seconds)

**Comment by UselessGuru** [comment]
{
  "0": {
    "accepted": 1,
    "board_name": "AMD Radeon RX 5700 XT",
    "core_clock": 2040,
    "dag": false,
    "fan": 46,
    "gpu": 0,
    "gpu_temp": 0,
    "hashrate": 749,
    "mem_clock": 1840,
    "mem_temp": 0,
    "pcie_id": 9,
    "rejected": 0,
    "stale": 0,
    "type": "OpenCL",
    "watt": 0,
    "xintensity": 9600
  },
  "1": {
    "accepted": 0,
    "board_name": "Radeon RX 580 Series",
    "core_clock": 0,
    "dag": false,
    "fan": 0,
    "gpu": 1,
    "gpu_temp": 0,
    "hashrate": 504,
    "mem_clock": 0,
    "mem_temp": 0,
    "pcie_id": 1,
    "rejected": 0,
    "stale": 0,
    "type": "OpenCL",
    "watt": 0,
    "xintensity": 9600
  },

Gives me best speeds.
But I think reported values are 1000 too small.

**Comment by sp-hash** [comment]
yes. looks like a bug in the api. multiply by 1024

**Comment by cruelnovo** [comment]
Is this miner nvidia LHR unlocked for Verthash?

**Comment by sp-hash** [comment]
Yes But you need to start The Black Pill in the background
 
https://github.com/sp-hash/TheBlackPill

**Comment by UselessGuru** [comment]
Will these fixes be in 1.65?

**Comment by sp-hash** [comment]
yes. will release in a few days

**Comment by sp-hash** [comment]
v1.65 has been released now.
