### ISSUE TITLE
Nvidia GTX 750 (Windows): Error Cannot open nvidia-smi for gpu utilization information

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#292]
This is with v1.65.

Red warning message, but mining still works.

No error with GTX 1660 Super

**Comment by UselessGuru** [comment]
Red warning message, but mining still works.

**Comment by sp-hash** [comment]
reinstall the driver

**Comment by UselessGuru** [comment]
Just did. No change -> This is not the case.
GTX 1660 Super (same driver) does not show this. I assume it is a version problem (GTX 750 is quite old)
