### ISSUE TITLE
LHR unlock for Verthash possible?

### ISSUE THREAD

**Issue by SpellsPT** [sp-hash/TeamBlackMiner#295]
My 3060 Ti LHR V2 cards are getting 400ish kh/s VertHash, instead of the usual 1200 like a Non-LHR.
Is a LHR unlock possible?

**Comment by sp-hash** [comment]
run this program as admin in the backgroubd to get a 100% unlock:

https://github.com/sp-hash/TheBlackPill

**Comment by SpellsPT** [comment]
Any Solution for Linux (HiveOS)?

**Comment by sp-hash** [comment]
The black pill can be run on linux. you need to run it when the computer start.

**Comment by learning-is-nothing** [comment]
> Any Solution for Linux (HiveOS)?

did you find something ? same for me 3060 make 800 kh/s et beginning and after 1 min 359kh/s

**Comment by sp-hash** [comment]
https://www.reddit.com/r/vertcoin/comments/xhjcfx/mine_vtc_at_full_hashrate_on_hiveos_using_lhr/
