### ISSUE TITLE
Application has crashed

### ISSUE THREAD

**Issue by Jorgelote** [sp-hash/TeamBlackMiner#296]
Issue on linux hiveos, application has crashed and it never start mining eth i tried on different pools just in case but nothing,

**Comment by sp-hash** [comment]
what's your launch config? And version number

**Comment by Jorgelote** [comment]
last version and the launch config is the default by hiveos, if you try you will see that it happens even reinstall hiveos, it works on windows but not on hiveos, it says "Application has crashed" please solve it or if there is any command to solve the issue could you let me know which one?

**Comment by sp-hash** [comment]
perhaps you need to upgrade the driver? amd or nvidia cards?

**Comment by Jorgelote** [comment]
i tried mining with only amd or only nvidia, but no case, and on windows is not happening that, there has to be some file that crashes on hiveos

**Comment by sp-hash** [comment]
try to extract the logfile, so we can see whats happening

**Comment by Jorgelote** [comment]
please could you let me know how to extract the logfile? 
for the while i took a screenshot of the issue[](url
![failure](https://user-images.githubusercontent.com/104233747/177075600-6c7ac01e-dc87-4871-bd92-f7b57fa3ed32.PNG)
i don't know if the image is displayed but it says:
the application has crashed
a crash report is written to file crash_report.txt
teamblackminer exiited (exit code=0) waiting to cooldown a bit

**Comment by Jorgelote** [comment]
miner log says the same thing on the picture i have just checked

**Comment by sp-hash** [comment]
The gfx1012 (ryzen internal graphics) is probobly not supported, so you need to exclude it. --nvidia-only

**Comment by sp-hash** [comment]
is ethereum classic working? If you have little physical memory in your rig you might need to add swap memory

**Comment by Jorgelote** [comment]
I got the issue the amd latest driver of hiveos is not working on teamblackminer, but that should make people think that the miner is not working correctly and quickly change it to other one, you could check what is causing that the latest driver of amd is not working for the miner
Drivers: 21.40.1 not working on teamblackminer
Drivers: 20.40 working fine
There must be some issue with the miner regarding that driver that wasn't tested

**Comment by sp-hash** [comment]
We have released 1.66 and tested on the latest hiveos with the 6700xt and other cards and it works fine.
