### ISSUE TITLE
CMp 170hx

### ISSUE THREAD

**Issue by Tradition2** [sp-hash/TeamBlackMiner#297]
hey guys im tying to use CMp 170hx on TBM but im only getting 140mhs where i get 169 on nanominer should i use a specific version/driver

**Comment by sp-hash** [comment]
You should get 185MHASH

try --xintensity 9000 
and mine on the 2miners pool

**Comment by Tradition2** [comment]
weird im still only getting 140 
its using cuda 11.4 by default
![image](https://user-images.githubusercontent.com/32690039/177620652-6d3883b5-ec18-4941-bfd3-32b1cd57095e.png)

**Comment by Tradition2** [comment]
there u go kernel 2
![image](https://user-images.githubusercontent.com/32690039/177621505-0214ba6f-0f67-4c92-99ff-040092bfdbca.png)
![image](https://user-images.githubusercontent.com/32690039/177621537-22cc2eb7-0678-40f3-a563-ea39e15c14ea.png)

**Comment by sp-hash** [comment]
Try to reduce powerlimit to 190watt. (75%pl) coreclock 1080, memory 1450.


I would expect --kernel 12 to be the fastest

tor. 7. jul. 2022, 01:53 skrev Tradition2 ***@***.***>:

**Comment by Tradition2** [comment]
i cant oc their memory they wont accept

**Comment by sp-hash** [comment]
--lock-cclock [1250,1250,1250,1250,1250,1250,1250,1250]

?

tor. 7. jul. 2022, 02:04 skrev Tradition2 ***@***.***>:

**Comment by sp-hash** [comment]
or lower. lockibg coreclock to force lower voltage

**Comment by Tradition2** [comment]
im using hive i can lower to 1080 and my hs still 140mhs so there is something wierd

**Comment by Tradition2** [comment]
tried everything every kernel wont go above 140mhs

**Comment by sp-hash** [comment]
The cards svould be able to run on a higher
gher memclock than what you are using.

Memory Clock1458 MHz
2.9 Gbps effective

**Comment by Tradition2** [comment]
Yeah I wish I could increase but they are locked at 1215 can't really
increase

Em qua., 6 de jul. de 2022 21:46, sp-hash ***@***.***>
escreveu:

**Comment by sp-hash** [comment]
You can change to windows. v1.65 give 185mhash with oc

**Comment by sp-hash** [comment]
Try the cuda 11.5 build? a user has reported 185mhash on thia card

tor. 7. jul. 2022, 02:14 skrev Tradition2 ***@***.***>:
