### ISSUE TITLE
New release 1.66 for CUDA 11.x

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#299]
Could you please add some compiles for CUDA 11.5/11.6 too?

**Comment by sp-hash** [comment]
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

The cuda 11.7 build should be compatible with old drivers as well.

>=450.80.02  (linux)
 >=452.39 (windows)

**Comment by UselessGuru** [comment]
Any news on this?

**Comment by sp-hash** [comment]
1.67 is cuda 11.5
