### ISSUE TITLE
Device selection doesn't work

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#3]
The parameter `--cuda-devices` doesn't work. TBMiner uses all avail devices, always.

Using my testrig (1xGTX1070, 1xRTX3070, 1xINTEL), there is no way to select the GTX1070 (`--cuda-devices 0`) or the RTX3070 (`--cuda-devices 1`), only. TBMiner always starts mining to both of the GPUs.

**Comment by sp-hash** [comment]
use brackets around the selection --cuda-devices [1] or --cuda-devices [0,1]

**Comment by RainbowMiner** [comment]
Is this true for Linux, Windows and `--cl-devices`, as well?

**Comment by sp-hash** [comment]
yes
