### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by itsaLca** [sp-hash/TeamBlackMiner#30]
Hey, great miner, good job on this!

But one thing i stumbled upon is; CPU Usage. Its quite "high" compared to T-Rex, Gminer, and so on. It would be good to keep an eye on to reduce it.

**Comment by sp-hash** [comment]
On nvidia you can use --no-cpu , but some hashrate is lost. On AMD you can reduce it abit with a low --xintensity , but hashrate is lost.

**Comment by itsaLca** [comment]
Thanks! Now its at 0%, same Hashrate(s). <3
