### ISSUE TITLE
Does TBM mine ethereum full hashrate with LHR cards?

### ISSUE THREAD

**Issue by alptolga** [sp-hash/TeamBlackMiner#300]
I tried to see the performance of tbm but I couldn't mine with full speed  with lhr cards like the nbm or t-rex. I need information about it if it is possible.

edit:
After I open  black pill I started the tbm. I think it doesn't apply the overclock. and also I live problem to set the fan speed. here is are the logs.

00:00:05 [2022-08-14 18:41:08.246] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT   
00:00:05 [2022-08-14 18:41:08.246] GPU0    3060Ti   CUDA    13      284     61/0    30      1565    6994    93     
00:00:05 [2022-08-14 18:41:08.246] GPU1    3060Ti   CUDA    2       284     62/0    30      1582    6994    88     
00:00:05 [2022-08-14 18:41:08.246] GPU2    3060Ti   CUDA    2       284     57/0    60      1580    6994    92     
00:00:05 [2022-08-14 18:41:08.246] GPU3    3060Ti   CUDA    2       284     55/0    58      1587    6994    92     
00:00:05 [2022-08-14 18:41:08.246]                                                                          365    
00:00:05 [2022-08-14 18:41:08.246] 
00:00:05 [2022-08-14 18:41:08.246] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE    
00:00:05 [2022-08-14 18:41:08.246] GPU0    3060Ti   403.50 kH/W   54.88 MH/s    55.13 MH/s    1/0/0        100.00% 
00:00:05 [2022-08-14 18:41:08.246] GPU1    3060Ti   415.89 kH/W   54.90 MH/s    54.81 MH/s    1/0/0        100.00% 
00:00:05 [2022-08-14 18:41:08.246] GPU2    3060Ti   413.00 kH/W   54.93 MH/s    54.18 MH/s    4/0/0        100.00% 
00:00:05 [2022-08-14 18:41:08.246] GPU3    3060Ti   439.43 kH/W   54.93 MH/s    55.12 MH/s    2/0/0        100.00% 
00:00:05 [2022-08-14 18:41:08.246]                  417.95 kH/W   219.63 MH/s   219.24 MH/s   8/0/0        100.00% 
00:00:05 [2022-08-14 18:41:08.246]                                                                                 
00:00:05 [2022-08-14 18:41:08.246] SHARES PER MINUTE: 1.60				POOL HASHRATE: 114.53 MH/s
00:00:05 [2022-08-14 18:41:08.246] 
00:00:05 [2022-08-14 18:41:08.246] Fan speed is is below gpu fan speed limit 30
00:00:05 [2022-08-14 18:41:08.246] GPU0 Putting GPU to sleep for 30 seconds
00:00:05 [2022-08-14 18:41:08.246] Fan speed is is below gpu fan speed limit 30
00:00:05 [2022-08-14 18:41:08.246] GPU1 Putting GPU to sleep for 30 seconds
00:00:05 [2022-08-14 18:41:08.246] Fan speed is is below gpu fan speed limit 60
00:00:05 [2022-08-14 18:41:08.246] GPU2 Putting GPU to sleep for 30 seconds
00:00:05 [2022-08-14 18:41:08.246] Fan speed is is below gpu fan speed limit 58
00:00:05 [2022-08-14 18:41:08.246] GPU3 Putting GPU to sleep for 30 seconds

**Comment by sp-hash** [comment]
yes. But you need to run the BlackPiil in the background.

https://github.com/sp-hash/TheBlackPill/releases

**Comment by alptolga** [comment]
@sp-hash 
thanks for your answer. 
please can you give me detail about overckıck the memory. 
--lock-mclock [[8230,8230],[8230,8230],[8250,8250],[8180,8180]]
I use this for mem overclock but it didn't work.

**Comment by sp-hash** [comment]
The correct syntax inthe latest version is

--lock-mclock [8230,8230,8250,8180]
--lock-cclock [1250,1250,1250,1250]

but high clocks are not supported. So use another program to OC.

**Comment by alptolga** [comment]
it is not a good way using another program for oc. I have too many cards and all of their settings are different.

**Comment by sp-hash** [comment]
This is already an open issue. Should be easy to implement on linux.

https://github.com/sp-hash/TeamBlackMiner/issues/258
