### ISSUE TITLE
Support Ethermine 

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#31]
Hello it's possible to support pool ethermine ?

thank you

**Comment by binaryf** [comment]
Ethermine is supported.
Try the tbminer_ethermine_eth.bat start script.

**Comment by sp-hash** [comment]
But the submit hashrate bug is still not fixed. will be fixed in v1.08. Also you might want to run with --xintensity 32 or 64 on amd cards.

**Comment by MrNuTruT** [comment]
I have only Nvidia Card ! i wait the 1.08 version

**Comment by sp-hash** [comment]
submit hashrate on ethermine fixed in v1.08
