### ISSUE TITLE
New Kawpow release not working

### ISSUE THREAD

**Issue by Jorgelote** [sp-hash/TeamBlackMiner#315]
I have already tried on linux, and windows and the new kawpow release not working not even with flypool the one that uses teamblackminer by default, i have tried with 2miners too just in case
for windows is missing dll so i cannot even advance
and for linux 
00:00:00 [2022-10-12 04:04:29.148]                                                                                 
00:00:00 [2022-10-12 04:04:29.258] OpenCL driver version: 510.60
00:00:00 [2022-10-12 04:04:29.264] Cuda driver version: 11.6
00:00:00 [2022-10-12 04:04:29.264] Cuda runtime API version: 11.4
00:00:00 [2022-10-12 04:04:29.264] 
00:00:00 [2022-10-12 04:04:29.264]                                 
00:00:00 [2022-10-12 04:04:29.264] 
00:00:00 [2022-10-12 04:04:29.264] Welcome to Team Black Miner 1.70
00:00:00 [2022-10-12 04:04:29.264]                                 
00:00:00 [2022-10-12 04:04:29.264]  
00:00:00 [2022-10-12 04:04:29.342] GPU0 NVIDIA GeForce GTX 1660 Ti 6GB added to miner as Cuda device
00:00:00 [2022-10-12 04:04:29.463] GPU1 NVIDIA GeForce RTX 2060 SUPER 8GB added to miner as Cuda device
00:00:00 [2022-10-12 04:04:29.585] GPU2 NVIDIA GeForce RTX 3060 12GB added to miner as Cuda device
00:00:00 [2022-10-12 04:04:29.586] Trying stratum-ravencoin.flypool.org:3333 (kawpow)
00:00:00 [2022-10-12 04:04:29.590] Api server started at *
00:00:00 [2022-10-12 04:04:29.650] stratum-ravencoin.flypool.org did not reply to subscribe with pool version info
00:00:00 [2022-10-12 04:04:29.650] stratum-ravencoin.flypool.org did not reply to subscribe with pool version info
00:00:00 [2022-10-12 04:04:29.695] Pool responded successfully to extranonce subscribe
00:00:00 [2022-10-12 04:04:29.702] Pool responded successfully to authorize
00:00:00 [2022-10-12 04:04:29.702] Target is 00000009f5ffffffffffffffffffffffffffffffffffffffffffffffffffe570
00:00:00 [2022-10-12 04:04:29.706] Target is 00000009f5ffffffffffffffffffffffffffffffffffffffffffffffffffe570
00:00:00 [2022-10-12 04:04:29.908] GPU2 Starting generating kawpow dag (Epoch: 332)
00:00:00 [2022-10-12 04:04:29.908] GPU1 Starting generating kawpow dag (Epoch: 332)
00:00:00 [2022-10-12 04:04:29.908] GPU0 Starting generating kawpow dag (Epoch: 332)
then it jumps to crashfile.txt

**Comment by UselessGuru** [comment]
See https://github.com/sp-hash/TeamBlackMiner/issues/311 and

**Comment by UselessGuru** [comment]
Same error with NIceHash. Guess we have to wait for 1.71.
