### ISSUE TITLE
Submit delta time is incorrect when share solution time is very low

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#32]
Mixed AMD and NVidia rig mining with intensity of 97 using the following script results in incorrect submit every (x) seconds time.

**Script:**
```
Set ETH_WALLET=0x3dA6ccEb768DD3753945f75B0cd570****
:loop
	.\TBMiner --algo ethash --hostname pool.us.woolypooly.com --port 3096 --wallet %ETH_WALLET% --worker_name %1 --xintensity %2
	timeout 10
goto :loop
```

Result:
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:45.104] us.woolypooly.com (ethash)    PING: 42ms    DIFFICULTY: 268.44 M    EPOCH: 442
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:45.104] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    24m [2021-09-24 09:05:45.104] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    24m [2021-09-24 09:05:45.104] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    24m [2021-09-24 09:05:45.104] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    24m [2021-09-24 09:05:45.104] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    24m [2021-09-24 09:05:45.104] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    24m [2021-09-24 09:05:45.104] GPU5  2060    54/0    89      1830    7946    141     0.14    0.01USD
    24m [2021-09-24 09:05:45.104]                                               141     0.14    0.01USD
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:45.104] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    24m [2021-09-24 09:05:45.104] GPU0  6900XT  OpenCL  0.00 H/W        65.98 MH/s      66.05 MH/s      26/0/2 (100.00)
    24m [2021-09-24 09:05:45.104] GPU1  6800XT  OpenCL  0.00 H/W        67.51 MH/s      67.70 MH/s      37/0/2 (100.00)
    24m [2021-09-24 09:05:45.104] GPU2  6800XT  OpenCL  0.00 H/W        67.47 MH/s      67.92 MH/s      13/0/0 (100.00)
    24m [2021-09-24 09:05:45.104] GPU3  6800    OpenCL  0.00 H/W        67.19 MH/s      67.22 MH/s      14/0/1 (100.00)
    24m [2021-09-24 09:05:45.104] GPU4  6800XT  OpenCL  0.00 H/W        67.47 MH/s      67.46 MH/s      17/0/1 (100.00)
    24m [2021-09-24 09:05:45.104] GPU5  2060    Cuda    323.23 kH/W     45.57 MH/s      45.57 MH/s      9/0/2 (100.00)
    24m [2021-09-24 09:05:45.104]                       323.23 kH/s     381.19 MH/s     381.92 MH/s     116/0/8 (100.00)
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:45.104]
    24m [2021-09-24 09:05:58.841] Job a4872e9e64240329
    24m [2021-09-24 09:06:10.612] Job 858fdae0dcafd555
    24m [2021-09-24 09:06:11.264] GPU3 Solution found in 0.88s (Submit every 12.33 seconds)
    24m [2021-09-24 09:06:11.308] Accepted (117/117/8) Reply: 43ms
    24m [2021-09-24 09:06:15.343] GPU0 Solution found in 4.96s (Submit every 12.30 seconds)
    24m [2021-09-24 09:06:15.388] Accepted (118/118/8) Reply: 45ms
    24m [2021-09-24 09:06:17.903] Job 1641fa8d1534bc51
    24m [2021-09-24 09:06:18.414] Job fabfd2eaeab72cec
    24m [2021-09-24 09:06:18.865] GPU2 Solution found in 0.62s (Submit every 12.32 seconds)
    24m [2021-09-24 09:06:18.910] Accepted (119/119/8) Reply: 44ms
    24m [2021-09-24 09:06:19.438] Job 4876376373857dbd
    24m [2021-09-24 09:06:19.950] Job 50c11d209e7164cd
    24m [2021-09-24 09:06:20.974] Job e858995e111d0564
    24m [2021-09-24 09:06:21.997] Job 98a67d87fbbc27f4
    24m [2021-09-24 09:06:23.021] Job a0dd7d3f0ca5214d
    24m [2021-09-24 09:06:24.045] Job 0bc316b69ce5ea98
    24m [2021-09-24 09:06:25.068] Job 1dfdc3c48f45097f
    24m [2021-09-24 09:06:26.092] Job e936ea78a12ffd5e
   ****************Normal**************** 

    24m [2021-09-24 09:06:26.497] GPU5 Solution found in 0.54s (Submit every 12.36 seconds)
    
******************Abnormal*************
    24m [2021-09-24 09:06:26.498] GPU0 Solution found in 0.54s (Submit every 192153584101153.12 seconds)
 ...   
    24m [2021-09-24 09:06:26.542] Accepted (120/120/8) Reply: 44ms
    24m [2021-09-24 09:06:26.558] Accepted (121/121/8) Reply: 59ms
    24m [2021-09-24 09:06:28.034] Job 83b7e886334e3ca3
    24m [2021-09-24 09:06:29.058] Job 77eb40b3ad791d9e
    24m [2021-09-24 09:06:31.105] Job a872157ded72fba1
    24m [2021-09-24 09:06:32.129] Job 99146d3e79a86a49
    24m [2021-09-24 09:06:32.202] GPU1 Solution found in 0.35s (Submit every 192153584101153.16 seconds)
    24m [2021-09-24 09:06:32.251] Accepted (122/122/8) Reply: 48ms
    24m [2021-09-24 09:06:34.176] Job 1a4650fca5dad445
    24m [2021-09-24 09:06:35.119] GPU0 Solution found in 1.28s (Submit every 192153584101153.12 seconds)
    24m [2021-09-24 09:06:35.119] Job f9447525dd145298
    24m [2021-09-24 09:06:35.152] Accepted (123/123/8) Reply: 33ms
    24m [2021-09-24 09:06:35.908] GPU5 Solution found in 0.88s (Submit every 192153584101153.09 seconds)
    24m [2021-09-24 09:06:35.944] Accepted (124/124/8) Reply: 35ms
    24m [2021-09-24 09:06:36.143] Job c010a3a27e863513
    24m [2021-09-24 09:06:37.166] Job a110011daabfe2e4
    24m [2021-09-24 09:06:38.190] Job 296d5c52e98886a5
    24m [2021-09-24 09:06:38.702] Job 1668de7b55df3e2c
    24m [2021-09-24 09:06:40.749] Job 59887a52a20fb8fe
    24m [2021-09-24 09:06:41.773] Job f5f2dbc4ea9b6ee7
    24m [2021-09-24 09:06:42.285] Job 55b5e147915beacc
    24m [2021-09-24 09:06:43.308] Job a6eafc80739bfef0
    24m [2021-09-24 09:06:43.820] Job 598887928a6b68f6
    24m [2021-09-24 09:06:44.844] Job 6ac2a53a25181647
    24m [2021-09-24 09:06:45.868] Job ce96a4add9ff696b
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103] us.woolypooly.com (ethash)    PING: 41ms    DIFFICULTY: 268.44 M    EPOCH: 442
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    25m [2021-09-24 09:06:46.103] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    25m [2021-09-24 09:06:46.103] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    25m [2021-09-24 09:06:46.103] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    25m [2021-09-24 09:06:46.103] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    25m [2021-09-24 09:06:46.103] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    25m [2021-09-24 09:06:46.103] GPU5  2060    54/0    89      1833    7946    140     0.14    0.01USD
    25m [2021-09-24 09:06:46.103]                                               140     0.14    0.01USD
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    25m [2021-09-24 09:06:46.103] GPU0  6900XT  OpenCL  0.00 H/W        66.64 MH/s      66.41 MH/s      29/0/2 (100.00)
    25m [2021-09-24 09:06:46.103] GPU1  6800XT  OpenCL  0.00 H/W        67.50 MH/s      67.68 MH/s      38/0/2 (100.00)
    25m [2021-09-24 09:06:46.103] GPU2  6800XT  OpenCL  0.00 H/W        67.47 MH/s      67.95 MH/s      14/0/0 (100.00)
    25m [2021-09-24 09:06:46.103] GPU3  6800    OpenCL  0.00 H/W        67.19 MH/s      67.49 MH/s      15/0/1 (100.00)
    25m [2021-09-24 09:06:46.103] GPU4  6800XT  OpenCL  0.00 H/W        67.47 MH/s      67.46 MH/s      17/0/1 (100.00)
    25m [2021-09-24 09:06:46.103] GPU5  2060    Cuda    325.53 kH/W     45.57 MH/s      45.57 MH/s      11/0/2 (100.00)
    25m [2021-09-24 09:06:46.103]                       325.53 kH/s     381.84 MH/s     382.56 MH/s     124/0/8 (100.00)
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.103]
    25m [2021-09-24 09:06:46.892] Job 76b00f728b974349
    25m [2021-09-24 09:06:47.915] Job c46c5bf3b70b3027
    25m [2021-09-24 09:06:48.939] Job ec4819434740ae10
    25m [2021-09-24 09:06:50.987] Job d0c95bfdbed63cbb
    25m [2021-09-24 09:06:51.670] GPU0 Solution found in 0.89s (Submit every 192153584101153.22 seconds)
    25m [2021-09-24 09:06:51.705] Accepted (125/125/8) Reply: 35ms
    25m [2021-09-24 09:06:53.205] Job 8a5f7e5ffc2abadb
    25m [2021-09-24 09:06:54.229] Job 5801edcc607d2b4a
    25m [2021-09-24 09:06:55.253] Job 80f78692fbcaf431
    25m [2021-09-24 09:06:56.276] Job 2e2f67620163f663
    25m [2021-09-24 09:06:56.788] Job 0b483f0f65a6a3a8
    25m [2021-09-24 09:06:57.812] Job 81195ad204578c99
    25m [2021-09-24 09:06:59.254] GPU0 Solution found in 1.45s (Submit every 192153584101153.25 seconds)
    25m [2021-09-24 09:06:59.291] Accepted (126/126/8) Reply: 36ms
    25m [2021-09-24 09:06:59.727] GPU5 Solution found in 1.92s (Submit every 192153584101153.00 seconds)
    25m [2021-09-24 09:06:59.766] Job 40c41ba97f407cda
    25m [2021-09-24 09:06:59.772] Accepted (127/127/8) Reply: 45ms
    25m [2021-09-24 09:07:01.302] Job 02eee24ed561ff33
    25m [2021-09-24 09:07:03.154] GPU5 Solution found in 2.31s (Submit every 192153584101153.00 seconds)
    25m [2021-09-24 09:07:03.185] Accepted (128/128/8) Reply: 30ms
    25m [2021-09-24 09:07:03.349] Job 53e259a65c54ee2a
    25m [2021-09-24 09:07:04.145] GPU0 Solution found in 1.00s (Submit every 192153584101153.00 seconds)
    25m [2021-09-24 09:07:04.178] Accepted (129/129/8) Reply: 32ms

**Comment by sp-hash** [comment]
fixed in v1.08
