### ISSUE TITLE
Add Pool

### ISSUE THREAD

**Issue by Andozzz** [sp-hash/TeamBlackMiner#322]
This pool is not working for mining Vertcoin:  ( https://miningpoolsweden.eu
Server URLs: stratum+tcp://vtc.miningpoolsweden.eu:3052  And also port 3053

Miner:   teamblackminer
Version: 1.72-cuda115
00:00:00 [2022-10-29 13:36:46.896] Sorry the provided pool is not supported
00:00:00 [2022-10-29 13:36:46.896] If you think this pool should be, then ask us to configure it

**Comment by sp-hash** [comment]
fixed in 1.73
