### ISSUE TITLE
Verthash: miner API is not listening meanwhile building dat file

### ISSUE THREAD

**Issue by Funereal** [sp-hash/TeamBlackMiner#323]
I'm using Minerstat with your miner to mine Vertcoin. When I first start the miner it is generating Verthash.dat, the problem is that since the Miner API is not listening until the mining process begin (so is not listening during de generation of the verthash.dat file), minerstat will try to reset the software because it sees that the rig is at idle.

Minerstat dev told me this: "they should just move few lines of code up to start API when miner starts not when miner is mining.
Easy 5 minute fix on their end"

As a quick fix, I have to put my rig in maintenance mode to desactivate all automatic behaviour of minerstat and manually start the starth.bash file to generate the verthash.dat file in full.

**Comment by sp-hash** [comment]
The verthash.dat file is a static file that is only created once. Instead of creating it you can copy it from an already working instance. Or you can use the option to load the file from a network path.

**Comment by Funereal** [comment]
I know I can do this, but I shouldn't have to do this. I should be able to just run the miner and let it do his job.

If I understand right, you tell me that it is normal behaviour that the API is not listening while building dat file?

**Comment by Funereal** [comment]
Could you just make it so that the API start sooner? Like before the building of Verthash.dat file? It would fix the issue and would be easy to fix in the code (from what Minerstat devs are telling me)
