### ISSUE TITLE
Sometime, miner will try to build Verthash.dat file again even if it's already there

### ISSUE THREAD

**Issue by Funereal** [sp-hash/TeamBlackMiner#324]
Sometime, miner will try to build Verthash.dat even if it's already there.

I'm on Minerstat OS (Linux)

At first, the problem was that for some reason, when miner was stopped to switched to another miner/algo or for a reboot, or whatever, teamblackminer would break/corrupt verthash.dat file. It is not a thing that happens 100% of the time, but enough often that it's a hassle. So, the miner would restart for an infinite time because it wasn't able to read the verthash.dat because it detects it has "bad" like if it was corrupted.

To "fix" this issue, I made the verthash.dat file "read only", so that nothing can corrupt/damage it. It works. But, sometime, after a miner restart, teamblack miner would try to build the Verthash.dat file again instead of just reading the one in the SSD. It would show a Segmentation fault in miner. Minerstat devs says that "Segmentation fault means software error, unhandled exception happend in the miner in this case: teamblackminer"

This is like a 2 in 1 issue. There is something that sometime corrupt/damage verthash.dat file when miner is closed. And when we put the file in read only to "fix" this issue, sometime the miner will try to build again the verthash.dat file instead of just reading it. A reboot will fix the issue and teamblack miner will read the undamaged verthash.dat file.

See attached image

![image](https://user-images.githubusercontent.com/105163385/199252711-0c0435f4-0b2f-4b8a-a729-83338a7b079f.png)

**Comment by sp-hash** [comment]
fixed in 1.72
