### ISSUE TITLE
nvcuda.dll not found

### ISSUE THREAD

**Issue by toumby** [sp-hash/TeamBlackMiner#329]
![image](https://user-images.githubusercontent.com/85160490/206407095-eff2fc55-f1ec-4fe5-88ee-f99c721ead0f.png)

I have set all according to how_to.
i am trying 1_75_cuda_11_8. Also installed the cuda 11.8 stuff.
But still getting this error regarding nvcuda.dll.

Tried at Windows 10 Pro OS.

**Comment by sp-hash** [comment]
You need to install the latest driver from nvidia.

https://www.nvidia.com/download/index.aspx
