### ISSUE TITLE
Implement Dual mining for VTC? 

### ISSUE THREAD

**Issue by Funereal** [sp-hash/TeamBlackMiner#332]
Hi, could you consider developping dual mining for VTC? Maybe something like VTC+Kaspa or VTC+RXD or VTC+ALPH.

VTC is memory intensive and those other algo are core intensive, maybe it would be possible to dual mine them with VTC as we can with Ergo and ETC.

No other miner propose dual mining with VTC and personally I would be very interested into this

**Comment by sp-hash** [comment]
We have added VTC+ZIL and VTC+ETC+ZIL in v1.81

**Comment by sp-hash** [comment]
RVN+ZIL is coming soon. We will add dual support for all the algos we include in the future.
