### ISSUE TITLE
v1.80: How to dual mine etc+vtc with SSL ?

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#334]
As per title.
I'd expect something like

TeamBlackMiner-v1.80\TBMiner.exe --algo etc+vtc --hostname etc.hiveon.com --wallet ############################.########## --ssl --ssl-verify-none --ssl-port 20443 --server-passwd x --vtc-hostname etc.hiveon.com --vtc-wallet ########################.######### **--vtc-ssl --vtc-ssl-verify-none --vtc-ssl-port 20443** --api --api-port 4006 --cuda-devices [1]

**Comment by sp-hash** [comment]
SSL with +vtc has some issues on the verthash ssl so we have disabled it. Needs more work. But I think the etc+zil ssl should work

**Comment by UselessGuru** [comment]
Supported in 1.82??
If so, what are the correct parameters?

**Comment by UselessGuru** [comment]
Will this be supported in the upcoming 1.84?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Semi-optimal solution provided with 1.85 (Why do BOTH pools have to use SSL (or both not)?
