### ISSUE TITLE
TBMiner in Hiveos

### ISSUE THREAD

**Issue by Andozzz** [sp-hash/TeamBlackMiner#337]
Hi it did work before but since i reinstalled HiveOS and started up whith newest upgrade 0.6-220@230120
Iam getting error on TBMiner, Latest in HiveOS V 1.80
![TBMiner kaputt](https://user-images.githubusercontent.com/116953479/213880283-8a4d122e-6da1-4194-b8e7-ef114f265689.jpg)

**Comment by sp-hash** [comment]
in hiveos use the cuda11_6 build. Or you have to upgrade the driver
