### ISSUE TITLE
how to add another pool?

### ISSUE THREAD

**Issue by NeddZeplin** [sp-hash/TeamBlackMiner#338]
g'day guys
great work you're doing
I wasn't sure how to otherwise contact you regarding the addition of another mining pool for VTC, it's only a small one, but I find it handy
stratum+tcp://vtc-ca.javerity.com:9171
let me know if ya need any other info, tho' I'm sure you'll be able to suss it out
cheers

**Comment by sp-hash** [comment]
pool added in 1.81
