### ISSUE TITLE
Pool still times out

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#34]
(A)
    

    70m [2021-09-24 10:39:45.836] GPU5 Solution found in 12.41s (Submit every 12.39 seconds)
    70m [2021-09-24 10:39:46.209] GPU4 Solution found in 12.78s (Submit every 12.23 seconds)
    70m [2021-09-24 10:40:04.536] GPU5 Solution found in 31.11s (Submit every 12.26 seconds)
    70m [2021-09-24 10:40:17.459] GPU4 Solution found in 44.03s (Submit every 12.25 seconds)
    70m [2021-09-24 10:40:18.347] GPU3 Solution found in 44.92s (Submit every 12.21 seconds)
    70m [2021-09-24 10:40:22.144] GPU0 Solution found in 48.71s (Submit every 11.98 seconds)
    70m [2021-09-24 10:40:28.142] GPU3 Solution found in 54.71s (Submit every 11.52 seconds)
    70m [2021-09-24 10:40:31.273] GPU3 Solution found in 57.84s (Submit every 11.52 seconds)
    70m [2021-09-24 10:40:35.726] GPU3 Solution found in 62.29s (Submit every 11.53 seconds)
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154] us.woolypooly.com (ethash)    PING: 39ms    DIFFICULTY: 268.44 M    EPOCH: 442
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    71m [2021-09-24 10:40:44.154] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    71m [2021-09-24 10:40:44.154] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    71m [2021-09-24 10:40:44.154] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    71m [2021-09-24 10:40:44.154] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    71m [2021-09-24 10:40:44.154] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    71m [2021-09-24 10:40:44.154] GPU5  2060    53/0    89      1824    7946    136     0.14    0.01USD
    71m [2021-09-24 10:40:44.154]                                               136     0.14    0.01USD
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    71m [2021-09-24 10:40:44.154] GPU0  6900XT  OpenCL  0.00 H/W        65.83 MH/s      66.35 MH/s      56/0/4 (100.00)
    71m [2021-09-24 10:40:44.154] GPU1  6800XT  OpenCL  0.00 H/W        67.50 MH/s      67.50 MH/s      67/0/4 (100.00)
    71m [2021-09-24 10:40:44.154] GPU2  6800XT  OpenCL  0.00 H/W        67.51 MH/s      67.51 MH/s      56/0/1 (100.00)
    71m [2021-09-24 10:40:44.154] GPU3  6800    OpenCL  0.00 H/W        67.99 MH/s      68.09 MH/s      65/0/2 (100.00)
    71m [2021-09-24 10:40:44.154] GPU4  6800XT  OpenCL  0.00 H/W        67.49 MH/s      67.90 MH/s      68/0/6 (100.00)
    71m [2021-09-24 10:40:44.154] GPU5  2060    Cuda    335.07 kH/W     45.57 MH/s      45.57 MH/s      41/0/1 (100.00)
    71m [2021-09-24 10:40:44.154]                       335.07 kH/s     381.89 MH/s     382.92 MH/s     353/0/18 (100.00)
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:40:44.154]
    71m [2021-09-24 10:41:03.315] GPU4 Solution found in 89.88s (Submit every 11.38 seconds)
    71m [2021-09-24 10:41:09.655] GPU1 Solution found in 96.22s (Submit every 11.44 seconds)
    71m [2021-09-24 10:41:14.672] GPU1 Solution found in 101.24s (Submit every 11.02 seconds)
    71m [2021-09-24 10:41:27.221] GPU1 Solution found in 113.79s (Submit every 11.14 seconds)
    71m [2021-09-24 10:41:27.683] GPU4 Solution found in 114.25s (Submit every 10.76 seconds)
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:45.165] us.woolypooly.com (ethash)    PING: 39ms    DIFFICULTY: 268.44 M    EPOCH: 442
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:45.165] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    72m [2021-09-24 10:41:45.165] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    72m [2021-09-24 10:41:45.165] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    72m [2021-09-24 10:41:45.165] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    72m [2021-09-24 10:41:45.165] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    72m [2021-09-24 10:41:45.165] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    72m [2021-09-24 10:41:45.165] GPU5  2060    55/0    89      1820    7946    141     0.14    0.01USD
    72m [2021-09-24 10:41:45.165]                                               141     0.14    0.01USD
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:45.165] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    72m [2021-09-24 10:41:45.165] GPU0  6900XT  OpenCL  0.00 H/W        65.82 MH/s      66.14 MH/s      56/0/4 (100.00)
    72m [2021-09-24 10:41:45.165] GPU1  6800XT  OpenCL  0.00 H/W        67.50 MH/s      68.35 MH/s      67/0/4 (100.00)
    72m [2021-09-24 10:41:45.165] GPU2  6800XT  OpenCL  0.00 H/W        67.50 MH/s      67.46 MH/s      56/0/1 (100.00)
    72m [2021-09-24 10:41:45.165] GPU3  6800    OpenCL  0.00 H/W        67.22 MH/s      67.18 MH/s      65/0/2 (100.00)
    72m [2021-09-24 10:41:45.165] GPU4  6800XT  OpenCL  0.00 H/W        67.50 MH/s      67.59 MH/s      68/0/6 (100.00)
    72m [2021-09-24 10:41:45.165] GPU5  2060    Cuda    323.23 kH/W     45.58 MH/s      45.57 MH/s      41/0/1 (100.00)
    72m [2021-09-24 10:41:45.165]                       323.23 kH/s     381.12 MH/s     382.29 MH/s     353/0/18 (100.00)
    72m [2021-09-24 10:41:45.165]
    72m [2021-09-24 10:41:52.935] GPU2 Solution found in 139.50s (Submit every 10.86 seconds)
    72m [2021-09-24 10:42:06.375] GPU4 Solution found in 152.94s (Submit every 10.51 seconds)
    72m [2021-09-24 10:42:13.408] GPU4 Solution found in 159.98s (Submit every 10.51 seconds)
*******************************************

    72m [2021-09-24 10:42:38.007] Have not received data from pool for 3 min
    72m [2021-09-24 10:42:38.007] Have not received data from pool for 3 min
    72m [2021-09-24 10:42:38.007] Stratum thread exited
    72m [2021-09-24 10:42:38.022] Pool connection disconnected or timed out
    72m [2021-09-24 10:42:38.022] Starting new stratum thread
    72m [2021-09-24 10:42:38.023] Pool connection disconnected or timed out
    72m [2021-09-24 10:42:38.023] Starting new stratum thread
    72m [2021-09-24 10:42:39.389] GPU4 Solution found in 185.96s (Submit every 10.68 seconds)
    72m [2021-09-24 10:42:39.389] Not authorized. Cannot submit solution
    72m [2021-09-24 10:42:39.790] GPU1 Solution found in 186.36s (Submit every 10.93 seconds)
    72m [2021-09-24 10:42:39.790] Not authorized. Cannot submit solution
    72m [2021-09-24 10:42:45.135] Trying pool.us.woolypooly.com:3096 (ethash)
    72m [2021-09-24 10:42:45.174] Pool responded successfully to subscribe

*******************************************
    72m [2021-09-24 10:42:45.523] Job b1640370e7bc63c6
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103] us.woolypooly.com (ethash)    PING: 39ms    DIFFICULTY: 268.44 M    EPOCH: 442
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    73m [2021-09-24 10:42:46.103] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    73m [2021-09-24 10:42:46.103] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    73m [2021-09-24 10:42:46.103] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    73m [2021-09-24 10:42:46.103] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    73m [2021-09-24 10:42:46.103] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    73m [2021-09-24 10:42:46.103] GPU5  2060    54/0    89      1829    7946    136     0.14    0.01USD
    73m [2021-09-24 10:42:46.103]                                               136     0.14    0.01USD
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    73m [2021-09-24 10:42:46.103] GPU0  6900XT  OpenCL  0.00 H/W        65.82 MH/s      65.76 MH/s      56/0/4 (100.00)
    73m [2021-09-24 10:42:46.103] GPU1  6800XT  OpenCL  0.00 H/W        68.28 MH/s      67.55 MH/s      67/0/4 (100.00)
    73m [2021-09-24 10:42:46.103] GPU2  6800XT  OpenCL  0.00 H/W        67.51 MH/s      67.45 MH/s      56/0/1 (100.00)
    73m [2021-09-24 10:42:46.103] GPU3  6800    OpenCL  0.00 H/W        67.21 MH/s      67.11 MH/s      65/0/2 (100.00)
    73m [2021-09-24 10:42:46.103] GPU4  6800XT  OpenCL  0.00 H/W        69.33 MH/s      67.94 MH/s      68/0/6 (100.00)
    73m [2021-09-24 10:42:46.103] GPU5  2060    Cuda    335.18 kH/W     45.58 MH/s      45.55 MH/s      41/0/1 (100.00)
    73m [2021-09-24 10:42:46.103]                       335.18 kH/s     383.73 MH/s     381.37 MH/s     353/0/18 (100.00)
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:46.103]
    73m [2021-09-24 10:42:47.840] GPU3 Solution found in 2.62s (Submit every 11.24 seconds)
    73m [2021-09-24 10:42:47.889] Accepted (354/354/18) Reply: 48ms
    73m [2021-09-24 10:42:54.246] Job 6a2f838252eaf4de
    73m [2021-09-24 10:43:11.180] Job 5931b4740795ac51
    73m [2021-09-24 10:43:12.515] GPU2 Solution found in 1.46s (Submit every 11.38 seconds)
    73m [2021-09-24 10:43:12.555] Accepted (355/355/19) Reply: 39ms
    73m [2021-09-24 10:43:12.720] Job e74b30ecbb3fabca

(B)
    90m [2021-09-24 11:00:46.246] Job 032774779c8ba1bc
    90m [2021-09-24 11:00:46.759] Job 48161eae8d3d9546
    90m [2021-09-24 11:00:47.785] Job 2a02859044a8839c
    90m [2021-09-24 11:00:48.812] Job dbc8d2d17ba01d0f

    90m [2021-09-24 11:00:49.015] Have not received data from pool for 3 min
    90m [2021-09-24 11:00:49.030] Pool connection disconnected or timed out
  
   90m [2021-09-24 11:00:49.030] Starting new stratum thread
    90m [2021-09-24 11:00:49.839] Job 373c086f0b420ffc
    90m [2021-09-24 11:00:50.865] Job 264fcd97e8e62001
    90m [2021-09-24 11:00:52.405] Job e1dcf24f8fdec16c
    90m [2021-09-24 11:00:53.431] Job 536a25e7088e30b9

**Comment by sp-hash** [comment]
Your stale count is over 5%, Some pools throw you off if the stale share count is over 5%. Lower the xintensity

**Comment by KillrBee** [comment]
I'm not exactly sure how the stale shares are calculated in the miner, but I've had wooly kick me out with a specific "Stale Share submitted - Shutting down connection" message, so I'm not sure this is related to stale shares (I think I got disconnected earlier with ~130 submitted and 2 stales reported by the miner.  I'll monitor this and provide further details if I see a case where there are low stale % and I still get disconnected and provide the poolside error if it shuts me down with a "stale share" message.

**Comment by sp-hash** [comment]
Problem reproduced and fixed in v1.09
