### ISSUE TITLE
invalid json from api summary endpoint

### ISSUE THREAD

**Issue by dexmar** [sp-hash/TeamBlackMiner#341]
Hi, I am using ver 1.82 on windows and pulling data from the api /summary. The data returned is invalid json. I tried the recommendation in #321 to set --api-version 1.4 but that does not enable the api. 

Appreciate any help.

Thank you

**Comment by sp-hash** [comment]
Can  you try 1.83 with --api --api-version 1.4

**Comment by dexmar** [comment]
Works perfectly now. Thank you!
