### ISSUE TITLE
v1.83 (Windows): Errors mining EtcHash & Ethash@ProHashing pool

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#343]
TeamBlackMiner-v1.83\TBMiner.exe --algo etchash --hostname EU.mining.prohashing.com --wallet ##############--port 3357 --server-passwd a=etchash,e=off,n=########,o=########### --api --api-version 1.4 --api-port 4001 --cl-devices [0]
00:00:00 [2023-01-31 17:42:40.202]
00:00:00 [2023-01-31 17:42:40.270] OpenCL driver version: 527.56
00:00:00 [2023-01-31 17:42:40.289] Cuda driver version: 12.0
00:00:00 [2023-01-31 17:42:40.289] Cuda runtime API version: 12.0
00:00:00 [2023-01-31 17:42:40.289]
00:00:00 [2023-01-31 17:42:40.289]
00:00:00 [2023-01-31 17:42:40.289]
00:00:00 [2023-01-31 17:42:40.289] Welcome to Team Black Miner 1.83
00:00:00 [2023-01-31 17:42:40.289]
00:00:00 [2023-01-31 17:42:40.289]
00:00:00 [2023-01-31 17:42:40.289] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-01-31 17:42:40.289] Api server started at 127.0.0.1:4001
00:00:00 [2023-01-31 17:42:40.289] GPU0 Started CL work thread
00:00:00 [2023-01-31 17:42:40.289] GPU0 Starting generating zil dag (Epoch: 0)
00:00:00 [2023-01-31 17:42:40.289] Trying EU.mining.prohashing.com:3357 (etchash)
00:00:00 [2023-01-31 17:42:40.387] Pool responded successfully to subscribe
00:00:00 [2023-01-31 17:42:40.387] Difficulty is set to 0.250000
00:00:00 [2023-01-31 17:42:40.450] **mining.extranonce.subscribe: Pool reponded with error**
00:00:00 [2023-01-31 17:42:40.465] Pool responded successfully to authorize
00:00:00 [2023-01-31 17:42:42.945] GPU0 DAG generated in 2.65 seconds (1048574kb)
00:00:00 [2023-01-31 17:42:47.977] GPU0 XIntensity set to Dynamic
00:00:00 [2023-01-31 17:42:48.009] GPU0 Starting generating etchash dag (Epoch: 280)
00:00:00 [2023-01-31 17:42:54.806] GPU0 DAG generated in 6.82 seconds (3342335kb)
00:00:00 [2023-01-31 17:42:54.806] GPU0 XIntensity set to Dynamic
00:00:00 [2023-01-31 17:42:55.337] GPU0 Dag buffer verified ok!
00:00:00 [2023-01-31 17:43:02.572] ETCHASH: GPU0 Rejected (0/1/0) Reply: 62ms
00:00:00 [2023-01-31 17:43:02.572] **mining.submit: Pool reponded with error**
00:00:00 [2023-01-31 17:43:02.572] **Error(-2): The submitted share's difficulty of 1.38446526437e-09 is too easy; a single difficulty of 0.25 allowed for this algorithm|1.38446526437e-09**
00:00:00 [2023-01-31 17:43:05.792] Job a0f0f80a
00:00:00 [2023-01-31 17:43:18.967] Job a0f0f843
00:00:00 [2023-01-31 17:43:26.907] ETCHASH: GPU0 Accepted (1/2/0) Reply: 625ms

Same with Ethash

**Comment by sp-hash** [comment]
fixed in 1.84
