### ISSUE TITLE
v1.83 windows: Verthash@ZPool not working

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#344]
TeamBlackMiner-v1.83\TBMiner.exe --algo verthash --verthash-data VertHash.dat --hostname verthash.eu.mine.zpool.ca --wallet ################# --port 6144 --server-passwd #######,c=BTC --api --api-version 1.4 --api-port 4001 --cl-devices [0]

00:00:00 [2023-01-31 18:03:23.898]
00:00:00 [2023-01-31 18:03:24.072] OpenCL driver version: 527.56
00:00:00 [2023-01-31 18:03:24.103] Cuda driver version: 12.0
00:00:00 [2023-01-31 18:03:24.103] Cuda runtime API version: 12.0
00:00:00 [2023-01-31 18:03:24.103]
00:00:00 [2023-01-31 18:03:24.103]
00:00:00 [2023-01-31 18:03:24.103]
00:00:00 [2023-01-31 18:03:24.103] Welcome to Team Black Miner 1.83
00:00:00 [2023-01-31 18:03:24.103]
00:00:00 [2023-01-31 18:03:24.103]
00:00:00 [2023-01-31 18:03:24.103] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2023-01-31 18:03:24.103] Trying to read verthash data file from disk
00:00:00 [2023-01-31 18:03:24.114] Api server started at 127.0.0.1:4004
00:00:00 [2023-01-31 18:03:24.601] Verthash data file has been loaded succesfully
00:00:00 [2023-01-31 18:03:29.701] Verthash data file has been verified succesfully
00:00:00 [2023-01-31 18:03:29.701] GPU0 Intensity set to 256
00:00:00 [2023-01-31 18:03:29.701] Trying verthash.eu.mine.zpool.ca:6144 (verthash)
00:00:00 [2023-01-31 18:03:29.747] Pool responded successfully to subscribe (verthash)
00:00:00 [2023-01-31 18:03:29.780] Pool responded successfully to extranonce subscribe
00:00:00 [2023-01-31 18:03:30.007] GPU0 Load verthash data size 1283457024
00:00:00 [2023-01-31 18:03:30.164] Pool responded successfully to authorize
00:00:00 [2023-01-31 18:03:30.180] Difficulty is set to 0.200000
00:00:00 [2023-01-31 18:03:30.790] GPU0 Verthash data loaded to gpu

Nothing happens after this. ???

**Comment by sp-hash** [comment]
fixed in 1.84
