### ISSUE TITLE
v1.83 (windows): Invalid algo name in API 1.4 data upon miner startup

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#345]
"algo:" "zil" is shown even when not mining ZIL at all.
Command line used

`TBMiner.exe --algo etc+vtc --verthash-data ..\..\Cache\VertHash.dat --hostname etchash.auto.nicehash.com --wallet ******************.********* --port 9200 --server-passwd x --vtc-hostname verthash.mine.zergpool.com --vtc-wallet 1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF --vtc-port 4534 --api --api-version 1.4 --api-port 4004 --cl-devices [1]`

```
{
  "devices": {
    "0": {
      "accepted": 0,
      "algo": "zil",
      "board_name": "Ellesmere",
      "core_clock": 0,
      "dag": false,
      "fan": 0,
      "gpu": 0,
      "gpu_temp": 0,
      "hashrate": 0,
      "mem_clock": 0,
      "mem_temp": 0,
      "pcie_id": 1,
      "rejected": 0,
      "stale": 0,
      "type": "OpenCL",
      "watt": 0,
      "xintensity": 0
    },
    "1": {
      "accepted": 0,
      "algo": "verthash",
      "board_name": "Ellesmere",
      "core_clock": 0,
      "dag": false,
      "fan": 0,
      "gpu": 0,
      "gpu_temp": 0,
      "hashrate": 0,
      "mem_clock": 0,
      "mem_temp": 0,
      "pcie_id": 1,
      "rejected": 0,
      "stale": 0,
      "type": "OpenCL",
      "watt": 0,
      "xintensity": 0
    }
  }
}

```

After a few seconds the first algo gets updated with the correct value.

I guess it has to do with the (also questionable message 'Starting generating zil dag (Epoch: 0)').

**Comment by sp-hash** [comment]
fixed in v1.84
