### ISSUE TITLE
Duplicate shares being submitted - shuts miner down

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#35]
87m [2021-09-24 13:09:16.095] us.woolypooly.com (ethash)    PING: 50ms    DIFFICULTY: 268.44 M    EPOCH: 442
    87m [2021-09-24 13:09:16.095]
    87m [2021-09-24 13:09:16.095]
    87m [2021-09-24 13:09:16.095] ID    BOARD   TEMP    FAN     CORE    MEM     WATT    kW/h    COST/h
    87m [2021-09-24 13:09:16.095] GPU0  6900XT  0/0     0       0       0       0       0.00    0.00USD
    87m [2021-09-24 13:09:16.095] GPU1  6800XT  0/0     0       0       0       0       0.00    0.00USD
    87m [2021-09-24 13:09:16.095] GPU2  6800XT  0/0     0       0       0       0       0.00    0.00USD
    87m [2021-09-24 13:09:16.095] GPU3  6800    0/0     0       0       0       0       0.00    0.00USD
    87m [2021-09-24 13:09:16.095] GPU4  6800XT  0/0     0       0       0       0       0.00    0.00USD
    87m [2021-09-24 13:09:16.095] GPU5  2060    54/0    89      1824    7946    141     0.14    0.01USD
    87m [2021-09-24 13:09:16.095]                                               141     0.14    0.01USD
    87m [2021-09-24 13:09:16.095]
    87m [2021-09-24 13:09:16.095] ID    BOARD   TYPE    HASHRATE/W      HASHRATE        AVERAGE         SHARES
    87m [2021-09-24 13:09:16.095] GPU0  6900XT  OpenCL  0.00 H/W        65.81 MH/s      66.49 MH/s      74/0/8 (100.00)
    87m [2021-09-24 13:09:16.095] GPU1  6800XT  OpenCL  0.00 H/W        67.52 MH/s      67.71 MH/s      64/0/5 (100.00)
    87m [2021-09-24 13:09:16.095] GPU2  6800XT  OpenCL  0.00 H/W        67.52 MH/s      67.53 MH/s      87/0/6 (100.00)
    87m [2021-09-24 13:09:16.095] GPU3  6800    OpenCL  0.00 H/W        67.21 MH/s      67.21 MH/s      103/0/6 (100.00)
    87m [2021-09-24 13:09:16.095] GPU4  6800XT  OpenCL  0.00 H/W        67.51 MH/s      67.69 MH/s      68/0/6 (100.00)
    87m [2021-09-24 13:09:16.095] GPU5  2060    Cuda    323.90 kH/W     45.67 MH/s      45.67 MH/s      48/0/1 (100.00)
    87m [2021-09-24 13:09:16.095]                       323.90 kH/s     381.24 MH/s     382.30 MH/s     444/0/32 (100.00)
    87m [2021-09-24 13:09:16.095]
    87m [2021-09-24 13:09:16.095]
    87m [2021-09-24 13:09:18.846] Job c92deec3f09fe2b5
    87m [2021-09-24 13:09:23.474] Job 43447757de26eba7
    87m [2021-09-24 13:09:24.135] Job effe44ca647dae9b
    87m [2021-09-24 13:09:25.457] Job aee369085bc24b63
    87m [2021-09-24 13:09:27.441] Job 5e20676bf656d34a
    87m [2021-09-24 13:09:30.746] Job 15e4a38fadfdcb5c
    87m [2021-09-24 13:09:32.068] Job 46bdc3b463bad067
    87m [2021-09-24 13:09:35.374] Job bd2e72a56d0ac20d
    87m [2021-09-24 13:09:36.035] Job 45de706965d75b76
    87m [2021-09-24 13:09:37.357] Job 6833fadae8d5a8f3
    87m [2021-09-24 13:09:38.019] Job 0f99e99f114db07b
    87m [2021-09-24 13:09:39.341] Job 66eecbbf5a0938a5
    87m [2021-09-24 13:09:40.002] Job 2def460d4d7c877d
    87m [2021-09-24 13:09:45.277] GPU2 Solution found in 5.49s (Submit every 13.54 seconds)
    87m [2021-09-24 13:09:45.325] Accepted (445/445/32) Reply: 47ms
    87m [2021-09-24 13:09:46.614] Job 224eb755667b8681
    87m [2021-09-24 13:09:49.654] GPU2 Solution found in 3.15s (Submit every 13.48 seconds)
    87m [2021-09-24 13:09:49.700] Accepted (446/446/32) Reply: 45ms
    87m [2021-09-24 13:09:50.581] Job 2ea757dbf467a1b5
    87m [2021-09-24 13:09:53.887] Job f8c4bb5539a40103
    87m [2021-09-24 13:09:56.532] Job 01617ab47dcd6ff8
    87m [2021-09-24 13:09:56.728] GPU0 Solution found in 0.60s (Submit every 13.53 seconds)
    87m [2021-09-24 13:09:56.774] Rejected (446/447) Reply: 45ms
    87m [2021-09-24 13:09:56.774] mining.submit: Pool reponded with error
    87m [2021-09-24 13:09:56.774] Error(-1): duplicate share

 Miner fails and does not restart

**Comment by sp-hash** [comment]
What's your launch config? Auto?

**Comment by sp-hash** [comment]
Try to run 2 instances of the miner. One with cuda, and one with amd

**Comment by KillrBee** [comment]
Intensity is set to 125.  This is the first time I've seen this error.  I will run the CUDA card separately and see if it ever pops up again.

**Comment by sp-hash** [comment]
found a possible cause in the opencl loop. Fixed in v1.09
