### ISSUE TITLE
1.84: EtcHash@HiveOn not supported (could also be verthash@zergpool.com based on error message)

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#350]
`TeamBlackMiner-v1.84\TBMiner.exe --algo etc+vtc --verthash-data VertHash.dat --hostname etc.hiveon.com --wallet ******************.**** --port 8888 --server-passwd x --vtc-hostname verthash.mine.zergpool.com --vtc-wallet ************** --vtc-port 4534 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

Gives

00:00:00 [2023-02-09 15:30:06.951] Trying verthash.mine.zergpool.com:4534 (verthash)
00:00:00 [2023-02-09 15:30:06.967] Trying etc.hiveon.com:8888 (etchash)
00:00:00 [2023-02-09 15:30:07.068] Pool responded successfully to subscribe
00:00:00 [2023-02-09 15:30:07.086] **mining.subscribe: Pool reponded with error**
00:00:00 [2023-02-09 15:30:07.086] **Error(20): Not supported**
00:00:00 [2023-02-09 15:30:07.086] An error has occurred. Cannot subscribe to pool

The error message is not clear. Is this now for etchash or verthash?

**Comment by sp-hash** [comment]
fixed in v1.86
