### ISSUE TITLE
1.84 & 1.85: Verthash@ZPool giving errors

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#351]
`TeamBlackMiner-v1.84\TBMiner.exe --algo verthash --verthash-data VertHash.dat --hostname verthash.eu.mine.zpool.ca --wallet ************************* --ssl --ssl-verify-none --ssl-port 56144 --server-passwd ***********,c=BTC --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

00:00:00 [2023-02-09 15:51:54.770]
00:00:00 [2023-02-09 15:51:54.914] OpenCL driver version: 527.56
00:00:00 [2023-02-09 15:51:54.948] Cuda driver version: 12.0
00:00:00 [2023-02-09 15:51:54.948] Cuda runtime API version: 11.6
00:00:00 [2023-02-09 15:51:54.948]
00:00:00 [2023-02-09 15:51:54.948]
00:00:00 [2023-02-09 15:51:54.948]
00:00:00 [2023-02-09 15:51:54.948] Welcome to Team Black Miner 1.84
00:00:00 [2023-02-09 15:51:54.948]
00:00:00 [2023-02-09 15:51:54.948]
00:00:00 [2023-02-09 15:51:54.948] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-02-09 15:51:54.950] Trying to read verthash data file from disk
00:00:00 [2023-02-09 15:51:54.980] Api server started at 127.0.0.1:4001
00:00:00 [2023-02-09 15:51:55.898] Verthash data file has been loaded succesfully
00:00:00 [2023-02-09 15:52:01.670] Verthash data file has been verified succesfully
00:00:00 [2023-02-09 15:52:01.671] GPU0 Intensity set to 256
00:00:00 [2023-02-09 15:52:01.671] Trying stratum+ssl://verthash.eu.mine.zpool.ca:56144 (verthash)
00:00:00 [2023-02-09 15:52:01.738] Pool responded successfully to subscribe (verthash)
00:00:00 [2023-02-09 15:52:01.759] Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-09 15:52:02.096] GPU0 Load verthash data size 1283457024
00:00:00 [2023-02-09 15:52:02.176] Pool responded successfully to authorize
00:00:00 [2023-02-09 15:52:02.222] Difficulty is set to 0.200000
00:00:00 [2023-02-09 15:52:06.026] GPU0 Verthash data loaded to gpu
00:00:00 [2023-02-09 15:52:06.031] Job 5  (verthash)
00:00:00 [2023-02-09 15:52:30.778] Job 6  (verthash)
00:00:00 [2023-02-09 15:52:30.785] VERTHASH: GPU0 Rejected (0/1/0) Reply: 30ms
00:00:00 [2023-02-09 15:52:30.785] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.785] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.801] VERTHASH: GPU0 Rejected (0/2/0) Reply: 46ms
00:00:00 [2023-02-09 15:52:30.801] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.801] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.832] VERTHASH: GPU0 Rejected (0/3/0) Reply: 78ms
00:00:00 [2023-02-09 15:52:30.832] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.832] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.847] VERTHASH: GPU0 Rejected (0/4/0) Reply: 93ms
00:00:00 [2023-02-09 15:52:30.847] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.847] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.862] VERTHASH: GPU0 Rejected (0/5/0) Reply: 108ms
00:00:00 [2023-02-09 15:52:30.862] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.862] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.878] VERTHASH: GPU0 Rejected (0/6/0) Reply: 124ms
00:00:00 [2023-02-09 15:52:30.878] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.878] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.893] VERTHASH: GPU0 Rejected (0/7/0) Reply: 139ms
00:00:00 [2023-02-09 15:52:30.893] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.893] Error(21): Invalid job id
00:00:00 [2023-02-09 15:52:30.909] VERTHASH: GPU0 Rejected (0/8/0) Reply: 155ms
00:00:00 [2023-02-09 15:52:30.909] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 15:52:30.909] Error(21): Invalid job id

**Comment by UselessGuru** [comment]
Same with 1.85:

00:00:00 [2023-02-09 16:24:20.686]
00:00:00 [2023-02-09 16:24:20.837] OpenCL driver version: 527.56
00:00:00 [2023-02-09 16:24:20.896] Cuda driver version: 12.0
00:00:00 [2023-02-09 16:24:20.896] Cuda runtime API version: 11.6
00:00:00 [2023-02-09 16:24:20.896]
00:00:00 [2023-02-09 16:24:20.896]
00:00:00 [2023-02-09 16:24:20.896]
00:00:00 [2023-02-09 16:24:20.896] Welcome to Team Black Miner 1.85
00:00:00 [2023-02-09 16:24:20.896]
00:00:00 [2023-02-09 16:24:20.896]
00:00:00 [2023-02-09 16:24:20.896] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-02-09 16:24:20.897] Trying to read verthash data file from disk
00:00:00 [2023-02-09 16:24:20.897] Api server started at 127.0.0.1:4001
00:00:00 [2023-02-09 16:24:21.628] Verthash data file has been loaded succesfully
00:00:00 [2023-02-09 16:24:27.957] Verthash data file has been verified succesfully
00:00:00 [2023-02-09 16:24:27.957] GPU0 Intensity set to 256
00:00:00 [2023-02-09 16:24:27.957] Trying stratum+ssl://verthash.eu.mine.zpool.ca:56144 (verthash)
00:00:00 [2023-02-09 16:24:28.052] Pool responded successfully to subscribe (verthash)
00:00:00 [2023-02-09 16:24:28.083] Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-09 16:24:28.417] GPU0 Load verthash data size 1283457024
00:00:00 [2023-02-09 16:24:28.479] Pool responded successfully to authorize
00:00:00 [2023-02-09 16:24:28.527] Difficulty is set to 0.200000
00:00:00 [2023-02-09 16:24:32.321] GPU0 Verthash data loaded to gpu
00:00:00 [2023-02-09 16:24:32.321] Job 2426  (verthash)
00:00:00 [2023-02-09 16:24:46.784] VERTHASH: GPU0 Rejected (0/1/0) Reply: 29ms
00:00:00 [2023-02-09 16:24:46.784] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 16:24:46.784] Error(21): Invalid job id
00:00:00 [2023-02-09 16:24:46.809] VERTHASH: GPU0 Rejected (0/2/0) Reply: 54ms
00:00:00 [2023-02-09 16:24:46.809] mining.submit: Pool reponded with error
00:00:00 [2023-02-09 16:24:46.809] Error(21): Invalid job id
00:00:00 [2023-02-09 16:24:46.809] Job 2427  (verthash)

**Comment by sp-hash** [comment]
fixed in v1.86
