### ISSUE TITLE
v1.86 (Windows): Errors mining EtcHash & Ethash@ProHashing pool

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#353]
Same as https://github.com/sp-hash/TeamBlackMiner/issues/343

`TeamBlackMiner-v1.86>tBMiner.exe --algo etchash --hostname eu.mining.prohashing.com --wallet ******************--port 3357 --server-passwd a=etchash,e=off,n=*********,o=*******************--api --api-version 1.4 --api-port 4004 --cl-devices [1]`

00:00:00 [2023-02-11 17:52:57.450]
00:00:00 [2023-02-11 17:52:57.560] OpenCL driver version: 527.56
00:00:00 [2023-02-11 17:52:57.638] Cuda driver version: 12.0
00:00:00 [2023-02-11 17:52:57.638] Cuda runtime API version: 11.6
00:00:00 [2023-02-11 17:52:57.638]
00:00:00 [2023-02-11 17:52:57.638]
00:00:00 [2023-02-11 17:52:57.638]
00:00:00 [2023-02-11 17:52:57.638] Welcome to Team Black Miner 1.86
00:00:00 [2023-02-11 17:52:57.638]
00:00:00 [2023-02-11 17:52:57.638]
00:00:00 [2023-02-11 17:52:57.638] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2023-02-11 17:52:57.638] GPU0 Started CL work thread
00:00:00 [2023-02-11 17:52:57.638] Api server started at 127.0.0.1:4004
00:00:00 [2023-02-11 17:52:57.638] Trying eu.mining.prohashing.com:3357 (etchash)
00:00:00 [2023-02-11 17:52:57.701] eu.mining.prohashing.com: Pool responded successfully to subscribe
00:00:00 [2023-02-11 17:52:57.701] eu.mining.prohashing.com: Difficulty is set to 0.250000
00:00:00 [2023-02-11 17:52:57.779] mining.extranonce.subscribe: Pool reponded with error
00:00:00 [2023-02-11 17:52:57.795] eu.mining.prohashing.com: Pool responded successfully to authorize
00:00:00 [2023-02-11 17:53:09.067] GPU0 Starting generating etchash dag (Epoch: 282)
00:00:00 [2023-02-11 17:53:18.397] GPU0 DAG generated in 9.34 seconds (3358719kb)
00:00:00 [2023-02-11 17:53:18.397] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-11 17:53:18.944] GPU0 Dag buffer verified ok!
00:00:00 [2023-02-11 17:53:22.245] Job a0d115a1
00:00:00 [2023-02-11 17:53:23.423] ETCHASH: GPU0 Rejected (0/1/0) Reply: 62ms
**00:00:00 [2023-02-11 17:53:23.423] mining.submit: Pool reponded with error
00:00:00 [2023-02-11 17:53:23.423] Error(-2): The submitted share's difficulty of 1.00361996486e-09 is too easy; a single difficulty of 0.25 allowed for this algorithm|1.00361996486e-09**

**Comment by sp-hash** [comment]
fixed in v1.87
