### ISSUE TITLE
v1.86 (Windows): Error mining kawpow@prohashing

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#354]
`TeamBlackMiner-v1.86>TBMiner.exe --algo kawpow --hostname eu.mining.prohashing.com --wallet UselessGuru --port 3361 --server-passwd a=kawpow,e=off,n=Blackbox,o=UselessGuru --api --api-version 1.4 --api-port 4006 --cuda-devices [0]`

00:00:00 [2023-02-11 17:56:59.469]
00:00:00 [2023-02-11 17:56:59.531] OpenCL driver version: 527.56
00:00:00 [2023-02-11 17:56:59.547] Cuda driver version: 12.0
00:00:00 [2023-02-11 17:56:59.547] Cuda runtime API version: 11.6
00:00:00 [2023-02-11 17:56:59.547]
00:00:00 [2023-02-11 17:56:59.547]
00:00:00 [2023-02-11 17:56:59.547]
00:00:00 [2023-02-11 17:56:59.547] Welcome to Team Black Miner 1.86
00:00:00 [2023-02-11 17:56:59.547]
00:00:00 [2023-02-11 17:56:59.547]
00:00:00 [2023-02-11 17:56:59.658] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-02-11 17:56:59.658] Api server started at 127.0.0.1:4006
00:00:00 [2023-02-11 17:56:59.658] Trying eu.mining.prohashing.com:3361 (kawpow)
00:00:00 [2023-02-11 17:56:59.797] GPU0 XIntensity set to 256
**00:00:00 [2023-02-11 17:57:00.438] eu.mining.prohashing.com: Pool responded to subscribe**
00:00:00 [2023-02-11 17:57:00.454] GPU0 Starting generating kawpow dag (Epoch: 355)
00:00:00 [2023-02-11 17:57:00.500] mining.extranonce.subscribe: Pool reponded with error
00:00:00 [2023-02-11 17:57:00.516] eu.mining.prohashing.com: Pool responded successfully to authorize

**Comment by sp-hash** [comment]
The pol is working, but you get an error message:

mining.extranonce.subscribe: Pool reponded with error

This error has been removed in v1.87.

**Comment by sp-hash** [comment]
fixed in v1.87
