### ISSUE TITLE
v1.86 (Windows): Cannot open nvidia-smi for gpu utilization information

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#356]
00:00:00 [2023-02-11 17:41:43.043]
00:00:00 [2023-02-11 17:41:43.588] OpenCL driver version: 527.56
00:00:00 [2023-02-11 17:41:43.670] Cuda driver version: 12.0
00:00:00 [2023-02-11 17:41:43.670] Cuda runtime API version: 11.6
00:00:00 [2023-02-11 17:41:43.670]
00:00:00 [2023-02-11 17:41:43.670]
00:00:00 [2023-02-11 17:41:43.670]
00:00:00 [2023-02-11 17:41:43.670] Welcome to Team Black Miner 1.86
00:00:00 [2023-02-11 17:41:43.670]
00:00:00 [2023-02-11 17:41:43.670]
00:00:00 [2023-02-11 17:41:43.767] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-02-11 17:41:43.798] Trying to read verthash data file from disk
00:00:00 [2023-02-11 17:41:43.814] Api server started at 127.0.0.1:4006
00:00:00 [2023-02-11 17:41:44.743] Verthash data file has been loaded succesfully
00:00:00 [2023-02-11 17:41:51.444] Verthash data file has been verified succesfully
00:00:00 [2023-02-11 17:41:51.445] Trying stratum+ssl://verthash.mine.zergpool.com:14534 (verthash)
00:00:00 [2023-02-11 17:41:51.562] GPU0 Started Cuda Verthash work thread
00:00:00 [2023-02-11 17:41:51.562] GPU0 Intensity set to 1024
00:00:00 [2023-02-11 17:41:51.562] GPU0 Load verthash data size 1283457024
00:00:00 [2023-02-11 17:41:51.946] verthash.mine.zergpool.com: Pool responded successfully to subscribe
00:00:00 [2023-02-11 17:41:52.280] verthash.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-11 17:41:52.370] verthash.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-02-11 17:41:52.385] verthash.mine.zergpool.com: Difficulty is set to 2.000000
00:00:00 [2023-02-11 17:41:58.132] GPU0 Verthash data loaded to gpu
00:00:00 [2023-02-11 17:41:58.132] Job 2416  (verthash)
00:00:00 [2023-02-11 17:42:00.981] VERTHASH: GPU0 Accepted (1/1/0) Reply: 196ms
**The process cannot access the file because it is being used by another process.**
**00:00:00 [2023-02-11 17:42:21.012] Cannot open nvidia-smi for gpu utilization information**
00:00:00 [2023-02-11 17:42:24.434] Job 2417  (verthash)

I have only seen this with verthash. Other algos are fine

**Comment by sp-hash** [comment]
You get this error if you have 2 instances open of the miner and run from the same folder.

**Comment by UselessGuru** [comment]
> You get this error if you have 2 instances open of the miner and run from the same folder.

Yes

**Comment by sp-hash** [comment]
The workaround is to copy the folder and run each instance in it's own folder.
