### ISSUE TITLE
Dual mining Kawpow+etc or triple mining not working

### ISSUE THREAD

**Issue by MiningKiiNG** [sp-hash/TeamBlackMiner#359]
This is my config in hiveos, I have tried to triple mine, dual mine kawpow etc as well as kaspa ergo zil and I always get this errror 
![image](https://user-images.githubusercontent.com/125224762/218343413-eef01e57-8c3a-422a-b792-5915fb494a46.png)

![image](https://user-images.githubusercontent.com/125224762/218343343-5172e12f-f524-4d7c-abfa-7db432bcbc00.png)

I have tried triple mining and dual mining with your miner. Can please put in the readme or config a working example of your dual mining and triple mining. Always gives an error and the second Main Algo so in this case its Kawpow

**Comment by sp-hash** [comment]
You have to put Hash algorithm etchash. 

Ezil.me is using the wallet format %etcwallet%.%zilwallet%

Dual mining is only supported on crazypool at the moment.

**Comment by MiningKiiNG** [comment]
doesnt matter if its etchash still gets the same error

**Comment by sp-hash** [comment]
RVN+ is not supported on AMD. NVIDIA only. But you can mine ETC+VTC on amd

**Comment by MiningKiiNG** [comment]
i tried the samething and I get the same effect could I get an example for AMD cards?

**Comment by MiningKiiNG** [comment]
etc vtc zil or etc vtc I still get the same error

**Comment by sp-hash** [comment]
There is an issue with ETHPROXY pools ezil.me / hiveon.com and some others in +RVN and +VTC mode. We will fix it in the next release.

**Comment by sp-hash** [comment]
fixed in v1.87
