### ISSUE TITLE
v1.86 (Windows): Error dual mining etchash@hiveon & vtc@zergpool

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#361]
`TeamBlackMiner-v1.86>TBMiner.exe --algo etc+vtc --verthash-data ..\..\Cache\VertHash.dat --hostname etc.hiveon.com --wallet ################## --worker-name ########### --ssl-port 20443 --server-passwd x --vtc-hostname verthash.mine.zergpool.com --vtc-wallet ####################--vtc-port 14534 --ssl --ssl-verify-none --api --api-version 1.4 --api-port 4004 --cuda-devices [0]`

00:00:00 [2023-02-13 21:49:40.327]
00:00:00 [2023-02-13 21:49:40.386] OpenCL driver version: 527.56
00:00:00 [2023-02-13 21:49:40.407] Cuda driver version: 12.0
00:00:00 [2023-02-13 21:49:40.407] Cuda runtime API version: 11.6
00:00:00 [2023-02-13 21:49:40.407]
00:00:00 [2023-02-13 21:49:40.407]
00:00:00 [2023-02-13 21:49:40.407]
00:00:00 [2023-02-13 21:49:40.407] Welcome to Team Black Miner 1.86
00:00:00 [2023-02-13 21:49:40.407]
00:00:00 [2023-02-13 21:49:40.407]
00:00:00 [2023-02-13 21:49:40.512] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-02-13 21:49:40.512] Trying to read verthash data file from disk
00:00:00 [2023-02-13 21:49:40.513] Api server started at 127.0.0.1:4004
00:00:00 [2023-02-13 21:49:40.876] Verthash data file has been loaded succesfully
00:00:00 [2023-02-13 21:49:45.764] Verthash data file has been verified succesfully
00:00:00 [2023-02-13 21:49:45.764] Trying stratum+ssl://verthash.mine.zergpool.com:14534 (verthash)
00:00:00 [2023-02-13 21:49:45.765] Trying stratum+ssl://etc.hiveon.com:20443 (etchash)
00:00:00 [2023-02-13 21:49:45.885] etc.hiveon.com: Pool responded successfully to subscribe
00:00:00 [2023-02-13 21:49:45.908] GPU0 Started Cuda work thread
00:00:00 [2023-02-13 21:49:45.908] GPU0 Started Cuda Verthash work thread
00:00:00 [2023-02-13 21:49:45.908] GPU0 Intensity set to 1024
00:00:00 [2023-02-13 21:49:45.909] GPU0 Load verthash data size 1283457024

-> Back to prompt.

Note: There are no etc+vtc examples.
How do I specify the workername for the second algorithm (verthash)?

**Comment by sp-hash** [comment]
hiveon is a ethproxy pool but has been fixed in v1.87
