### ISSUE TITLE
v1.87 (Windows): Parameter '--amd-only' and 'nvidia-only' breaks individual device selection

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#363]
Fixed --cl-devices when the --amd-only flag was set.
Fixed --nvidia-devices when the --nvidia-only flag was set.

Still broken

`TeamBlackMiner-v1.87>TBMiner.exe --algo etc+vtc --verthash-data VertHash.dat --hostname etchash.auto.nicehash.com --wallet ###########################.######### --ssl-port 443 --server-passwd x --vtc-hostname verthash.mine.zergpool.com --vtc-wallet ########################### --vtc-port 14534 --ssl --ssl-verify-none --api --api-port 4001 --cl-devices [0] --amd-only`

00:00:00 [2023-02-14 20:38:58.008]
00:00:00 [2023-02-14 20:38:58.244] OpenCL driver version: 527.56
00:00:00 [2023-02-14 20:38:58.280] Cuda driver version: 12.0
00:00:00 [2023-02-14 20:38:58.280] Cuda runtime API version: 11.6
00:00:00 [2023-02-14 20:38:58.280]
00:00:00 [2023-02-14 20:38:58.280]
00:00:00 [2023-02-14 20:38:58.280]
00:00:00 [2023-02-14 20:38:58.280] Welcome to Team Black Miner 1.87
00:00:00 [2023-02-14 20:38:58.280]
00:00:00 [2023-02-14 20:38:58.280]
00:00:00 [2023-02-14 20:38:58.280] **Using all Amd devices**
00:00:00 [2023-02-14 20:38:58.280] GPU0 gfx1010:xnack- added to miner as OpenCL device
00:00:00 [2023-02-14 20:38:58.280] GPU1 Ellesmere added to miner as OpenCL device
00:00:00 [2023-02-14 20:38:58.280] Trying to read verthash data file from disk
00:00:00 [2023-02-14 20:38:58.280] Api server started at 127.0.0.1:4001
00:00:00 [2023-02-14 20:38:58.645] Verthash data file has been loaded succesfully
00:00:00 [2023-02-14 20:39:03.454] Verthash data file has been verified succesfully
00:00:00 [2023-02-14 20:39:03.454] GPU0 Started CL work thread
00:00:00 [2023-02-14 20:39:03.456] Trying stratum+ssl://etchash.auto.nicehash.com:443 (etchash)
00:00:00 [2023-02-14 20:39:03.456] GPU1 Started CL work thread
00:00:00 [2023-02-14 20:39:03.456] GPU1 Intensity set to 256
00:00:00 [2023-02-14 20:39:03.457] Trying stratum+ssl://verthash.mine.zergpool.com:14534 (verthash)
00:00:00 [2023-02-14 20:39:03.457] GPU0 Intensity set to 256
00:00:00 [2023-02-14 20:39:03.641] etchash.auto.nicehash.com: Pool responded successfully to subscribe
00:00:00 [2023-02-14 20:39:03.673] etchash.auto.nicehash.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-14 20:39:03.688] etchash.auto.nicehash.com: Pool responded successfully to authorize
00:00:00 [2023-02-14 20:39:03.698] verthash.mine.zergpool.com: Pool responded successfully to subscribe
00:00:00 [2023-02-14 20:39:03.703] etchash.auto.nicehash.com: Difficulty is set to 0.363122
00:00:00 [2023-02-14 20:39:03.733] GPU0 Starting generating zil dag (Epoch: 0)
00:00:00 [2023-02-14 20:39:03.733] GPU1 Starting generating zil dag (Epoch: 0)
00:00:00 [2023-02-14 20:39:03.879] GPU0 Load verthash data size 1283457024
00:00:00 [2023-02-14 20:39:04.014] verthash.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-14 20:39:04.089] GPU1 Load verthash data size 1283457024
00:00:00 [2023-02-14 20:39:04.104] verthash.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-02-14 20:39:04.120] verthash.mine.zergpool.com: Difficulty is set to 2.000000
00:00:00 [2023-02-14 20:39:07.905] GPU0 Verthash data loaded to gpu
00:00:00 [2023-02-14 20:39:07.910] Job d88  (verthash)
00:00:00 [2023-02-14 20:39:11.035] GPU1 DAG generated in 7.30 seconds (1048574kb)
00:00:00 [2023-02-14 20:39:11.035] GPU1 XIntensity set to Dynamic
00:00:00 [2023-02-14 20:39:11.079] GPU1 Starting generating etchash dag (Epoch: 282)
00:00:00 [2023-02-14 20:39:11.198] GPU1 Verthash data loaded to gpu
00:00:00 [2023-02-14 20:39:11.446] GPU0 DAG generated in 7.72 seconds (1048574kb)
00:00:00 [2023-02-14 20:39:11.446] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-14 20:39:12.432] GPU0 Starting generating etchash dag (Epoch: 282)
00:00:00 [2023-02-14 20:39:19.321] VERTHASH: GPU1 Accepted (1/1/0) Reply: 279ms
00:00:00 [2023-02-14 20:39:19.714] GPU0 DAG generated in 8.25 seconds (3358719kb)
00:00:00 [2023-02-14 20:39:19.714] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-14 20:39:19.734] GPU0 Dag buffer verified ok!
00:00:00 [2023-02-14 20:39:20.547] Job 000000005086e4ec
00:00:00 [2023-02-14 20:39:23.567] Job 000000008b4400b2
00:00:00 [2023-02-14 20:39:23.582] Job 000000005086e4ed
00:00:00 [2023-02-14 20:39:24.751] Job 000000008b4400b3
00:00:00 [2023-02-14 20:39:30.205] etchash.auto.nicehash.com: Extranonce is set to 62bc760000000000
00:00:00 [2023-02-14 20:39:30.220] etchash.auto.nicehash.com: Difficulty is set to 0.363122
00:00:00 [2023-02-14 20:39:30.237] Job 000000005086e4ef
00:00:00 [2023-02-14 20:39:30.250] Job 000000008b4400b4
00:00:00 [2023-02-14 20:39:31.492] GPU1 DAG generated in 20.44 seconds (3358719kb)
00:00:00 [2023-02-14 20:39:31.492] GPU1 XIntensity set to Dynamic
00:00:00 [2023-02-14 20:39:31.521] GPU1 Dag buffer verified ok!
00:00:00 [2023-02-14 20:39:36.737] VERTHASH: GPU1 Accepted (2/2/0) Reply: 84ms
00:00:00 [2023-02-14 20:39:37.041] VERTHASH: GPU0 Accepted (3/3/0) Reply: 142ms
00:00:00 [2023-02-14 20:39:37.406] Job 000000008b4400b5
00:00:00 [2023-02-14 20:39:37.421] Job 000000005086e4f0
00:00:00 [2023-02-14 20:39:46.464] Job 000000008b4400b6
00:00:00 [2023-02-14 20:39:46.479] Job 000000005086e4f1
00:00:00 [2023-02-14 20:39:47.313] Job 000000008b4400b7
00:00:00 [2023-02-14 20:39:47.324] Job 000000005086e4f2
00:00:00 [2023-02-14 20:39:48.985] Job d89  (verthash)
00:00:00 [2023-02-14 20:39:54.699] ETCHASH: GPU0 Accepted (1/1/0) Reply: 27ms
00:00:00 [2023-02-14 20:39:59.254] ETCHASH: GPU1 Rejected (1/2/0) Reply: 31ms
00:00:00 [2023-02-14 20:39:59.254] mining.submit: Pool reponded with error
00:00:00 [2023-02-14 20:39:59.254] Error(3): Duplicate share.
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] auto.nicehash.com (etchash)    PING: 28ms    DIFFICULTY: 0.363    EPOCH: 282
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-02-14 20:40:07.229] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-02-14 20:40:07.229] GPU1    580S     OpenCL  0       0       0/0     0       0       0       0
00:00:01 [2023-02-14 20:40:07.229]                                                                          0
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-02-14 20:40:07.229] GPU0    5700XT   0.00 H/W      4870.42 kH/s  4518.19 kH/s  1/0/0        100.00%
00:00:01 [2023-02-14 20:40:07.229] GPU1    580S     0.00 H/W      2604.22 kH/s  2670.12 kH/s  0/1/0        0.00%
00:00:01 [2023-02-14 20:40:07.229]                  0.00 H/W      7474.63 kH/s  7188.30 kH/s  1/1/0        50.00%
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] SHARES PER MINUTE: 1.00                              POOL HASHRATE: 25.99 MH/s
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] mine.zergpool.com (verthash)    PING: 139ms    DIFFICULTY: 2.00     EPOCH: 0
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-02-14 20:40:07.229] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-02-14 20:40:07.229] GPU1    580S     OpenCL  0       0       0/0     0       0       0       0
00:00:01 [2023-02-14 20:40:07.229]                                                                          0
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-02-14 20:40:07.229] GPU0    5700XT   0.00 H/W      712.20 kH/s   633.63 kH/s   1/0/0        100.00%
00:00:01 [2023-02-14 20:40:07.229] GPU1    580S     0.00 H/W      479.28 kH/s   435.39 kH/s   2/0/0        100.00%
00:00:01 [2023-02-14 20:40:07.229]                  0.00 H/W      1191.48 kH/s  1069.02 kH/s  3/0/0        100.00%
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.229] SHARES PER MINUTE: 3.00                              POOL HASHRATE: 1677.75 kH/s
00:00:01 [2023-02-14 20:40:07.229]
00:00:01 [2023-02-14 20:40:07.239] Job 000000008b4400b8
00:00:01 [2023-02-14 20:40:07.239] Job 000000008b4400b8

**Comment by sp-hash** [comment]
fixed in 1.88
