### ISSUE TITLE
v1.87 (Windows): No data for 2nd algorithm in API

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#364]
`TeamBlackMiner-v1.87>TBMiner.exe --algo etc+vtc --verthash-data VertHash.dat --hostname etchash.auto.nicehash.com --wallet ###########################.######### --ssl-port 443 --server-passwd x --vtc-hostname verthash.mine.zergpool.com --vtc-wallet ########################### --vtc-port 14534 --ssl --ssl-verify-none --api--api-version 1.4 --api-port 4001 --cl-devices [0]`

API 1.4: http://127.0.0.1:4001/threads only gives me:

```
{
  "devices": {
    "0": {
      "accepted": 0,
      "algo": "zil",
      "board_name": "AMD Radeon RX 5700 XT",
      "core_clock": 2040,
      "dag": true,
      "fan": 46,
      "gpu": 0,
      "gpu_temp": 0,
      "hashrate": 57475099,
      "mem_clock": 1840,
      "mem_temp": 0,
      "pcie_id": 9,
      "rejected": 0,
      "stale": 0,
      "type": "OpenCL",
      "watt": 0,
      "xintensity": 0
    }
  }
}
```

What am I doing wrong?

**Comment by sp-hash** [comment]
There are some fixes in v1.88 you can try. Pools is now showing all the pools, and +rvn.

**Comment by UselessGuru** [comment]
> Pools is now showing all the pools, and +rvn.

Tested with 1.88 - ok, but not the solution:
```
{
  "pool": {
    "1": {
      "algo": "verthash",
      "block": 0,
      "diff": 0,
      "epoch": 0,
      "job": "",
      "ping": 0,
      "port": 9991,
      "url": "stratum3.hashcryptos.com",
      "worker": ""
    },
    "2": {
      "algo": "etchash",
      "block": 0,
      "diff": 0.175804,
      "epoch": 282,
      "job": "0000000065b176c3",
      "ping": 26,
      "port": 0,
      "url": "etchash.auto.nicehash.com",
      "worker": ""
    }
  }
}
```

https://github.com/sp-hash/TeamBlackMiner/blob/main/API.md
says '- Threads now contain algorithm.', but there is no hash rate info for the sencond algorithm:

How can I get hashrate for the second algorithm?

**Comment by sp-hash** [comment]
In 1.89 We added hashrate in the pools tab and fixed hashrate in the threads tab. Note that in the miner window we use seperate stats for zil, but in the api ETC and zil stats are merged.
