### ISSUE TITLE
v1.94 (Windows). --cl-devices [0] --nvidia-only conflict, also in 1.95

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#368]
`TeamBlackMiner-v1.91\TBMiner.exe --algo ethash --hostname daggerhashimoto.auto.nicehash.com --wallet ######################.######## --ssl-port 443 --server-passwd x --ssl --ssl-verify-none --api --api-version 1.4 --api-port 4001 --cl-devices [0] --nvidia-only`

00:00:00 [2023-02-22 09:17:39.033]
00:00:00 [2023-02-22 09:17:39.069] Cuda driver version: 12.0
00:00:00 [2023-02-22 09:17:39.069] Cuda runtime API version: 11.6
00:00:00 [2023-02-22 09:17:39.069]
00:00:00 [2023-02-22 09:17:39.069]
00:00:00 [2023-02-22 09:17:39.069]
00:00:00 [2023-02-22 09:17:39.069] Welcome to Team Black Miner 1.91
00:00:00 [2023-02-22 09:17:39.069]
00:00:00 [2023-02-22 09:17:39.069]
00:00:00 [2023-02-22 09:17:39.069] Only using Nvidia devices
**00:00:00 [2023-02-22 09:17:39.231] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-02-22 09:17:39.315] GPU1 NVIDIA GeForce GT 1030 2GB added to miner as Cuda device
00:00:00 [2023-02-22 09:17:39.378] GPU2 NVIDIA GeForce GTX 750 Ti 2GB added to miner as Cuda device**
00:00:00 [2023-02-22 09:17:39.378] Api server started at 127.0.0.1:4001
00:00:00 [2023-02-22 09:17:39.379] Trying stratum+ssl://daggerhashimoto.auto.nicehash.com:443 (ethash)
00:00:00 [2023-02-22 09:17:39.431] daggerhashimoto.auto.nicehash.com: Pool responded successfully to subscribe
00:00:00 [2023-02-22 09:17:39.488] daggerhashimoto.auto.nicehash.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-22 09:17:39.519] daggerhashimoto.auto.nicehash.com: Pool responded successfully to authorize
00:00:00 [2023-02-22 09:17:39.519] GPU0 Started Cuda work thread
00:00:00 [2023-02-22 09:17:39.534] daggerhashimoto.auto.nicehash.com: Difficulty is set to 0.481757
00:00:00 [2023-02-22 09:17:39.612] GPU1 Started Cuda work thread
00:00:00 [2023-02-22 09:17:39.692] GPU2 Started Cuda work thread

I'd expect that no devices would get selected, and not all NVIDIA and thereby ignoring --cl-devices

Suggestion:
Remove '--amd-only' & '--nvidia-only' and make the device id selector ([n]) with  '--cl-device' & '--cuda-device' optional.
-> if device ID is omitted then all cuda / cl devices are selected

**Comment by sp-hash** [comment]
nvidia is disabled by default in the --cl-devices

**Comment by UselessGuru** [comment]
> nvidia is disabled by default in the --cl-devices

So why does it select ALL nvidia devices and ignore the CL device?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Still the same in v1.94

**Comment by UselessGuru** [comment]
Still the same in v1.95

**Comment by sp-hash** [comment]
not sure if this will be fixed. nvidia cards doesnt support opencl

**Comment by UselessGuru** [comment]
> not sure if this will be fixed. nvidia cards doesnt support opencl

This is not my point. Is my original post not clear?

'--amd-only' & '--nvidia-only' should **always exclude all devices of that type** no matter what other deveice selection parameter is added. 
As you can see if used in combination with '--cl-devices' / '--cude-devices' this is not the case.

Suggestion:
Remove '--amd-only' & '--nvidia-only' parameters. Make the device id number ([n]) an optional parameter for --cl-device' & '--cuda-device'.
-> if device number is omitted then all cuda or all cl devices are selected.

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Do you ever look at open issues???

**Comment by sp-hash** [comment]
fixed in v2.01
