### ISSUE TITLE
No reported hashrate on Ethermine

### ISSUE THREAD

**Issue by MrNuTruT** [sp-hash/TeamBlackMiner#37]
Hello,

Same problem with 1.08 on ethermine.

![image](https://user-images.githubusercontent.com/11719145/134755933-9e8a6193-930a-4ed7-b872-d9e3d7235ca5.png)

I have Current Hashrate, Valid Shares but not the reported Hashrate.

He is always at 0

![image](https://user-images.githubusercontent.com/11719145/134755992-08682ac3-fdaa-4039-bf91-42b99f8008a4.png)

**Comment by sp-hash** [comment]
Amd cards?

**Comment by sp-hash** [comment]
Working here for cuda.
Fix in opencl v1.09
![working](https://user-images.githubusercontent.com/9572668/134772401-fe4f73b9-79e7-414c-bf0b-4e9b9e2196f5.png)

**Comment by MrNuTruT** [comment]
only nvidia card on 3080

**Comment by sp-hash** [comment]
which server?

I tested with:

TBMiner --algo ethash --hostname eu1.ethermine.org --port 4444 --wallet %ETH_WALLET% --worker_name pckingkong  --xintensity -1


![ethermine2](https://user-images.githubusercontent.com/9572668/134776728-67dd1115-ad04-4f08-b16e-42cbcb73ab94.png)

**Comment by MrNuTruT** [comment]
Windows 10  21H1 with cuda 11.4

it displays 1.08 on start

**Comment by sp-hash** [comment]
v1.09 has been released. you can try that one.

**Comment by MrNuTruT** [comment]
Same problem 

![image](https://user-images.githubusercontent.com/11719145/134797348-8b3d7d66-5f35-40e5-922d-abf51786ae53.png)

**Comment by MrNuTruT** [comment]
1.09 not fix the problem
