### ISSUE TITLE
v1.92 (Windows): No hashrate for 2nd algorithm etc+rvn

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#370]
`TeamBlackMiner-v1.92\TBMiner.exe --algo eth+rvn --hostname daggerhashimoto.auto.nicehash.com --wallet #######################.######### --port 9200 --server-passwd x --rvn-hostname kawpow.auto.nicehash.com --rvn-wallet #######################.######### --rvn-port 9200 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

00:00:00 [2023-02-24 18:32:17.114]
00:00:00 [2023-02-24 18:32:17.234] OpenCL driver version: 527.56
00:00:00 [2023-02-24 18:32:17.254] Cuda driver version: 12.0
00:00:00 [2023-02-24 18:32:17.254] Cuda runtime API version: 12.0
00:00:00 [2023-02-24 18:32:17.254]
00:00:00 [2023-02-24 18:32:17.254]
00:00:00 [2023-02-24 18:32:17.254]
00:00:00 [2023-02-24 18:32:17.254] Welcome to Team Black Miner 1.92
00:00:00 [2023-02-24 18:32:17.254]
00:00:00 [2023-02-24 18:32:17.254]
00:00:00 [2023-02-24 18:32:17.254] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-02-24 18:32:17.254] Api server started at 127.0.0.1:4001
00:00:00 [2023-02-24 18:32:17.254] GPU0 Started CL work thread
00:00:00 [2023-02-24 18:32:17.254] Trying daggerhashimoto.auto.nicehash.com:9200 (ethash)
00:00:00 [2023-02-24 18:32:17.254] Trying kawpow.auto.nicehash.com:9200 (kawpow)
00:00:00 [2023-02-24 18:32:17.299] daggerhashimoto.auto.nicehash.com: Pool responded successfully to subscribe
00:00:00 [2023-02-24 18:32:17.299] kawpow.auto.nicehash.com: Pool responded to subscribe
00:00:00 [2023-02-24 18:32:17.344] daggerhashimoto.auto.nicehash.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-24 18:32:17.344] kawpow.auto.nicehash.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-02-24 18:32:17.374] kawpow.auto.nicehash.com: Pool responded successfully to authorize
00:00:00 [2023-02-24 18:32:17.389] daggerhashimoto.auto.nicehash.com: Pool responded successfully to authorize
00:00:00 [2023-02-24 18:32:17.404] daggerhashimoto.auto.nicehash.com: Difficulty is set to 0.478452
00:00:00 [2023-02-24 18:32:17.434] GPU0 Starting generating zil dag (Epoch: 0)
00:00:00 [2023-02-24 18:32:19.929] GPU0 DAG generated in 2.50 seconds (1048574kb)
00:00:00 [2023-02-24 18:32:19.929] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-24 18:32:19.965] GPU0 Starting generating ethash dag (Epoch: 553)
00:00:00 [2023-02-24 18:32:20.051] Job 0000000051a285a8
00:00:00 [2023-02-24 18:32:31.306] GPU0 DAG generated in 11.35 seconds (5578751kb)
00:00:00 [2023-02-24 18:32:31.306] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-24 18:32:31.343] GPU0 Fetching ethash dag (Epoch: 553)
00:00:00 [2023-02-24 18:32:31.343] GPU0 XIntensity set to Dynamic
00:00:00 [2023-02-24 18:32:31.360] GPU0 Dag buffer verified ok!
00:00:00 [2023-02-24 18:32:32.971] Job 0000000024016b54
00:00:00 [2023-02-24 18:32:39.923] Job 0000000024016b55
00:00:00 [2023-02-24 18:32:43.517] ETHASH: GPU0 Accepted (1/1/0) Reply: 45ms
00:00:00 [2023-02-24 18:32:46.734] Job 0000000024016b56
00:00:00 [2023-02-24 18:32:46.842] Job 0000000024016b57
00:00:00 [2023-02-24 18:32:48.482] ETHASH: GPU0 Accepted (2/2/0) Reply: 45ms
00:00:00 [2023-02-24 18:32:53.838] Job 0000000024016b58
00:00:00 [2023-02-24 18:33:00.814] Job 0000000024016b59
00:00:00 [2023-02-24 18:33:03.506] kawpow.auto.nicehash.com: Extranonce is set to dc01790000000000
00:00:00 [2023-02-24 18:33:04.135] ETHASH: GPU0 Accepted (3/3/0) Reply: 44ms
00:00:00 [2023-02-24 18:33:07.790] Job 0000000024016b5a
00:00:00 [2023-02-24 18:33:11.432] Job 0000000024016b5b
00:00:00 [2023-02-24 18:33:15.823] daggerhashimoto.auto.nicehash.com: Extranonce is set to 58a39b0000000000
00:00:00 [2023-02-24 18:33:15.836] daggerhashimoto.auto.nicehash.com: Difficulty is set to 0.478452
00:00:00 [2023-02-24 18:33:15.854] Job 0000000024016b5c
00:00:01 [2023-02-24 18:33:17.355] auto.nicehash.com (ethash)    PING: 39ms    DIFFICULTY: 0.478    EPOCH: 553
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:17.355] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-02-24 18:33:17.355] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-02-24 18:33:17.355]                                                                          0
00:00:01 [2023-02-24 18:33:17.355] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-02-24 18:33:17.355] GPU0    5700XT   0.00 H/W      11.54 MH/s    11.54 MH/s    3/0/0        100.00%
00:00:01 [2023-02-24 18:33:17.355]                  0.00 H/W      11.54 MH/s    11.54 MH/s    3/0/0        100.00%
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:17.355] SHARES PER MINUTE: 3.00                              POOL HASHRATE: 102.75 MH/s
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:17.355] auto.nicehash.com (kawpow)    PING: 25ms    DIFFICULTY: 1054.34 M    EPOCH: 53
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:17.355] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-02-24 18:33:17.355] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-02-24 18:33:17.355]                                                                          0
00:00:01 [2023-02-24 18:33:17.355] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-02-24 18:33:17.355] GPU0    5700XT   0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-02-24 18:33:17.355]                  0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:17.355] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:01 [2023-02-24 18:33:17.355]
00:00:01 [2023-02-24 18:33:20.223] Job 0000000024016b5d
00:00:01 [2023-02-24 18:33:23.951] Job 0000000024016b5e
00:00:01 [2023-02-24 18:33:26.470] Job 0000000024016b5f
00:00:01 [2023-02-24 18:33:34.127] Job 0000000024016b60
00:00:01 [2023-02-24 18:33:35.031] Job 0000000024016b61
00:00:01 [2023-02-24 18:33:45.019] Job 0000000024016b62
00:00:01 [2023-02-24 18:33:51.155] Job 0000000024016b63
00:00:01 [2023-02-24 18:33:51.262] Job 0000000024016b64
00:00:01 [2023-02-24 18:33:56.407] Job 0000000024016b65
00:00:01 [2023-02-24 18:34:06.470] Job 0000000024016b66
00:00:01 [2023-02-24 18:34:16.446] Job 0000000024016b67
00:00:02 [2023-02-24 18:34:17.314] daggerhashimoto.auto.nicehash.com: Difficulty is set to 0.239226
00:00:02 [2023-02-24 18:34:17.354] auto.nicehash.com (ethash)    PING: 39ms    DIFFICULTY: 0.239    EPOCH: 553
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:17.354] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:02 [2023-02-24 18:34:17.354] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:02 [2023-02-24 18:34:17.354]                                                                          0
00:00:02 [2023-02-24 18:34:17.354] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:02 [2023-02-24 18:34:17.354] GPU0    5700XT   0.00 H/W      11.81 MH/s    12.17 MH/s    3/0/0        100.00%
00:00:02 [2023-02-24 18:34:17.354]                  0.00 H/W      11.81 MH/s    12.17 MH/s    3/0/0        100.00%
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:17.354] SHARES PER MINUTE: 1.50                              POOL HASHRATE: 25.69 MH/s
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:17.354] auto.nicehash.com (kawpow)    PING: 25ms    DIFFICULTY: 1054.34 M    EPOCH: 53
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:17.354] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:02 [2023-02-24 18:34:17.354] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:02 [2023-02-24 18:34:17.354]                                                                          0
00:00:02 [2023-02-24 18:34:17.354] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:02 [2023-02-24 18:34:17.354] GPU0    5700XT   0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:02 [2023-02-24 18:34:17.354]                  0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:17.354] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:02 [2023-02-24 18:34:17.354]
00:00:02 [2023-02-24 18:34:22.853] daggerhashimoto.auto.nicehash.com: Extranonce is set to c5e6280000000000
00:00:02 [2023-02-24 18:34:22.868] daggerhashimoto.auto.nicehash.com: Difficulty is set to 0.239226
00:00:02 [2023-02-24 18:34:22.883] Job 0000000024016b68
00:00:02 [2023-02-24 18:34:22.903] GPU0 Starting generating ethash dag (Epoch: 31)
00:00:02 [2023-02-24 18:34:25.645] GPU0 DAG generated in 2.75 seconds (1302527kb)
00:00:02 [2023-02-24 18:34:25.669] GPU0 Fetching ethash dag (Epoch: 31)
00:00:02 [2023-02-24 18:34:28.992] Job 0000000024016b69
00:00:02 [2023-02-24 18:34:32.360] Job 0000000024016b6a
00:00:02 [2023-02-24 18:34:32.719] Job 0000000024016b6b
00:00:02 [2023-02-24 18:34:35.850] Job 0000000024016b6c
00:00:02 [2023-02-24 18:34:37.079] Job 0000000024016b6d
00:00:02 [2023-02-24 18:34:44.187] Job 0000000024016b6e
00:00:02 [2023-02-24 18:34:46.472] Job 0000000024016b6f
00:00:02 [2023-02-24 18:34:53.926] Job 0000000024016b70
00:00:02 [2023-02-24 18:34:59.222] Job 0000000024016b71
00:00:02 [2023-02-24 18:35:04.380] Job 0000000024016b72
00:00:02 [2023-02-24 18:35:05.574] Job 0000000024016b73
00:00:02 [2023-02-24 18:35:06.026] kawpow.auto.nicehash.com: Extranonce is set to 8e2d000000000000
00:00:02 [2023-02-24 18:35:12.066] Job 0000000024016b74
00:00:03 [2023-02-24 18:35:17.012] auto.nicehash.com (ethash)    PING: 39ms    VARDIFF: 0.239    EPOCH: 31
00:00:03 [2023-02-24 18:35:17.012]
00:00:03 [2023-02-24 18:35:17.012] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:03 [2023-02-24 18:35:17.012] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:03 [2023-02-24 18:35:17.012]                                                                          0
00:00:03 [2023-02-24 18:35:17.012] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:03 [2023-02-24 18:35:17.012] GPU0    5700XT   0.00 H/W      12.77 MH/s    12.58 MH/s    3/0/0        100.00%
00:00:03 [2023-02-24 18:35:17.012]                  0.00 H/W      12.77 MH/s    12.58 MH/s    3/0/0        100.00%
00:00:03 [2023-02-24 18:35:17.012]
00:00:03 [2023-02-24 18:35:17.012] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s

**Comment by UselessGuru** [comment]
Any news?

**Comment by sp-hash** [comment]
RVN on amf (5700XT) is not completed / supported yet.
