### ISSUE TITLE
Hide statistics in hiveOS amd card.

### ISSUE THREAD

**Issue by Timonchegs** [sp-hash/TeamBlackMiner#371]
I have a little difficulty displaying miner statistics in hiveOS

![image](https://user-images.githubusercontent.com/49078005/222950262-7f70fb8a-2cb5-470e-8616-9f860f56e91d.png)

![Screenshot 2023-03-05 203946](https://user-images.githubusercontent.com/49078005/222950576-2f2774d4-31d6-4219-a5ff-52d0096cabf9.png)

![Screenshot 2023-03-05 204036](https://user-images.githubusercontent.com/49078005/222950595-88c968b0-db70-4568-a68a-d529afa44bad.png)

Advise where else to configure please.

**Comment by Andozzz** [comment]
Same to me, its hashing but show Null in hiveos.
![image](https://user-images.githubusercontent.com/116953479/222953520-1bdc0c2a-001b-438f-a265-c0476fc2dc23.png)

**Comment by sp-hash** [comment]
you can try to add --api-version 1.3

**Comment by Andozzz** [comment]
> --api-version 1.3

That worked it shows in Hive now ;) Thanks

**Comment by Timonchegs** [comment]
> you can try to add --api-version 1.3 in the extra config

Thanks
