### ISSUE TITLE
Verthash miner API is not listening meanwhile building dat file.

### ISSUE THREAD

**Issue by Funereal** [sp-hash/TeamBlackMiner#375]
I'm bringing up an old issue. It seems like you fixed it few months ago, but with newer release it got broken again. So here is the copy-paste:

I'm using Minerstat with your miner to mine Vertcoin. When I first start the miner it is generating Verthash.dat, the problem is that since the Miner API is not listening until the mining process begin (so is not listening during de generation of the verthash.dat file), minerstat will try to reset the software because it sees that the rig is at idle.

Minerstat dev told me this: "they should just move few lines of code up to start API when miner starts not when miner is mining.
Easy 5 minute fix on their end"

As a quick fix, I have to put my rig in maintenance mode to desactivate all automatic behaviour of minerstat and manually start the start.bash file to generate the verthash.dat file in full.

**Comment by Funereal** [comment]
Also, even if I bypass the verthash file building and I copy it myself, the API seems to not start before a GPU start showing some hashrate. On my 12x GTX 1660S rig, it takes approx 3 min before hashrate are shown on some GPU after I start the mining process. But, I can only see this result while I run my rig in maintenance mode (so no remote control at all), because if I run my rig in normal mode, sine the API isn't detected after few mins, MSOS will restart/kill the process and launch again.

Just move the API at the start of the miner and everything will be fixed.

**Comment by sp-hash** [comment]
fixed in v1.95
