### ISSUE TITLE
v1.96 (Windows): etchash@hiveon not working

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#381]
`TBMiner.exe --algo etc+rvn --hostname etc.hiveon.com --wallet ##########################.######### --port 8888 --server-passwd x --api --api-version 1.4 --api-port 4006 --cuda-devices [0]`

```
00:00:00 [2023-08-27 18:05:39.701]
00:00:00 [2023-08-27 18:05:39.872] OpenCL driver version: 536.99
00:00:00 [2023-08-27 18:05:39.919] Cuda driver version: 12.2
00:00:00 [2023-08-27 18:05:39.919] Cuda runtime API version: 12.0
00:00:00 [2023-08-27 18:05:39.919]
00:00:00 [2023-08-27 18:05:39.919]
00:00:00 [2023-08-27 18:05:39.919]
00:00:00 [2023-08-27 18:05:39.919] Welcome to Team Black Miner 1.96
00:00:00 [2023-08-27 18:05:39.919]
00:00:00 [2023-08-27 18:05:39.919]
00:00:00 [2023-08-27 18:05:40.026] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-08-27 18:05:40.027] C:\code\tbminer\source\api.cpp:set_fee_mining_context():1527: A runtime error has occured: malloc()
00:00:00 [2023-08-27 18:05:40.027] Shutting down threads
00:00:00 [2023-08-27 18:05:40.028] Api server started at 127.0.0.1:4006
00:00:00 [2023-08-27 18:05:40.028] Api thread exited`
```
What is wrong?

**Comment by UselessGuru** [comment]
The same also happens with etchash@miningpoolhub

**Comment by sp-hash** [comment]
You have the wrong algo specified. If you want to mine rvn standalone you need to use --algo kawpow.
if you want etc+rvn you need to specify the rvn pool. --rvn-wallet --rvn-hostname --rvn-port

This will mine zil standalone on crazypool , and rvn on the hiveon pool: (6gb cards supported)

tbminer_hiveon_zil+rvn.bat

    TBMiner --algo etc+rvn --hostname eu.crazypool.org --port 5005 --wallet %zilwallet% --worker-name %computername% --rvn-wallet R9RaKw5HNuwtbXYRXWrpUugAE8WhtMhfUk.%computername% --rvn-hostname rvn.hiveon.com --rvn-port 8888
