### ISSUE TITLE
1.99 (Windows): SSL connection to pool failed with error load_verify_file

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#382]
`Bin\TeamBlackMiner-v1.99\TBMiner.exe --algo etc+rvn --hostname etchash.auto.nicehash.com --wallet **********************.********* --ssl-port 443 --server-passwd x --rvn-hostname kawpow.auto.nicehash.com --rvn-wallet *******************************.********** --rvn-port 443 --ssl --ssl-verify-none --api --api-version 1.4 --api-port 4006 --cuda-devices [0]`

00:00:00 [2023-08-30 23:38:31.783]
00:00:00 [2023-08-30 23:38:32.222] OpenCL driver version: 536.99
00:00:00 [2023-08-30 23:38:32.272] Cuda driver version: 12.2
00:00:00 [2023-08-30 23:38:32.272] Cuda runtime API version: 12.0
00:00:00 [2023-08-30 23:38:32.272]
00:00:00 [2023-08-30 23:38:32.272]
00:00:00 [2023-08-30 23:38:32.272]
00:00:00 [2023-08-30 23:38:32.272] Welcome to Team Black Miner 1.99
00:00:00 [2023-08-30 23:38:32.272]
00:00:00 [2023-08-30 23:38:32.272]
00:00:00 [2023-08-30 23:38:32.379] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-08-30 23:38:32.380] Api server started at 127.0.0.1:4006
00:00:00 [2023-08-30 23:38:32.380] Trying stratum+ssl://kawpow.auto.nicehash.com:443 (kawpow)
00:00:00 [2023-08-30 23:38:32.380] Trying stratum+ssl://etchash.auto.nicehash.com:443 (etchash)
00:00:00 [2023-08-30 23:38:32.386] etchash.auto.nicehash.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]
00:00:00 [2023-08-30 23:38:32.387] Shutting down threads
00:00:00 [2023-08-30 23:38:32.387] kawpow.auto.nicehash.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]
00:00:00 [2023-08-30 23:38:32.387] etchash.auto.nicehash.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]

**Comment by UselessGuru** [comment]
`Bin\TeamBlackMiner-v1.99\TBMiner.exe --algo etc+rvn --hostname etc.hiveon.com --wallet ********************************************.************** --ssl-port 20443 --server-passwd x --rvn-hostname kawpow.mine.zergpool.com --rvn-wallet ****************************************** --rvn-port 13638 --ssl --ssl-verify-none --api --api-version 1.4 --api-port 4006 --cuda-devices [0]`

00:00:00 [2023-08-30 23:55:15.849]
00:00:00 [2023-08-30 23:55:15.929] OpenCL driver version: 536.99
00:00:00 [2023-08-30 23:55:15.954] Cuda driver version: 12.2
00:00:00 [2023-08-30 23:55:15.954] Cuda runtime API version: 12.0
00:00:00 [2023-08-30 23:55:15.954]
00:00:00 [2023-08-30 23:55:15.954]
00:00:00 [2023-08-30 23:55:15.954]
00:00:00 [2023-08-30 23:55:15.954] Welcome to Team Black Miner 1.99
00:00:00 [2023-08-30 23:55:15.954]
00:00:00 [2023-08-30 23:55:15.954]
00:00:00 [2023-08-30 23:55:16.075] GPU0 NVIDIA GeForce GTX 1660 SUPER 6GB added to miner as Cuda device
00:00:00 [2023-08-30 23:55:16.075] Trying stratum+ssl://etc.hiveon.com:20443 (etchash)
00:00:00 [2023-08-30 23:55:16.075] Api server started at 127.0.0.1:4006
00:00:00 [2023-08-30 23:55:16.075] Trying stratum+ssl://kawpow.mine.zergpool.com:13638 (kawpow)
00:00:00 [2023-08-30 23:55:16.095] kawpow.mine.zergpool.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]
00:00:00 [2023-08-30 23:55:16.095] Shutting down threads
00:00:00 [2023-08-30 23:55:16.095] etc.hiveon.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]
00:00:00 [2023-08-30 23:55:16.095] etc.hiveon.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]

**Comment by UselessGuru** [comment]
`Bin\TeamBlackMiner-v1.99\TBMiner.exe --algo etchash --hostname etc.hiveon.com --wallet *******************.******** --ssl-port 20443 --server-passwd x --ssl --ssl-verify-none --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

00:00:00 [2023-08-30 23:59:26.445]
00:00:00 [2023-08-30 23:59:26.962] OpenCL driver version: 536.99
00:00:00 [2023-08-30 23:59:27.010] Cuda driver version: 12.2
00:00:00 [2023-08-30 23:59:27.010] Cuda runtime API version: 12.0
00:00:00 [2023-08-30 23:59:27.010]
00:00:00 [2023-08-30 23:59:27.010]
00:00:00 [2023-08-30 23:59:27.010]
00:00:00 [2023-08-30 23:59:27.010] Welcome to Team Black Miner 1.99
00:00:00 [2023-08-30 23:59:27.010]
00:00:00 [2023-08-30 23:59:27.010]
00:00:00 [2023-08-30 23:59:27.010] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-08-30 23:59:27.010] Trying stratum+ssl://etc.hiveon.com:20443 (etchash)
00:00:00 [2023-08-30 23:59:27.010] Api server started at 127.0.0.1:4001
00:00:00 [2023-08-30 23:59:27.010] GPU0 Started CL work thread
00:00:00 [2023-08-30 23:59:27.021] etc.hiveon.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]
00:00:00 [2023-08-30 23:59:27.021] Shutting down threads
00:00:00 [2023-08-30 23:59:27.021] etc.hiveon.com: SSL connection to pool failed with error load_verify_file: No such file or directory (system library, fopen) [asio.ssl:33558530]

**Comment by UselessGuru** [comment]
Any news?

**Comment by sp-hash** [comment]
this bat is working fine in v2.0
