### ISSUE TITLE
Please improve your miner documentation

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#386]
Ideally you post a complete table with the following information per algo:

Algo or algo combination
Supported devices, e.g. AMD, NVIDIA
Donation %
min. memory required
List of supported pools
SSL support (Yes / No)

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/blob/main/README.md

<h2 tabindex="-1" id="user-content-supported-algorithms-and-developer-commission" dir="auto"><a class="heading-link" href="https://github.com/sp-hash/TeamBlackMiner/blob/main/README.md#supported-algorithms-and-developer-commission">Supported algorithms and developer commission<svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h2>

Algo | Coin | Platform | Commission
-- | -- | -- | --
Ethash | EthereumPOW | Nvidia, AMD | 0.5%
Ethash | EthereumFair | Nvidia, AMD | 0.5%
Ethash | Zilliqa | Nvidia, AMD | 0.5%
Etchash | Ethereum Classic | Nvidia, AMD | 0.5%
Verthash | Vertcoin | Nvidia, AMD | 1.0%
Kawpow | Ravencoin | Nvidia | 1.0%
EthashB3 | Rethereum | Nvidia | 0.5%

[Supported algorithms and developer commission](https://github.com/sp-hash/TeamBlackMiner/blob/main/README.md#supported-algorithms-and-developer-commission)
Algo 	Coin 	Platform 	Commission
Ethash 	EthereumPOW 	Nvidia, AMD 	0.5%
Ethash 	EthereumFair 	Nvidia, AMD 	0.5%
Ethash 	Zilliqa 	Nvidia, AMD 	0.5%
Etchash 	Ethereum Classic 	Nvidia, AMD 	0.5%
Verthash 	Vertcoin 	Nvidia, AMD 	1.0%
Kawpow 	Ravencoin 	Nvidia 	1.0%
EthashB3 	Rethereum 	Nvidia 	0.5%

**Comment by UselessGuru** [comment]
Good start. Thank you!
What about the available dual mining combinations?
What about Intel?

**Comment by UselessGuru** [comment]
Any news?

**Comment by sp-hash** [comment]
all algos are now AMD/NVIDIA closing
