### ISSUE TITLE
2.02 (Windows): Kawpow not working with AMD RX580 8GB

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#391]
`TeamBlackMiner-v2.02>TBMiner.exe --algo kawpow --hostname kawpow.eu.mine.zpool.ca --wallet *********************--ssl --ssl-verify-none --ssl-port 51325 --server-passwd **********,c=BTC,zap=GPN --api --api-version 1.4 --api-port 4005 --cl-devices [1]`

00:00:00 [2023-10-08 21:44:25.214]
00:00:00 [2023-10-08 21:44:25.277] OpenCL driver version: 351.457
00:00:00 [2023-10-08 21:44:25.308] Cuda driver version: 12.2
00:00:00 [2023-10-08 21:44:25.308] Cuda runtime API version: 12.2
00:00:00 [2023-10-08 21:44:25.308]
00:00:00 [2023-10-08 21:44:25.308]
00:00:00 [2023-10-08 21:44:25.308]
00:00:00 [2023-10-08 21:44:25.308] Welcome to Team Black Miner 2.02
00:00:00 [2023-10-08 21:44:25.308]
00:00:00 [2023-10-08 21:44:25.308]
00:00:00 [2023-10-08 21:44:25.308] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2023-10-08 21:44:25.308] Api server started at 127.0.0.1:4005
00:00:00 [2023-10-08 21:44:25.308] Trying stratum+ssl://kawpow.eu.mine.zpool.ca:51325 (kawpow)
00:00:00 [2023-10-08 21:44:25.683] kawpow.eu.mine.zpool.ca: Pool responded to subscribe
00:00:00 [2023-10-08 21:44:26.011] kawpow.eu.mine.zpool.ca: Pool responded successfully to extranonce subscribe
00:00:00 [2023-10-08 21:44:26.027] kawpow.eu.mine.zpool.ca: Pool responded successfully to authorize
00:00:00 [2023-10-08 21:44:27.074] Job 3143
**Build log for Ellesmere:
Error: HSAIL doesn't support OpenCL extension spir.
An invalid option was specified.
Error: Compiling CL to IR**

**Comment by sp-hash** [comment]
should be ok in 2.03
