### ISSUE TITLE
2.02 (Windows): Kawpow crashing on RX5700

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#392]
`TBMiner.exe --algo kawpow --hostname kawpow.eu.mine.zpool.ca --wallet ************************* --ssl --ssl-verify-none --ssl-port 51325 --server-passwd ***********,c=BTC,zap=GPN --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

00:00:00 [2023-10-08 22:01:15.325]
00:00:00 [2023-10-08 22:01:15.387] OpenCL driver version: 351.440
00:00:00 [2023-10-08 22:01:15.412] Cuda driver version: 12.2
00:00:00 [2023-10-08 22:01:15.412] Cuda runtime API version: 12.2
00:00:00 [2023-10-08 22:01:15.412]
00:00:00 [2023-10-08 22:01:15.412]
00:00:00 [2023-10-08 22:01:15.412]
00:00:00 [2023-10-08 22:01:15.412] Welcome to Team Black Miner 2.02
00:00:00 [2023-10-08 22:01:15.412]
00:00:00 [2023-10-08 22:01:15.412]
00:00:00 [2023-10-08 22:01:15.412] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-10-08 22:01:15.413] Api server started at 127.0.0.1:4001
00:00:00 [2023-10-08 22:01:15.413] Trying stratum+ssl://kawpow.eu.mine.zpool.ca:51325 (kawpow)
00:00:00 [2023-10-08 22:01:15.777] kawpow.eu.mine.zpool.ca: Pool responded to subscribe
00:00:00 [2023-10-08 22:01:16.101] kawpow.eu.mine.zpool.ca: Pool responded successfully to extranonce subscribe
00:00:00 [2023-10-08 22:01:16.117] kawpow.eu.mine.zpool.ca: Pool responded successfully to authorize
00:00:00 [2023-10-08 22:01:17.356] Job 14a7
00:00:00 [2023-10-08 22:01:18.176] GPU0 generating kawpow DAG (Epoch: 30)
00:00:00 [2023-10-08 22:01:22.994] GPU0 kawpow dag generated (Epoch: 30)
00:00:00 [2023-10-08 22:01:23.783] Job 14b5

Then back to commandline witout any error message.

**Comment by sp-hash** [comment]
please try again with 2.01. Does it work without ssl?

**Comment by UselessGuru** [comment]
Working in 2.03.

All errors I have reported recently are the same , regardless of SSL.
