### ISSUE TITLE
archive name and folder name are not same

### ISSUE THREAD

**Issue by EugeneRymarev** [sp-hash/TeamBlackMiner#398]
Archive name: `TeamBlackMiner_2_04_Ubuntu_20_04_Cuda_12` - **20**
Folder name in archive: `TeamBlackMiner_2_04_Ubuntu_18_04_Cuda_12` - **18**
Please fix this or remove the Ubuntu version from the miner version altogether - in my opinion, it is superfluous there.

**Comment by sp-hash** [comment]
fixed
