### ISSUE TITLE
ProHashing Pool support

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#4]
TBMiner.exe --algo ethash --hostname eu.prohashing.com --port 3358 --wallet ############### --worker_name ###### --server_passwd a=Ethash-LowMemory,n=##########,o=###########,l=1.8671875 --cuda-devices 1

Output:
     0m [2021-09-07 19:37:25.167] Sorry the provided pool is not supported
     0m [2021-09-07 19:37:25.167] If you think this pool should be, then ask us to configure it
     0m [2021-09-07 19:37:25.167] Shutting down threads
     0m [2021-09-07 19:37:29.173] Exiting

**Comment by sp-hash** [comment]
added
