### ISSUE TITLE
Pool Stratum connection fails

### ISSUE THREAD

**Issue by KillrBee** [sp-hash/TeamBlackMiner#40]
Miner throws the following errors:  WoolyPooly.com

**************

     0m [2021-09-28 09:19:50.301] GPU0 thread exited
     0m [2021-09-28 09:19:50.784] C:\gc\TBMiner\source\sp_stratum\eth_stratum_pool.cpp:sp_pool_connect():180: A curl runtime error occured: Couldn't connect to server
     0m [2021-09-28 09:19:50.784] Shutting down threads
     0m [2021-09-28 09:19:54.300] Exiting

Followed by the following on reconnection:

     0m [2021-09-28 09:17:35.719]
     0m [2021-09-28 09:17:35.719] Welcome to Team Black Miner 1.09
     0m [2021-09-28 09:17:35.719]
     0m [2021-09-28 09:17:35.719]
     0m [2021-09-28 09:17:35.796] GPU0 NVIDIA GeForce RTX 3090 25GB added to miner as Cuda device
     0m [2021-09-28 09:17:35.908] GPU0 Started Cuda work thread
     0m [2021-09-28 09:17:38.035] Cannot connect to mining pool. Retrying...
     0m [2021-09-28 09:17:38.035] Sleeping for 10 seconds
     0m [2021-09-28 09:17:38.055] Cannot connect to mining pool. Retrying...
     0m [2021-09-28 09:17:38.056] Sleeping for 15 seconds
     0m [2021-09-28 09:17:50.285] Cannot connect to mining pool. Retrying...
     0m [2021-09-28 09:17:50.285] Sleeping for 10 seconds
     0m [2021-09-28 09:17:55.283] Cannot connect to mining pool. Retrying...
     0m [2021-09-28 09:17:55.283] Sleeping for 15 seconds
     0m [2021-09-28 09:18:02.508] Cannot connect to mining pool. Retrying...
     0m [2021-09-28 09:18:02.797] Sleeping for 10 seconds

T-Rex miner is able to connect and mine 
Change of IP using VPN does not affect connectivity

After several minutes the issue resolved itself and the miner was able to reconnect on launch

**Comment by sp-hash** [comment]
Did you get a rejected duplicate share? We had an issue some releases ago.

The pool will ban you for a while if you submit duplicates.
