### ISSUE TITLE
v2.07 (Windows): etc+rvn No KawPow hashrate on RX5700

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#403]
`Bin\TeamBlackMiner-v2.07\TBMiner.exe --algo etc+rvn --hostname europe.etchash-hub.miningpoolhub.com --wallet ****************.********* --port 20615 --server-passwd x --rvn-hostname kawpow.eu.mine.zergpool.com --rvn-wallet ***************** --rvn-passwd c=BTC,mc=CLORE,ID=*********** ,pl=0 --rvn-port 3638 --api --api-version 1.4 --api-port 4001 --cl-devices [0]
`
00:00:00 [2023-10-31 11:21:04.245]
00:00:00 [2023-10-31 11:21:04.366] OpenCL driver version: 537.42
00:00:00 [2023-10-31 11:21:04.418] Cuda driver version: 12.2
00:00:00 [2023-10-31 11:21:04.418] Cuda runtime API version: 12.2
00:00:00 [2023-10-31 11:21:04.418]
00:00:00 [2023-10-31 11:21:04.418]
00:00:00 [2023-10-31 11:21:04.418]
00:00:00 [2023-10-31 11:21:04.418] Welcome to Team Black Miner 2.07
00:00:00 [2023-10-31 11:21:04.418]
00:00:00 [2023-10-31 11:21:04.418]
00:00:00 [2023-10-31 11:21:04.418] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-10-31 11:21:04.419] Trying kawpow.eu.mine.zergpool.com:3638 (kawpow)
00:00:00 [2023-10-31 11:21:04.419] Api server started at 127.0.0.1:4001
00:00:00 [2023-10-31 11:21:04.419] Trying europe.etchash-hub.miningpoolhub.com:20615 (etchash)
00:00:00 [2023-10-31 11:21:04.420] GPU0 Started CL work thread
00:00:00 [2023-10-31 11:21:04.488] europe.etchash-hub.miningpoolhub.com: Pool responded successfully to subscribe
00:00:00 [2023-10-31 11:21:04.518] europe.etchash-hub.miningpoolhub.com: Difficulty is set to 3.000000
00:00:00 [2023-10-31 11:21:04.549] europe.etchash-hub.miningpoolhub.com: Pool responded successfully to authorize
00:00:00 [2023-10-31 11:21:04.549] GPU0 Starting generating etchash dag (Epoch: 310)
00:00:00 [2023-10-31 11:21:04.564] kawpow.eu.mine.zergpool.com: Pool responded to subscribe
00:00:00 [2023-10-31 11:21:04.639] kawpow.eu.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-10-31 11:21:04.702] kawpow.eu.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-10-31 11:21:07.549] Job 20749 (kawpow)
00:00:00 [2023-10-31 11:21:08.794] GPU0 generating kawpow DAG (Epoch: 62)
00:00:00 [2023-10-31 11:21:12.264] GPU0 DAG generated in 7.71 seconds (3588093kb)
00:00:00 [2023-10-31 11:21:12.264] GPU0 XIntensity set to Dynamic
00:00:00 [2023-10-31 11:21:12.296] GPU0 Fetching etchash dag (Epoch: 310)
00:00:00 [2023-10-31 11:21:12.297] GPU0 XIntensity set to Dynamic
00:00:00 [2023-10-31 11:21:12.809] GPU0 Dag buffer verified ok!
00:00:00 [2023-10-31 11:21:31.862] Job 9fa3 (etchash)
00:00:00 [2023-10-31 11:21:35.174] Job 9fa4 (etchash)
00:00:00 [2023-10-31 11:21:43.350] Job 9fa5 (etchash)
00:00:00 [2023-10-31 11:21:47.121] Job 9fa6 (etchash)
00:00:00 [2023-10-31 11:21:59.412] Job 9fa7 (etchash)
00:00:00 [2023-10-31 11:22:02.107] Job 9fa8 (etchash)
00:00:00 [2023-10-31 11:22:02.647] Job 9fac (etchash)
00:00:01 [2023-10-31 11:22:05.577] miningpoolhub.com (etchash)    PING: 14ms    DIFFICULTY: 3.00     EPOCH: 310
00:00:01 [2023-10-31 11:22:05.577]
00:00:01 [2023-10-31 11:22:05.577] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-10-31 11:22:05.577] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-10-31 11:22:05.577]                                                                          0
00:00:01 [2023-10-31 11:22:05.577] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-10-31 11:22:05.577] GPU0    5700XT   0.00 H/W      54.83 MH/s    55.38 MH/s    0/0/0        100.00%
00:00:01 [2023-10-31 11:22:05.577]                  0.00 H/W      54.83 MH/s    55.38 MH/s    0/0/0        100.00%
00:00:01 [2023-10-31 11:22:05.577]
00:00:01 [2023-10-31 11:22:05.577] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:01 [2023-10-31 11:22:05.577]
00:00:01 [2023-10-31 11:22:05.577] eu.mine.zergpool.com (kawpow)    PING: 60ms    DIFFICULTY: 429.50 M    EPOCH: 62
00:00:01 [2023-10-31 11:22:05.577]
00:00:01 [2023-10-31 11:22:05.577] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-10-31 11:22:05.577] GPU0    5700XT   OpenCL  0       0       0/0     46      2040    1840    0
00:00:01 [2023-10-31 11:22:05.577]                                                                          0
00:00:01 [2023-10-31 11:22:05.577] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-10-31 11:22:05.577] GPU0    5700XT   0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-10-31 11:22:05.577]                  0.00 H/W      0.00 H/s      0.00 H/s      0/0/0        100.00%
00:00:01 [2023-10-31 11:22:05.577]
00:00:01 [2023-10-31 11:22:05.577] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s

RX580 (8GB) with same parameters is working fine

**Comment by sp-hash** [comment]
fixed in v2.08

**Comment by UselessGuru** [comment]
Not fixed in 2.08.

I use 

`TeamBlackMiner-v2.08\TBMiner.exe --algo etc+rvn --hostname europe.etchash-hub.miningpoolhub.com --wallet ************.***********--port 20615 --server-passwd x --rvn-hostname kawpow.eu.mine.zpool.ca --rvn-wallet ************** --rvn-passwd *********,c=BTC,zap=XNA --rvn-port 1325 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

RX580 with same parameters is OK.

**Comment by sp-hash** [comment]
its just very slow. Dag will take forever to complete. Run with --zil-only for the best speed on AMD.

**Comment by UselessGuru** [comment]
Thank you for v2.11.
I will run a complete re-test for all Algo / Pool combos that NemosMiner supports and post my findings in a new Issue.
