### ISSUE TITLE
v2.07 (Windows): Error ming KawPow@ZPool/ZergPool when using 'mc=[currency]' in password field

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#404]
`TeamBlackMiner-v2.07\TBMiner.exe --algo kawpow --hostname kawpow.eu.mine.zergpool.com --wallet *********************** --ssl --ssl-verify-none --ssl-port 13638 --server-passwd c=BTC,mc=RVN,ID=***************,pl=0 --api --api-version 1.4 --api-port 4004 --cl-devices [1]`

Miner has issue with 'mc=RVN'
--server-passwd c=BTC,mc=RVN,ID=***************,pl=0
I can reproduce this with ZPool & ZergPool. I have not tested other pools.

00:00:00 [2023-10-31 16:34:27.266]
00:00:00 [2023-10-31 16:34:27.360] OpenCL driver version: 537.42
00:00:00 [2023-10-31 16:34:27.391] Cuda driver version: 12.2
00:00:00 [2023-10-31 16:34:27.391] Cuda runtime API version: 12.2
00:00:00 [2023-10-31 16:34:27.391]
00:00:00 [2023-10-31 16:34:27.391]
00:00:00 [2023-10-31 16:34:27.391]
00:00:00 [2023-10-31 16:34:27.391] Welcome to Team Black Miner 2.07
00:00:00 [2023-10-31 16:34:27.391]
00:00:00 [2023-10-31 16:34:27.391]
00:00:00 [2023-10-31 16:34:27.391] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2023-10-31 16:34:27.391] Trying stratum+ssl://kawpow.eu.mine.zergpool.com:13638 (kawpow)
00:00:00 [2023-10-31 16:34:27.391] Api server started at 127.0.0.1:4004
00:00:00 [2023-10-31 16:34:57.609] kawpow.eu.mine.zergpool.com: Pool responded to subscribe
00:00:00 [2023-10-31 16:34:57.687] kawpow.eu.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-10-31 16:34:57.749] kawpow.eu.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-10-31 16:35:00.673] Job 21de3 (kawpow)
00:00:00 [2023-10-31 16:35:01.433] GPU0 generating kawpow DAG (Epoch: 405)
00:00:00 [2023-10-31 16:35:02.904] GPU0 kawpow dag generated (Epoch: 405)
00:00:01 [2023-10-31 16:35:28.555] zergpool.com (kawpow)    PING: 30072ms    DIFFICULTY: 429.50 M    EPOCH: 405
00:00:01 [2023-10-31 16:35:28.555]
00:00:01 [2023-10-31 16:35:28.555] ID      BOARD    TYPE    KERN    XINT    TEMP    FAN     CORE    MEM     WATT
00:00:01 [2023-10-31 16:35:28.555] GPU0    580S     OpenCL  0       0       0/0     0       0       0       0
00:00:01 [2023-10-31 16:35:28.555]                                                                          0
00:00:01 [2023-10-31 16:35:28.555] ID      BOARD    HASHRATE/W    HASHRATE      AVERAGE       SHARES       RATE
00:00:01 [2023-10-31 16:35:28.555] GPU0    580S     0.00 H/W      9476.98 kH/s  9373.02 kH/s  0/0/0        100.00%
00:00:01 [2023-10-31 16:35:28.555]                  0.00 H/W      9476.98 kH/s  9373.02 kH/s  0/0/0        100.00%
00:00:01 [2023-10-31 16:35:28.555]
00:00:01 [2023-10-31 16:35:28.555] SHARES PER MINUTE: 0.00                              POOL HASHRATE: 0.00 H/s
00:00:01 [2023-10-31 16:35:28.555]
00:00:01 [2023-10-31 16:35:40.091] KAWPOW: GPU0 Rejected (0/1/0) Reply: 123ms
00:00:01 [2023-10-31 16:35:40.091] mining.submit: Pool reponded with error
00:00:01 [2023-10-31 16:35:40.091] Error(26): Low difficulty share
00:00:01 [2023-10-31 16:35:41.962] Job 21def (kawpow)

When omitting ',mc=RVN' mining works.
Other miners (I tested BZMiner & GMiner) work fine when setting '.mc=[currency]'.

**Comment by sp-hash** [comment]
fixed in v2.08
