### ISSUE TITLE
v2.07 (Windows): 'mining.submit: Pool reponded with error' when mining KawPow@hashcryptos.com/mining-dutch.nl/prohashing.com/miningpoolhub.com/nicehash.com

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#405]
`Bin\TeamBlackMiner-v2.07\TBMiner.exe --algo kawpow --hostname stratum4.hashcryptos.com --wallet ******************** .********--port 9985 --server-passwd ****************** --server-passwd ************* --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

```
00:00:00 [2023-10-31 16:59:52.123]
00:00:00 [2023-10-31 16:59:52.196] OpenCL driver version: 537.42
00:00:00 [2023-10-31 16:59:52.217] Cuda driver version: 12.2
00:00:00 [2023-10-31 16:59:52.217] Cuda runtime API version: 12.2
00:00:00 [2023-10-31 16:59:52.217]
00:00:00 [2023-10-31 16:59:52.217]
00:00:00 [2023-10-31 16:59:52.217]
00:00:00 [2023-10-31 16:59:52.217] Welcome to Team Black Miner 2.07
00:00:00 [2023-10-31 16:59:52.217]
00:00:00 [2023-10-31 16:59:52.217]
00:00:00 [2023-10-31 16:59:52.217] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-10-31 16:59:52.217] Api server started at 127.0.0.1:4001
00:00:00 [2023-10-31 16:59:52.217] Trying stratum4.hashcryptos.com:9985 (kawpow)
00:00:00 [2023-10-31 16:59:52.609] stratum4.hashcryptos.com: Pool responded to subscribe
00:00:00 [2023-10-31 16:59:52.656] stratum4.hashcryptos.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-10-31 16:59:53.631] stratum4.hashcryptos.com: Pool responded successfully to authorize
00:00:00 [2023-10-31 16:59:55.358] Job 6e656f78612d63386561 (kawpow)
00:00:00 [2023-10-31 16:59:56.143] GPU0 generating kawpow DAG (Epoch: 101)
00:00:00 [2023-10-31 17:00:03.318] GPU0 kawpow dag generated (Epoch: 101)
00:00:00 [2023-10-31 17:00:08.646] KAWPOW: GPU0 Rejected (0/1/0) Reply: 61ms
00:00:00 [2023-10-31 17:00:08.646] mining.submit: Pool reponded with error
00:00:00 [2023-10-31 17:00:09.045] KAWPOW: GPU0 Rejected (0/2/0) Reply: 51ms
00:00:00 [2023-10-31 17:00:09.045] mining.submit: Pool reponded with error
00:00:00 [2023-10-31 17:00:10.129] KAWPOW: GPU0 Rejected (0/3/0) Reply: 62ms
00:00:00 [2023-10-31 17:00:10.129] mining.submit: Pool reponded with error
```

Other miners (I tested BZMiner & Gminer) work fine for KawPow@HashCryptos.com, @mining-dutch.nl, @prohashing.com, miningpoolhub or nicehash.com

**Comment by sp-hash** [comment]
fixed in v2.08

**Comment by UselessGuru** [comment]
v2.08 is confirmed to work with NiceHash & MiningPoolHub

But:
**Error message is gone, but mining does not work (DAG not built, no GPU memory get allocated & no hasrate) with
- HashCryptos
- MiningDutch
- ProHashing**

`TBMiner.exe --algo kawpow --hostname stratum1.hashcryptos.com --wallet ********************* --port 9985 --server-passwd x --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

`TBMiner.exe --algo kawpow --hostname europe.mining-dutch.nl --wallet ******************.***********--port 9985 --server-passwd Blackbox,c=BTC --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

`TBMiner.exe --algo kawpow --hostname eu.mining.prohashing.com --wallet ********************--port 3361 --server-passwd a=kawpow,n=*************--api --api-version 1.4 --api-port 4001 --cl-devices [0]`

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Thank you for v2.11.
I will run a complete re-test for all Algo / Pool combos that NemosMiner supports and post my findings in a new Issue.
