### ISSUE TITLE
2.08 Ubuntu 18 not work.

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [sp-hash/TeamBlackMiner#407]
Hi. I see that since this version you no longer support Ubuntu 20.
Can you prepare binary also for this system? SimpleMining is actually support only up to Ubuntu 20.

./TBMiner --help
./TBMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./TBMiner)
./TBMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./TBMiner)
./TBMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./TBMiner)
./TBMiner: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./TBMiner)
./TBMiner: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./TBMiner)
./TBMiner: libcrypto.so.3: version `OPENSSL_3.0.0' not found (required by ./TBMiner)
./TBMiner: libssl.so.3: version `OPENSSL_3.0.0' not found (required by ./TBMiner)
(those libs are only available since Ubuntu 22)

Thanks

**Comment by sp-hash** [comment]
We are working on a build..

**Comment by sp-hash** [comment]
A working 20.04 build has been added. It crash on hiveos with 18.04, but works on SMOS with 20.04
