### ISSUE TITLE
v2.07 (Windows): Loading ZIL DAG for no reason (follow up)

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#408]
https://github.com/sp-hash/TeamBlackMiner/issues/406

I don't have a ZIL wallet in my config Why should it build a ZIL DAG. Other miner don't do this.
I don't want to dedicate ZIL hashpower to someone else.

**Comment by sp-hash** [comment]
ZIL is ETHASH epoch 1. On multipools you mine many different coins with payout in the currency you choose.

**Comment by sp-hash** [comment]
in 2.08 there is a --zil-only option that will ignore all other ethash jobs than ZIL. This can improve dual mining performance
