### ISSUE TITLE
v2.08 (Windows): Verthash not working @ZPool (single & dual mining)

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#412]
`TeamBlackMiner-v2.08\TBMiner.exe --algo verthash --verthash-data ..\..\Cache\VertHash.dat --hostname verthash.eu.mine.zpool.ca --wallet ************************* --port 6144 --server-passwd **********,c=BTC --api --api-version 1.4 --api-port 4004 --cl-devices [1]`

Miner connects and subscribes successfully, but never starts mining. I tested with NVIDIA GTX1660 Super, AMD RX580 & RX5700. They all fail.
The same is true for dual mining.

Other pools are working I tested Mining-Dutch, HashCryptos  & ZergPool.

**Comment by sp-hash** [comment]
I failed to reproduce this in 2.09

**Comment by UselessGuru** [comment]
Seem to be an intermitting pool issue. Sometimes it works, sometimes not.

**Comment by sp-hash** [comment]
can you test with 2.10 please

**Comment by sp-hash** [comment]
2.11 has been released with a fix for this

**Comment by UselessGuru** [comment]
Thank you for v2.11.
I will run a complete re-test for all Algo / Pool combos that NemosMiner supports and post my findings in a new Issue.
