### ISSUE TITLE
TeamBlackMiner version 2.09 does not lift or does not work.

### ISSUE THREAD

**Issue by croelanjr** [sp-hash/TeamBlackMiner#413]
Dear SP-HASH, 
I have been using teamblackminer version 2.08, it works fine in Ubuntu 18.04, I have changed to the latest version 2.09, it does not work, it freezes in the Ubuntu 18.04 operating system, please give the solution to the latest version.

Version 2.08
![Captura1](https://github.com/sp-hash/TeamBlackMiner/assets/7844532/44429aff-f4ec-4051-811f-eac9e8098786)

Version 2.09
I have waited more than 5 minutes, nothing comes out. And I had to go back to the previous version.

![Captura2](https://github.com/sp-hash/TeamBlackMiner/assets/7844532/d347cf6a-b527-411c-9f0f-4e7a40cbe6b9)

**Comment by sp-hash** [comment]
try 2.10 it was buildt for 18.04
