### ISSUE TITLE
v2.10 (Windows): Miner crashing when querying API [GTX 10660 Super]

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#415]
`TeamBlackMiner-v2.10\TBMiner.exe --algo eth+rvn --hostname ethash.eu.mine.zergpool.com --wallet ********************** --port 9999 --server-passwd c=BTC,mc=AVS,ID=Blackbox --rvn-hostname kawpow.eu.mine.zergpool.com --rvn-wallet ***************************** --rvn-passwd c=BTC,mc=CLORE,ID=*************** --rvn-port 3638 --api --api-version 1.4 --api-port 4006 --cuda-devices [0]`

Starts mining OK.

As soon as I attempt to query the API on 'http://127.0.0.1:4006/summary' the miner crashes.

**Comment by sp-hash** [comment]
thanks. We managed to reproduce and fix this. A new 2.10 exe has been uploaded
