### ISSUE TITLE
v2.10 (Windows): Miner crashing

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#416]
`TeamBlackMiner-v2.10\TBMiner.exe --algo eth+rvn --hostname ethash.eu.mine.zergpool.com --wallet ************************** --port 9999 --server-passwd c=BTC,mc=AVS,ID=****************** --rvn-hostname kawpow.eu.mine.zergpool.com --rvn-wallet ************************** --rvn-passwd c=BTC,mc=CLORE,ID=******************* --rvn-port 3638 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

![image](https://github.com/sp-hash/TeamBlackMiner/assets/30080938/1cfc486e-4629-4dfa-8d8e-060ea47bf3b9)

`TeamBlackMiner-v2.10\TBMiner.exe --algo eth+rvn --hostname ethash.eu.mine.zergpool.com --wallet ****************** --port 9999 --server-passwd c=BTC,mc=AVS,ID=******************* --rvn-hostname kawpow.eu.mine.zergpool.com --rvn-wallet ******************** --rvn-passwd c=BTC,mc=CLORE,ID=********************** --rvn-port 3638 --api --api-version 1.4 --api-port 4004 --cl-devices [1]`

![image](https://github.com/sp-hash/TeamBlackMiner/assets/30080938/3133f96e-cf6c-47dc-a396-6b86a93a1b89)

These are just 2 examples of many pool/algo combinations.

Do you have a private email / discord channel where I can upload my full commandlines and test results?

**Comment by sp-hash** [comment]
2.11 has been released with a fix for this

**Comment by UselessGuru** [comment]
Thank you for v2.11.
I will run a complete re-test for all Algo / Pool combos that NemosMiner supports and post my findings in a new Issue.
