### ISSUE TITLE
How to mine EthashB3+Verthash??

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#418]
EthashB3+Verthash is a supported algo combo (https://github.com/sp-hash/TeamBlackMiner#supported-dual-mining-and-tripple-mining-combos-and-developer-commission)

I tried  --algo  eth3b+vtc  but get this:

00:00:00 [2023-12-03 15:04:16.869] You have to specify a valid protocol
00:00:00 [2023-12-03 15:04:16.869] **Valid protocols are zil, ethash, etchash, verthash, kawpow, eth+vtc, eth+rvn, etc+vtc, eth+ethb3, etc+ethb3 and etc+rvn**
00:00:00 [2023-12-03 15:04:16.869] Shutting down threads

**Comment by sp-hash** [comment]
not 3b but b3
try:
ethb3+vtc

**Comment by UselessGuru** [comment]
> ethb3+vtc

Thank you - stupid type.

Still you should update the list of valid protocols:
Valid protocols are zil, ethash, etchash, verthash, kawpow, eth+vtc, eth+rvn, etc+vtc, eth+ethb3, etc+ethb3 and etc+rvn
