### ISSUE TITLE
v2.12 (Windows): Miner crashing when querying API

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#419]
`TeamBlackMiner-v2.11\TBMiner.exe --algo ethb3+rvn --hostname ethashb3.eu.mine.zergpool.com --wallet *********************** --port 9996 --server-passwd c=BTC,ID=******************** --rvn-hostname stratum1.hashcryptos.com --rvn-wallet *********************** --rvn-passwd x --rvn-port 9985 --api --api-version 1.4 --api-port 4004 --cl-devices [1]`

Second algorithm (rvn) never starts:

00:00:00 [2023-12-03 15:55:52.902]
00:00:00 [2023-12-03 15:55:52.968] OpenCL driver version: 546.1
00:00:00 [2023-12-03 15:55:53.004] Cuda driver version: 12.3
00:00:00 [2023-12-03 15:55:53.004] Cuda runtime API version: 12.0
00:00:00 [2023-12-03 15:55:53.004]
00:00:00 [2023-12-03 15:55:53.004]
00:00:00 [2023-12-03 15:55:53.004]
00:00:00 [2023-12-03 15:55:53.004] Welcome to Team Black Miner 2.11
00:00:00 [2023-12-03 15:55:53.004]
00:00:00 [2023-12-03 15:55:53.004]
00:00:00 [2023-12-03 15:55:53.004] GPU0 Ellesmere 8GB added to miner as OpenCL device
00:00:00 [2023-12-03 15:55:53.004] Trying ethashb3.eu.mine.zergpool.com:9996 (ethb3+rvn)
00:00:00 [2023-12-03 15:55:53.004] Api server started at 127.0.0.1:4004
00:00:00 [2023-12-03 15:55:53.168] ethashb3.eu.mine.zergpool.com: Pool responded successfully to subscribe
00:00:00 [2023-12-03 15:55:53.253] ethashb3.eu.mine.zergpool.com: Pool responded successfully to extranonce subscribe
00:00:00 [2023-12-03 15:55:53.268] ethashb3.eu.mine.zergpool.com: Extranonce is set to 9769000000000000
00:00:00 [2023-12-03 15:55:53.347] ethashb3.eu.mine.zergpool.com: Pool responded successfully to authorize
00:00:00 [2023-12-03 15:55:53.362] ethashb3.eu.mine.zergpool.com: Difficulty is set to 0.249996
...
nothing more.

As soon as I attempt to query the API on 'http://127.0.0.1:4004/summary' the miner crashes.

**Comment by UselessGuru** [comment]
Still happening with 2.12. I tried with RTH@zergPool and different pools for RVN.
Miner crashes in any case when accessing API.

**Comment by sp-hash** [comment]
fixed in 2.13
