### ISSUE TITLE
[BUG] New API not working in v1.10

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#42]
Two things, I have noticed:
- if we call any API endpoint with curl (this example is http://127.0.0.1:36500/threads, parameters `--api --api-port 36500`), we get:

1 | UNSUPPORTED_PROTOCOL | The URL you passed to libcurl used a protocol that this “curl.exe” does not support. it can be a misspelled protocol string or just a protocol that curl has no code for.
-- | -- | --

- calling the API seems to slow down the miner heavily. Since we ping the miner every 10 seconds, the start + creation of DAG takes a couple of minutes.

**Comment by sp-hash** [comment]
We have added a http header in v1.11 so you can open it in a browser. 
Statistics are not available until the miner starts and have enough values to produce average. shouldn't take minutes. 20-30 secs or less for the rig is normally enough

**Comment by UselessGuru** [comment]
> We have added a http header in v1.11 so you can open it in a browser.

Where is v1.11?
