### ISSUE TITLE
v2.13new (Windows): Etchash/Ethash & Kawpow dual mining broken with Rx5700

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#424]
from https://github.com/sp-hash/TeamBlackMiner/issues/421

> A new version of 2.13 is uploaded with a fix for this

Nope. Still not fixed (with new 2.13). It is annoying to report same issue again and again. Can't you test yourself?

**Comment by sp-hash** [comment]
seems to be working here
![image](https://github.com/sp-hash/TeamBlackMiner/assets/9572668/3cff6269-c2ac-43dc-ae10-f8ddd1794ca9)

**Comment by sp-hash** [comment]
Miningpoolhub+zergpool also working
![image](https://github.com/sp-hash/TeamBlackMiner/assets/9572668/518aeff9-3c0f-4e22-a4c9-120c4bce401e)

**Comment by UselessGuru** [comment]
`Bin\TeamBlackMiner-v2.13\TBMiner.exe --algo eth+rvn --hostname ethash.eu.mine.zergpool.com --wallet ********************* --port 9999 --server-passwd c=BTC,mc=AVS,ID=**************** --rvn-hostname stratum1.hashcryptos.com --rvn-wallet ******************************* --rvn-passwd x --rvn-port 9985 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

`Bin\TeamBlackMiner-v2.13\TBMiner.exe --algo eth+rvn --hostname ethash.eu.mine.zergpool.com --wallet ************************* --port 9999 --server-passwd c=BTC,mc=XPB,ID=******************* --rvn-hostname europe.mining-dutch.nl --rvn-wallet **********************.******************* --rvn-passwd Blackbox,c=BTC --rvn-port 9985 --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

No hashrate for KawPow.

**Comment by sp-hash** [comment]
The same bat is working here.
![image](https://github.com/sp-hash/TeamBlackMiner/assets/9572668/8015ed7b-a613-478e-842e-7b20f86a6d1c)

**Comment by sp-hash** [comment]
cryptohash.com was fixed in v2.14
