### ISSUE TITLE
v2.14 (Windows): Error mining FiroPow@ZergPool with RX580 & RX5700

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#425]
`c:\Users\*********************************\Desktop\NemosMiner\Bin\TeamBlackMiner-v2.14>TBMiner.exe --algo firopow --hostname firopow.eu.mine.zergpool.com --wallet ********************************** --port 3001 --server-passwd c=BTC,ID=***************** --api --api-version 1.4 --api-port 4001 --cl-devices [0]`

```
00:00:00 [2023-12-11 11:21:41.195]
00:00:00 [2023-12-11 11:21:41.266] OpenCL driver version: 546.1
00:00:00 [2023-12-11 11:21:41.301] Cuda driver version: 12.3
00:00:00 [2023-12-11 11:21:41.301] Cuda runtime API version: 12.0
00:00:00 [2023-12-11 11:21:41.301]
00:00:00 [2023-12-11 11:21:41.301]
00:00:00 [2023-12-11 11:21:41.301]
00:00:00 [2023-12-11 11:21:41.301] Welcome to Team Black Miner 2.14
00:00:00 [2023-12-11 11:21:41.301]
00:00:00 [2023-12-11 11:21:41.301]
00:00:00 [2023-12-11 11:21:41.301] GPU0 gfx1010:xnack- 8GB added to miner as OpenCL device
00:00:00 [2023-12-11 11:21:41.303] Trying firopow.eu.mine.zergpool.com:3001 (firopow)
```

c:\Users\****************************\Desktop\NemosMiner\Bin\TeamBlackMiner-v2.14>

Sometimes works, sometimes not.
How about a meaningful error message?

**Comment by sp-hash** [comment]
2.14 windows exe v3 has been released with api and stats fixes.
