### ISSUE TITLE
Please be precise with your parameter instructions

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#435]
In https://github.com/sp-hash/TeamBlackMiner/issues/433#issuecomment-1857962789 You write:
 **--dual-intensity 16**

And in https://github.com/sp-hash/TeamBlackMiner/issues/434#issuecomment-1858842240  in you write:
**the parameter is --dual-xintensity**

What now? And why does
--dual-intensity 8 or --dual-intensity 12 or --dual-intensity 16
work and the miner does not print a 'invalid parameter message' message?

**Comment by UselessGuru** [comment]
and in https://github.com/sp-hash/TeamBlackMiner/issues/430#issuecomment-1857964900 you write

**--xintensity for ETC algo
--dual-intensity for VTC algo.**

I expect the mier to work well (not optimal) with the built in default settings.
I test a lot of other miners. I am sorry to say but TeamBlackMiner it the one causing the most issues. Others (I am not naming them to not advertise) just work out of the box with all combinations.

**Comment by sp-hash** [comment]
2.16 windows is ready to test.

Dual mining defaults will take time to find optimal values for, and different cards have different optimal setting.
