### ISSUE TITLE
2.16: How to dual mine with firo?

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#437]
https://github.com/sp-hash/TeamBlackMiner?tab=readme-ov-file#supported-dual-mining-and-tripple-mining-combos-and-developer-commission says that dual ming with firo is supported.

But I can not find the correct parameters. Can you please provide a working command line sample.

**Comment by sp-hash** [comment]
https://github.com/sp-hash/TeamBlackMiner/tree/main/Launchscripts/Windows/FIROPOW%2BZIL

**Comment by sp-hash** [comment]
![image](https://github.com/sp-hash/TeamBlackMiner/assets/9572668/da8b0106-bcd0-4497-8117-ecf63a948050)
