### ISSUE TITLE
    TBMiner --algo etc+firo --hostname eu.crazypool.org --port 5005 --wallet %ZIL_WALLET% --rvn-hostname firopow.eu.mine.zergpool.com --rvn-port 3001 --rvn-wallet %BTC_WALLET% --worker-name %computername% --log

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#438]
These parameters don't make sense.

Why should we use --rvn* when mining firo?

I'd expect --firo-hostname etc.

Or keep it even simpler for all dual mining and use something generic like --**dual**-hostname instead.

**Comment by sp-hash** [comment]
in the next build -firo-hoistname etc is possible

**Comment by sp-hash** [comment]
fixed in v2.16 v2 (new upload same name)
