### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by muua666** [sp-hash/TeamBlackMiner#439]
Hello, how can I edit my wallet address and mining pool address in the start.bat, after the editing is completed, double-click start.bat can only open the notepad, 
what is the reason? The graphics card is 6600 and the operating system is WIN10.

![219153028](https://github.com/sp-hash/TeamBlackMiner/assets/154310792/a1f07acc-f0f7-4be4-b0a7-4bc84ba8a68b)

**Comment by muua666** [comment]
![1219153010](https://github.com/sp-hash/TeamBlackMiner/assets/154310792/37ea55f3-b3a1-4a0e-be73-91fad82ffcec)

**Comment by muua666** [comment]
thanks

**Comment by sp-hash** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-change-a-txt-file-to-a-bat-file/95d97abb-723b-46d2-b990-dbe8cb0deccc

**Comment by muua666** [comment]
Thank you very much for the above issue being resolved。
but I'm a Chinese user, I can't directly connect to 2miners, use the relay address rvns1.pool.cn.com:52003(ssl), and it prompts Sorry the provided pool is not supported, how to solve it, thank you again
TBMiner.exe --algo kawpow --ssl --hostname rvn.ethsvip.org --ssl-port 52140 --wallet xxxxx.H1 -d
