### ISSUE TITLE
v2.16 (new binary):  --algo etc+firo Illegal option detected:

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#440]
TeamBlackMiner-v2.16>TBMiner.exe --algo etc+firo --hostname europe.etchash-hub.miningpoolhub.com --wallet #######################.############## --port 20615 --server-passwd x --firo-hostname firopow.eu.mine.zergpool.com --firo-wallet ################### --firo-passwd c=BTC,mc=KIIRO,ID=########## --firo-port 3001 --api --api-version 1.4 --api-port 4001 --cl-devices [0]
Illegal option detected:
-a -al --algo
-O -ap --all-platforms
-b -ao --amd-only
-F -ai --api-ip
-R -at --api-port
-d -ad --api
-8 -av --api-version
-c -cf --configfile
-Y -cl --cl-devices
-U -cu --cuda-devices
....

??? Which option?
What am I doing wrong?

Once more: Stop closing issues until they are really solved!!!!

**Comment by sp-hash** [comment]
fixed in build v3.

**Comment by UselessGuru** [comment]
Fixed in build v3
