### ISSUE TITLE
Thank you very much for the above issue being resolved。

### ISSUE THREAD

**Issue by muua666** [sp-hash/TeamBlackMiner#441]
Thank you very much for the above issue being resolved。
but I'm a Chinese user, I can't directly connect to 2miners, use the relay address,and it prompts :Sorry the provided pool is not supported, how to solve it, thank you again.
TBMiner.exe --algo kawpow --ssl --hostname rvn.ethsvip.org --ssl-port 52140 --wallet xxxxx.H1 -d

_Originally posted by @muua666 in https://github.com/sp-hash/TeamBlackMiner/issues/439#issuecomment-1862408256_

**Comment by sp-hash** [comment]
not fixed
