### ISSUE TITLE
Is the offset parameter set like this?

### ISSUE THREAD

**Issue by tolygbaby** [sp-hash/TeamBlackMiner#442]
Is the offset parameter set like this?

**Comment by sp-hash** [comment]
set like what?

**Comment by tolygbaby** [comment]
Sets GPU memory clock frequency offset in MHz
Sets GPU core clock frequency offset in MHz

**Comment by sp-hash** [comment]
offset is not supported, use MSI afterburner on windows, or set the clocks with hiveos, smos, mpos on linux.
On nvidia we support to lock the clock to decrease voltage.

--lock-cclock
--lock-mclock

F.ex:
--lock-cclock 1200

will lock the core clock to 1200

**Comment by tolygbaby** [comment]
I get it, thank
