### ISSUE TITLE
v2.17 (Windows): eth+ethb3 building DAG takes almost 4 minutes or even more

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#447]
<img width="493" alt="image" src="https://github.com/sp-hash/TeamBlackMiner/assets/30080938/5a2d6db6-206b-40f0-9166-73355b79fcf5">

Bin\TeamBlackMiner-v2.17\TBMiner.exe --algo eth+ethb3 --hostname ethash.eu.mine.zergpool.com --wallet *********************** --port 9999 --server-passwd c=BTC,mc=ALT,ID=************* --ethb3-hostname ethashb3.eu.mine.zergpool.com --ethb3-wallet *************** --ethb3-passwd c=BTC,mc=HYP,ID=***************** --ethb3-port 9996 --api --api-version 1.4 --api-port 4002 --cl-devices [1]

**Comment by UselessGuru** [comment]
<img width="625" alt="image" src="https://github.com/sp-hash/TeamBlackMiner/assets/30080938/a9fd752b-cff5-4abe-90fe-47dac6351d06">

No EthashB3 DAG built even after 7 minutes!

Bin\TeamBlackMiner-v2.17\TBMiner.exe --algo eth+ethb3 --hostname ethash.eu.mine.zergpool.com --wallet ********************** --port 9999 --server-passwd c=BTC,mc=OCTA,ID=*************** --ethb3-hostname ethashb3.eu.mine.zergpool.com --ethb3-wallet *********************** --ethb3-passwd c=BTC,mc=HYP,ID=********************* --ethb3-port 9996 --api --api-version 1.4 --api-port 4002 --cl-devices [1]

**Comment by sp-hash** [comment]
2.18 hasnt been released yet

**Comment by UselessGuru** [comment]
OK, totle changed. Error is with 2.17

**Comment by UselessGuru** [comment]
Any news?
