### ISSUE TITLE
v2.19: etchash & ethashb3: DAG building very slow or not working at all

### ISSUE THREAD

**Issue by UselessGuru** [sp-hash/TeamBlackMiner#450]
Bin\TeamBlackMiner-v2.19\TBMiner.exe --algo etc+ethb3 --hostname etchash.auto.nicehash.com --wallet **********************.**************  --port 9200 --server-passwd x --ethb3-hostname ethashb3.eu.mine.zergpool.com --ethb3-wallet *********************************** --ethb3-passwd c=BTC,mc=HYP,ID=************************** --ethb3-port 9996 --api --api-version 1.4 --api-port 4002 --cl-devices [0]

On RX580 bilding DAG takes more than 3 minutes
On RX 5700 DAG never gets built

Similar issue like
https://github.com/sp-hash/TeamBlackMiner/issues/447

Do you ever test your miner????

**Comment by UselessGuru** [comment]
DAG generation for dual algo mining is still very slow with 2.23.
Any plans to improve this?

**Comment by sp-hash** [comment]
I have debugged this, but not yet fixed this. Perhaps in the next release

**Comment by UselessGuru** [comment]
> I have debugged this, but not yet fixed this. Perhaps in the next release

Any news on this?

**Comment by UselessGuru** [comment]
Any news on this? An update would be nice.

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by sp-hash** [comment]
yes. we will fix this

**Comment by UselessGuru** [comment]
> yes. we will fix this

When? This is such an old issue.

**Comment by UselessGuru** [comment]
Resolved with 2.27
