### ISSUE TITLE
Miner not working on arch linux

### ISSUE THREAD

**Issue by szentigrad3** [sp-hash/TeamBlackMiner#451]
./Bin/GPU-Teamblack/TBMiner --algo kawpow --hostname kawpow.mine.zergpool.com --port 3638 --wallet MQmRsLvQVaYxGCfLCaECqjQwm3ehEGo4Zm --worker-name JASON --server-passwd c=LTC,mc=NEOX,ID=JASON --amd-only --cl-devices [0] --api --api-port 36500 --no-ansi --no-cpu

./Bin/GPU-Teamblack/TBMiner: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

running on a 7900 XTX

**Comment by sp-hash** [comment]
--amd-only and --no-cpu is not needed. Can you try again without these options?

**Comment by szentigrad3** [comment]
> --amd-only and --no-cpu is not needed. Can you try again without these options?

same error

**Comment by sp-hash** [comment]
We are working to improve static linking. Looks like you need cuda instlaled or nvidia drivers

**Comment by szentigrad3** [comment]
> We are working to improve static linking. Looks like you need cuda instlaled or nvidia drivers

i'll wait for an update to fix it, not installing nvidia crap

**Comment by szentigrad3** [comment]
tried installing cuda and now getting this error: ./Bin/GPU-Teamblack/TBMiner: /usr/lib/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by ./Bin/GPU-Teamblack/TBMiner)

**Comment by sp-hash** [comment]
Did you try the ubuntu 20.04 build? We are going to add a ubuntu 22.04 build as well

**Comment by szentigrad3** [comment]
> Did you try the ubuntu 20.04 build? We are going to add a ubuntu 22.04 build as well that will work on newer linux

yes same issue

**Comment by sp-hash** [comment]
v2.25 has been released with ubuntu 22.2 support. Should work on modern linux

**Comment by szentigrad3** [comment]
> v2.25 has been released with ubuntu 22.2 support. Should work on modern linux

Working now
