### ISSUE TITLE
MeowPoW+KLS+ZIL 

### ISSUE THREAD

**Issue by JustAResearcher** [sp-hash/TeamBlackMiner#453]
Is this possible? If not, what options are available for triple mining with Meowpow?
Thank you so much for your support.

**Comment by sp-hash** [comment]
The answer is in the front page

![image](https://github.com/sp-hash/TeamBlackMiner/assets/9572668/e4859e72-2880-4098-9f4b-89530b27b438)

**Comment by sp-hash** [comment]
zil+MeowPow 		Nvidia, AMD 	0.5%
Ethash+MeowPow 		Nvidia, AMD 	0.5%
Etchash+MeowPow 		Nvidia, AMD 	0.5%
EthashB3+MeowPow 		Nvidia, AMD 	0.5%

if you mine on a ethash/etc hash pool with zil you can use the --zil-only flag to ignore etc of ethhash.

**Comment by sp-hash** [comment]
meowpow is similar to kawpow and will take all the resources out of the 3rd algo so meowpow+zil will be the most profitable
