### ISSUE TITLE
add evr+zil support

### ISSUE THREAD

**Issue by danyalfa79** [sp-hash/TeamBlackMiner#454]
Hello. i want use your miner but it doesn't allow me to mine evr+zil
please add evr+zil mining

**Comment by sp-hash** [comment]
This has already been added. The algo is etc+evr
launch script example:
https://github.com/sp-hash/TeamBlackMiner/blob/main/Launchscripts/Windows/ETC%2BEVR/tbminer_zergpool_etc%2Bevr.bat
