### ISSUE TITLE
rtx 2060 super list as 2060 in the stats

### ISSUE THREAD

**Issue by sp-hash** [sp-hash/TeamBlackMiner#46]

**Comment by binaryf** [comment]
Call it 2060s ?

**Comment by sp-hash** [comment]
yes

**Comment by binaryf** [comment]
Done.

**Comment by sp-hash** [comment]
from somaton@bitcointalk

found one more bug in 1.11:

     0m [2021-10-04 22:42:55.759] GPU0 NVIDIA GeForce RTX 3070 8GB added to miner as Cuda device
     0m [2021-10-04 22:42:55.869] GPU1 NVIDIA GeForce RTX 3060 Ti 8GB added to miner as Cuda device
     0m [2021-10-04 22:42:55.962] GPU2 NVIDIA GeForce RTX 3060 12GB added to miner as Cuda device

     1m [2021-10-04 22:43:57.214] miningpoolhub.com (ethash)    PING: 0ms    DIFFICULTY: 3.00     EPOCH: 445
     1m [2021-10-04 22:43:57.214]                                                                           
     1m [2021-10-04 22:43:57.214]
     1m [2021-10-04 22:43:57.214] ID   BOARD   TYPE   TEMP   FAN   CORE   MEM   WATT   kW/h   COST/h
     1m [2021-10-04 22:43:57.214] GPU0   3070   Cuda   44/0   88   1481   8462   107   0.11   0.00USD
     1m [2021-10-04 22:43:57.214] GPU1   3060   Cuda   41/0   75   1639   8022   125   0.12   0.00USD
     1m [2021-10-04 22:43:57.214] GPU2   3060   Cuda   43/0   78   1701   7963   135   0.14   0.00USD
     1m [2021-10-04 22:43:57.214]                      367   0.37   0.00USD
