### ISSUE TITLE
Error while loading shared libraries: libcudart

### ISSUE THREAD

**Issue by smoslinux** [sp-hash/TeamBlackMiner#47]
Hi Support,

We talked on the Reddit, but to keep this issue tracked I'm creating the ticket here:
`./TBMiner: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory`

1. Ubuntu 18
2. Installed the latest driver on the Ubuntu
3. Cuda Kit - Is NOT installed

Just let me know is a condition for making the miner working Cuda Kit installed, or should your miner work without any additional installation except the standard driver.

Thanks

**Comment by binaryf** [comment]
Hi. Thanks for your feedback.
On my system with Nvidia Cuda Toolkit installed I have this library file and the symlinks:

frode@linux20:~$ locate libcudart.so

/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.4.108

frode@linux20:~$ ll /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.*

lrwxrwxrwx 1 root root     17 juli  27 08:08 /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so -> libcudart.so.11.0
lrwxrwxrwx 1 root root     21 juli  27 08:08 /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0 -> libcudart.so.11.4.108
-rw-r--r-- 1 root root 658784 juli  27 08:08 /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.4.108

If you run a search for libcudart.so what do you get ?

**Comment by smoslinux** [comment]
Nothing, it's empty. I don't have installed cuda by default, just Nvidia driver. 

It's all clear now, we can close this ticket. These files are coming with installed Cuda Kit, which was the only unclear. Basically, everyone needs to install a fully Nvidia kit in order to have this working. Which is 1-2GB.

I'm suggesting exporting all libraries inside your miner if that is possible. If other miners find a solution, I'm suggesting it to you too.

Best

**Comment by binaryf** [comment]
Thank you.

**Comment by sp-hash** [comment]
v1.11 will have static cuda libraries linked in

**Comment by smoslinux** [comment]
> v1.11 will have static cuda libraries linked in

Nice! Waiting for it to deploy to SMOS Dashboard.

Best!
