### ISSUE TITLE
[REQ] please add these pools

### ISSUE THREAD

**Issue by RainbowMiner** [sp-hash/TeamBlackMiner#5]
Hi, your miner runs fine, I have already included it into RainbowMiner.
But there are some good pools, I would like to request to be added:
- **MiningRigRentals.com**
- **ProHashing.com**
- **unMineable.com**

Also these, would be nice as well:
- BeePool
- Hellominer
- HeroMiners
- MiningDutch
- MoneroOcean
- Poolin
- PoolSexy
- SuprNova
- WoolyPooly
- Zpool (verthash)

**Comment by RainbowMiner** [comment]
Proposal for enhancement: you could add a parameter to select the pool protocol. With that, all pools could be used with the miner. Something like `--proto <protocol>` or similar
E.g.
- `--proto 1` --> minerproxy
- `--proto 2` --> ethproxy
- `--proto 3` --> qtminer
- `--proto 4` --> ethstratum/ethstratum1/ethstratumnh
- `--proto 5` --> ethstratum2

Or whatever :)

**Comment by momanz** [comment]
Can you also add...

Crazypool (https://eth.crazypool.org/#/)

thanks!

**Comment by sp-hash** [comment]
MiningRigRentals.com
ProHashing.com
Crazypool

has been added

**Comment by binaryf** [comment]
I will have another go at miningrigrentals.com tomorrow.

**Comment by KillrBee** [comment]
Can you add WoolyPooly as well?

**Comment by RainbowMiner** [comment]
> Can you add WoolyPooly as well?

I second that. Forgot to put it on my list,

**Comment by sp-hash** [comment]
added in v1.06
