### ISSUE TITLE
Req: add DTHash gpu mining

### ISSUE THREAD

**Issue by JABirchall** [sp-hash/TeamBlackMiner#51]
An ethereum fork started called Detonus, and they keeping the algo private. But I have reversed the algo. 
The algo is basically the same as ethash with 2 lines changed.

the first `crypto.Keccak512(seed)` was changed to `crypto.Keccak512(crypto.Keccak256(seed))`

and the second return `crypto.Keccak256(append(seed, digest...))` was changed to `crypto.Keccak256(crypto.Keccak512(append(seed, digest...)))`

**Comment by sp-hash** [comment]
probobly not
