### ISSUE TITLE
cudaminer.cpp:cuda_search():394: A cuda runtime error occured

### ISSUE THREAD

**Issue by team-community** [sp-hash/TeamBlackMiner#54]
Hello
on cuda 11.4 (472.12 driver)

```
DAG generated in 1.70 seconds (2916346kb)[0m
GPU0 XIntensity set to 224[0m
C:\gc\TBMiner\source\sp_cuda\cudaminer.cpp:cuda_search():394: A cuda runtime error occured: the launch timed out and was terminated[0m
Shutting down threads[0m
mControl thread exited[0m
Stratum thread exited[0m
Exiting[0m
```

![img-2021-10-08-22-32-44](https://user-images.githubusercontent.com/85034250/136615437-c45dd33e-d771-4ab9-b616-8c439743a1e0.png)

**Comment by sp-hash** [comment]
Can you run tbminer.exe --list-devices ?

**Comment by team-community** [comment]
```
Available Cuda devices
-----------------------

Device Number: 0
    Device name: NVIDIA GeForce GTX 1080 Ti
    PCIe bus id: 1
    Memory: 11GB
    Memory clock rate (KHz): 5505000
    Memory bus width (bits): 352
    Peak memory bandwidth (GB/s): 484.440000


Available OpenCL devices
-------------------------

Device Number: 0
    Device name: NVIDIA GeForce GTX 1080 Ti
    PCIe bus id: 0
    Memory: 11GB
```

**Comment by sp-hash** [comment]
We had another user with the same problem. Perhaps you can try to install the whole cuda 11.4 toolkit?

**Comment by team-community** [comment]
Sorry, CUDA Toolkit 11.4 currently weighs about 3GB. I am temporarily unable to install it.
I think it makes sense to create releases for other cuda versions as well, because this problem can occur for many people.

**Comment by team-community** [comment]
On 11.2 the same error

**Comment by team-community** [comment]
It looks like I can run ZIL. However, the hashrate is written 0 after 5 minutes. But the card starts to heat up.
![img-2021-10-09-20-47-50](https://user-images.githubusercontent.com/85034250/136669044-8454290c-a7c5-4816-b5a9-709ca9f84931.png)
