### ISSUE TITLE
Corrupt ansi output in v1.12, v1.10 is working

### ISSUE THREAD

**Issue by sp-hash** [sp-hash/TeamBlackMiner#57]
somaton@bitcointalk

:loop

tbminer.exe --algo ethash --hostname europe.ethash-hub.miningpoolhub.com --port 20535 --wallet XXX --worker_name XXX --retries=999 --retry-pause 2 --electricity-cost 0 --log --xintensity 352

timeout 
<img width="300" alt="last ned" src="https://user-images.githubusercontent.com/9572668/136671569-ddc70aa9-1a9e-4796-ae7a-ebd143f7fd3f.png">
5

**Comment by binaryf** [comment]
The problem might be very unusual and is releated to ansi output.
Try a different terminal like "Windows Terminal".
