### ISSUE TITLE
Pstate + mclock offset

### ISSUE THREAD

**Issue by thaneb** [sp-hash/TeamBlackMiner#67]
As the core clock lock as been released, I wanted to give another try to TBM, unfortunately, the spiderpool new (and faster ping) URL for asia isn't usable, so it would be nice to allow any pool URL to be used (with maybe a list of the officially supported ones in the readme, it would also allow to let only 4 or 5 generic .bat in the archive (one per algo maybe).
Other must have arguments for the miner (at least on windows systems) would be the Pstate -> P0 and a memory clock offset (without P0 it will lead to system crash while existing the miner).
I guess at least many windows miners are using task scheduler to start mining at the boot, avoid the UA dialogue box to run as admin, and having to manage a second task/script to apply P0 (doesn't work anymore with nvidia inspector) and memory clock offset is a real pain in our mining process.
Many thanks, I'm impatient to be able to fully switch from t rex to TBM !!
PS : New pools for spiderpool : 
Southeast Asia Node Address:　stratum+tcp://eth-asia.spiderpool.com:3867
Japan Node Address:　stratum+tcp://eth-jp.pool.zhizhu.top:3867
Europe Node Address:　stratum+tcp://eth-eu.pool.zhizhu.top:3867
USA Node Address:　stratum+tcp://eth-us.pool.zhizhu.top:3867
Inno A10 port:　6868
PS2 : you can remove the sparkpool.bat now that their activity shutdown... ;)

**Comment by sp-hash** [comment]
pool url and lockmemclock added in v1.16

**Comment by thaneb** [comment]
Ok, so, it would be much better to get the lockmemclock activated after DAG verification, because activating it earlier often lead to error.

**Comment by plavirudar** [comment]
Can confirm that as of latest release 1.25 memory clock setting is still completely broken, and cannot be set to their optimized values, at least for a 3080/3060 rig and a 3070 rig. The same settings using mem offsets worked fine for gminer, trex, and msi afterburner.

**Comment by binaryf** [comment]
I am not sure If this idea is going somewhere, so we will close this.
Thank you for the feedback.
