### ISSUE TITLE
Mixed Polaris and RDNA GPU's not detected on v1.16

### ISSUE THREAD

**Issue by geezar** [sp-hash/TeamBlackMiner#71]
6600XTs are detected in Linux but the RX580's are not. adding the --cl-devices switch results in a miner exit state and the --auto-detect does not find the Polaris GPU's.

**Comment by sp-hash** [comment]
what do you get with:

$ .\tbminer --list-devices

**Comment by jeremyhammon** [comment]
I will confirm the same issue.  Rig with 6 cards, 2 5600xt are detected.  4 580 are not detected, but are detected fine in hive os and by other miners.   --list-devices only shows the 5600xt and the 580's are ignored.  Specifying the addresses does not work either.

**Comment by sp-hash** [comment]
Other ppl have made it work on hive. Try to upgrade to the latest verision of hiveos.

https://ibb.co/YZZJnLM

**Comment by sp-hash** [comment]
this issue has been fixed in v1.51
