### ISSUE TITLE
TBM does not work with RX480

### ISSUE THREAD

**Issue by arislan91** [sp-hash/TeamBlackMiner#90]
The miner starts with all the other GPUs but the RX480 8GB does not start. Mining Ethereum on HiveOS. Does this miner supports older GPUs such as RX480 ?

**Comment by sp-hash** [comment]
Other ppl have made it work on hiveos. Install the latest amd driver

https://ibb.co/YZZJnLM

**Comment by yean76** [comment]
He still some card 0m/h. And, not mixed rig

**Comment by sp-hash** [comment]
try to upgrade to 1.22. and put --dag-intensity 1
